//VJOB0660 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLT01WNH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN01 DD DISP=SHR,DSN=GENAPP.DDLTIN01.DATA
//DDLTOT01 DD DISP=SHR,DSN=GENAPP.DDLTOT01.DATA
//DDLTRP01 DD DISP=SHR,DSN=GENAPP.DDLTRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01WNI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN02 DD DISP=SHR,DSN=GENAPP.DDTXIN02.DATA
//DDTXOT02 DD DISP=SHR,DSN=GENAPP.DDTXOT02.DATA
//DDTXRP02 DD DISP=SHR,DSN=GENAPP.DDTXRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01WNJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN03 DD DISP=SHR,DSN=GENAPP.DDHOIN03.DATA
//DDHOOT03 DD DISP=SHR,DSN=GENAPP.DDHOOT03.DATA
//DDHORP03 DD DISP=SHR,DSN=GENAPP.DDHORP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
