//VJOB0589 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01WHK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN58 DD DISP=SHR,DSN=GENAPP.DDMTIN58.DATA
//DDMTOT58 DD DISP=SHR,DSN=GENAPP.DDMTOT58.DATA
//DDMTRP58 DD DISP=SHR,DSN=GENAPP.DDMTRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPT01WHL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN59 DD DISP=SHR,DSN=GENAPP.DDPTIN59.DATA
//DDPTOT59 DD DISP=SHR,DSN=GENAPP.DDPTOT59.DATA
//DDPTRP59 DD DISP=SHR,DSN=GENAPP.DDPTRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF01WHM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN60 DD DISP=SHR,DSN=GENAPP.DDIFIN60.DATA
//DDIFOT60 DD DISP=SHR,DSN=GENAPP.DDIFOT60.DATA
//DDIFRP60 DD DISP=SHR,DSN=GENAPP.DDIFRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
