//VJOB1993 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01ZQK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN40 DD DISP=SHR,DSN=GENAPP.DDAVIN40.DATA
//DDAVOT40 DD DISP=SHR,DSN=GENAPP.DDAVOT40.DATA
//DDAVRP40 DD DISP=SHR,DSN=GENAPP.DDAVRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG01ZQL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN41 DD DISP=SHR,DSN=GENAPP.DDRGIN41.DATA
//DDRGOT41 DD DISP=SHR,DSN=GENAPP.DDRGOT41.DATA
//DDRGRP41 DD DISP=SHR,DSN=GENAPP.DDRGRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN01ZQM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN42 DD DISP=SHR,DSN=GENAPP.DDPNIN42.DATA
//DDPNOT42 DD DISP=SHR,DSN=GENAPP.DDPNOT42.DATA
//DDPNRP42 DD DISP=SHR,DSN=GENAPP.DDPNRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
