//VJOB2152 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLT0203T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN67 DD DISP=SHR,DSN=GENAPP.DDLTIN67.DATA
//DDLTOT67 DD DISP=SHR,DSN=GENAPP.DDLTOT67.DATA
//DDLTRP67 DD DISP=SHR,DSN=GENAPP.DDLTRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE0203U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN68 DD DISP=SHR,DSN=GENAPP.DDPEIN68.DATA
//DDPEOT68 DD DISP=SHR,DSN=GENAPP.DDPEOT68.DATA
//DDPERP68 DD DISP=SHR,DSN=GENAPP.DDPERP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTY0203V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN69 DD DISP=SHR,DSN=GENAPP.DDTYIN69.DATA
//DDTYOT69 DD DISP=SHR,DSN=GENAPP.DDTYOT69.DATA
//DDTYRP69 DD DISP=SHR,DSN=GENAPP.DDTYRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
