//VJOB2980 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBR0220T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN31 DD DISP=SHR,DSN=GENAPP.DDBRIN31.DATA
//DDBROT31 DD DISP=SHR,DSN=GENAPP.DDBROT31.DATA
//DDBRRP31 DD DISP=SHR,DSN=GENAPP.DDBRRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE0220U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN32 DD DISP=SHR,DSN=GENAPP.DDHEIN32.DATA
//DDHEOT32 DD DISP=SHR,DSN=GENAPP.DDHEOT32.DATA
//DDHERP32 DD DISP=SHR,DSN=GENAPP.DDHERP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN0220V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN33 DD DISP=SHR,DSN=GENAPP.DDANIN33.DATA
//DDANOT33 DD DISP=SHR,DSN=GENAPP.DDANOT33.DATA
//DDANRP33 DD DISP=SHR,DSN=GENAPP.DDANRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
