//VJOB1608 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE01YUH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN55 DD DISP=SHR,DSN=GENAPP.DDPEIN55.DATA
//DDPEOT55 DD DISP=SHR,DSN=GENAPP.DDPEOT55.DATA
//DDPERP55 DD DISP=SHR,DSN=GENAPP.DDPERP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT01YUI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN56 DD DISP=SHR,DSN=GENAPP.DDLTIN56.DATA
//DDLTOT56 DD DISP=SHR,DSN=GENAPP.DDLTOT56.DATA
//DDLTRP56 DD DISP=SHR,DSN=GENAPP.DDLTRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSU01YUJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN57 DD DISP=SHR,DSN=GENAPP.DDSUIN57.DATA
//DDSUOT57 DD DISP=SHR,DSN=GENAPP.DDSUOT57.DATA
//DDSURP57 DD DISP=SHR,DSN=GENAPP.DDSURP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
