//VJOB1732 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR01Z4T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN67 DD DISP=SHR,DSN=GENAPP.DDTRIN67.DATA
//DDTROT67 DD DISP=SHR,DSN=GENAPP.DDTROT67.DATA
//DDTRRP67 DD DISP=SHR,DSN=GENAPP.DDTRRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN01Z4U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN68 DD DISP=SHR,DSN=GENAPP.DDPNIN68.DATA
//DDPNOT68 DD DISP=SHR,DSN=GENAPP.DDPNOT68.DATA
//DDPNRP68 DD DISP=SHR,DSN=GENAPP.DDPNRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS01Z4V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN69 DD DISP=SHR,DSN=GENAPP.DDRSIN69.DATA
//DDRSOT69 DD DISP=SHR,DSN=GENAPP.DDRSOT69.DATA
//DDRSRP69 DD DISP=SHR,DSN=GENAPP.DDRSRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
