//VJOB4134 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE024OZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN73 DD DISP=SHR,DSN=GENAPP.DDHEIN73.DATA
//DDHEOT73 DD DISP=SHR,DSN=GENAPP.DDHEOT73.DATA
//DDHERP73 DD DISP=SHR,DSN=GENAPP.DDHERP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT024P0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN74 DD DISP=SHR,DSN=GENAPP.DDMTIN74.DATA
//DDMTOT74 DD DISP=SHR,DSN=GENAPP.DDMTOT74.DATA
//DDMTRP74 DD DISP=SHR,DSN=GENAPP.DDMTRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE024P1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN75 DD DISP=SHR,DSN=GENAPP.DDHEIN75.DATA
//DDHEOT75 DD DISP=SHR,DSN=GENAPP.DDHEOT75.DATA
//DDHERP75 DD DISP=SHR,DSN=GENAPP.DDHERP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
