//VJOB2873 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW021RW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN70 DD DISP=SHR,DSN=GENAPP.DDUWIN70.DATA
//DDUWOT70 DD DISP=SHR,DSN=GENAPP.DDUWOT70.DATA
//DDUWRP70 DD DISP=SHR,DSN=GENAPP.DDUWRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRT021RX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN71 DD DISP=SHR,DSN=GENAPP.DDRTIN71.DATA
//DDRTOT71 DD DISP=SHR,DSN=GENAPP.DDRTOT71.DATA
//DDRTRP71 DD DISP=SHR,DSN=GENAPP.DDRTRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN021RY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN72 DD DISP=SHR,DSN=GENAPP.DDENIN72.DATA
//DDENOT72 DD DISP=SHR,DSN=GENAPP.DDENOT72.DATA
//DDENRP72 DD DISP=SHR,DSN=GENAPP.DDENRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
