//VJOB1327 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZGW01Y72
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN22 DD DISP=SHR,DSN=GENAPP.DDGWIN22.DATA
//DDGWOT22 DD DISP=SHR,DSN=GENAPP.DDGWOT22.DATA
//DDGWRP22 DD DISP=SHR,DSN=GENAPP.DDGWRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01Y73
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN23 DD DISP=SHR,DSN=GENAPP.DDCUIN23.DATA
//DDCUOT23 DD DISP=SHR,DSN=GENAPP.DDCUOT23.DATA
//DDCURP23 DD DISP=SHR,DSN=GENAPP.DDCURP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG01Y74
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN24 DD DISP=SHR,DSN=GENAPP.DDRGIN24.DATA
//DDRGOT24 DD DISP=SHR,DSN=GENAPP.DDRGOT24.DATA
//DDRGRP24 DD DISP=SHR,DSN=GENAPP.DDRGRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
