//VJOB3603 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDO023GQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN10 DD DISP=SHR,DSN=GENAPP.DDDOIN10.DATA
//DDDOOT10 DD DISP=SHR,DSN=GENAPP.DDDOOT10.DATA
//DDDORP10 DD DISP=SHR,DSN=GENAPP.DDDORP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV023GR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN11 DD DISP=SHR,DSN=GENAPP.DDIVIN11.DATA
//DDIVOT11 DD DISP=SHR,DSN=GENAPP.DDIVOT11.DATA
//DDIVRP11 DD DISP=SHR,DSN=GENAPP.DDIVRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV023GS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN12 DD DISP=SHR,DSN=GENAPP.DDIVIN12.DATA
//DDIVOT12 DD DISP=SHR,DSN=GENAPP.DDIVOT12.DATA
//DDIVRP12 DD DISP=SHR,DSN=GENAPP.DDIVRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
