//VJOB2159 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSB0204E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN88 DD DISP=SHR,DSN=GENAPP.DDSBIN88.DATA
//DDSBOT88 DD DISP=SHR,DSN=GENAPP.DDSBOT88.DATA
//DDSBRP88 DD DISP=SHR,DSN=GENAPP.DDSBRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0204F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN89 DD DISP=SHR,DSN=GENAPP.DDMTIN89.DATA
//DDMTOT89 DD DISP=SHR,DSN=GENAPP.DDMTOT89.DATA
//DDMTRP89 DD DISP=SHR,DSN=GENAPP.DDMTRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW0204G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN90 DD DISP=SHR,DSN=GENAPP.DDUWIN90.DATA
//DDUWOT90 DD DISP=SHR,DSN=GENAPP.DDUWOT90.DATA
//DDUWRP90 DD DISP=SHR,DSN=GENAPP.DDUWRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
