//VJOB1811 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01ZBE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN34 DD DISP=SHR,DSN=GENAPP.DDHOIN34.DATA
//DDHOOT34 DD DISP=SHR,DSN=GENAPP.DDHOOT34.DATA
//DDHORP34 DD DISP=SHR,DSN=GENAPP.DDHORP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT01ZBF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN35 DD DISP=SHR,DSN=GENAPP.DDLTIN35.DATA
//DDLTOT35 DD DISP=SHR,DSN=GENAPP.DDLTOT35.DATA
//DDLTRP35 DD DISP=SHR,DSN=GENAPP.DDLTRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZGW01ZBG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN36 DD DISP=SHR,DSN=GENAPP.DDGWIN36.DATA
//DDGWOT36 DD DISP=SHR,DSN=GENAPP.DDGWOT36.DATA
//DDGWRP36 DD DISP=SHR,DSN=GENAPP.DDGWRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
