//VJOB2095 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01ZZ2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN76 DD DISP=SHR,DSN=GENAPP.DDHOIN76.DATA
//DDHOOT76 DD DISP=SHR,DSN=GENAPP.DDHOOT76.DATA
//DDHORP76 DD DISP=SHR,DSN=GENAPP.DDHORP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDO01ZZ3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN77 DD DISP=SHR,DSN=GENAPP.DDDOIN77.DATA
//DDDOOT77 DD DISP=SHR,DSN=GENAPP.DDDOOT77.DATA
//DDDORP77 DD DISP=SHR,DSN=GENAPP.DDDORP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01ZZ4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN78 DD DISP=SHR,DSN=GENAPP.DDPRIN78.DATA
//DDPROT78 DD DISP=SHR,DSN=GENAPP.DDPROT78.DATA
//DDPRRP78 DD DISP=SHR,DSN=GENAPP.DDPRRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
