//VJOB3115 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN022C2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN76 DD DISP=SHR,DSN=GENAPP.DDENIN76.DATA
//DDENOT76 DD DISP=SHR,DSN=GENAPP.DDENOT76.DATA
//DDENRP76 DD DISP=SHR,DSN=GENAPP.DDENRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT022C3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN77 DD DISP=SHR,DSN=GENAPP.DDMTIN77.DATA
//DDMTOT77 DD DISP=SHR,DSN=GENAPP.DDMTOT77.DATA
//DDMTRP77 DD DISP=SHR,DSN=GENAPP.DDMTRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLT022C4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN78 DD DISP=SHR,DSN=GENAPP.DDLTIN78.DATA
//DDLTOT78 DD DISP=SHR,DSN=GENAPP.DDLTOT78.DATA
//DDLTRP78 DD DISP=SHR,DSN=GENAPP.DDLTRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
