//VJOB0309 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCN01VU8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN28 DD DISP=SHR,DSN=GENAPP.DDCNIN28.DATA
//DDCNOT28 DD DISP=SHR,DSN=GENAPP.DDCNOT28.DATA
//DDCNRP28 DD DISP=SHR,DSN=GENAPP.DDCNRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01VU9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN29 DD DISP=SHR,DSN=GENAPP.DDHOIN29.DATA
//DDHOOT29 DD DISP=SHR,DSN=GENAPP.DDHOOT29.DATA
//DDHORP29 DD DISP=SHR,DSN=GENAPP.DDHORP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAZ01VUA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN30 DD DISP=SHR,DSN=GENAPP.DDAZIN30.DATA
//DDAZOT30 DD DISP=SHR,DSN=GENAPP.DDAZOT30.DATA
//DDAZRP30 DD DISP=SHR,DSN=GENAPP.DDAZRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
