//VJOB1572 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01YRH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN37 DD DISP=SHR,DSN=GENAPP.DDBIIN37.DATA
//DDBIOT37 DD DISP=SHR,DSN=GENAPP.DDBIOT37.DATA
//DDBIRP37 DD DISP=SHR,DSN=GENAPP.DDBIRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01YRI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN38 DD DISP=SHR,DSN=GENAPP.DDMTIN38.DATA
//DDMTOT38 DD DISP=SHR,DSN=GENAPP.DDMTOT38.DATA
//DDMTRP38 DD DISP=SHR,DSN=GENAPP.DDMTRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLB01YRJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN39 DD DISP=SHR,DSN=GENAPP.DDLBIN39.DATA
//DDLBOT39 DD DISP=SHR,DSN=GENAPP.DDLBOT39.DATA
//DDLBRP39 DD DISP=SHR,DSN=GENAPP.DDLBRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
