//VJOB1395 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE01YCQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN46 DD DISP=SHR,DSN=GENAPP.DDREIN46.DATA
//DDREOT46 DD DISP=SHR,DSN=GENAPP.DDREOT46.DATA
//DDRERP46 DD DISP=SHR,DSN=GENAPP.DDRERP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01YCR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN47 DD DISP=SHR,DSN=GENAPP.DDCLIN47.DATA
//DDCLOT47 DD DISP=SHR,DSN=GENAPP.DDCLOT47.DATA
//DDCLRP47 DD DISP=SHR,DSN=GENAPP.DDCLRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLB01YCS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN48 DD DISP=SHR,DSN=GENAPP.DDLBIN48.DATA
//DDLBOT48 DD DISP=SHR,DSN=GENAPP.DDLBOT48.DATA
//DDLBRP48 DD DISP=SHR,DSN=GENAPP.DDLBRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
