//VJOB2484 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV020VH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN73 DD DISP=SHR,DSN=GENAPP.DDAVIN73.DATA
//DDAVOT73 DD DISP=SHR,DSN=GENAPP.DDAVOT73.DATA
//DDAVRP73 DD DISP=SHR,DSN=GENAPP.DDAVRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO020VI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN74 DD DISP=SHR,DSN=GENAPP.DDHOIN74.DATA
//DDHOOT74 DD DISP=SHR,DSN=GENAPP.DDHOOT74.DATA
//DDHORP74 DD DISP=SHR,DSN=GENAPP.DDHORP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV020VJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN75 DD DISP=SHR,DSN=GENAPP.DDIVIN75.DATA
//DDIVOT75 DD DISP=SHR,DSN=GENAPP.DDIVOT75.DATA
//DDIVRP75 DD DISP=SHR,DSN=GENAPP.DDIVRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
