//VJOB0511 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01WB2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN04 DD DISP=SHR,DSN=GENAPP.DDMTIN04.DATA
//DDMTOT04 DD DISP=SHR,DSN=GENAPP.DDMTOT04.DATA
//DDMTRP04 DD DISP=SHR,DSN=GENAPP.DDMTRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01WB3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN05 DD DISP=SHR,DSN=GENAPP.DDFLIN05.DATA
//DDFLOT05 DD DISP=SHR,DSN=GENAPP.DDFLOT05.DATA
//DDFLRP05 DD DISP=SHR,DSN=GENAPP.DDFLRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01WB4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN06 DD DISP=SHR,DSN=GENAPP.DDTRIN06.DATA
//DDTROT06 DD DISP=SHR,DSN=GENAPP.DDTROT06.DATA
//DDTRRP06 DD DISP=SHR,DSN=GENAPP.DDTRRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
