//VJOB0236 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSB01VO5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN79 DD DISP=SHR,DSN=GENAPP.DDSBIN79.DATA
//DDSBOT79 DD DISP=SHR,DSN=GENAPP.DDSBOT79.DATA
//DDSBRP79 DD DISP=SHR,DSN=GENAPP.DDSBRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01VO6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN80 DD DISP=SHR,DSN=GENAPP.DDCUIN80.DATA
//DDCUOT80 DD DISP=SHR,DSN=GENAPP.DDCUOT80.DATA
//DDCURP80 DD DISP=SHR,DSN=GENAPP.DDCURP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN01VO7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN81 DD DISP=SHR,DSN=GENAPP.DDPNIN81.DATA
//DDPNOT81 DD DISP=SHR,DSN=GENAPP.DDPNOT81.DATA
//DDPNRP81 DD DISP=SHR,DSN=GENAPP.DDPNRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
