//VJOB2566 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE0212B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN49 DD DISP=SHR,DSN=GENAPP.DDREIN49.DATA
//DDREOT49 DD DISP=SHR,DSN=GENAPP.DDREOT49.DATA
//DDRERP49 DD DISP=SHR,DSN=GENAPP.DDRERP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI0212C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN50 DD DISP=SHR,DSN=GENAPP.DDBIIN50.DATA
//DDBIOT50 DD DISP=SHR,DSN=GENAPP.DDBIOT50.DATA
//DDBIRP50 DD DISP=SHR,DSN=GENAPP.DDBIRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL0212D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN51 DD DISP=SHR,DSN=GENAPP.DDCLIN51.DATA
//DDCLOT51 DD DISP=SHR,DSN=GENAPP.DDCLOT51.DATA
//DDCLRP51 DD DISP=SHR,DSN=GENAPP.DDCLRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
