//VJOB3874 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT0243B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN13 DD DISP=SHR,DSN=GENAPP.DDMTIN13.DATA
//DDMTOT13 DD DISP=SHR,DSN=GENAPP.DDMTOT13.DATA
//DDMTRP13 DD DISP=SHR,DSN=GENAPP.DDMTRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO0243C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN14 DD DISP=SHR,DSN=GENAPP.DDHOIN14.DATA
//DDHOOT14 DD DISP=SHR,DSN=GENAPP.DDHOOT14.DATA
//DDHORP14 DD DISP=SHR,DSN=GENAPP.DDHORP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT0243D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN15 DD DISP=SHR,DSN=GENAPP.DDMTIN15.DATA
//DDMTOT15 DD DISP=SHR,DSN=GENAPP.DDMTOT15.DATA
//DDMTRP15 DD DISP=SHR,DSN=GENAPP.DDMTRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
