//VJOB1139 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01XRE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN88 DD DISP=SHR,DSN=GENAPP.DDCOIN88.DATA
//DDCOOT88 DD DISP=SHR,DSN=GENAPP.DDCOOT88.DATA
//DDCORP88 DD DISP=SHR,DSN=GENAPP.DDCORP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01XRF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN89 DD DISP=SHR,DSN=GENAPP.DDMTIN89.DATA
//DDMTOT89 DD DISP=SHR,DSN=GENAPP.DDMTOT89.DATA
//DDMTRP89 DD DISP=SHR,DSN=GENAPP.DDMTRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI01XRG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN90 DD DISP=SHR,DSN=GENAPP.DDLIIN90.DATA
//DDLIOT90 DD DISP=SHR,DSN=GENAPP.DDLIOT90.DATA
//DDLIRP90 DD DISP=SHR,DSN=GENAPP.DDLIRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
