//VJOB3936 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI0248H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN19 DD DISP=SHR,DSN=GENAPP.DDBIIN19.DATA
//DDBIOT19 DD DISP=SHR,DSN=GENAPP.DDBIOT19.DATA
//DDBIRP19 DD DISP=SHR,DSN=GENAPP.DDBIRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZVA0248I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN20 DD DISP=SHR,DSN=GENAPP.DDVAIN20.DATA
//DDVAOT20 DD DISP=SHR,DSN=GENAPP.DDVAOT20.DATA
//DDVARP20 DD DISP=SHR,DSN=GENAPP.DDVARP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG0248J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN21 DD DISP=SHR,DSN=GENAPP.DDRGIN21.DATA
//DDRGOT21 DD DISP=SHR,DSN=GENAPP.DDRGOT21.DATA
//DDRGRP21 DD DISP=SHR,DSN=GENAPP.DDRGRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
