//VJOB0283 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN01VS2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN40 DD DISP=SHR,DSN=GENAPP.DDPNIN40.DATA
//DDPNOT40 DD DISP=SHR,DSN=GENAPP.DDPNOT40.DATA
//DDPNRP40 DD DISP=SHR,DSN=GENAPP.DDPNRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR01VS3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN41 DD DISP=SHR,DSN=GENAPP.DDPRIN41.DATA
//DDPROT41 DD DISP=SHR,DSN=GENAPP.DDPROT41.DATA
//DDPRRP41 DD DISP=SHR,DSN=GENAPP.DDPRRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN01VS4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN42 DD DISP=SHR,DSN=GENAPP.DDPNIN42.DATA
//DDPNOT42 DD DISP=SHR,DSN=GENAPP.DDPNOT42.DATA
//DDPNRP42 DD DISP=SHR,DSN=GENAPP.DDPNRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
