//VJOB3930 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN0247Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN01 DD DISP=SHR,DSN=GENAPP.DDANIN01.DATA
//DDANOT01 DD DISP=SHR,DSN=GENAPP.DDANOT01.DATA
//DDANRP01 DD DISP=SHR,DSN=GENAPP.DDANRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSL02480
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN02 DD DISP=SHR,DSN=GENAPP.DDSLIN02.DATA
//DDSLOT02 DD DISP=SHR,DSN=GENAPP.DDSLOT02.DATA
//DDSLRP02 DD DISP=SHR,DSN=GENAPP.DDSLRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN02481
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN03 DD DISP=SHR,DSN=GENAPP.DDENIN03.DATA
//DDENOT03 DD DISP=SHR,DSN=GENAPP.DDENOT03.DATA
//DDENRP03 DD DISP=SHR,DSN=GENAPP.DDENRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
