//VJOB0165 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01VI8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN46 DD DISP=SHR,DSN=GENAPP.DDAVIN46.DATA
//DDAVOT46 DD DISP=SHR,DSN=GENAPP.DDAVOT46.DATA
//DDAVRP46 DD DISP=SHR,DSN=GENAPP.DDAVRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCP01VI9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN47 DD DISP=SHR,DSN=GENAPP.DDCPIN47.DATA
//DDCPOT47 DD DISP=SHR,DSN=GENAPP.DDCPOT47.DATA
//DDCPRP47 DD DISP=SHR,DSN=GENAPP.DDCPRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW01VIA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN48 DD DISP=SHR,DSN=GENAPP.DDUWIN48.DATA
//DDUWOT48 DD DISP=SHR,DSN=GENAPP.DDUWOT48.DATA
//DDUWRP48 DD DISP=SHR,DSN=GENAPP.DDUWRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
