//VJOB3485 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG0236W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN16 DD DISP=SHR,DSN=GENAPP.DDAGIN16.DATA
//DDAGOT16 DD DISP=SHR,DSN=GENAPP.DDAGOT16.DATA
//DDAGRP16 DD DISP=SHR,DSN=GENAPP.DDAGRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY0236X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN17 DD DISP=SHR,DSN=GENAPP.DDTYIN17.DATA
//DDTYOT17 DD DISP=SHR,DSN=GENAPP.DDTYOT17.DATA
//DDTYRP17 DD DISP=SHR,DSN=GENAPP.DDTYRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCR0236Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN18 DD DISP=SHR,DSN=GENAPP.DDCRIN18.DATA
//DDCROT18 DD DISP=SHR,DSN=GENAPP.DDCROT18.DATA
//DDCRRP18 DD DISP=SHR,DSN=GENAPP.DDCRRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
