//VJOB4030 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZQU024GB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN31 DD DISP=SHR,DSN=GENAPP.DDQUIN31.DATA
//DDQUOT31 DD DISP=SHR,DSN=GENAPP.DDQUOT31.DATA
//DDQURP31 DD DISP=SHR,DSN=GENAPP.DDQURP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB024GC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN32 DD DISP=SHR,DSN=GENAPP.DDLBIN32.DATA
//DDLBOT32 DD DISP=SHR,DSN=GENAPP.DDLBOT32.DATA
//DDLBRP32 DD DISP=SHR,DSN=GENAPP.DDLBRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC024GD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN33 DD DISP=SHR,DSN=GENAPP.DDSCIN33.DATA
//DDSCOT33 DD DISP=SHR,DSN=GENAPP.DDSCOT33.DATA
//DDSCRP33 DD DISP=SHR,DSN=GENAPP.DDSCRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
