//VJOB1774 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01Z8B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN13 DD DISP=SHR,DSN=GENAPP.DDAVIN13.DATA
//DDAVOT13 DD DISP=SHR,DSN=GENAPP.DDAVOT13.DATA
//DDAVRP13 DD DISP=SHR,DSN=GENAPP.DDAVRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01Z8C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN14 DD DISP=SHR,DSN=GENAPP.DDAGIN14.DATA
//DDAGOT14 DD DISP=SHR,DSN=GENAPP.DDAGOT14.DATA
//DDAGRP14 DD DISP=SHR,DSN=GENAPP.DDAGRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG01Z8D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN15 DD DISP=SHR,DSN=GENAPP.DDRGIN15.DATA
//DDRGOT15 DD DISP=SHR,DSN=GENAPP.DDRGOT15.DATA
//DDRGRP15 DD DISP=SHR,DSN=GENAPP.DDRGRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
