//VJOB4193 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDO024TW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN70 DD DISP=SHR,DSN=GENAPP.DDDOIN70.DATA
//DDDOOT70 DD DISP=SHR,DSN=GENAPP.DDDOOT70.DATA
//DDDORP70 DD DISP=SHR,DSN=GENAPP.DDDORP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV024TX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN71 DD DISP=SHR,DSN=GENAPP.DDIVIN71.DATA
//DDIVOT71 DD DISP=SHR,DSN=GENAPP.DDIVOT71.DATA
//DDIVRP71 DD DISP=SHR,DSN=GENAPP.DDIVRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT024TY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN72 DD DISP=SHR,DSN=GENAPP.DDPTIN72.DATA
//DDPTOT72 DD DISP=SHR,DSN=GENAPP.DDPTOT72.DATA
//DDPTRP72 DD DISP=SHR,DSN=GENAPP.DDPTRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
