//VJOB1510 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA01YMB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN31 DD DISP=SHR,DSN=GENAPP.DDPAIN31.DATA
//DDPAOT31 DD DISP=SHR,DSN=GENAPP.DDPAOT31.DATA
//DDPARP31 DD DISP=SHR,DSN=GENAPP.DDPARP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ01YMC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN32 DD DISP=SHR,DSN=GENAPP.DDAZIN32.DATA
//DDAZOT32 DD DISP=SHR,DSN=GENAPP.DDAZOT32.DATA
//DDAZRP32 DD DISP=SHR,DSN=GENAPP.DDAZRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01YMD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN33 DD DISP=SHR,DSN=GENAPP.DDBIIN33.DATA
//DDBIOT33 DD DISP=SHR,DSN=GENAPP.DDBIOT33.DATA
//DDBIRP33 DD DISP=SHR,DSN=GENAPP.DDBIRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
