//VJOB1155 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01XSQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN46 DD DISP=SHR,DSN=GENAPP.DDBIIN46.DATA
//DDBIOT46 DD DISP=SHR,DSN=GENAPP.DDBIOT46.DATA
//DDBIRP46 DD DISP=SHR,DSN=GENAPP.DDBIRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRS01XSR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN47 DD DISP=SHR,DSN=GENAPP.DDRSIN47.DATA
//DDRSOT47 DD DISP=SHR,DSN=GENAPP.DDRSOT47.DATA
//DDRSRP47 DD DISP=SHR,DSN=GENAPP.DDRSRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR01XSS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN48 DD DISP=SHR,DSN=GENAPP.DDBRIN48.DATA
//DDBROT48 DD DISP=SHR,DSN=GENAPP.DDBROT48.DATA
//DDBRRP48 DD DISP=SHR,DSN=GENAPP.DDBRRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
