//VJOB4322 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB0254N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN07 DD DISP=SHR,DSN=GENAPP.DDMBIN07.DATA
//DDMBOT07 DD DISP=SHR,DSN=GENAPP.DDMBOT07.DATA
//DDMBRP07 DD DISP=SHR,DSN=GENAPP.DDMBRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL0254O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN08 DD DISP=SHR,DSN=GENAPP.DDCLIN08.DATA
//DDCLOT08 DD DISP=SHR,DSN=GENAPP.DDCLOT08.DATA
//DDCLRP08 DD DISP=SHR,DSN=GENAPP.DDCLRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI0254P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN09 DD DISP=SHR,DSN=GENAPP.DDLIIN09.DATA
//DDLIOT09 DD DISP=SHR,DSN=GENAPP.DDLIOT09.DATA
//DDLIRP09 DD DISP=SHR,DSN=GENAPP.DDLIRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
