//VJOB0968 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCR01XD5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN25 DD DISP=SHR,DSN=GENAPP.DDCRIN25.DATA
//DDCROT25 DD DISP=SHR,DSN=GENAPP.DDCROT25.DATA
//DDCRRP25 DD DISP=SHR,DSN=GENAPP.DDCRRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01XD6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN26 DD DISP=SHR,DSN=GENAPP.DDCUIN26.DATA
//DDCUOT26 DD DISP=SHR,DSN=GENAPP.DDCUOT26.DATA
//DDCURP26 DD DISP=SHR,DSN=GENAPP.DDCURP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRN01XD7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN27 DD DISP=SHR,DSN=GENAPP.DDRNIN27.DATA
//DDRNOT27 DD DISP=SHR,DSN=GENAPP.DDRNOT27.DATA
//DDRNRP27 DD DISP=SHR,DSN=GENAPP.DDRNRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
