//VJOB4089 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE024L8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN28 DD DISP=SHR,DSN=GENAPP.DDPEIN28.DATA
//DDPEOT28 DD DISP=SHR,DSN=GENAPP.DDPEOT28.DATA
//DDPERP28 DD DISP=SHR,DSN=GENAPP.DDPERP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO024L9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN29 DD DISP=SHR,DSN=GENAPP.DDHOIN29.DATA
//DDHOOT29 DD DISP=SHR,DSN=GENAPP.DDHOOT29.DATA
//DDHORP29 DD DISP=SHR,DSN=GENAPP.DDHORP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR024LA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN30 DD DISP=SHR,DSN=GENAPP.DDARIN30.DATA
//DDAROT30 DD DISP=SHR,DSN=GENAPP.DDAROT30.DATA
//DDARRP30 DD DISP=SHR,DSN=GENAPP.DDARRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
