//VJOB4319 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT0254E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN88 DD DISP=SHR,DSN=GENAPP.DDMTIN88.DATA
//DDMTOT88 DD DISP=SHR,DSN=GENAPP.DDMTOT88.DATA
//DDMTRP88 DD DISP=SHR,DSN=GENAPP.DDMTRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0254F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN89 DD DISP=SHR,DSN=GENAPP.DDMTIN89.DATA
//DDMTOT89 DD DISP=SHR,DSN=GENAPP.DDMTOT89.DATA
//DDMTRP89 DD DISP=SHR,DSN=GENAPP.DDMTRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE0254G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN90 DD DISP=SHR,DSN=GENAPP.DDHEIN90.DATA
//DDHEOT90 DD DISP=SHR,DSN=GENAPP.DDHEOT90.DATA
//DDHERP90 DD DISP=SHR,DSN=GENAPP.DDHERP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
