//VJOB2421 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL020Q8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN64 DD DISP=SHR,DSN=GENAPP.DDFLIN64.DATA
//DDFLOT64 DD DISP=SHR,DSN=GENAPP.DDFLOT64.DATA
//DDFLRP64 DD DISP=SHR,DSN=GENAPP.DDFLRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN020Q9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN65 DD DISP=SHR,DSN=GENAPP.DDANIN65.DATA
//DDANOT65 DD DISP=SHR,DSN=GENAPP.DDANOT65.DATA
//DDANRP65 DD DISP=SHR,DSN=GENAPP.DDANRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR020QA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN66 DD DISP=SHR,DSN=GENAPP.DDFRIN66.DATA
//DDFROT66 DD DISP=SHR,DSN=GENAPP.DDFROT66.DATA
//DDFRRP66 DD DISP=SHR,DSN=GENAPP.DDFRRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
