//VJOB4208 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL024V5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN25 DD DISP=SHR,DSN=GENAPP.DDFLIN25.DATA
//DDFLOT25 DD DISP=SHR,DSN=GENAPP.DDFLOT25.DATA
//DDFLRP25 DD DISP=SHR,DSN=GENAPP.DDFLRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZGW024V6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN26 DD DISP=SHR,DSN=GENAPP.DDGWIN26.DATA
//DDGWOT26 DD DISP=SHR,DSN=GENAPP.DDGWOT26.DATA
//DDGWRP26 DD DISP=SHR,DSN=GENAPP.DDGWRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL024V7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN27 DD DISP=SHR,DSN=GENAPP.DDCLIN27.DATA
//DDCLOT27 DD DISP=SHR,DSN=GENAPP.DDCLOT27.DATA
//DDCLRP27 DD DISP=SHR,DSN=GENAPP.DDCLRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
