//VJOB3810 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT023XZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN01 DD DISP=SHR,DSN=GENAPP.DDPTIN01.DATA
//DDPTOT01 DD DISP=SHR,DSN=GENAPP.DDPTOT01.DATA
//DDPTRP01 DD DISP=SHR,DSN=GENAPP.DDPTRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN023Y0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN02 DD DISP=SHR,DSN=GENAPP.DDRNIN02.DATA
//DDRNOT02 DD DISP=SHR,DSN=GENAPP.DDRNOT02.DATA
//DDRNRP02 DD DISP=SHR,DSN=GENAPP.DDRNRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG023Y1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN03 DD DISP=SHR,DSN=GENAPP.DDRGIN03.DATA
//DDRGOT03 DD DISP=SHR,DSN=GENAPP.DDRGOT03.DATA
//DDRGRP03 DD DISP=SHR,DSN=GENAPP.DDRGRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
