//VJOB3563 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE023DE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN70 DD DISP=SHR,DSN=GENAPP.DDREIN70.DATA
//DDREOT70 DD DISP=SHR,DSN=GENAPP.DDREOT70.DATA
//DDRERP70 DD DISP=SHR,DSN=GENAPP.DDRERP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN023DF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN71 DD DISP=SHR,DSN=GENAPP.DDENIN71.DATA
//DDENOT71 DD DISP=SHR,DSN=GENAPP.DDENOT71.DATA
//DDENRP71 DD DISP=SHR,DSN=GENAPP.DDENRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL023DG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN72 DD DISP=SHR,DSN=GENAPP.DDFLIN72.DATA
//DDFLOT72 DD DISP=SHR,DSN=GENAPP.DDFLOT72.DATA
//DDFLRP72 DD DISP=SHR,DSN=GENAPP.DDFLRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
