//VJOB1773 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE01Z88
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN10 DD DISP=SHR,DSN=GENAPP.DDREIN10.DATA
//DDREOT10 DD DISP=SHR,DSN=GENAPP.DDREOT10.DATA
//DDRERP10 DD DISP=SHR,DSN=GENAPP.DDRERP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF01Z89
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN11 DD DISP=SHR,DSN=GENAPP.DDIFIN11.DATA
//DDIFOT11 DD DISP=SHR,DSN=GENAPP.DDIFOT11.DATA
//DDIFRP11 DD DISP=SHR,DSN=GENAPP.DDIFRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01Z8A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN12 DD DISP=SHR,DSN=GENAPP.DDMTIN12.DATA
//DDMTOT12 DD DISP=SHR,DSN=GENAPP.DDMTOT12.DATA
//DDMTRP12 DD DISP=SHR,DSN=GENAPP.DDMTRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
