//VJOB1046 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01XJN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN79 DD DISP=SHR,DSN=GENAPP.DDRGIN79.DATA
//DDRGOT79 DD DISP=SHR,DSN=GENAPP.DDRGOT79.DATA
//DDRGRP79 DD DISP=SHR,DSN=GENAPP.DDRGRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR01XJO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN80 DD DISP=SHR,DSN=GENAPP.DDTRIN80.DATA
//DDTROT80 DD DISP=SHR,DSN=GENAPP.DDTROT80.DATA
//DDTRRP80 DD DISP=SHR,DSN=GENAPP.DDTRRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01XJP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN81 DD DISP=SHR,DSN=GENAPP.DDMAIN81.DATA
//DDMAOT81 DD DISP=SHR,DSN=GENAPP.DDMAOT81.DATA
//DDMARP81 DD DISP=SHR,DSN=GENAPP.DDMARP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
