//VJOB2034 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSU01ZTZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN73 DD DISP=SHR,DSN=GENAPP.DDSUIN73.DATA
//DDSUOT73 DD DISP=SHR,DSN=GENAPP.DDSUOT73.DATA
//DDSURP73 DD DISP=SHR,DSN=GENAPP.DDSURP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA01ZU0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN74 DD DISP=SHR,DSN=GENAPP.DDMAIN74.DATA
//DDMAOT74 DD DISP=SHR,DSN=GENAPP.DDMAOT74.DATA
//DDMARP74 DD DISP=SHR,DSN=GENAPP.DDMARP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW01ZU1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN75 DD DISP=SHR,DSN=GENAPP.DDUWIN75.DATA
//DDUWOT75 DD DISP=SHR,DSN=GENAPP.DDUWOT75.DATA
//DDUWRP75 DD DISP=SHR,DSN=GENAPP.DDUWRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
