//VJOB1832 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01ZD5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN07 DD DISP=SHR,DSN=GENAPP.DDRGIN07.DATA
//DDRGOT07 DD DISP=SHR,DSN=GENAPP.DDRGOT07.DATA
//DDRGRP07 DD DISP=SHR,DSN=GENAPP.DDRGRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR01ZD6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN08 DD DISP=SHR,DSN=GENAPP.DDPRIN08.DATA
//DDPROT08 DD DISP=SHR,DSN=GENAPP.DDPROT08.DATA
//DDPRRP08 DD DISP=SHR,DSN=GENAPP.DDPRRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTY01ZD7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN09 DD DISP=SHR,DSN=GENAPP.DDTYIN09.DATA
//DDTYOT09 DD DISP=SHR,DSN=GENAPP.DDTYOT09.DATA
//DDTYRP09 DD DISP=SHR,DSN=GENAPP.DDTYRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
