//VJOB0461 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRT01W6W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN34 DD DISP=SHR,DSN=GENAPP.DDRTIN34.DATA
//DDRTOT34 DD DISP=SHR,DSN=GENAPP.DDRTOT34.DATA
//DDRTRP34 DD DISP=SHR,DSN=GENAPP.DDRTRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZVA01W6X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN35 DD DISP=SHR,DSN=GENAPP.DDVAIN35.DATA
//DDVAOT35 DD DISP=SHR,DSN=GENAPP.DDVAOT35.DATA
//DDVARP35 DD DISP=SHR,DSN=GENAPP.DDVARP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV01W6Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN36 DD DISP=SHR,DSN=GENAPP.DDAVIN36.DATA
//DDAVOT36 DD DISP=SHR,DSN=GENAPP.DDAVOT36.DATA
//DDAVRP36 DD DISP=SHR,DSN=GENAPP.DDAVRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
