//VJOB0686 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA01WPN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN79 DD DISP=SHR,DSN=GENAPP.DDPAIN79.DATA
//DDPAOT79 DD DISP=SHR,DSN=GENAPP.DDPAOT79.DATA
//DDPARP79 DD DISP=SHR,DSN=GENAPP.DDPARP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO01WPO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN80 DD DISP=SHR,DSN=GENAPP.DDCOIN80.DATA
//DDCOOT80 DD DISP=SHR,DSN=GENAPP.DDCOOT80.DATA
//DDCORP80 DD DISP=SHR,DSN=GENAPP.DDCORP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01WPP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN81 DD DISP=SHR,DSN=GENAPP.DDREIN81.DATA
//DDREOT81 DD DISP=SHR,DSN=GENAPP.DDREOT81.DATA
//DDRERP81 DD DISP=SHR,DSN=GENAPP.DDRERP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
