//VJOB2304 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT020GH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN73 DD DISP=SHR,DSN=GENAPP.DDMTIN73.DATA
//DDMTOT73 DD DISP=SHR,DSN=GENAPP.DDMTOT73.DATA
//DDMTRP73 DD DISP=SHR,DSN=GENAPP.DDMTRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZVA020GI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN74 DD DISP=SHR,DSN=GENAPP.DDVAIN74.DATA
//DDVAOT74 DD DISP=SHR,DSN=GENAPP.DDVAOT74.DATA
//DDVARP74 DD DISP=SHR,DSN=GENAPP.DDVARP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL020GJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN75 DD DISP=SHR,DSN=GENAPP.DDFLIN75.DATA
//DDFLOT75 DD DISP=SHR,DSN=GENAPP.DDFLOT75.DATA
//DDFLRP75 DD DISP=SHR,DSN=GENAPP.DDFLRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
