//VJOB1181 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS01XUW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN34 DD DISP=SHR,DSN=GENAPP.DDRSIN34.DATA
//DDRSOT34 DD DISP=SHR,DSN=GENAPP.DDRSOT34.DATA
//DDRSRP34 DD DISP=SHR,DSN=GENAPP.DDRSRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ01XUX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN35 DD DISP=SHR,DSN=GENAPP.DDAZIN35.DATA
//DDAZOT35 DD DISP=SHR,DSN=GENAPP.DDAZOT35.DATA
//DDAZRP35 DD DISP=SHR,DSN=GENAPP.DDAZRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01XUY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN36 DD DISP=SHR,DSN=GENAPP.DDMTIN36.DATA
//DDMTOT36 DD DISP=SHR,DSN=GENAPP.DDMTOT36.DATA
//DDMTRP36 DD DISP=SHR,DSN=GENAPP.DDMTRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
