//VJOB3771 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL023UQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN64 DD DISP=SHR,DSN=GENAPP.DDCLIN64.DATA
//DDCLOT64 DD DISP=SHR,DSN=GENAPP.DDCLOT64.DATA
//DDCLRP64 DD DISP=SHR,DSN=GENAPP.DDCLRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ023UR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN65 DD DISP=SHR,DSN=GENAPP.DDAZIN65.DATA
//DDAZOT65 DD DISP=SHR,DSN=GENAPP.DDAZOT65.DATA
//DDAZRP65 DD DISP=SHR,DSN=GENAPP.DDAZRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI023US
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN66 DD DISP=SHR,DSN=GENAPP.DDBIIN66.DATA
//DDBIOT66 DD DISP=SHR,DSN=GENAPP.DDBIOT66.DATA
//DDBIRP66 DD DISP=SHR,DSN=GENAPP.DDBIRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
