//VJOB0138 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01VFZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN55 DD DISP=SHR,DSN=GENAPP.DDENIN55.DATA
//DDENOT55 DD DISP=SHR,DSN=GENAPP.DDENOT55.DATA
//DDENRP55 DD DISP=SHR,DSN=GENAPP.DDENRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01VG0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN56 DD DISP=SHR,DSN=GENAPP.DDMTIN56.DATA
//DDMTOT56 DD DISP=SHR,DSN=GENAPP.DDMTOT56.DATA
//DDMTRP56 DD DISP=SHR,DSN=GENAPP.DDMTRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01VG1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN57 DD DISP=SHR,DSN=GENAPP.DDPRIN57.DATA
//DDPROT57 DD DISP=SHR,DSN=GENAPP.DDPROT57.DATA
//DDPRRP57 DD DISP=SHR,DSN=GENAPP.DDPRRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
