//VJOB4262 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU024ZN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN07 DD DISP=SHR,DSN=GENAPP.DDCUIN07.DATA
//DDCUOT07 DD DISP=SHR,DSN=GENAPP.DDCUOT07.DATA
//DDCURP07 DD DISP=SHR,DSN=GENAPP.DDCURP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE024ZO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN08 DD DISP=SHR,DSN=GENAPP.DDPEIN08.DATA
//DDPEOT08 DD DISP=SHR,DSN=GENAPP.DDPEOT08.DATA
//DDPERP08 DD DISP=SHR,DSN=GENAPP.DDPERP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT024ZP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN09 DD DISP=SHR,DSN=GENAPP.DDMTIN09.DATA
//DDMTOT09 DD DISP=SHR,DSN=GENAPP.DDMTOT09.DATA
//DDMTRP09 DD DISP=SHR,DSN=GENAPP.DDMTRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
