//VJOB2549 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR0210W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN88 DD DISP=SHR,DSN=GENAPP.DDTRIN88.DATA
//DDTROT88 DD DISP=SHR,DSN=GENAPP.DDTROT88.DATA
//DDTRRP88 DD DISP=SHR,DSN=GENAPP.DDTRRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE0210X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN89 DD DISP=SHR,DSN=GENAPP.DDPEIN89.DATA
//DDPEOT89 DD DISP=SHR,DSN=GENAPP.DDPEOT89.DATA
//DDPERP89 DD DISP=SHR,DSN=GENAPP.DDPERP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL0210Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN90 DD DISP=SHR,DSN=GENAPP.DDCLIN90.DATA
//DDCLOT90 DD DISP=SHR,DSN=GENAPP.DDCLOT90.DATA
//DDCLRP90 DD DISP=SHR,DSN=GENAPP.DDCLRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
