//VJOB0155 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE01VHE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN16 DD DISP=SHR,DSN=GENAPP.DDREIN16.DATA
//DDREOT16 DD DISP=SHR,DSN=GENAPP.DDREOT16.DATA
//DDRERP16 DD DISP=SHR,DSN=GENAPP.DDRERP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDO01VHF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN17 DD DISP=SHR,DSN=GENAPP.DDDOIN17.DATA
//DDDOOT17 DD DISP=SHR,DSN=GENAPP.DDDOOT17.DATA
//DDDORP17 DD DISP=SHR,DSN=GENAPP.DDDORP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTY01VHG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN18 DD DISP=SHR,DSN=GENAPP.DDTYIN18.DATA
//DDTYOT18 DD DISP=SHR,DSN=GENAPP.DDTYOT18.DATA
//DDTYRP18 DD DISP=SHR,DSN=GENAPP.DDTYRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
