//VJOB1438 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01YGB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN85 DD DISP=SHR,DSN=GENAPP.DDBIIN85.DATA
//DDBIOT85 DD DISP=SHR,DSN=GENAPP.DDBIOT85.DATA
//DDBIRP85 DD DISP=SHR,DSN=GENAPP.DDBIRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01YGC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN86 DD DISP=SHR,DSN=GENAPP.DDAGIN86.DATA
//DDAGOT86 DD DISP=SHR,DSN=GENAPP.DDAGOT86.DATA
//DDAGRP86 DD DISP=SHR,DSN=GENAPP.DDAGRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLB01YGD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN87 DD DISP=SHR,DSN=GENAPP.DDLBIN87.DATA
//DDLBOT87 DD DISP=SHR,DSN=GENAPP.DDLBOT87.DATA
//DDLBRP87 DD DISP=SHR,DSN=GENAPP.DDLBRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
