//VJOB4244 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZED024Y5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN43 DD DISP=SHR,DSN=GENAPP.DDEDIN43.DATA
//DDEDOT43 DD DISP=SHR,DSN=GENAPP.DDEDOT43.DATA
//DDEDRP43 DD DISP=SHR,DSN=GENAPP.DDEDRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR024Y6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN44 DD DISP=SHR,DSN=GENAPP.DDPRIN44.DATA
//DDPROT44 DD DISP=SHR,DSN=GENAPP.DDPROT44.DATA
//DDPRRP44 DD DISP=SHR,DSN=GENAPP.DDPRRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA024Y7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN45 DD DISP=SHR,DSN=GENAPP.DDPAIN45.DATA
//DDPAOT45 DD DISP=SHR,DSN=GENAPP.DDPAOT45.DATA
//DDPARP45 DD DISP=SHR,DSN=GENAPP.DDPARP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
