//VJOB2300 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN020G5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN61 DD DISP=SHR,DSN=GENAPP.DDANIN61.DATA
//DDANOT61 DD DISP=SHR,DSN=GENAPP.DDANOT61.DATA
//DDANRP61 DD DISP=SHR,DSN=GENAPP.DDANRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE020G6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN62 DD DISP=SHR,DSN=GENAPP.DDHEIN62.DATA
//DDHEOT62 DD DISP=SHR,DSN=GENAPP.DDHEOT62.DATA
//DDHERP62 DD DISP=SHR,DSN=GENAPP.DDHERP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN020G7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN63 DD DISP=SHR,DSN=GENAPP.DDENIN63.DATA
//DDENOT63 DD DISP=SHR,DSN=GENAPP.DDENOT63.DATA
//DDENRP63 DD DISP=SHR,DSN=GENAPP.DDENRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
