//VJOB1624 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPR01YVT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN13 DD DISP=SHR,DSN=GENAPP.DDPRIN13.DATA
//DDPROT13 DD DISP=SHR,DSN=GENAPP.DDPROT13.DATA
//DDPRRP13 DD DISP=SHR,DSN=GENAPP.DDPRRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMB01YVU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN14 DD DISP=SHR,DSN=GENAPP.DDMBIN14.DATA
//DDMBOT14 DD DISP=SHR,DSN=GENAPP.DDMBOT14.DATA
//DDMBRP14 DD DISP=SHR,DSN=GENAPP.DDMBRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDI01YVV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN15 DD DISP=SHR,DSN=GENAPP.DDDIIN15.DATA
//DDDIOT15 DD DISP=SHR,DSN=GENAPP.DDDIOT15.DATA
//DDDIRP15 DD DISP=SHR,DSN=GENAPP.DDDIRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
