//VJOB0749 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZGW01WUW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN88 DD DISP=SHR,DSN=GENAPP.DDGWIN88.DATA
//DDGWOT88 DD DISP=SHR,DSN=GENAPP.DDGWOT88.DATA
//DDGWRP88 DD DISP=SHR,DSN=GENAPP.DDGWRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01WUX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN89 DD DISP=SHR,DSN=GENAPP.DDCLIN89.DATA
//DDCLOT89 DD DISP=SHR,DSN=GENAPP.DDCLOT89.DATA
//DDCLRP89 DD DISP=SHR,DSN=GENAPP.DDCLRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01WUY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN90 DD DISP=SHR,DSN=GENAPP.DDCLIN90.DATA
//DDCLOT90 DD DISP=SHR,DSN=GENAPP.DDCLOT90.DATA
//DDCLRP90 DD DISP=SHR,DSN=GENAPP.DDCLRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
