//VJOB3407 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDO0230E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN52 DD DISP=SHR,DSN=GENAPP.DDDOIN52.DATA
//DDDOOT52 DD DISP=SHR,DSN=GENAPP.DDDOOT52.DATA
//DDDORP52 DD DISP=SHR,DSN=GENAPP.DDDORP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU0230F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN53 DD DISP=SHR,DSN=GENAPP.DDCUIN53.DATA
//DDCUOT53 DD DISP=SHR,DSN=GENAPP.DDCUOT53.DATA
//DDCURP53 DD DISP=SHR,DSN=GENAPP.DDCURP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI0230G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN54 DD DISP=SHR,DSN=GENAPP.DDBIIN54.DATA
//DDBIOT54 DD DISP=SHR,DSN=GENAPP.DDBIOT54.DATA
//DDBIRP54 DD DISP=SHR,DSN=GENAPP.DDBIRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
