//VJOB2437 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW020RK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN22 DD DISP=SHR,DSN=GENAPP.DDUWIN22.DATA
//DDUWOT22 DD DISP=SHR,DSN=GENAPP.DDUWOT22.DATA
//DDUWRP22 DD DISP=SHR,DSN=GENAPP.DDUWRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT020RL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN23 DD DISP=SHR,DSN=GENAPP.DDMTIN23.DATA
//DDMTOT23 DD DISP=SHR,DSN=GENAPP.DDMTOT23.DATA
//DDMTRP23 DD DISP=SHR,DSN=GENAPP.DDMTRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN020RM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN24 DD DISP=SHR,DSN=GENAPP.DDPNIN24.DATA
//DDPNOT24 DD DISP=SHR,DSN=GENAPP.DDPNOT24.DATA
//DDPNRP24 DD DISP=SHR,DSN=GENAPP.DDPNRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
