//VJOB3352 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN022VT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN67 DD DISP=SHR,DSN=GENAPP.DDENIN67.DATA
//DDENOT67 DD DISP=SHR,DSN=GENAPP.DDENOT67.DATA
//DDENRP67 DD DISP=SHR,DSN=GENAPP.DDENRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT022VU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN68 DD DISP=SHR,DSN=GENAPP.DDMTIN68.DATA
//DDMTOT68 DD DISP=SHR,DSN=GENAPP.DDMTOT68.DATA
//DDMTRP68 DD DISP=SHR,DSN=GENAPP.DDMTRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL022VV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN69 DD DISP=SHR,DSN=GENAPP.DDCLIN69.DATA
//DDCLOT69 DD DISP=SHR,DSN=GENAPP.DDCLOT69.DATA
//DDCLRP69 DD DISP=SHR,DSN=GENAPP.DDCLRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
