//VJOB3434 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN0232N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN43 DD DISP=SHR,DSN=GENAPP.DDANIN43.DATA
//DDANOT43 DD DISP=SHR,DSN=GENAPP.DDANOT43.DATA
//DDANRP43 DD DISP=SHR,DSN=GENAPP.DDANRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0232O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN44 DD DISP=SHR,DSN=GENAPP.DDMTIN44.DATA
//DDMTOT44 DD DISP=SHR,DSN=GENAPP.DDMTOT44.DATA
//DDMTRP44 DD DISP=SHR,DSN=GENAPP.DDMTRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI0232P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN45 DD DISP=SHR,DSN=GENAPP.DDBIIN45.DATA
//DDBIOT45 DD DISP=SHR,DSN=GENAPP.DDBIOT45.DATA
//DDBIRP45 DD DISP=SHR,DSN=GENAPP.DDBIRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
