//VJOB1358 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP01Y9N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN25 DD DISP=SHR,DSN=GENAPP.DDCPIN25.DATA
//DDCPOT25 DD DISP=SHR,DSN=GENAPP.DDCPOT25.DATA
//DDCPRP25 DD DISP=SHR,DSN=GENAPP.DDCPRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRS01Y9O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN26 DD DISP=SHR,DSN=GENAPP.DDRSIN26.DATA
//DDRSOT26 DD DISP=SHR,DSN=GENAPP.DDRSOT26.DATA
//DDRSRP26 DD DISP=SHR,DSN=GENAPP.DDRSRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01Y9P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN27 DD DISP=SHR,DSN=GENAPP.DDMAIN27.DATA
//DDMAOT27 DD DISP=SHR,DSN=GENAPP.DDMAOT27.DATA
//DDMARP27 DD DISP=SHR,DSN=GENAPP.DDMARP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
