//VJOB2951 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT021YE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN34 DD DISP=SHR,DSN=GENAPP.DDNTIN34.DATA
//DDNTOT34 DD DISP=SHR,DSN=GENAPP.DDNTOT34.DATA
//DDNTRP34 DD DISP=SHR,DSN=GENAPP.DDNTRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO021YF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN35 DD DISP=SHR,DSN=GENAPP.DDHOIN35.DATA
//DDHOOT35 DD DISP=SHR,DSN=GENAPP.DDHOOT35.DATA
//DDHORP35 DD DISP=SHR,DSN=GENAPP.DDHORP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO021YG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN36 DD DISP=SHR,DSN=GENAPP.DDHOIN36.DATA
//DDHOOT36 DD DISP=SHR,DSN=GENAPP.DDHOOT36.DATA
//DDHORP36 DD DISP=SHR,DSN=GENAPP.DDHORP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
