//VJOB1410 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01YDZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN01 DD DISP=SHR,DSN=GENAPP.DDCUIN01.DATA
//DDCUOT01 DD DISP=SHR,DSN=GENAPP.DDCUOT01.DATA
//DDCURP01 DD DISP=SHR,DSN=GENAPP.DDCURP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN01YE0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN02 DD DISP=SHR,DSN=GENAPP.DDPNIN02.DATA
//DDPNOT02 DD DISP=SHR,DSN=GENAPP.DDPNOT02.DATA
//DDPNRP02 DD DISP=SHR,DSN=GENAPP.DDPNRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR01YE1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN03 DD DISP=SHR,DSN=GENAPP.DDBRIN03.DATA
//DDBROT03 DD DISP=SHR,DSN=GENAPP.DDBROT03.DATA
//DDBRRP03 DD DISP=SHR,DSN=GENAPP.DDBRRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
