//VJOB0184 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP01VJT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN13 DD DISP=SHR,DSN=GENAPP.DDCPIN13.DATA
//DDCPOT13 DD DISP=SHR,DSN=GENAPP.DDCPOT13.DATA
//DDCPRP13 DD DISP=SHR,DSN=GENAPP.DDCPRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ01VJU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN14 DD DISP=SHR,DSN=GENAPP.DDAZIN14.DATA
//DDAZOT14 DD DISP=SHR,DSN=GENAPP.DDAZOT14.DATA
//DDAZRP14 DD DISP=SHR,DSN=GENAPP.DDAZRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01VJV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN15 DD DISP=SHR,DSN=GENAPP.DDMAIN15.DATA
//DDMAOT15 DD DISP=SHR,DSN=GENAPP.DDMAOT15.DATA
//DDMARP15 DD DISP=SHR,DSN=GENAPP.DDMARP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
