//VJOB4111 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN024N2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN04 DD DISP=SHR,DSN=GENAPP.DDANIN04.DATA
//DDANOT04 DD DISP=SHR,DSN=GENAPP.DDANOT04.DATA
//DDANRP04 DD DISP=SHR,DSN=GENAPP.DDANRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU024N3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN05 DD DISP=SHR,DSN=GENAPP.DDCUIN05.DATA
//DDCUOT05 DD DISP=SHR,DSN=GENAPP.DDCUOT05.DATA
//DDCURP05 DD DISP=SHR,DSN=GENAPP.DDCURP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR024N4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN06 DD DISP=SHR,DSN=GENAPP.DDTRIN06.DATA
//DDTROT06 DD DISP=SHR,DSN=GENAPP.DDTROT06.DATA
//DDTRRP06 DD DISP=SHR,DSN=GENAPP.DDTRRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
