//VJOB2265 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE020D8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN46 DD DISP=SHR,DSN=GENAPP.DDREIN46.DATA
//DDREOT46 DD DISP=SHR,DSN=GENAPP.DDREOT46.DATA
//DDRERP46 DD DISP=SHR,DSN=GENAPP.DDRERP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF020D9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN47 DD DISP=SHR,DSN=GENAPP.DDIFIN47.DATA
//DDIFOT47 DD DISP=SHR,DSN=GENAPP.DDIFOT47.DATA
//DDIFRP47 DD DISP=SHR,DSN=GENAPP.DDIFRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMB020DA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN48 DD DISP=SHR,DSN=GENAPP.DDMBIN48.DATA
//DDMBOT48 DD DISP=SHR,DSN=GENAPP.DDMBOT48.DATA
//DDMBRP48 DD DISP=SHR,DSN=GENAPP.DDMBRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
