//VJOB2854 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA021QB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN13 DD DISP=SHR,DSN=GENAPP.DDMAIN13.DATA
//DDMAOT13 DD DISP=SHR,DSN=GENAPP.DDMAOT13.DATA
//DDMARP13 DD DISP=SHR,DSN=GENAPP.DDMARP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL021QC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN14 DD DISP=SHR,DSN=GENAPP.DDCLIN14.DATA
//DDCLOT14 DD DISP=SHR,DSN=GENAPP.DDCLOT14.DATA
//DDCLRP14 DD DISP=SHR,DSN=GENAPP.DDCLRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSB021QD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN15 DD DISP=SHR,DSN=GENAPP.DDSBIN15.DATA
//DDSBOT15 DD DISP=SHR,DSN=GENAPP.DDSBOT15.DATA
//DDSBRP15 DD DISP=SHR,DSN=GENAPP.DDSBRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
