//VJOB0362 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX01VYN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN07 DD DISP=SHR,DSN=GENAPP.DDTXIN07.DATA
//DDTXOT07 DD DISP=SHR,DSN=GENAPP.DDTXOT07.DATA
//DDTXRP07 DD DISP=SHR,DSN=GENAPP.DDTXRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA01VYO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN08 DD DISP=SHR,DSN=GENAPP.DDBAIN08.DATA
//DDBAOT08 DD DISP=SHR,DSN=GENAPP.DDBAOT08.DATA
//DDBARP08 DD DISP=SHR,DSN=GENAPP.DDBARP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR01VYP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN09 DD DISP=SHR,DSN=GENAPP.DDFRIN09.DATA
//DDFROT09 DD DISP=SHR,DSN=GENAPP.DDFROT09.DATA
//DDFRRP09 DD DISP=SHR,DSN=GENAPP.DDFRRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
