//VJOB2230 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI020AB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN31 DD DISP=SHR,DSN=GENAPP.DDBIIN31.DATA
//DDBIOT31 DD DISP=SHR,DSN=GENAPP.DDBIOT31.DATA
//DDBIRP31 DD DISP=SHR,DSN=GENAPP.DDBIRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR020AC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN32 DD DISP=SHR,DSN=GENAPP.DDTRIN32.DATA
//DDTROT32 DD DISP=SHR,DSN=GENAPP.DDTROT32.DATA
//DDTRRP32 DD DISP=SHR,DSN=GENAPP.DDTRRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI020AD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN33 DD DISP=SHR,DSN=GENAPP.DDBIIN33.DATA
//DDBIOT33 DD DISP=SHR,DSN=GENAPP.DDBIOT33.DATA
//DDBIRP33 DD DISP=SHR,DSN=GENAPP.DDBIRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
