//VJOB4230 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT024WZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN01 DD DISP=SHR,DSN=GENAPP.DDMTIN01.DATA
//DDMTOT01 DD DISP=SHR,DSN=GENAPP.DDMTOT01.DATA
//DDMTRP01 DD DISP=SHR,DSN=GENAPP.DDMTRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU024X0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN02 DD DISP=SHR,DSN=GENAPP.DDCUIN02.DATA
//DDCUOT02 DD DISP=SHR,DSN=GENAPP.DDCUOT02.DATA
//DDCURP02 DD DISP=SHR,DSN=GENAPP.DDCURP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU024X1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN03 DD DISP=SHR,DSN=GENAPP.DDCUIN03.DATA
//DDCUOT03 DD DISP=SHR,DSN=GENAPP.DDCUOT03.DATA
//DDCURP03 DD DISP=SHR,DSN=GENAPP.DDCURP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
