//VJOB1949 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDO01ZMW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN88 DD DISP=SHR,DSN=GENAPP.DDDOIN88.DATA
//DDDOOT88 DD DISP=SHR,DSN=GENAPP.DDDOOT88.DATA
//DDDORP88 DD DISP=SHR,DSN=GENAPP.DDDORP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01ZMX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN89 DD DISP=SHR,DSN=GENAPP.DDMTIN89.DATA
//DDMTOT89 DD DISP=SHR,DSN=GENAPP.DDMTOT89.DATA
//DDMTRP89 DD DISP=SHR,DSN=GENAPP.DDMTRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRT01ZMY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN90 DD DISP=SHR,DSN=GENAPP.DDRTIN90.DATA
//DDRTOT90 DD DISP=SHR,DSN=GENAPP.DDRTOT90.DATA
//DDRTRP90 DD DISP=SHR,DSN=GENAPP.DDRTRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
