//VJOB3677 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA023MW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN52 DD DISP=SHR,DSN=GENAPP.DDPAIN52.DATA
//DDPAOT52 DD DISP=SHR,DSN=GENAPP.DDPAOT52.DATA
//DDPARP52 DD DISP=SHR,DSN=GENAPP.DDPARP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV023MX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN53 DD DISP=SHR,DSN=GENAPP.DDAVIN53.DATA
//DDAVOT53 DD DISP=SHR,DSN=GENAPP.DDAVOT53.DATA
//DDAVRP53 DD DISP=SHR,DSN=GENAPP.DDAVRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN023MY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN54 DD DISP=SHR,DSN=GENAPP.DDENIN54.DATA
//DDENOT54 DD DISP=SHR,DSN=GENAPP.DDENOT54.DATA
//DDENRP54 DD DISP=SHR,DSN=GENAPP.DDENRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
