//VJOB1750 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCR01Z6B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN31 DD DISP=SHR,DSN=GENAPP.DDCRIN31.DATA
//DDCROT31 DD DISP=SHR,DSN=GENAPP.DDCROT31.DATA
//DDCRRP31 DD DISP=SHR,DSN=GENAPP.DDCRRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE01Z6C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN32 DD DISP=SHR,DSN=GENAPP.DDREIN32.DATA
//DDREOT32 DD DISP=SHR,DSN=GENAPP.DDREOT32.DATA
//DDRERP32 DD DISP=SHR,DSN=GENAPP.DDRERP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01Z6D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN33 DD DISP=SHR,DSN=GENAPP.DDHOIN33.DATA
//DDHOOT33 DD DISP=SHR,DSN=GENAPP.DDHOOT33.DATA
//DDHORP33 DD DISP=SHR,DSN=GENAPP.DDHORP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
