//VJOB3816 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL023YH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN19 DD DISP=SHR,DSN=GENAPP.DDFLIN19.DATA
//DDFLOT19 DD DISP=SHR,DSN=GENAPP.DDFLOT19.DATA
//DDFLRP19 DD DISP=SHR,DSN=GENAPP.DDFLRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI023YI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN20 DD DISP=SHR,DSN=GENAPP.DDBIIN20.DATA
//DDBIOT20 DD DISP=SHR,DSN=GENAPP.DDBIOT20.DATA
//DDBIRP20 DD DISP=SHR,DSN=GENAPP.DDBIRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV023YJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN21 DD DISP=SHR,DSN=GENAPP.DDAVIN21.DATA
//DDAVOT21 DD DISP=SHR,DSN=GENAPP.DDAVOT21.DATA
//DDAVRP21 DD DISP=SHR,DSN=GENAPP.DDAVRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
