//VJOB2577 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRN02138
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN82 DD DISP=SHR,DSN=GENAPP.DDRNIN82.DATA
//DDRNOT82 DD DISP=SHR,DSN=GENAPP.DDRNOT82.DATA
//DDRNRP82 DD DISP=SHR,DSN=GENAPP.DDRNRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE02139
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN83 DD DISP=SHR,DSN=GENAPP.DDSEIN83.DATA
//DDSEOT83 DD DISP=SHR,DSN=GENAPP.DDSEOT83.DATA
//DDSERP83 DD DISP=SHR,DSN=GENAPP.DDSERP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG0213A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN84 DD DISP=SHR,DSN=GENAPP.DDRGIN84.DATA
//DDRGOT84 DD DISP=SHR,DSN=GENAPP.DDRGOT84.DATA
//DDRGRP84 DD DISP=SHR,DSN=GENAPP.DDRGRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
