//VJOB1679 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01Z0E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN88 DD DISP=SHR,DSN=GENAPP.DDMTIN88.DATA
//DDMTOT88 DD DISP=SHR,DSN=GENAPP.DDMTOT88.DATA
//DDMTRP88 DD DISP=SHR,DSN=GENAPP.DDMTRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR01Z0F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN89 DD DISP=SHR,DSN=GENAPP.DDTRIN89.DATA
//DDTROT89 DD DISP=SHR,DSN=GENAPP.DDTROT89.DATA
//DDTRRP89 DD DISP=SHR,DSN=GENAPP.DDTRRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA01Z0G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN90 DD DISP=SHR,DSN=GENAPP.DDPAIN90.DATA
//DDPAOT90 DD DISP=SHR,DSN=GENAPP.DDPAOT90.DATA
//DDPARP90 DD DISP=SHR,DSN=GENAPP.DDPARP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
