//VJOB2900 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI021U5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN61 DD DISP=SHR,DSN=GENAPP.DDBIIN61.DATA
//DDBIOT61 DD DISP=SHR,DSN=GENAPP.DDBIOT61.DATA
//DDBIRP61 DD DISP=SHR,DSN=GENAPP.DDBIRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA021U6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN62 DD DISP=SHR,DSN=GENAPP.DDBAIN62.DATA
//DDBAOT62 DD DISP=SHR,DSN=GENAPP.DDBAOT62.DATA
//DDBARP62 DD DISP=SHR,DSN=GENAPP.DDBARP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV021U7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN63 DD DISP=SHR,DSN=GENAPP.DDIVIN63.DATA
//DDIVOT63 DD DISP=SHR,DSN=GENAPP.DDIVOT63.DATA
//DDIVRP63 DD DISP=SHR,DSN=GENAPP.DDIVRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
