//VJOB1329 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01Y78
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN28 DD DISP=SHR,DSN=GENAPP.DDMTIN28.DATA
//DDMTOT28 DD DISP=SHR,DSN=GENAPP.DDMTOT28.DATA
//DDMTRP28 DD DISP=SHR,DSN=GENAPP.DDMTRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT01Y79
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN29 DD DISP=SHR,DSN=GENAPP.DDNTIN29.DATA
//DDNTOT29 DD DISP=SHR,DSN=GENAPP.DDNTOT29.DATA
//DDNTRP29 DD DISP=SHR,DSN=GENAPP.DDNTRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01Y7A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN30 DD DISP=SHR,DSN=GENAPP.DDMAIN30.DATA
//DDMAOT30 DD DISP=SHR,DSN=GENAPP.DDMAOT30.DATA
//DDMARP30 DD DISP=SHR,DSN=GENAPP.DDMARP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
