//VJOB3397 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT022ZK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN22 DD DISP=SHR,DSN=GENAPP.DDMTIN22.DATA
//DDMTOT22 DD DISP=SHR,DSN=GENAPP.DDMTOT22.DATA
//DDMTRP22 DD DISP=SHR,DSN=GENAPP.DDMTRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU022ZL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN23 DD DISP=SHR,DSN=GENAPP.DDCUIN23.DATA
//DDCUOT23 DD DISP=SHR,DSN=GENAPP.DDCUOT23.DATA
//DDCURP23 DD DISP=SHR,DSN=GENAPP.DDCURP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZWF022ZM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN24 DD DISP=SHR,DSN=GENAPP.DDWFIN24.DATA
//DDWFOT24 DD DISP=SHR,DSN=GENAPP.DDWFOT24.DATA
//DDWFRP24 DD DISP=SHR,DSN=GENAPP.DDWFRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
