//VJOB4023 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF024FQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN10 DD DISP=SHR,DSN=GENAPP.DDWFIN10.DATA
//DDWFOT10 DD DISP=SHR,DSN=GENAPP.DDWFOT10.DATA
//DDWFRP10 DD DISP=SHR,DSN=GENAPP.DDWFRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCP024FR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN11 DD DISP=SHR,DSN=GENAPP.DDCPIN11.DATA
//DDCPOT11 DD DISP=SHR,DSN=GENAPP.DDCPOT11.DATA
//DDCPRP11 DD DISP=SHR,DSN=GENAPP.DDCPRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSB024FS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN12 DD DISP=SHR,DSN=GENAPP.DDSBIN12.DATA
//DDSBOT12 DD DISP=SHR,DSN=GENAPP.DDSBOT12.DATA
//DDSBRP12 DD DISP=SHR,DSN=GENAPP.DDSBRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
