//VJOB1413 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL01YE8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN10 DD DISP=SHR,DSN=GENAPP.DDFLIN10.DATA
//DDFLOT10 DD DISP=SHR,DSN=GENAPP.DDFLOT10.DATA
//DDFLRP10 DD DISP=SHR,DSN=GENAPP.DDFLRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01YE9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN11 DD DISP=SHR,DSN=GENAPP.DDCUIN11.DATA
//DDCUOT11 DD DISP=SHR,DSN=GENAPP.DDCUOT11.DATA
//DDCURP11 DD DISP=SHR,DSN=GENAPP.DDCURP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01YEA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN12 DD DISP=SHR,DSN=GENAPP.DDMTIN12.DATA
//DDMTOT12 DD DISP=SHR,DSN=GENAPP.DDMTOT12.DATA
//DDMTRP12 DD DISP=SHR,DSN=GENAPP.DDMTRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
