//VJOB3304 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN022RT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN13 DD DISP=SHR,DSN=GENAPP.DDENIN13.DATA
//DDENOT13 DD DISP=SHR,DSN=GENAPP.DDENOT13.DATA
//DDENRP13 DD DISP=SHR,DSN=GENAPP.DDENRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI022RU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN14 DD DISP=SHR,DSN=GENAPP.DDLIIN14.DATA
//DDLIOT14 DD DISP=SHR,DSN=GENAPP.DDLIOT14.DATA
//DDLIRP14 DD DISP=SHR,DSN=GENAPP.DDLIRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV022RV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN15 DD DISP=SHR,DSN=GENAPP.DDAVIN15.DATA
//DDAVOT15 DD DISP=SHR,DSN=GENAPP.DDAVOT15.DATA
//DDAVRP15 DD DISP=SHR,DSN=GENAPP.DDAVRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
