//VJOB2537 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG020ZW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN52 DD DISP=SHR,DSN=GENAPP.DDAGIN52.DATA
//DDAGOT52 DD DISP=SHR,DSN=GENAPP.DDAGOT52.DATA
//DDAGRP52 DD DISP=SHR,DSN=GENAPP.DDAGRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO020ZX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN53 DD DISP=SHR,DSN=GENAPP.DDCOIN53.DATA
//DDCOOT53 DD DISP=SHR,DSN=GENAPP.DDCOOT53.DATA
//DDCORP53 DD DISP=SHR,DSN=GENAPP.DDCORP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR020ZY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN54 DD DISP=SHR,DSN=GENAPP.DDTRIN54.DATA
//DDTROT54 DD DISP=SHR,DSN=GENAPP.DDTROT54.DATA
//DDTRRP54 DD DISP=SHR,DSN=GENAPP.DDTRRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
