//VJOB2975 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCR0220E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN16 DD DISP=SHR,DSN=GENAPP.DDCRIN16.DATA
//DDCROT16 DD DISP=SHR,DSN=GENAPP.DDCROT16.DATA
//DDCRRP16 DD DISP=SHR,DSN=GENAPP.DDCRRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSB0220F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN17 DD DISP=SHR,DSN=GENAPP.DDSBIN17.DATA
//DDSBOT17 DD DISP=SHR,DSN=GENAPP.DDSBOT17.DATA
//DDSBRP17 DD DISP=SHR,DSN=GENAPP.DDSBRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT0220G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN18 DD DISP=SHR,DSN=GENAPP.DDMTIN18.DATA
//DDMTOT18 DD DISP=SHR,DSN=GENAPP.DDMTOT18.DATA
//DDMTRP18 DD DISP=SHR,DSN=GENAPP.DDMTRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
