//VJOB3995 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI024DE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN16 DD DISP=SHR,DSN=GENAPP.DDBIIN16.DATA
//DDBIOT16 DD DISP=SHR,DSN=GENAPP.DDBIOT16.DATA
//DDBIRP16 DD DISP=SHR,DSN=GENAPP.DDBIRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA024DF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN17 DD DISP=SHR,DSN=GENAPP.DDPAIN17.DATA
//DDPAOT17 DD DISP=SHR,DSN=GENAPP.DDPAOT17.DATA
//DDPARP17 DD DISP=SHR,DSN=GENAPP.DDPARP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG024DG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN18 DD DISP=SHR,DSN=GENAPP.DDRGIN18.DATA
//DDRGOT18 DD DISP=SHR,DSN=GENAPP.DDRGOT18.DATA
//DDRGRP18 DD DISP=SHR,DSN=GENAPP.DDRGRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
