//VJOB1696 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01Z1T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN49 DD DISP=SHR,DSN=GENAPP.DDRGIN49.DATA
//DDRGOT49 DD DISP=SHR,DSN=GENAPP.DDRGOT49.DATA
//DDRGRP49 DD DISP=SHR,DSN=GENAPP.DDRGRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT01Z1U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN50 DD DISP=SHR,DSN=GENAPP.DDNTIN50.DATA
//DDNTOT50 DD DISP=SHR,DSN=GENAPP.DDNTOT50.DATA
//DDNTRP50 DD DISP=SHR,DSN=GENAPP.DDNTRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLB01Z1V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN51 DD DISP=SHR,DSN=GENAPP.DDLBIN51.DATA
//DDLBOT51 DD DISP=SHR,DSN=GENAPP.DDLBOT51.DATA
//DDLBRP51 DD DISP=SHR,DSN=GENAPP.DDLBRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
