//VJOB1299 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01Y4Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN28 DD DISP=SHR,DSN=GENAPP.DDCLIN28.DATA
//DDCLOT28 DD DISP=SHR,DSN=GENAPP.DDCLOT28.DATA
//DDCLRP28 DD DISP=SHR,DSN=GENAPP.DDCLRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT01Y4R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN29 DD DISP=SHR,DSN=GENAPP.DDLTIN29.DATA
//DDLTOT29 DD DISP=SHR,DSN=GENAPP.DDLTOT29.DATA
//DDLTRP29 DD DISP=SHR,DSN=GENAPP.DDLTRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCR01Y4S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN30 DD DISP=SHR,DSN=GENAPP.DDCRIN30.DATA
//DDCROT30 DD DISP=SHR,DSN=GENAPP.DDCROT30.DATA
//DDCRRP30 DD DISP=SHR,DSN=GENAPP.DDCRRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
