//VJOB3442 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW0233B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN67 DD DISP=SHR,DSN=GENAPP.DDUWIN67.DATA
//DDUWOT67 DD DISP=SHR,DSN=GENAPP.DDUWOT67.DATA
//DDUWRP67 DD DISP=SHR,DSN=GENAPP.DDUWRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO0233C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN68 DD DISP=SHR,DSN=GENAPP.DDHOIN68.DATA
//DDHOOT68 DD DISP=SHR,DSN=GENAPP.DDHOOT68.DATA
//DDHORP68 DD DISP=SHR,DSN=GENAPP.DDHORP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT0233D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN69 DD DISP=SHR,DSN=GENAPP.DDMTIN69.DATA
//DDMTOT69 DD DISP=SHR,DSN=GENAPP.DDMTOT69.DATA
//DDMTRP69 DD DISP=SHR,DSN=GENAPP.DDMTRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
