//VJOB3106 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAR022BB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN49 DD DISP=SHR,DSN=GENAPP.DDARIN49.DATA
//DDAROT49 DD DISP=SHR,DSN=GENAPP.DDAROT49.DATA
//DDARRP49 DD DISP=SHR,DSN=GENAPP.DDARRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA022BC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN50 DD DISP=SHR,DSN=GENAPP.DDBAIN50.DATA
//DDBAOT50 DD DISP=SHR,DSN=GENAPP.DDBAOT50.DATA
//DDBARP50 DD DISP=SHR,DSN=GENAPP.DDBARP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO022BD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN51 DD DISP=SHR,DSN=GENAPP.DDHOIN51.DATA
//DDHOOT51 DD DISP=SHR,DSN=GENAPP.DDHOOT51.DATA
//DDHORP51 DD DISP=SHR,DSN=GENAPP.DDHORP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
