//VJOB0024 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG01V6H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN73 DD DISP=SHR,DSN=GENAPP.DDAGIN73.DATA
//DDAGOT73 DD DISP=SHR,DSN=GENAPP.DDAGOT73.DATA
//DDAGRP73 DD DISP=SHR,DSN=GENAPP.DDAGRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR01V6I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN74 DD DISP=SHR,DSN=GENAPP.DDPRIN74.DATA
//DDPROT74 DD DISP=SHR,DSN=GENAPP.DDPROT74.DATA
//DDPRRP74 DD DISP=SHR,DSN=GENAPP.DDPRRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG01V6J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN75 DD DISP=SHR,DSN=GENAPP.DDAGIN75.DATA
//DDAGOT75 DD DISP=SHR,DSN=GENAPP.DDAGOT75.DATA
//DDAGRP75 DD DISP=SHR,DSN=GENAPP.DDAGRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
