//VJOB2496 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAU020WH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN19 DD DISP=SHR,DSN=GENAPP.DDAUIN19.DATA
//DDAUOT19 DD DISP=SHR,DSN=GENAPP.DDAUOT19.DATA
//DDAURP19 DD DISP=SHR,DSN=GENAPP.DDAURP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU020WI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN20 DD DISP=SHR,DSN=GENAPP.DDCUIN20.DATA
//DDCUOT20 DD DISP=SHR,DSN=GENAPP.DDCUOT20.DATA
//DDCURP20 DD DISP=SHR,DSN=GENAPP.DDCURP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA020WJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN21 DD DISP=SHR,DSN=GENAPP.DDPAIN21.DATA
//DDPAOT21 DD DISP=SHR,DSN=GENAPP.DDPAOT21.DATA
//DDPARP21 DD DISP=SHR,DSN=GENAPP.DDPARP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
