//VJOB0639 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01WLQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN28 DD DISP=SHR,DSN=GENAPP.DDENIN28.DATA
//DDENOT28 DD DISP=SHR,DSN=GENAPP.DDENOT28.DATA
//DDENRP28 DD DISP=SHR,DSN=GENAPP.DDENRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01WLR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN29 DD DISP=SHR,DSN=GENAPP.DDAGIN29.DATA
//DDAGOT29 DD DISP=SHR,DSN=GENAPP.DDAGOT29.DATA
//DDAGRP29 DD DISP=SHR,DSN=GENAPP.DDAGRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG01WLS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN30 DD DISP=SHR,DSN=GENAPP.DDAGIN30.DATA
//DDAGOT30 DD DISP=SHR,DSN=GENAPP.DDAGOT30.DATA
//DDAGRP30 DD DISP=SHR,DSN=GENAPP.DDAGRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
