//VJOB0298 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY01VTB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN85 DD DISP=SHR,DSN=GENAPP.DDTYIN85.DATA
//DDTYOT85 DD DISP=SHR,DSN=GENAPP.DDTYOT85.DATA
//DDTYRP85 DD DISP=SHR,DSN=GENAPP.DDTYRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR01VTC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN86 DD DISP=SHR,DSN=GENAPP.DDTRIN86.DATA
//DDTROT86 DD DISP=SHR,DSN=GENAPP.DDTROT86.DATA
//DDTRRP86 DD DISP=SHR,DSN=GENAPP.DDTRRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO01VTD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN87 DD DISP=SHR,DSN=GENAPP.DDCOIN87.DATA
//DDCOOT87 DD DISP=SHR,DSN=GENAPP.DDCOOT87.DATA
//DDCORP87 DD DISP=SHR,DSN=GENAPP.DDCORP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
