//VJOB3481 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV0236K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN04 DD DISP=SHR,DSN=GENAPP.DDAVIN04.DATA
//DDAVOT04 DD DISP=SHR,DSN=GENAPP.DDAVOT04.DATA
//DDAVRP04 DD DISP=SHR,DSN=GENAPP.DDAVRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY0236L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN05 DD DISP=SHR,DSN=GENAPP.DDTYIN05.DATA
//DDTYOT05 DD DISP=SHR,DSN=GENAPP.DDTYOT05.DATA
//DDTYRP05 DD DISP=SHR,DSN=GENAPP.DDTYRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT0236M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN06 DD DISP=SHR,DSN=GENAPP.DDPTIN06.DATA
//DDPTOT06 DD DISP=SHR,DSN=GENAPP.DDPTOT06.DATA
//DDPTRP06 DD DISP=SHR,DSN=GENAPP.DDPTRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
