//VJOB3429 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE02328
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN28 DD DISP=SHR,DSN=GENAPP.DDPEIN28.DATA
//DDPEOT28 DD DISP=SHR,DSN=GENAPP.DDPEOT28.DATA
//DDPERP28 DD DISP=SHR,DSN=GENAPP.DDPERP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAR02329
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN29 DD DISP=SHR,DSN=GENAPP.DDARIN29.DATA
//DDAROT29 DD DISP=SHR,DSN=GENAPP.DDAROT29.DATA
//DDARRP29 DD DISP=SHR,DSN=GENAPP.DDARRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX0232A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN30 DD DISP=SHR,DSN=GENAPP.DDTXIN30.DATA
//DDTXOT30 DD DISP=SHR,DSN=GENAPP.DDTXOT30.DATA
//DDTXRP30 DD DISP=SHR,DSN=GENAPP.DDTXRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
