//VJOB2154 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB0203Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN73 DD DISP=SHR,DSN=GENAPP.DDMBIN73.DATA
//DDMBOT73 DD DISP=SHR,DSN=GENAPP.DDMBOT73.DATA
//DDMBRP73 DD DISP=SHR,DSN=GENAPP.DDMBRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT02040
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN74 DD DISP=SHR,DSN=GENAPP.DDMTIN74.DATA
//DDMTOT74 DD DISP=SHR,DSN=GENAPP.DDMTOT74.DATA
//DDMTRP74 DD DISP=SHR,DSN=GENAPP.DDMTRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL02041
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN75 DD DISP=SHR,DSN=GENAPP.DDCLIN75.DATA
//DDCLOT75 DD DISP=SHR,DSN=GENAPP.DDCLOT75.DATA
//DDCLRP75 DD DISP=SHR,DSN=GENAPP.DDCLRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
