//VJOB3050 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRN0226N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN61 DD DISP=SHR,DSN=GENAPP.DDRNIN61.DATA
//DDRNOT61 DD DISP=SHR,DSN=GENAPP.DDRNOT61.DATA
//DDRNRP61 DD DISP=SHR,DSN=GENAPP.DDRNRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN0226O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN62 DD DISP=SHR,DSN=GENAPP.DDANIN62.DATA
//DDANOT62 DD DISP=SHR,DSN=GENAPP.DDANOT62.DATA
//DDANRP62 DD DISP=SHR,DSN=GENAPP.DDANRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO0226P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN63 DD DISP=SHR,DSN=GENAPP.DDHOIN63.DATA
//DDHOOT63 DD DISP=SHR,DSN=GENAPP.DDHOOT63.DATA
//DDHORP63 DD DISP=SHR,DSN=GENAPP.DDHORP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
