//VJOB3818 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT023YN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN25 DD DISP=SHR,DSN=GENAPP.DDMTIN25.DATA
//DDMTOT25 DD DISP=SHR,DSN=GENAPP.DDMTOT25.DATA
//DDMTRP25 DD DISP=SHR,DSN=GENAPP.DDMTRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR023YO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN26 DD DISP=SHR,DSN=GENAPP.DDPRIN26.DATA
//DDPROT26 DD DISP=SHR,DSN=GENAPP.DDPROT26.DATA
//DDPRRP26 DD DISP=SHR,DSN=GENAPP.DDPRRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW023YP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN27 DD DISP=SHR,DSN=GENAPP.DDUWIN27.DATA
//DDUWOT27 DD DISP=SHR,DSN=GENAPP.DDUWOT27.DATA
//DDUWRP27 DD DISP=SHR,DSN=GENAPP.DDUWRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
