//VJOB0515 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL01WBE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN16 DD DISP=SHR,DSN=GENAPP.DDFLIN16.DATA
//DDFLOT16 DD DISP=SHR,DSN=GENAPP.DDFLOT16.DATA
//DDFLRP16 DD DISP=SHR,DSN=GENAPP.DDFLRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZWF01WBF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN17 DD DISP=SHR,DSN=GENAPP.DDWFIN17.DATA
//DDWFOT17 DD DISP=SHR,DSN=GENAPP.DDWFOT17.DATA
//DDWFRP17 DD DISP=SHR,DSN=GENAPP.DDWFRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01WBG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN18 DD DISP=SHR,DSN=GENAPP.DDBIIN18.DATA
//DDBIOT18 DD DISP=SHR,DSN=GENAPP.DDBIOT18.DATA
//DDBIRP18 DD DISP=SHR,DSN=GENAPP.DDBIRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
