//VJOB2650 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI0219B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN31 DD DISP=SHR,DSN=GENAPP.DDBIIN31.DATA
//DDBIOT31 DD DISP=SHR,DSN=GENAPP.DDBIOT31.DATA
//DDBIRP31 DD DISP=SHR,DSN=GENAPP.DDBIRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ0219C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN32 DD DISP=SHR,DSN=GENAPP.DDAZIN32.DATA
//DDAZOT32 DD DISP=SHR,DSN=GENAPP.DDAZOT32.DATA
//DDAZRP32 DD DISP=SHR,DSN=GENAPP.DDAZRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE0219D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN33 DD DISP=SHR,DSN=GENAPP.DDREIN33.DATA
//DDREOT33 DD DISP=SHR,DSN=GENAPP.DDREOT33.DATA
//DDRERP33 DD DISP=SHR,DSN=GENAPP.DDRERP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
