//VJOB1426 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE01YFB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN49 DD DISP=SHR,DSN=GENAPP.DDHEIN49.DATA
//DDHEOT49 DD DISP=SHR,DSN=GENAPP.DDHEOT49.DATA
//DDHERP49 DD DISP=SHR,DSN=GENAPP.DDHERP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE01YFC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN50 DD DISP=SHR,DSN=GENAPP.DDHEIN50.DATA
//DDHEOT50 DD DISP=SHR,DSN=GENAPP.DDHEOT50.DATA
//DDHERP50 DD DISP=SHR,DSN=GENAPP.DDHERP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01YFD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN51 DD DISP=SHR,DSN=GENAPP.DDCLIN51.DATA
//DDCLOT51 DD DISP=SHR,DSN=GENAPP.DDCLOT51.DATA
//DDCLRP51 DD DISP=SHR,DSN=GENAPP.DDCLRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
