//VJOB4214 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN024VN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN43 DD DISP=SHR,DSN=GENAPP.DDANIN43.DATA
//DDANOT43 DD DISP=SHR,DSN=GENAPP.DDANOT43.DATA
//DDANRP43 DD DISP=SHR,DSN=GENAPP.DDANRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRC024VO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN44 DD DISP=SHR,DSN=GENAPP.DDRCIN44.DATA
//DDRCOT44 DD DISP=SHR,DSN=GENAPP.DDRCOT44.DATA
//DDRCRP44 DD DISP=SHR,DSN=GENAPP.DDRCRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI024VP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN45 DD DISP=SHR,DSN=GENAPP.DDBIIN45.DATA
//DDBIOT45 DD DISP=SHR,DSN=GENAPP.DDBIOT45.DATA
//DDBIRP45 DD DISP=SHR,DSN=GENAPP.DDBIRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
