//VJOB3052 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN0226T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN67 DD DISP=SHR,DSN=GENAPP.DDENIN67.DATA
//DDENOT67 DD DISP=SHR,DSN=GENAPP.DDENOT67.DATA
//DDENRP67 DD DISP=SHR,DSN=GENAPP.DDENRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSB0226U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN68 DD DISP=SHR,DSN=GENAPP.DDSBIN68.DATA
//DDSBOT68 DD DISP=SHR,DSN=GENAPP.DDSBOT68.DATA
//DDSBRP68 DD DISP=SHR,DSN=GENAPP.DDSBRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO0226V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN69 DD DISP=SHR,DSN=GENAPP.DDCOIN69.DATA
//DDCOOT69 DD DISP=SHR,DSN=GENAPP.DDCOOT69.DATA
//DDCORP69 DD DISP=SHR,DSN=GENAPP.DDCORP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
