//VJOB0183 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01VJQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN10 DD DISP=SHR,DSN=GENAPP.DDBIIN10.DATA
//DDBIOT10 DD DISP=SHR,DSN=GENAPP.DDBIOT10.DATA
//DDBIRP10 DD DISP=SHR,DSN=GENAPP.DDBIRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZVA01VJR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN11 DD DISP=SHR,DSN=GENAPP.DDVAIN11.DATA
//DDVAOT11 DD DISP=SHR,DSN=GENAPP.DDVAOT11.DATA
//DDVARP11 DD DISP=SHR,DSN=GENAPP.DDVARP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01VJS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN12 DD DISP=SHR,DSN=GENAPP.DDPEIN12.DATA
//DDPEOT12 DD DISP=SHR,DSN=GENAPP.DDPEOT12.DATA
//DDPERP12 DD DISP=SHR,DSN=GENAPP.DDPERP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
