//VJOB4304 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP02535
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN43 DD DISP=SHR,DSN=GENAPP.DDCPIN43.DATA
//DDCPOT43 DD DISP=SHR,DSN=GENAPP.DDCPOT43.DATA
//DDCPRP43 DD DISP=SHR,DSN=GENAPP.DDCPRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW02536
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN44 DD DISP=SHR,DSN=GENAPP.DDUWIN44.DATA
//DDUWOT44 DD DISP=SHR,DSN=GENAPP.DDUWOT44.DATA
//DDUWRP44 DD DISP=SHR,DSN=GENAPP.DDUWRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE02537
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN45 DD DISP=SHR,DSN=GENAPP.DDPEIN45.DATA
//DDPEOT45 DD DISP=SHR,DSN=GENAPP.DDPEOT45.DATA
//DDPERP45 DD DISP=SHR,DSN=GENAPP.DDPERP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
