//VJOB2008 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01ZRT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN85 DD DISP=SHR,DSN=GENAPP.DDENIN85.DATA
//DDENOT85 DD DISP=SHR,DSN=GENAPP.DDENOT85.DATA
//DDENRP85 DD DISP=SHR,DSN=GENAPP.DDENRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN01ZRU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN86 DD DISP=SHR,DSN=GENAPP.DDENIN86.DATA
//DDENOT86 DD DISP=SHR,DSN=GENAPP.DDENOT86.DATA
//DDENRP86 DD DISP=SHR,DSN=GENAPP.DDENRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01ZRV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN87 DD DISP=SHR,DSN=GENAPP.DDREIN87.DATA
//DDREOT87 DD DISP=SHR,DSN=GENAPP.DDREOT87.DATA
//DDRERP87 DD DISP=SHR,DSN=GENAPP.DDRERP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
