//VJOB0590 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01WHN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN61 DD DISP=SHR,DSN=GENAPP.DDMTIN61.DATA
//DDMTOT61 DD DISP=SHR,DSN=GENAPP.DDMTOT61.DATA
//DDMTRP61 DD DISP=SHR,DSN=GENAPP.DDMTRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV01WHO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN62 DD DISP=SHR,DSN=GENAPP.DDAVIN62.DATA
//DDAVOT62 DD DISP=SHR,DSN=GENAPP.DDAVOT62.DATA
//DDAVRP62 DD DISP=SHR,DSN=GENAPP.DDAVRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZED01WHP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN63 DD DISP=SHR,DSN=GENAPP.DDEDIN63.DATA
//DDEDOT63 DD DISP=SHR,DSN=GENAPP.DDEDOT63.DATA
//DDEDRP63 DD DISP=SHR,DSN=GENAPP.DDEDRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
