//VJOB1607 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAZ01YUE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN52 DD DISP=SHR,DSN=GENAPP.DDAZIN52.DATA
//DDAZOT52 DD DISP=SHR,DSN=GENAPP.DDAZOT52.DATA
//DDAZRP52 DD DISP=SHR,DSN=GENAPP.DDAZRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01YUF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN53 DD DISP=SHR,DSN=GENAPP.DDBIIN53.DATA
//DDBIOT53 DD DISP=SHR,DSN=GENAPP.DDBIOT53.DATA
//DDBIRP53 DD DISP=SHR,DSN=GENAPP.DDBIRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDO01YUG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN54 DD DISP=SHR,DSN=GENAPP.DDDOIN54.DATA
//DDDOOT54 DD DISP=SHR,DSN=GENAPP.DDDOOT54.DATA
//DDDORP54 DD DISP=SHR,DSN=GENAPP.DDDORP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
