//VJOB1059 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR01XKQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN28 DD DISP=SHR,DSN=GENAPP.DDTRIN28.DATA
//DDTROT28 DD DISP=SHR,DSN=GENAPP.DDTROT28.DATA
//DDTRRP28 DD DISP=SHR,DSN=GENAPP.DDTRRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT01XKR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN29 DD DISP=SHR,DSN=GENAPP.DDLTIN29.DATA
//DDLTOT29 DD DISP=SHR,DSN=GENAPP.DDLTOT29.DATA
//DDLTRP29 DD DISP=SHR,DSN=GENAPP.DDLTRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZNT01XKS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN30 DD DISP=SHR,DSN=GENAPP.DDNTIN30.DATA
//DDNTOT30 DD DISP=SHR,DSN=GENAPP.DDNTOT30.DATA
//DDNTRP30 DD DISP=SHR,DSN=GENAPP.DDNTRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
