//VJOB3110 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT022BN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN61 DD DISP=SHR,DSN=GENAPP.DDMTIN61.DATA
//DDMTOT61 DD DISP=SHR,DSN=GENAPP.DDMTOT61.DATA
//DDMTRP61 DD DISP=SHR,DSN=GENAPP.DDMTRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT022BO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN62 DD DISP=SHR,DSN=GENAPP.DDMTIN62.DATA
//DDMTOT62 DD DISP=SHR,DSN=GENAPP.DDMTOT62.DATA
//DDMTRP62 DD DISP=SHR,DSN=GENAPP.DDMTRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI022BP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN63 DD DISP=SHR,DSN=GENAPP.DDLIIN63.DATA
//DDLIOT63 DD DISP=SHR,DSN=GENAPP.DDLIOT63.DATA
//DDLIRP63 DD DISP=SHR,DSN=GENAPP.DDLIRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
