//VJOB3985 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO024CK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN76 DD DISP=SHR,DSN=GENAPP.DDHOIN76.DATA
//DDHOOT76 DD DISP=SHR,DSN=GENAPP.DDHOOT76.DATA
//DDHORP76 DD DISP=SHR,DSN=GENAPP.DDHORP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB024CL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN77 DD DISP=SHR,DSN=GENAPP.DDLBIN77.DATA
//DDLBOT77 DD DISP=SHR,DSN=GENAPP.DDLBOT77.DATA
//DDLBRP77 DD DISP=SHR,DSN=GENAPP.DDLBRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN024CM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN78 DD DISP=SHR,DSN=GENAPP.DDENIN78.DATA
//DDENOT78 DD DISP=SHR,DSN=GENAPP.DDENOT78.DATA
//DDENRP78 DD DISP=SHR,DSN=GENAPP.DDENRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
