//VJOB0751 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01WV2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN04 DD DISP=SHR,DSN=GENAPP.DDMTIN04.DATA
//DDMTOT04 DD DISP=SHR,DSN=GENAPP.DDMTOT04.DATA
//DDMTRP04 DD DISP=SHR,DSN=GENAPP.DDMTRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01WV3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN05 DD DISP=SHR,DSN=GENAPP.DDMTIN05.DATA
//DDMTOT05 DD DISP=SHR,DSN=GENAPP.DDMTOT05.DATA
//DDMTRP05 DD DISP=SHR,DSN=GENAPP.DDMTRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLB01WV4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN06 DD DISP=SHR,DSN=GENAPP.DDLBIN06.DATA
//DDLBOT06 DD DISP=SHR,DSN=GENAPP.DDLBOT06.DATA
//DDLBRP06 DD DISP=SHR,DSN=GENAPP.DDLBRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
