//VJOB3755 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDI023TE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN16 DD DISP=SHR,DSN=GENAPP.DDDIIN16.DATA
//DDDIOT16 DD DISP=SHR,DSN=GENAPP.DDDIOT16.DATA
//DDDIRP16 DD DISP=SHR,DSN=GENAPP.DDDIRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL023TF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN17 DD DISP=SHR,DSN=GENAPP.DDFLIN17.DATA
//DDFLOT17 DD DISP=SHR,DSN=GENAPP.DDFLOT17.DATA
//DDFLRP17 DD DISP=SHR,DSN=GENAPP.DDFLRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU023TG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN18 DD DISP=SHR,DSN=GENAPP.DDCUIN18.DATA
//DDCUOT18 DD DISP=SHR,DSN=GENAPP.DDCUOT18.DATA
//DDCURP18 DD DISP=SHR,DSN=GENAPP.DDCURP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
