//VJOB0832 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV01X1T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN67 DD DISP=SHR,DSN=GENAPP.DDIVIN67.DATA
//DDIVOT67 DD DISP=SHR,DSN=GENAPP.DDIVOT67.DATA
//DDIVRP67 DD DISP=SHR,DSN=GENAPP.DDIVRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR01X1U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN68 DD DISP=SHR,DSN=GENAPP.DDCRIN68.DATA
//DDCROT68 DD DISP=SHR,DSN=GENAPP.DDCROT68.DATA
//DDCRRP68 DD DISP=SHR,DSN=GENAPP.DDCRRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01X1V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN69 DD DISP=SHR,DSN=GENAPP.DDMTIN69.DATA
//DDMTOT69 DD DISP=SHR,DSN=GENAPP.DDMTOT69.DATA
//DDMTRP69 DD DISP=SHR,DSN=GENAPP.DDMTRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
