//VJOB0195 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01VKQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN46 DD DISP=SHR,DSN=GENAPP.DDENIN46.DATA
//DDENOT46 DD DISP=SHR,DSN=GENAPP.DDENOT46.DATA
//DDENRP46 DD DISP=SHR,DSN=GENAPP.DDENRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRS01VKR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN47 DD DISP=SHR,DSN=GENAPP.DDRSIN47.DATA
//DDRSOT47 DD DISP=SHR,DSN=GENAPP.DDRSOT47.DATA
//DDRSRP47 DD DISP=SHR,DSN=GENAPP.DDRSRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01VKS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN48 DD DISP=SHR,DSN=GENAPP.DDMTIN48.DATA
//DDMTOT48 DD DISP=SHR,DSN=GENAPP.DDMTOT48.DATA
//DDMTRP48 DD DISP=SHR,DSN=GENAPP.DDMTRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
