//VJOB3864 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL0242H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN73 DD DISP=SHR,DSN=GENAPP.DDCLIN73.DATA
//DDCLOT73 DD DISP=SHR,DSN=GENAPP.DDCLOT73.DATA
//DDCLRP73 DD DISP=SHR,DSN=GENAPP.DDCLRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO0242I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN74 DD DISP=SHR,DSN=GENAPP.DDHOIN74.DATA
//DDHOOT74 DD DISP=SHR,DSN=GENAPP.DDHOOT74.DATA
//DDHORP74 DD DISP=SHR,DSN=GENAPP.DDHORP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW0242J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN75 DD DISP=SHR,DSN=GENAPP.DDUWIN75.DATA
//DDUWOT75 DD DISP=SHR,DSN=GENAPP.DDUWOT75.DATA
//DDUWRP75 DD DISP=SHR,DSN=GENAPP.DDUWRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
