//VJOB0472 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01W7T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN67 DD DISP=SHR,DSN=GENAPP.DDAVIN67.DATA
//DDAVOT67 DD DISP=SHR,DSN=GENAPP.DDAVOT67.DATA
//DDAVRP67 DD DISP=SHR,DSN=GENAPP.DDAVRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01W7U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN68 DD DISP=SHR,DSN=GENAPP.DDHOIN68.DATA
//DDHOOT68 DD DISP=SHR,DSN=GENAPP.DDHOOT68.DATA
//DDHORP68 DD DISP=SHR,DSN=GENAPP.DDHORP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMB01W7V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN69 DD DISP=SHR,DSN=GENAPP.DDMBIN69.DATA
//DDMBOT69 DD DISP=SHR,DSN=GENAPP.DDMBOT69.DATA
//DDMBRP69 DD DISP=SHR,DSN=GENAPP.DDMBRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
