//VJOB3806 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT023XN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN79 DD DISP=SHR,DSN=GENAPP.DDMTIN79.DATA
//DDMTOT79 DD DISP=SHR,DSN=GENAPP.DDMTOT79.DATA
//DDMTRP79 DD DISP=SHR,DSN=GENAPP.DDMTRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN023XO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN80 DD DISP=SHR,DSN=GENAPP.DDENIN80.DATA
//DDENOT80 DD DISP=SHR,DSN=GENAPP.DDENOT80.DATA
//DDENRP80 DD DISP=SHR,DSN=GENAPP.DDENRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU023XP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN81 DD DISP=SHR,DSN=GENAPP.DDCUIN81.DATA
//DDCUOT81 DD DISP=SHR,DSN=GENAPP.DDCUOT81.DATA
//DDCURP81 DD DISP=SHR,DSN=GENAPP.DDCURP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
