//VJOB2156 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE02045
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN79 DD DISP=SHR,DSN=GENAPP.DDREIN79.DATA
//DDREOT79 DD DISP=SHR,DSN=GENAPP.DDREOT79.DATA
//DDRERP79 DD DISP=SHR,DSN=GENAPP.DDRERP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO02046
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN80 DD DISP=SHR,DSN=GENAPP.DDHOIN80.DATA
//DDHOOT80 DD DISP=SHR,DSN=GENAPP.DDHOOT80.DATA
//DDHORP80 DD DISP=SHR,DSN=GENAPP.DDHORP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT02047
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN81 DD DISP=SHR,DSN=GENAPP.DDMTIN81.DATA
//DDMTOT81 DD DISP=SHR,DSN=GENAPP.DDMTOT81.DATA
//DDMTRP81 DD DISP=SHR,DSN=GENAPP.DDMTRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
