//VJOB1716 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01Z3H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN19 DD DISP=SHR,DSN=GENAPP.DDRGIN19.DATA
//DDRGOT19 DD DISP=SHR,DSN=GENAPP.DDRGOT19.DATA
//DDRGRP19 DD DISP=SHR,DSN=GENAPP.DDRGRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01Z3I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN20 DD DISP=SHR,DSN=GENAPP.DDMTIN20.DATA
//DDMTOT20 DD DISP=SHR,DSN=GENAPP.DDMTOT20.DATA
//DDMTRP20 DD DISP=SHR,DSN=GENAPP.DDMTRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZVA01Z3J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN21 DD DISP=SHR,DSN=GENAPP.DDVAIN21.DATA
//DDVAOT21 DD DISP=SHR,DSN=GENAPP.DDVAOT21.DATA
//DDVARP21 DD DISP=SHR,DSN=GENAPP.DDVARP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
