//VJOB3461 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSL0234W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN34 DD DISP=SHR,DSN=GENAPP.DDSLIN34.DATA
//DDSLOT34 DD DISP=SHR,DSN=GENAPP.DDSLOT34.DATA
//DDSLRP34 DD DISP=SHR,DSN=GENAPP.DDSLRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA0234X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN35 DD DISP=SHR,DSN=GENAPP.DDPAIN35.DATA
//DDPAOT35 DD DISP=SHR,DSN=GENAPP.DDPAOT35.DATA
//DDPARP35 DD DISP=SHR,DSN=GENAPP.DDPARP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO0234Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN36 DD DISP=SHR,DSN=GENAPP.DDHOIN36.DATA
//DDHOOT36 DD DISP=SHR,DSN=GENAPP.DDHOOT36.DATA
//DDHORP36 DD DISP=SHR,DSN=GENAPP.DDHORP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
