//VJOB0990 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG01XEZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN01 DD DISP=SHR,DSN=GENAPP.DDAGIN01.DATA
//DDAGOT01 DD DISP=SHR,DSN=GENAPP.DDAGOT01.DATA
//DDAGRP01 DD DISP=SHR,DSN=GENAPP.DDAGRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE01XF0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN02 DD DISP=SHR,DSN=GENAPP.DDPEIN02.DATA
//DDPEOT02 DD DISP=SHR,DSN=GENAPP.DDPEOT02.DATA
//DDPERP02 DD DISP=SHR,DSN=GENAPP.DDPERP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR01XF1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN03 DD DISP=SHR,DSN=GENAPP.DDBRIN03.DATA
//DDBROT03 DD DISP=SHR,DSN=GENAPP.DDBROT03.DATA
//DDBRRP03 DD DISP=SHR,DSN=GENAPP.DDBRRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
