//VJOB1186 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPL01XVB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN49 DD DISP=SHR,DSN=GENAPP.DDPLIN49.DATA
//DDPLOT49 DD DISP=SHR,DSN=GENAPP.DDPLOT49.DATA
//DDPLRP49 DD DISP=SHR,DSN=GENAPP.DDPLRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01XVC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN50 DD DISP=SHR,DSN=GENAPP.DDHOIN50.DATA
//DDHOOT50 DD DISP=SHR,DSN=GENAPP.DDHOOT50.DATA
//DDHORP50 DD DISP=SHR,DSN=GENAPP.DDHORP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS01XVD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN51 DD DISP=SHR,DSN=GENAPP.DDRSIN51.DATA
//DDRSOT51 DD DISP=SHR,DSN=GENAPP.DDRSOT51.DATA
//DDRSRP51 DD DISP=SHR,DSN=GENAPP.DDRSRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
