//VJOB2757 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW021I8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN82 DD DISP=SHR,DSN=GENAPP.DDUWIN82.DATA
//DDUWOT82 DD DISP=SHR,DSN=GENAPP.DDUWOT82.DATA
//DDUWRP82 DD DISP=SHR,DSN=GENAPP.DDUWRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR021I9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN83 DD DISP=SHR,DSN=GENAPP.DDTRIN83.DATA
//DDTROT83 DD DISP=SHR,DSN=GENAPP.DDTROT83.DATA
//DDTRRP83 DD DISP=SHR,DSN=GENAPP.DDTRRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT021IA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN84 DD DISP=SHR,DSN=GENAPP.DDMTIN84.DATA
//DDMTOT84 DD DISP=SHR,DSN=GENAPP.DDMTOT84.DATA
//DDMTRP84 DD DISP=SHR,DSN=GENAPP.DDMTRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
