//VJOB1037 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01XIW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN52 DD DISP=SHR,DSN=GENAPP.DDUWIN52.DATA
//DDUWOT52 DD DISP=SHR,DSN=GENAPP.DDUWOT52.DATA
//DDUWRP52 DD DISP=SHR,DSN=GENAPP.DDUWRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01XIX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN53 DD DISP=SHR,DSN=GENAPP.DDLIIN53.DATA
//DDLIOT53 DD DISP=SHR,DSN=GENAPP.DDLIOT53.DATA
//DDLIRP53 DD DISP=SHR,DSN=GENAPP.DDLIRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZQU01XIY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN54 DD DISP=SHR,DSN=GENAPP.DDQUIN54.DATA
//DDQUOT54 DD DISP=SHR,DSN=GENAPP.DDQUOT54.DATA
//DDQURP54 DD DISP=SHR,DSN=GENAPP.DDQURP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
