//VJOB0998 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF01XFN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN25 DD DISP=SHR,DSN=GENAPP.DDWFIN25.DATA
//DDWFOT25 DD DISP=SHR,DSN=GENAPP.DDWFOT25.DATA
//DDWFRP25 DD DISP=SHR,DSN=GENAPP.DDWFRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF01XFO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN26 DD DISP=SHR,DSN=GENAPP.DDIFIN26.DATA
//DDIFOT26 DD DISP=SHR,DSN=GENAPP.DDIFOT26.DATA
//DDIFRP26 DD DISP=SHR,DSN=GENAPP.DDIFRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPL01XFP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN27 DD DISP=SHR,DSN=GENAPP.DDPLIN27.DATA
//DDPLOT27 DD DISP=SHR,DSN=GENAPP.DDPLOT27.DATA
//DDPLRP27 DD DISP=SHR,DSN=GENAPP.DDPLRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
