//VJOB3036 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZST0225H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN19 DD DISP=SHR,DSN=GENAPP.DDSTIN19.DATA
//DDSTOT19 DD DISP=SHR,DSN=GENAPP.DDSTOT19.DATA
//DDSTRP19 DD DISP=SHR,DSN=GENAPP.DDSTRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCP0225I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN20 DD DISP=SHR,DSN=GENAPP.DDCPIN20.DATA
//DDCPOT20 DD DISP=SHR,DSN=GENAPP.DDCPOT20.DATA
//DDCPRP20 DD DISP=SHR,DSN=GENAPP.DDCPRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO0225J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN21 DD DISP=SHR,DSN=GENAPP.DDCOIN21.DATA
//DDCOOT21 DD DISP=SHR,DSN=GENAPP.DDCOOT21.DATA
//DDCORP21 DD DISP=SHR,DSN=GENAPP.DDCORP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
