//VJOB3465 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT02358
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN46 DD DISP=SHR,DSN=GENAPP.DDNTIN46.DATA
//DDNTOT46 DD DISP=SHR,DSN=GENAPP.DDNTOT46.DATA
//DDNTRP46 DD DISP=SHR,DSN=GENAPP.DDNTRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB02359
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN47 DD DISP=SHR,DSN=GENAPP.DDLBIN47.DATA
//DDLBOT47 DD DISP=SHR,DSN=GENAPP.DDLBOT47.DATA
//DDLBRP47 DD DISP=SHR,DSN=GENAPP.DDLBRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT0235A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN48 DD DISP=SHR,DSN=GENAPP.DDPTIN48.DATA
//DDPTOT48 DD DISP=SHR,DSN=GENAPP.DDPTOT48.DATA
//DDPTRP48 DD DISP=SHR,DSN=GENAPP.DDPTRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
