//VJOB0904 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT01X7T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN13 DD DISP=SHR,DSN=GENAPP.DDNTIN13.DATA
//DDNTOT13 DD DISP=SHR,DSN=GENAPP.DDNTOT13.DATA
//DDNTRP13 DD DISP=SHR,DSN=GENAPP.DDNTRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01X7U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN14 DD DISP=SHR,DSN=GENAPP.DDHOIN14.DATA
//DDHOOT14 DD DISP=SHR,DSN=GENAPP.DDHOOT14.DATA
//DDHORP14 DD DISP=SHR,DSN=GENAPP.DDHORP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO01X7V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN15 DD DISP=SHR,DSN=GENAPP.DDCOIN15.DATA
//DDCOOT15 DD DISP=SHR,DSN=GENAPP.DDCOOT15.DATA
//DDCORP15 DD DISP=SHR,DSN=GENAPP.DDCORP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
