//VJOB3992 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV024D5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN07 DD DISP=SHR,DSN=GENAPP.DDIVIN07.DATA
//DDIVOT07 DD DISP=SHR,DSN=GENAPP.DDIVOT07.DATA
//DDIVRP07 DD DISP=SHR,DSN=GENAPP.DDIVRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT024D6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN08 DD DISP=SHR,DSN=GENAPP.DDNTIN08.DATA
//DDNTOT08 DD DISP=SHR,DSN=GENAPP.DDNTOT08.DATA
//DDNTRP08 DD DISP=SHR,DSN=GENAPP.DDNTRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT024D7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN09 DD DISP=SHR,DSN=GENAPP.DDMTIN09.DATA
//DDMTOT09 DD DISP=SHR,DSN=GENAPP.DDMTOT09.DATA
//DDMTRP09 DD DISP=SHR,DSN=GENAPP.DDMTRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
