//VJOB0264 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01VQH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN73 DD DISP=SHR,DSN=GENAPP.DDCLIN73.DATA
//DDCLOT73 DD DISP=SHR,DSN=GENAPP.DDCLOT73.DATA
//DDCLRP73 DD DISP=SHR,DSN=GENAPP.DDCLRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01VQI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN74 DD DISP=SHR,DSN=GENAPP.DDMTIN74.DATA
//DDMTOT74 DD DISP=SHR,DSN=GENAPP.DDMTOT74.DATA
//DDMTRP74 DD DISP=SHR,DSN=GENAPP.DDMTRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX01VQJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN75 DD DISP=SHR,DSN=GENAPP.DDTXIN75.DATA
//DDTXOT75 DD DISP=SHR,DSN=GENAPP.DDTXOT75.DATA
//DDTXRP75 DD DISP=SHR,DSN=GENAPP.DDTXRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
