//VJOB4196 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT024U5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN79 DD DISP=SHR,DSN=GENAPP.DDNTIN79.DATA
//DDNTOT79 DD DISP=SHR,DSN=GENAPP.DDNTOT79.DATA
//DDNTRP79 DD DISP=SHR,DSN=GENAPP.DDNTRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV024U6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN80 DD DISP=SHR,DSN=GENAPP.DDAVIN80.DATA
//DDAVOT80 DD DISP=SHR,DSN=GENAPP.DDAVOT80.DATA
//DDAVRP80 DD DISP=SHR,DSN=GENAPP.DDAVRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBA024U7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN81 DD DISP=SHR,DSN=GENAPP.DDBAIN81.DATA
//DDBAOT81 DD DISP=SHR,DSN=GENAPP.DDBAOT81.DATA
//DDBARP81 DD DISP=SHR,DSN=GENAPP.DDBARP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
