//VJOB3914 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL0246N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN43 DD DISP=SHR,DSN=GENAPP.DDCLIN43.DATA
//DDCLOT43 DD DISP=SHR,DSN=GENAPP.DDCLOT43.DATA
//DDCLRP43 DD DISP=SHR,DSN=GENAPP.DDCLRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEX0246O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN44 DD DISP=SHR,DSN=GENAPP.DDEXIN44.DATA
//DDEXOT44 DD DISP=SHR,DSN=GENAPP.DDEXOT44.DATA
//DDEXRP44 DD DISP=SHR,DSN=GENAPP.DDEXRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO0246P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN45 DD DISP=SHR,DSN=GENAPP.DDHOIN45.DATA
//DDHOOT45 DD DISP=SHR,DSN=GENAPP.DDHOOT45.DATA
//DDHORP45 DD DISP=SHR,DSN=GENAPP.DDHORP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
