//VJOB0125 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01VEW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN16 DD DISP=SHR,DSN=GENAPP.DDAVIN16.DATA
//DDAVOT16 DD DISP=SHR,DSN=GENAPP.DDAVOT16.DATA
//DDAVRP16 DD DISP=SHR,DSN=GENAPP.DDAVRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01VEX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN17 DD DISP=SHR,DSN=GENAPP.DDCUIN17.DATA
//DDCUOT17 DD DISP=SHR,DSN=GENAPP.DDCUOT17.DATA
//DDCURP17 DD DISP=SHR,DSN=GENAPP.DDCURP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01VEY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN18 DD DISP=SHR,DSN=GENAPP.DDMTIN18.DATA
//DDMTOT18 DD DISP=SHR,DSN=GENAPP.DDMTOT18.DATA
//DDMTRP18 DD DISP=SHR,DSN=GENAPP.DDMTRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
