//VJOB1049 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01XJW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN88 DD DISP=SHR,DSN=GENAPP.DDCOIN88.DATA
//DDCOOT88 DD DISP=SHR,DSN=GENAPP.DDCOOT88.DATA
//DDCORP88 DD DISP=SHR,DSN=GENAPP.DDCORP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01XJX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN89 DD DISP=SHR,DSN=GENAPP.DDMTIN89.DATA
//DDMTOT89 DD DISP=SHR,DSN=GENAPP.DDMTOT89.DATA
//DDMTRP89 DD DISP=SHR,DSN=GENAPP.DDMTRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO01XJY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN90 DD DISP=SHR,DSN=GENAPP.DDCOIN90.DATA
//DDCOOT90 DD DISP=SHR,DSN=GENAPP.DDCOOT90.DATA
//DDCORP90 DD DISP=SHR,DSN=GENAPP.DDCORP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
