//VJOB1938 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01ZLZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN55 DD DISP=SHR,DSN=GENAPP.DDRGIN55.DATA
//DDRGOT55 DD DISP=SHR,DSN=GENAPP.DDRGOT55.DATA
//DDRGRP55 DD DISP=SHR,DSN=GENAPP.DDRGRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01ZM0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN56 DD DISP=SHR,DSN=GENAPP.DDCLIN56.DATA
//DDCLOT56 DD DISP=SHR,DSN=GENAPP.DDCLOT56.DATA
//DDCLRP56 DD DISP=SHR,DSN=GENAPP.DDCLRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO01ZM1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN57 DD DISP=SHR,DSN=GENAPP.DDCOIN57.DATA
//DDCOOT57 DD DISP=SHR,DSN=GENAPP.DDCOOT57.DATA
//DDCORP57 DD DISP=SHR,DSN=GENAPP.DDCORP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
