//VJOB2603 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT0215E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN70 DD DISP=SHR,DSN=GENAPP.DDPTIN70.DATA
//DDPTOT70 DD DISP=SHR,DSN=GENAPP.DDPTOT70.DATA
//DDPTRP70 DD DISP=SHR,DSN=GENAPP.DDPTRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR0215F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN71 DD DISP=SHR,DSN=GENAPP.DDPRIN71.DATA
//DDPROT71 DD DISP=SHR,DSN=GENAPP.DDPROT71.DATA
//DDPRRP71 DD DISP=SHR,DSN=GENAPP.DDPRRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBA0215G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN72 DD DISP=SHR,DSN=GENAPP.DDBAIN72.DATA
//DDBAOT72 DD DISP=SHR,DSN=GENAPP.DDBAOT72.DATA
//DDBARP72 DD DISP=SHR,DSN=GENAPP.DDBARP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
