//VJOB4097 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLT024LW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN52 DD DISP=SHR,DSN=GENAPP.DDLTIN52.DATA
//DDLTOT52 DD DISP=SHR,DSN=GENAPP.DDLTOT52.DATA
//DDLTRP52 DD DISP=SHR,DSN=GENAPP.DDLTRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR024LX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN53 DD DISP=SHR,DSN=GENAPP.DDTRIN53.DATA
//DDTROT53 DD DISP=SHR,DSN=GENAPP.DDTROT53.DATA
//DDTRRP53 DD DISP=SHR,DSN=GENAPP.DDTRRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAZ024LY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN54 DD DISP=SHR,DSN=GENAPP.DDAZIN54.DATA
//DDAZOT54 DD DISP=SHR,DSN=GENAPP.DDAZOT54.DATA
//DDAZRP54 DD DISP=SHR,DSN=GENAPP.DDAZRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
