//VJOB3184 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSL022HT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN13 DD DISP=SHR,DSN=GENAPP.DDSLIN13.DATA
//DDSLOT13 DD DISP=SHR,DSN=GENAPP.DDSLOT13.DATA
//DDSLRP13 DD DISP=SHR,DSN=GENAPP.DDSLRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT022HU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN14 DD DISP=SHR,DSN=GENAPP.DDMTIN14.DATA
//DDMTOT14 DD DISP=SHR,DSN=GENAPP.DDMTOT14.DATA
//DDMTRP14 DD DISP=SHR,DSN=GENAPP.DDMTRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAZ022HV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN15 DD DISP=SHR,DSN=GENAPP.DDAZIN15.DATA
//DDAZOT15 DD DISP=SHR,DSN=GENAPP.DDAZOT15.DATA
//DDAZRP15 DD DISP=SHR,DSN=GENAPP.DDAZRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
