//VJOB2416 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG020PT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN49 DD DISP=SHR,DSN=GENAPP.DDAGIN49.DATA
//DDAGOT49 DD DISP=SHR,DSN=GENAPP.DDAGOT49.DATA
//DDAGRP49 DD DISP=SHR,DSN=GENAPP.DDAGRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT020PU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN50 DD DISP=SHR,DSN=GENAPP.DDNTIN50.DATA
//DDNTOT50 DD DISP=SHR,DSN=GENAPP.DDNTOT50.DATA
//DDNTRP50 DD DISP=SHR,DSN=GENAPP.DDNTRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO020PV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN51 DD DISP=SHR,DSN=GENAPP.DDHOIN51.DATA
//DDHOOT51 DD DISP=SHR,DSN=GENAPP.DDHOOT51.DATA
//DDHORP51 DD DISP=SHR,DSN=GENAPP.DDHORP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
