//VJOB3344 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG022V5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN43 DD DISP=SHR,DSN=GENAPP.DDRGIN43.DATA
//DDRGOT43 DD DISP=SHR,DSN=GENAPP.DDRGOT43.DATA
//DDRGRP43 DD DISP=SHR,DSN=GENAPP.DDRGRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG022V6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN44 DD DISP=SHR,DSN=GENAPP.DDRGIN44.DATA
//DDRGOT44 DD DISP=SHR,DSN=GENAPP.DDRGOT44.DATA
//DDRGRP44 DD DISP=SHR,DSN=GENAPP.DDRGRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV022V7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN45 DD DISP=SHR,DSN=GENAPP.DDIVIN45.DATA
//DDIVOT45 DD DISP=SHR,DSN=GENAPP.DDIVOT45.DATA
//DDIVRP45 DD DISP=SHR,DSN=GENAPP.DDIVRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
