//VJOB0200 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY01VL5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN61 DD DISP=SHR,DSN=GENAPP.DDTYIN61.DATA
//DDTYOT61 DD DISP=SHR,DSN=GENAPP.DDTYOT61.DATA
//DDTYRP61 DD DISP=SHR,DSN=GENAPP.DDTYRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT01VL6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN62 DD DISP=SHR,DSN=GENAPP.DDLTIN62.DATA
//DDLTOT62 DD DISP=SHR,DSN=GENAPP.DDLTOT62.DATA
//DDLTRP62 DD DISP=SHR,DSN=GENAPP.DDLTRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCR01VL7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN63 DD DISP=SHR,DSN=GENAPP.DDCRIN63.DATA
//DDCROT63 DD DISP=SHR,DSN=GENAPP.DDCROT63.DATA
//DDCRRP63 DD DISP=SHR,DSN=GENAPP.DDCRRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
