//VJOB0663 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF01WNQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN10 DD DISP=SHR,DSN=GENAPP.DDWFIN10.DATA
//DDWFOT10 DD DISP=SHR,DSN=GENAPP.DDWFOT10.DATA
//DDWFRP10 DD DISP=SHR,DSN=GENAPP.DDWFRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCN01WNR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN11 DD DISP=SHR,DSN=GENAPP.DDCNIN11.DATA
//DDCNOT11 DD DISP=SHR,DSN=GENAPP.DDCNOT11.DATA
//DDCNRP11 DD DISP=SHR,DSN=GENAPP.DDCNRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE01WNS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN12 DD DISP=SHR,DSN=GENAPP.DDHEIN12.DATA
//DDHEOT12 DD DISP=SHR,DSN=GENAPP.DDHEOT12.DATA
//DDHERP12 DD DISP=SHR,DSN=GENAPP.DDHERP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
