//VJOB1569 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01YR8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN28 DD DISP=SHR,DSN=GENAPP.DDMTIN28.DATA
//DDMTOT28 DD DISP=SHR,DSN=GENAPP.DDMTOT28.DATA
//DDMTRP28 DD DISP=SHR,DSN=GENAPP.DDMTRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR01YR9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN29 DD DISP=SHR,DSN=GENAPP.DDCRIN29.DATA
//DDCROT29 DD DISP=SHR,DSN=GENAPP.DDCROT29.DATA
//DDCRRP29 DD DISP=SHR,DSN=GENAPP.DDCRRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01YRA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN30 DD DISP=SHR,DSN=GENAPP.DDPEIN30.DATA
//DDPEOT30 DD DISP=SHR,DSN=GENAPP.DDPEOT30.DATA
//DDPERP30 DD DISP=SHR,DSN=GENAPP.DDPERP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
