//VJOB2682 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG021BZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN37 DD DISP=SHR,DSN=GENAPP.DDAGIN37.DATA
//DDAGOT37 DD DISP=SHR,DSN=GENAPP.DDAGOT37.DATA
//DDAGRP37 DD DISP=SHR,DSN=GENAPP.DDAGRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE021C0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN38 DD DISP=SHR,DSN=GENAPP.DDPEIN38.DATA
//DDPEOT38 DD DISP=SHR,DSN=GENAPP.DDPEOT38.DATA
//DDPERP38 DD DISP=SHR,DSN=GENAPP.DDPERP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR021C1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN39 DD DISP=SHR,DSN=GENAPP.DDPRIN39.DATA
//DDPROT39 DD DISP=SHR,DSN=GENAPP.DDPROT39.DATA
//DDPRRP39 DD DISP=SHR,DSN=GENAPP.DDPRRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
