//VJOB0302 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR01VTN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN07 DD DISP=SHR,DSN=GENAPP.DDFRIN07.DATA
//DDFROT07 DD DISP=SHR,DSN=GENAPP.DDFROT07.DATA
//DDFRRP07 DD DISP=SHR,DSN=GENAPP.DDFRRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCP01VTO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN08 DD DISP=SHR,DSN=GENAPP.DDCPIN08.DATA
//DDCPOT08 DD DISP=SHR,DSN=GENAPP.DDCPOT08.DATA
//DDCPRP08 DD DISP=SHR,DSN=GENAPP.DDCPRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01VTP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN09 DD DISP=SHR,DSN=GENAPP.DDMTIN09.DATA
//DDMTOT09 DD DISP=SHR,DSN=GENAPP.DDMTOT09.DATA
//DDMTRP09 DD DISP=SHR,DSN=GENAPP.DDMTRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
