//VJOB3318 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDI022SZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN55 DD DISP=SHR,DSN=GENAPP.DDDIIN55.DATA
//DDDIOT55 DD DISP=SHR,DSN=GENAPP.DDDIOT55.DATA
//DDDIRP55 DD DISP=SHR,DSN=GENAPP.DDDIRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPL022T0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN56 DD DISP=SHR,DSN=GENAPP.DDPLIN56.DATA
//DDPLOT56 DD DISP=SHR,DSN=GENAPP.DDPLOT56.DATA
//DDPLRP56 DD DISP=SHR,DSN=GENAPP.DDPLRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV022T1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN57 DD DISP=SHR,DSN=GENAPP.DDAVIN57.DATA
//DDAVOT57 DD DISP=SHR,DSN=GENAPP.DDAVOT57.DATA
//DDAVRP57 DD DISP=SHR,DSN=GENAPP.DDAVRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
