//VJOB0773 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZST01WWW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN70 DD DISP=SHR,DSN=GENAPP.DDSTIN70.DATA
//DDSTOT70 DD DISP=SHR,DSN=GENAPP.DDSTOT70.DATA
//DDSTRP70 DD DISP=SHR,DSN=GENAPP.DDSTRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN01WWX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN71 DD DISP=SHR,DSN=GENAPP.DDENIN71.DATA
//DDENOT71 DD DISP=SHR,DSN=GENAPP.DDENOT71.DATA
//DDENRP71 DD DISP=SHR,DSN=GENAPP.DDENRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBA01WWY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN72 DD DISP=SHR,DSN=GENAPP.DDBAIN72.DATA
//DDBAOT72 DD DISP=SHR,DSN=GENAPP.DDBAOT72.DATA
//DDBARP72 DD DISP=SHR,DSN=GENAPP.DDBARP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
