//VJOB4293 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG02528
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN10 DD DISP=SHR,DSN=GENAPP.DDRGIN10.DATA
//DDRGOT10 DD DISP=SHR,DSN=GENAPP.DDRGOT10.DATA
//DDRGRP10 DD DISP=SHR,DSN=GENAPP.DDRGRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRT02529
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN11 DD DISP=SHR,DSN=GENAPP.DDRTIN11.DATA
//DDRTOT11 DD DISP=SHR,DSN=GENAPP.DDRTOT11.DATA
//DDRTRP11 DD DISP=SHR,DSN=GENAPP.DDRTRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTY0252A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN12 DD DISP=SHR,DSN=GENAPP.DDTYIN12.DATA
//DDTYOT12 DD DISP=SHR,DSN=GENAPP.DDTYOT12.DATA
//DDTYRP12 DD DISP=SHR,DSN=GENAPP.DDTYRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
