//VJOB3459 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO0234Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN28 DD DISP=SHR,DSN=GENAPP.DDHOIN28.DATA
//DDHOOT28 DD DISP=SHR,DSN=GENAPP.DDHOOT28.DATA
//DDHORP28 DD DISP=SHR,DSN=GENAPP.DDHORP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX0234R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN29 DD DISP=SHR,DSN=GENAPP.DDTXIN29.DATA
//DDTXOT29 DD DISP=SHR,DSN=GENAPP.DDTXOT29.DATA
//DDTXRP29 DD DISP=SHR,DSN=GENAPP.DDTXRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT0234S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN30 DD DISP=SHR,DSN=GENAPP.DDMTIN30.DATA
//DDMTOT30 DD DISP=SHR,DSN=GENAPP.DDMTOT30.DATA
//DDMTRP30 DD DISP=SHR,DSN=GENAPP.DDMTRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
