//VJOB2388 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE020NH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN55 DD DISP=SHR,DSN=GENAPP.DDPEIN55.DATA
//DDPEOT55 DD DISP=SHR,DSN=GENAPP.DDPEOT55.DATA
//DDPERP55 DD DISP=SHR,DSN=GENAPP.DDPERP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO020NI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN56 DD DISP=SHR,DSN=GENAPP.DDHOIN56.DATA
//DDHOOT56 DD DISP=SHR,DSN=GENAPP.DDHOOT56.DATA
//DDHORP56 DD DISP=SHR,DSN=GENAPP.DDHORP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL020NJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN57 DD DISP=SHR,DSN=GENAPP.DDCLIN57.DATA
//DDCLOT57 DD DISP=SHR,DSN=GENAPP.DDCLOT57.DATA
//DDCLRP57 DD DISP=SHR,DSN=GENAPP.DDCLRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
