//VJOB0673 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBR01WOK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN40 DD DISP=SHR,DSN=GENAPP.DDBRIN40.DATA
//DDBROT40 DD DISP=SHR,DSN=GENAPP.DDBROT40.DATA
//DDBRRP40 DD DISP=SHR,DSN=GENAPP.DDBRRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSU01WOL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN41 DD DISP=SHR,DSN=GENAPP.DDSUIN41.DATA
//DDSUOT41 DD DISP=SHR,DSN=GENAPP.DDSUOT41.DATA
//DDSURP41 DD DISP=SHR,DSN=GENAPP.DDSURP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01WOM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN42 DD DISP=SHR,DSN=GENAPP.DDREIN42.DATA
//DDREOT42 DD DISP=SHR,DSN=GENAPP.DDREOT42.DATA
//DDRERP42 DD DISP=SHR,DSN=GENAPP.DDRERP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
