//VJOB3328 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG022TT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN85 DD DISP=SHR,DSN=GENAPP.DDRGIN85.DATA
//DDRGOT85 DD DISP=SHR,DSN=GENAPP.DDRGOT85.DATA
//DDRGRP85 DD DISP=SHR,DSN=GENAPP.DDRGRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA022TU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN86 DD DISP=SHR,DSN=GENAPP.DDBAIN86.DATA
//DDBAOT86 DD DISP=SHR,DSN=GENAPP.DDBAOT86.DATA
//DDBARP86 DD DISP=SHR,DSN=GENAPP.DDBARP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX022TV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN87 DD DISP=SHR,DSN=GENAPP.DDTXIN87.DATA
//DDTXOT87 DD DISP=SHR,DSN=GENAPP.DDTXOT87.DATA
//DDTXRP87 DD DISP=SHR,DSN=GENAPP.DDTXRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
