//VJOB0453 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01W68
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN10 DD DISP=SHR,DSN=GENAPP.DDCUIN10.DATA
//DDCUOT10 DD DISP=SHR,DSN=GENAPP.DDCUOT10.DATA
//DDCURP10 DD DISP=SHR,DSN=GENAPP.DDCURP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01W69
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN11 DD DISP=SHR,DSN=GENAPP.DDTXIN11.DATA
//DDTXOT11 DD DISP=SHR,DSN=GENAPP.DDTXOT11.DATA
//DDTXRP11 DD DISP=SHR,DSN=GENAPP.DDTXRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN01W6A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN12 DD DISP=SHR,DSN=GENAPP.DDANIN12.DATA
//DDANOT12 DD DISP=SHR,DSN=GENAPP.DDANOT12.DATA
//DDANRP12 DD DISP=SHR,DSN=GENAPP.DDANRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
