//VJOB4330 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT0255B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN31 DD DISP=SHR,DSN=GENAPP.DDMTIN31.DATA
//DDMTOT31 DD DISP=SHR,DSN=GENAPP.DDMTOT31.DATA
//DDMTRP31 DD DISP=SHR,DSN=GENAPP.DDMTRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZGW0255C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN32 DD DISP=SHR,DSN=GENAPP.DDGWIN32.DATA
//DDGWOT32 DD DISP=SHR,DSN=GENAPP.DDGWOT32.DATA
//DDGWRP32 DD DISP=SHR,DSN=GENAPP.DDGWRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO0255D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN33 DD DISP=SHR,DSN=GENAPP.DDHOIN33.DATA
//DDHOOT33 DD DISP=SHR,DSN=GENAPP.DDHOOT33.DATA
//DDHORP33 DD DISP=SHR,DSN=GENAPP.DDHORP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
