//VJOB0809 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01WZW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN88 DD DISP=SHR,DSN=GENAPP.DDHOIN88.DATA
//DDHOOT88 DD DISP=SHR,DSN=GENAPP.DDHOOT88.DATA
//DDHORP88 DD DISP=SHR,DSN=GENAPP.DDHORP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA01WZX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN89 DD DISP=SHR,DSN=GENAPP.DDBAIN89.DATA
//DDBAOT89 DD DISP=SHR,DSN=GENAPP.DDBAOT89.DATA
//DDBARP89 DD DISP=SHR,DSN=GENAPP.DDBARP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01WZY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN90 DD DISP=SHR,DSN=GENAPP.DDMTIN90.DATA
//DDMTOT90 DD DISP=SHR,DSN=GENAPP.DDMTOT90.DATA
//DDMTRP90 DD DISP=SHR,DSN=GENAPP.DDMTRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
