//VJOB2258 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL020CN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN25 DD DISP=SHR,DSN=GENAPP.DDCLIN25.DATA
//DDCLOT25 DD DISP=SHR,DSN=GENAPP.DDCLOT25.DATA
//DDCLRP25 DD DISP=SHR,DSN=GENAPP.DDCLRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN020CO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN26 DD DISP=SHR,DSN=GENAPP.DDRNIN26.DATA
//DDRNOT26 DD DISP=SHR,DSN=GENAPP.DDRNOT26.DATA
//DDRNRP26 DD DISP=SHR,DSN=GENAPP.DDRNRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO020CP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN27 DD DISP=SHR,DSN=GENAPP.DDCOIN27.DATA
//DDCOOT27 DD DISP=SHR,DSN=GENAPP.DDCOOT27.DATA
//DDCORP27 DD DISP=SHR,DSN=GENAPP.DDCORP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
