//VJOB3766 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDI023UB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN49 DD DISP=SHR,DSN=GENAPP.DDDIIN49.DATA
//DDDIOT49 DD DISP=SHR,DSN=GENAPP.DDDIOT49.DATA
//DDDIRP49 DD DISP=SHR,DSN=GENAPP.DDDIRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG023UC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN50 DD DISP=SHR,DSN=GENAPP.DDRGIN50.DATA
//DDRGOT50 DD DISP=SHR,DSN=GENAPP.DDRGOT50.DATA
//DDRGRP50 DD DISP=SHR,DSN=GENAPP.DDRGRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDI023UD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN51 DD DISP=SHR,DSN=GENAPP.DDDIIN51.DATA
//DDDIOT51 DD DISP=SHR,DSN=GENAPP.DDDIOT51.DATA
//DDDIRP51 DD DISP=SHR,DSN=GENAPP.DDDIRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
