//VJOB1261 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01Y1K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN04 DD DISP=SHR,DSN=GENAPP.DDENIN04.DATA
//DDENOT04 DD DISP=SHR,DSN=GENAPP.DDENOT04.DATA
//DDENRP04 DD DISP=SHR,DSN=GENAPP.DDENRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01Y1L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN05 DD DISP=SHR,DSN=GENAPP.DDBIIN05.DATA
//DDBIOT05 DD DISP=SHR,DSN=GENAPP.DDBIOT05.DATA
//DDBIRP05 DD DISP=SHR,DSN=GENAPP.DDBIRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC01Y1M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN06 DD DISP=SHR,DSN=GENAPP.DDACIN06.DATA
//DDACOT06 DD DISP=SHR,DSN=GENAPP.DDACOT06.DATA
//DDACRP06 DD DISP=SHR,DSN=GENAPP.DDACRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
