//VJOB2789 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRN021KW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN88 DD DISP=SHR,DSN=GENAPP.DDRNIN88.DATA
//DDRNOT88 DD DISP=SHR,DSN=GENAPP.DDRNOT88.DATA
//DDRNRP88 DD DISP=SHR,DSN=GENAPP.DDRNRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZGW021KX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN89 DD DISP=SHR,DSN=GENAPP.DDGWIN89.DATA
//DDGWOT89 DD DISP=SHR,DSN=GENAPP.DDGWOT89.DATA
//DDGWRP89 DD DISP=SHR,DSN=GENAPP.DDGWRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE021KY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN90 DD DISP=SHR,DSN=GENAPP.DDPEIN90.DATA
//DDPEOT90 DD DISP=SHR,DSN=GENAPP.DDPEOT90.DATA
//DDPERP90 DD DISP=SHR,DSN=GENAPP.DDPERP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
