//VJOB3817 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA023YK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN22 DD DISP=SHR,DSN=GENAPP.DDBAIN22.DATA
//DDBAOT22 DD DISP=SHR,DSN=GENAPP.DDBAOT22.DATA
//DDBARP22 DD DISP=SHR,DSN=GENAPP.DDBARP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG023YL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN23 DD DISP=SHR,DSN=GENAPP.DDAGIN23.DATA
//DDAGOT23 DD DISP=SHR,DSN=GENAPP.DDAGOT23.DATA
//DDAGRP23 DD DISP=SHR,DSN=GENAPP.DDAGRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT023YM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN24 DD DISP=SHR,DSN=GENAPP.DDMTIN24.DATA
//DDMTOT24 DD DISP=SHR,DSN=GENAPP.DDMTOT24.DATA
//DDMTRP24 DD DISP=SHR,DSN=GENAPP.DDMTRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
