//VJOB4048 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR024HT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN85 DD DISP=SHR,DSN=GENAPP.DDFRIN85.DATA
//DDFROT85 DD DISP=SHR,DSN=GENAPP.DDFROT85.DATA
//DDFRRP85 DD DISP=SHR,DSN=GENAPP.DDFRRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT024HU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN86 DD DISP=SHR,DSN=GENAPP.DDMTIN86.DATA
//DDMTOT86 DD DISP=SHR,DSN=GENAPP.DDMTOT86.DATA
//DDMTRP86 DD DISP=SHR,DSN=GENAPP.DDMTRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF024HV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN87 DD DISP=SHR,DSN=GENAPP.DDIFIN87.DATA
//DDIFOT87 DD DISP=SHR,DSN=GENAPP.DDIFOT87.DATA
//DDIFRP87 DD DISP=SHR,DSN=GENAPP.DDIFRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
