//VJOB3941 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO0248W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN34 DD DISP=SHR,DSN=GENAPP.DDHOIN34.DATA
//DDHOOT34 DD DISP=SHR,DSN=GENAPP.DDHOOT34.DATA
//DDHORP34 DD DISP=SHR,DSN=GENAPP.DDHORP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA0248X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN35 DD DISP=SHR,DSN=GENAPP.DDMAIN35.DATA
//DDMAOT35 DD DISP=SHR,DSN=GENAPP.DDMAOT35.DATA
//DDMARP35 DD DISP=SHR,DSN=GENAPP.DDMARP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE0248Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN36 DD DISP=SHR,DSN=GENAPP.DDREIN36.DATA
//DDREOT36 DD DISP=SHR,DSN=GENAPP.DDREOT36.DATA
//DDRERP36 DD DISP=SHR,DSN=GENAPP.DDRERP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
