//VJOB3254 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCR022NN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN43 DD DISP=SHR,DSN=GENAPP.DDCRIN43.DATA
//DDCROT43 DD DISP=SHR,DSN=GENAPP.DDCROT43.DATA
//DDCRRP43 DD DISP=SHR,DSN=GENAPP.DDCRRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN022NO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN44 DD DISP=SHR,DSN=GENAPP.DDENIN44.DATA
//DDENOT44 DD DISP=SHR,DSN=GENAPP.DDENOT44.DATA
//DDENRP44 DD DISP=SHR,DSN=GENAPP.DDENRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW022NP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN45 DD DISP=SHR,DSN=GENAPP.DDUWIN45.DATA
//DDUWOT45 DD DISP=SHR,DSN=GENAPP.DDUWOT45.DATA
//DDUWRP45 DD DISP=SHR,DSN=GENAPP.DDUWRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
