//VJOB4174 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE024SB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN13 DD DISP=SHR,DSN=GENAPP.DDREIN13.DATA
//DDREOT13 DD DISP=SHR,DSN=GENAPP.DDREOT13.DATA
//DDRERP13 DD DISP=SHR,DSN=GENAPP.DDRERP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE024SC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN14 DD DISP=SHR,DSN=GENAPP.DDHEIN14.DATA
//DDHEOT14 DD DISP=SHR,DSN=GENAPP.DDHEOT14.DATA
//DDHERP14 DD DISP=SHR,DSN=GENAPP.DDHERP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN024SD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN15 DD DISP=SHR,DSN=GENAPP.DDENIN15.DATA
//DDENOT15 DD DISP=SHR,DSN=GENAPP.DDENOT15.DATA
//DDENRP15 DD DISP=SHR,DSN=GENAPP.DDENRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
