//VJOB2444 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPL020S5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN43 DD DISP=SHR,DSN=GENAPP.DDPLIN43.DATA
//DDPLOT43 DD DISP=SHR,DSN=GENAPP.DDPLOT43.DATA
//DDPLRP43 DD DISP=SHR,DSN=GENAPP.DDPLRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI020S6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN44 DD DISP=SHR,DSN=GENAPP.DDBIIN44.DATA
//DDBIOT44 DD DISP=SHR,DSN=GENAPP.DDBIOT44.DATA
//DDBIRP44 DD DISP=SHR,DSN=GENAPP.DDBIRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR020S7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN45 DD DISP=SHR,DSN=GENAPP.DDFRIN45.DATA
//DDFROT45 DD DISP=SHR,DSN=GENAPP.DDFROT45.DATA
//DDFRRP45 DD DISP=SHR,DSN=GENAPP.DDFRRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
