//VJOB2998 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE0222B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN85 DD DISP=SHR,DSN=GENAPP.DDREIN85.DATA
//DDREOT85 DD DISP=SHR,DSN=GENAPP.DDREOT85.DATA
//DDRERP85 DD DISP=SHR,DSN=GENAPP.DDRERP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO0222C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN86 DD DISP=SHR,DSN=GENAPP.DDHOIN86.DATA
//DDHOOT86 DD DISP=SHR,DSN=GENAPP.DDHOOT86.DATA
//DDHORP86 DD DISP=SHR,DSN=GENAPP.DDHORP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU0222D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN87 DD DISP=SHR,DSN=GENAPP.DDCUIN87.DATA
//DDCUOT87 DD DISP=SHR,DSN=GENAPP.DDCUOT87.DATA
//DDCURP87 DD DISP=SHR,DSN=GENAPP.DDCURP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
