//VJOB1062 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE01XKZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN37 DD DISP=SHR,DSN=GENAPP.DDSEIN37.DATA
//DDSEOT37 DD DISP=SHR,DSN=GENAPP.DDSEOT37.DATA
//DDSERP37 DD DISP=SHR,DSN=GENAPP.DDSERP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAC01XL0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN38 DD DISP=SHR,DSN=GENAPP.DDACIN38.DATA
//DDACOT38 DD DISP=SHR,DSN=GENAPP.DDACOT38.DATA
//DDACRP38 DD DISP=SHR,DSN=GENAPP.DDACRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01XL1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN39 DD DISP=SHR,DSN=GENAPP.DDCLIN39.DATA
//DDCLOT39 DD DISP=SHR,DSN=GENAPP.DDCLOT39.DATA
//DDCLRP39 DD DISP=SHR,DSN=GENAPP.DDCLRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
