//VJOB0722 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP01WSN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN07 DD DISP=SHR,DSN=GENAPP.DDCPIN07.DATA
//DDCPOT07 DD DISP=SHR,DSN=GENAPP.DDCPOT07.DATA
//DDCPRP07 DD DISP=SHR,DSN=GENAPP.DDCPRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB01WSO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN08 DD DISP=SHR,DSN=GENAPP.DDLBIN08.DATA
//DDLBOT08 DD DISP=SHR,DSN=GENAPP.DDLBOT08.DATA
//DDLBRP08 DD DISP=SHR,DSN=GENAPP.DDLBRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZWF01WSP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN09 DD DISP=SHR,DSN=GENAPP.DDWFIN09.DATA
//DDWFOT09 DD DISP=SHR,DSN=GENAPP.DDWFOT09.DATA
//DDWFRP09 DD DISP=SHR,DSN=GENAPP.DDWFRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
