//VJOB2791 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBR021L2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN04 DD DISP=SHR,DSN=GENAPP.DDBRIN04.DATA
//DDBROT04 DD DISP=SHR,DSN=GENAPP.DDBROT04.DATA
//DDBRRP04 DD DISP=SHR,DSN=GENAPP.DDBRRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT021L3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN05 DD DISP=SHR,DSN=GENAPP.DDMTIN05.DATA
//DDMTOT05 DD DISP=SHR,DSN=GENAPP.DDMTOT05.DATA
//DDMTRP05 DD DISP=SHR,DSN=GENAPP.DDMTRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF021L4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN06 DD DISP=SHR,DSN=GENAPP.DDIFIN06.DATA
//DDIFOT06 DD DISP=SHR,DSN=GENAPP.DDIFOT06.DATA
//DDIFRP06 DD DISP=SHR,DSN=GENAPP.DDIFRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
