//VJOB4321 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA0254K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN04 DD DISP=SHR,DSN=GENAPP.DDBAIN04.DATA
//DDBAOT04 DD DISP=SHR,DSN=GENAPP.DDBAOT04.DATA
//DDBARP04 DD DISP=SHR,DSN=GENAPP.DDBARP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ0254L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN05 DD DISP=SHR,DSN=GENAPP.DDAZIN05.DATA
//DDAZOT05 DD DISP=SHR,DSN=GENAPP.DDAZOT05.DATA
//DDAZRP05 DD DISP=SHR,DSN=GENAPP.DDAZRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI0254M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN06 DD DISP=SHR,DSN=GENAPP.DDLIIN06.DATA
//DDLIOT06 DD DISP=SHR,DSN=GENAPP.DDLIOT06.DATA
//DDLIRP06 DD DISP=SHR,DSN=GENAPP.DDLIRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
