//VJOB1902 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01ZIZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN37 DD DISP=SHR,DSN=GENAPP.DDHOIN37.DATA
//DDHOOT37 DD DISP=SHR,DSN=GENAPP.DDHOOT37.DATA
//DDHORP37 DD DISP=SHR,DSN=GENAPP.DDHORP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01ZJ0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN38 DD DISP=SHR,DSN=GENAPP.DDCLIN38.DATA
//DDCLOT38 DD DISP=SHR,DSN=GENAPP.DDCLOT38.DATA
//DDCLRP38 DD DISP=SHR,DSN=GENAPP.DDCLRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZWF01ZJ1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN39 DD DISP=SHR,DSN=GENAPP.DDWFIN39.DATA
//DDWFOT39 DD DISP=SHR,DSN=GENAPP.DDWFOT39.DATA
//DDWFRP39 DD DISP=SHR,DSN=GENAPP.DDWFRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
