//VJOB1209 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS01XX8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN28 DD DISP=SHR,DSN=GENAPP.DDRSIN28.DATA
//DDRSOT28 DD DISP=SHR,DSN=GENAPP.DDRSOT28.DATA
//DDRSRP28 DD DISP=SHR,DSN=GENAPP.DDRSRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01XX9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN29 DD DISP=SHR,DSN=GENAPP.DDHOIN29.DATA
//DDHOOT29 DD DISP=SHR,DSN=GENAPP.DDHOOT29.DATA
//DDHORP29 DD DISP=SHR,DSN=GENAPP.DDHORP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZNT01XXA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN30 DD DISP=SHR,DSN=GENAPP.DDNTIN30.DATA
//DDNTOT30 DD DISP=SHR,DSN=GENAPP.DDNTOT30.DATA
//DDNTRP30 DD DISP=SHR,DSN=GENAPP.DDNTRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
