//VJOB0392 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01W15
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN07 DD DISP=SHR,DSN=GENAPP.DDMTIN07.DATA
//DDMTOT07 DD DISP=SHR,DSN=GENAPP.DDMTOT07.DATA
//DDMTRP07 DD DISP=SHR,DSN=GENAPP.DDMTRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT01W16
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN08 DD DISP=SHR,DSN=GENAPP.DDNTIN08.DATA
//DDNTOT08 DD DISP=SHR,DSN=GENAPP.DDNTOT08.DATA
//DDNTRP08 DD DISP=SHR,DSN=GENAPP.DDNTRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG01W17
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN09 DD DISP=SHR,DSN=GENAPP.DDAGIN09.DATA
//DDAGOT09 DD DISP=SHR,DSN=GENAPP.DDAGOT09.DATA
//DDAGRP09 DD DISP=SHR,DSN=GENAPP.DDAGRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
