//VJOB0620 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01WK5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN61 DD DISP=SHR,DSN=GENAPP.DDHOIN61.DATA
//DDHOOT61 DD DISP=SHR,DSN=GENAPP.DDHOOT61.DATA
//DDHORP61 DD DISP=SHR,DSN=GENAPP.DDHORP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDI01WK6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN62 DD DISP=SHR,DSN=GENAPP.DDDIIN62.DATA
//DDDIOT62 DD DISP=SHR,DSN=GENAPP.DDDIOT62.DATA
//DDDIRP62 DD DISP=SHR,DSN=GENAPP.DDDIRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01WK7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN63 DD DISP=SHR,DSN=GENAPP.DDTRIN63.DATA
//DDTROT63 DD DISP=SHR,DSN=GENAPP.DDTROT63.DATA
//DDTRRP63 DD DISP=SHR,DSN=GENAPP.DDTRRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
