//VJOB0410 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01W2N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN61 DD DISP=SHR,DSN=GENAPP.DDBIIN61.DATA
//DDBIOT61 DD DISP=SHR,DSN=GENAPP.DDBIOT61.DATA
//DDBIRP61 DD DISP=SHR,DSN=GENAPP.DDBIRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC01W2O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN62 DD DISP=SHR,DSN=GENAPP.DDSCIN62.DATA
//DDSCOT62 DD DISP=SHR,DSN=GENAPP.DDSCOT62.DATA
//DDSCRP62 DD DISP=SHR,DSN=GENAPP.DDSCRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01W2P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN63 DD DISP=SHR,DSN=GENAPP.DDPRIN63.DATA
//DDPROT63 DD DISP=SHR,DSN=GENAPP.DDPROT63.DATA
//DDPRRP63 DD DISP=SHR,DSN=GENAPP.DDPRRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
