//VJOB3814 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI023YB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN13 DD DISP=SHR,DSN=GENAPP.DDLIIN13.DATA
//DDLIOT13 DD DISP=SHR,DSN=GENAPP.DDLIOT13.DATA
//DDLIRP13 DD DISP=SHR,DSN=GENAPP.DDLIRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO023YC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN14 DD DISP=SHR,DSN=GENAPP.DDHOIN14.DATA
//DDHOOT14 DD DISP=SHR,DSN=GENAPP.DDHOOT14.DATA
//DDHORP14 DD DISP=SHR,DSN=GENAPP.DDHORP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL023YD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN15 DD DISP=SHR,DSN=GENAPP.DDCLIN15.DATA
//DDCLOT15 DD DISP=SHR,DSN=GENAPP.DDCLOT15.DATA
//DDCLRP15 DD DISP=SHR,DSN=GENAPP.DDCLRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
