//VJOB1227 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01XYQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN82 DD DISP=SHR,DSN=GENAPP.DDMTIN82.DATA
//DDMTOT82 DD DISP=SHR,DSN=GENAPP.DDMTOT82.DATA
//DDMTRP82 DD DISP=SHR,DSN=GENAPP.DDMTRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE01XYR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN83 DD DISP=SHR,DSN=GENAPP.DDHEIN83.DATA
//DDHEOT83 DD DISP=SHR,DSN=GENAPP.DDHEOT83.DATA
//DDHERP83 DD DISP=SHR,DSN=GENAPP.DDHERP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01XYS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN84 DD DISP=SHR,DSN=GENAPP.DDENIN84.DATA
//DDENOT84 DD DISP=SHR,DSN=GENAPP.DDENOT84.DATA
//DDENRP84 DD DISP=SHR,DSN=GENAPP.DDENRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
