//VJOB3265 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW022OK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN76 DD DISP=SHR,DSN=GENAPP.DDUWIN76.DATA
//DDUWOT76 DD DISP=SHR,DSN=GENAPP.DDUWOT76.DATA
//DDUWRP76 DD DISP=SHR,DSN=GENAPP.DDUWRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSL022OL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN77 DD DISP=SHR,DSN=GENAPP.DDSLIN77.DATA
//DDSLOT77 DD DISP=SHR,DSN=GENAPP.DDSLOT77.DATA
//DDSLRP77 DD DISP=SHR,DSN=GENAPP.DDSLRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR022OM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN78 DD DISP=SHR,DSN=GENAPP.DDARIN78.DATA
//DDAROT78 DD DISP=SHR,DSN=GENAPP.DDAROT78.DATA
//DDARRP78 DD DISP=SHR,DSN=GENAPP.DDARRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
