//VJOB2729 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLT021FW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN88 DD DISP=SHR,DSN=GENAPP.DDLTIN88.DATA
//DDLTOT88 DD DISP=SHR,DSN=GENAPP.DDLTOT88.DATA
//DDLTRP88 DD DISP=SHR,DSN=GENAPP.DDLTRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPT021FX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN89 DD DISP=SHR,DSN=GENAPP.DDPTIN89.DATA
//DDPTOT89 DD DISP=SHR,DSN=GENAPP.DDPTOT89.DATA
//DDPTRP89 DD DISP=SHR,DSN=GENAPP.DDPTRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO021FY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN90 DD DISP=SHR,DSN=GENAPP.DDHOIN90.DATA
//DDHOOT90 DD DISP=SHR,DSN=GENAPP.DDHOOT90.DATA
//DDHORP90 DD DISP=SHR,DSN=GENAPP.DDHORP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
