//VJOB2450 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG020SN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN61 DD DISP=SHR,DSN=GENAPP.DDAGIN61.DATA
//DDAGOT61 DD DISP=SHR,DSN=GENAPP.DDAGOT61.DATA
//DDAGRP61 DD DISP=SHR,DSN=GENAPP.DDAGRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU020SO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN62 DD DISP=SHR,DSN=GENAPP.DDCUIN62.DATA
//DDCUOT62 DD DISP=SHR,DSN=GENAPP.DDCUOT62.DATA
//DDCURP62 DD DISP=SHR,DSN=GENAPP.DDCURP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPL020SP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN63 DD DISP=SHR,DSN=GENAPP.DDPLIN63.DATA
//DDPLOT63 DD DISP=SHR,DSN=GENAPP.DDPLOT63.DATA
//DDPLRP63 DD DISP=SHR,DSN=GENAPP.DDPLRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
