//VJOB3615 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI023HQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN46 DD DISP=SHR,DSN=GENAPP.DDBIIN46.DATA
//DDBIOT46 DD DISP=SHR,DSN=GENAPP.DDBIOT46.DATA
//DDBIRP46 DD DISP=SHR,DSN=GENAPP.DDBIRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR023HR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN47 DD DISP=SHR,DSN=GENAPP.DDCRIN47.DATA
//DDCROT47 DD DISP=SHR,DSN=GENAPP.DDCROT47.DATA
//DDCRRP47 DD DISP=SHR,DSN=GENAPP.DDCRRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE023HS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN48 DD DISP=SHR,DSN=GENAPP.DDPEIN48.DATA
//DDPEOT48 DD DISP=SHR,DSN=GENAPP.DDPEOT48.DATA
//DDPERP48 DD DISP=SHR,DSN=GENAPP.DDPERP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
