//VJOB2108 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW02005
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN25 DD DISP=SHR,DSN=GENAPP.DDUWIN25.DATA
//DDUWOT25 DD DISP=SHR,DSN=GENAPP.DDUWOT25.DATA
//DDUWRP25 DD DISP=SHR,DSN=GENAPP.DDUWRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY02006
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN26 DD DISP=SHR,DSN=GENAPP.DDTYIN26.DATA
//DDTYOT26 DD DISP=SHR,DSN=GENAPP.DDTYOT26.DATA
//DDTYRP26 DD DISP=SHR,DSN=GENAPP.DDTYRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA02007
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN27 DD DISP=SHR,DSN=GENAPP.DDPAIN27.DATA
//DDPAOT27 DD DISP=SHR,DSN=GENAPP.DDPAOT27.DATA
//DDPARP27 DD DISP=SHR,DSN=GENAPP.DDPARP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
