//VJOB1879 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01ZH2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN58 DD DISP=SHR,DSN=GENAPP.DDENIN58.DATA
//DDENOT58 DD DISP=SHR,DSN=GENAPP.DDENOT58.DATA
//DDENRP58 DD DISP=SHR,DSN=GENAPP.DDENRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE01ZH3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN59 DD DISP=SHR,DSN=GENAPP.DDHEIN59.DATA
//DDHEOT59 DD DISP=SHR,DSN=GENAPP.DDHEOT59.DATA
//DDHERP59 DD DISP=SHR,DSN=GENAPP.DDHERP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01ZH4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN60 DD DISP=SHR,DSN=GENAPP.DDENIN60.DATA
//DDENOT60 DD DISP=SHR,DSN=GENAPP.DDENOT60.DATA
//DDENRP60 DD DISP=SHR,DSN=GENAPP.DDENRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
