//VJOB3624 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP023IH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN73 DD DISP=SHR,DSN=GENAPP.DDCPIN73.DATA
//DDCPOT73 DD DISP=SHR,DSN=GENAPP.DDCPOT73.DATA
//DDCPRP73 DD DISP=SHR,DSN=GENAPP.DDCPRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI023II
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN74 DD DISP=SHR,DSN=GENAPP.DDBIIN74.DATA
//DDBIOT74 DD DISP=SHR,DSN=GENAPP.DDBIOT74.DATA
//DDBIRP74 DD DISP=SHR,DSN=GENAPP.DDBIRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO023IJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN75 DD DISP=SHR,DSN=GENAPP.DDHOIN75.DATA
//DDHOOT75 DD DISP=SHR,DSN=GENAPP.DDHOOT75.DATA
//DDHORP75 DD DISP=SHR,DSN=GENAPP.DDHORP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
