//VJOB2430 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA020QZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN01 DD DISP=SHR,DSN=GENAPP.DDPAIN01.DATA
//DDPAOT01 DD DISP=SHR,DSN=GENAPP.DDPAOT01.DATA
//DDPARP01 DD DISP=SHR,DSN=GENAPP.DDPARP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZVA020R0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN02 DD DISP=SHR,DSN=GENAPP.DDVAIN02.DATA
//DDVAOT02 DD DISP=SHR,DSN=GENAPP.DDVAOT02.DATA
//DDVARP02 DD DISP=SHR,DSN=GENAPP.DDVARP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO020R1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN03 DD DISP=SHR,DSN=GENAPP.DDHOIN03.DATA
//DDHOOT03 DD DISP=SHR,DSN=GENAPP.DDHOOT03.DATA
//DDHORP03 DD DISP=SHR,DSN=GENAPP.DDHORP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
