//VJOB0859 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSU01X42
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN58 DD DISP=SHR,DSN=GENAPP.DDSUIN58.DATA
//DDSUOT58 DD DISP=SHR,DSN=GENAPP.DDSUOT58.DATA
//DDSURP58 DD DISP=SHR,DSN=GENAPP.DDSURP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF01X43
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN59 DD DISP=SHR,DSN=GENAPP.DDIFIN59.DATA
//DDIFOT59 DD DISP=SHR,DSN=GENAPP.DDIFOT59.DATA
//DDIFRP59 DD DISP=SHR,DSN=GENAPP.DDIFRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEX01X44
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN60 DD DISP=SHR,DSN=GENAPP.DDEXIN60.DATA
//DDEXOT60 DD DISP=SHR,DSN=GENAPP.DDEXOT60.DATA
//DDEXRP60 DD DISP=SHR,DSN=GENAPP.DDEXRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
