//VJOB1233 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL01XZ8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN10 DD DISP=SHR,DSN=GENAPP.DDFLIN10.DATA
//DDFLOT10 DD DISP=SHR,DSN=GENAPP.DDFLOT10.DATA
//DDFLRP10 DD DISP=SHR,DSN=GENAPP.DDFLRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT01XZ9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN11 DD DISP=SHR,DSN=GENAPP.DDLTIN11.DATA
//DDLTOT11 DD DISP=SHR,DSN=GENAPP.DDLTOT11.DATA
//DDLTRP11 DD DISP=SHR,DSN=GENAPP.DDLTRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZGW01XZA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN12 DD DISP=SHR,DSN=GENAPP.DDGWIN12.DATA
//DDGWOT12 DD DISP=SHR,DSN=GENAPP.DDGWOT12.DATA
//DDGWRP12 DD DISP=SHR,DSN=GENAPP.DDGWRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
