//VJOB1249 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT01Y0K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN58 DD DISP=SHR,DSN=GENAPP.DDPTIN58.DATA
//DDPTOT58 DD DISP=SHR,DSN=GENAPP.DDPTOT58.DATA
//DDPTRP58 DD DISP=SHR,DSN=GENAPP.DDPTRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01Y0L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN59 DD DISP=SHR,DSN=GENAPP.DDCUIN59.DATA
//DDCUOT59 DD DISP=SHR,DSN=GENAPP.DDCUOT59.DATA
//DDCURP59 DD DISP=SHR,DSN=GENAPP.DDCURP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL01Y0M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN60 DD DISP=SHR,DSN=GENAPP.DDFLIN60.DATA
//DDFLOT60 DD DISP=SHR,DSN=GENAPP.DDFLOT60.DATA
//DDFLRP60 DD DISP=SHR,DSN=GENAPP.DDFLRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
