//VJOB4068 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT024JH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN55 DD DISP=SHR,DSN=GENAPP.DDMTIN55.DATA
//DDMTOT55 DD DISP=SHR,DSN=GENAPP.DDMTOT55.DATA
//DDMTRP55 DD DISP=SHR,DSN=GENAPP.DDMTRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX024JI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN56 DD DISP=SHR,DSN=GENAPP.DDTXIN56.DATA
//DDTXOT56 DD DISP=SHR,DSN=GENAPP.DDTXOT56.DATA
//DDTXRP56 DD DISP=SHR,DSN=GENAPP.DDTXRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO024JJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN57 DD DISP=SHR,DSN=GENAPP.DDHOIN57.DATA
//DDHOOT57 DD DISP=SHR,DSN=GENAPP.DDHOOT57.DATA
//DDHORP57 DD DISP=SHR,DSN=GENAPP.DDHORP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
