//VJOB1460 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZVA01YI5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN61 DD DISP=SHR,DSN=GENAPP.DDVAIN61.DATA
//DDVAOT61 DD DISP=SHR,DSN=GENAPP.DDVAOT61.DATA
//DDVARP61 DD DISP=SHR,DSN=GENAPP.DDVARP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN01YI6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN62 DD DISP=SHR,DSN=GENAPP.DDANIN62.DATA
//DDANOT62 DD DISP=SHR,DSN=GENAPP.DDANOT62.DATA
//DDANRP62 DD DISP=SHR,DSN=GENAPP.DDANRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01YI7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN63 DD DISP=SHR,DSN=GENAPP.DDMAIN63.DATA
//DDMAOT63 DD DISP=SHR,DSN=GENAPP.DDMAOT63.DATA
//DDMARP63 DD DISP=SHR,DSN=GENAPP.DDMARP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
