//VJOB1783 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01Z92
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN40 DD DISP=SHR,DSN=GENAPP.DDMTIN40.DATA
//DDMTOT40 DD DISP=SHR,DSN=GENAPP.DDMTOT40.DATA
//DDMTRP40 DD DISP=SHR,DSN=GENAPP.DDMTRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ01Z93
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN41 DD DISP=SHR,DSN=GENAPP.DDAZIN41.DATA
//DDAZOT41 DD DISP=SHR,DSN=GENAPP.DDAZOT41.DATA
//DDAZRP41 DD DISP=SHR,DSN=GENAPP.DDAZRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC01Z94
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN42 DD DISP=SHR,DSN=GENAPP.DDACIN42.DATA
//DDACOT42 DD DISP=SHR,DSN=GENAPP.DDACOT42.DATA
//DDACRP42 DD DISP=SHR,DSN=GENAPP.DDACRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
