//VJOB1078 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01XMB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN85 DD DISP=SHR,DSN=GENAPP.DDCUIN85.DATA
//DDCUOT85 DD DISP=SHR,DSN=GENAPP.DDCUOT85.DATA
//DDCURP85 DD DISP=SHR,DSN=GENAPP.DDCURP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCN01XMC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN86 DD DISP=SHR,DSN=GENAPP.DDCNIN86.DATA
//DDCNOT86 DD DISP=SHR,DSN=GENAPP.DDCNOT86.DATA
//DDCNRP86 DD DISP=SHR,DSN=GENAPP.DDCNRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTY01XMD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN87 DD DISP=SHR,DSN=GENAPP.DDTYIN87.DATA
//DDTYOT87 DD DISP=SHR,DSN=GENAPP.DDTYOT87.DATA
//DDTYRP87 DD DISP=SHR,DSN=GENAPP.DDTYRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
