//VJOB0013 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA01V5K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN40 DD DISP=SHR,DSN=GENAPP.DDBAIN40.DATA
//DDBAOT40 DD DISP=SHR,DSN=GENAPP.DDBAOT40.DATA
//DDBARP40 DD DISP=SHR,DSN=GENAPP.DDBARP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF01V5L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN41 DD DISP=SHR,DSN=GENAPP.DDIFIN41.DATA
//DDIFOT41 DD DISP=SHR,DSN=GENAPP.DDIFOT41.DATA
//DDIFRP41 DD DISP=SHR,DSN=GENAPP.DDIFRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZGW01V5M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN42 DD DISP=SHR,DSN=GENAPP.DDGWIN42.DATA
//DDGWOT42 DD DISP=SHR,DSN=GENAPP.DDGWOT42.DATA
//DDGWRP42 DD DISP=SHR,DSN=GENAPP.DDGWRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
