//VJOB3731 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN023RE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN34 DD DISP=SHR,DSN=GENAPP.DDENIN34.DATA
//DDENOT34 DD DISP=SHR,DSN=GENAPP.DDENOT34.DATA
//DDENRP34 DD DISP=SHR,DSN=GENAPP.DDENRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI023RF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN35 DD DISP=SHR,DSN=GENAPP.DDBIIN35.DATA
//DDBIOT35 DD DISP=SHR,DSN=GENAPP.DDBIOT35.DATA
//DDBIRP35 DD DISP=SHR,DSN=GENAPP.DDBIRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR023RG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN36 DD DISP=SHR,DSN=GENAPP.DDTRIN36.DATA
//DDTROT36 DD DISP=SHR,DSN=GENAPP.DDTROT36.DATA
//DDTRRP36 DD DISP=SHR,DSN=GENAPP.DDTRRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
