//VJOB0738 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY01WTZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN55 DD DISP=SHR,DSN=GENAPP.DDTYIN55.DATA
//DDTYOT55 DD DISP=SHR,DSN=GENAPP.DDTYOT55.DATA
//DDTYRP55 DD DISP=SHR,DSN=GENAPP.DDTYRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR01WU0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN56 DD DISP=SHR,DSN=GENAPP.DDCRIN56.DATA
//DDCROT56 DD DISP=SHR,DSN=GENAPP.DDCROT56.DATA
//DDCRRP56 DD DISP=SHR,DSN=GENAPP.DDCRRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01WU1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN57 DD DISP=SHR,DSN=GENAPP.DDENIN57.DATA
//DDENOT57 DD DISP=SHR,DSN=GENAPP.DDENOT57.DATA
//DDENRP57 DD DISP=SHR,DSN=GENAPP.DDENRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
