//VJOB1001 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAR01XFW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN34 DD DISP=SHR,DSN=GENAPP.DDARIN34.DATA
//DDAROT34 DD DISP=SHR,DSN=GENAPP.DDAROT34.DATA
//DDARRP34 DD DISP=SHR,DSN=GENAPP.DDARRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY01XFX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN35 DD DISP=SHR,DSN=GENAPP.DDTYIN35.DATA
//DDTYOT35 DD DISP=SHR,DSN=GENAPP.DDTYOT35.DATA
//DDTYRP35 DD DISP=SHR,DSN=GENAPP.DDTYRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRT01XFY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN36 DD DISP=SHR,DSN=GENAPP.DDRTIN36.DATA
//DDRTOT36 DD DISP=SHR,DSN=GENAPP.DDRTOT36.DATA
//DDRTRP36 DD DISP=SHR,DSN=GENAPP.DDRTRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
