//VJOB0839 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01X2E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN88 DD DISP=SHR,DSN=GENAPP.DDCLIN88.DATA
//DDCLOT88 DD DISP=SHR,DSN=GENAPP.DDCLOT88.DATA
//DDCLRP88 DD DISP=SHR,DSN=GENAPP.DDCLRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT01X2F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN89 DD DISP=SHR,DSN=GENAPP.DDNTIN89.DATA
//DDNTOT89 DD DISP=SHR,DSN=GENAPP.DDNTOT89.DATA
//DDNTRP89 DD DISP=SHR,DSN=GENAPP.DDNTRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01X2G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN90 DD DISP=SHR,DSN=GENAPP.DDMTIN90.DATA
//DDMTOT90 DD DISP=SHR,DSN=GENAPP.DDMTOT90.DATA
//DDMTRP90 DD DISP=SHR,DSN=GENAPP.DDMTRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
