//VJOB1667 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01YZE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN52 DD DISP=SHR,DSN=GENAPP.DDHOIN52.DATA
//DDHOOT52 DD DISP=SHR,DSN=GENAPP.DDHOOT52.DATA
//DDHORP52 DD DISP=SHR,DSN=GENAPP.DDHORP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01YZF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN53 DD DISP=SHR,DSN=GENAPP.DDHOIN53.DATA
//DDHOOT53 DD DISP=SHR,DSN=GENAPP.DDHOOT53.DATA
//DDHORP53 DD DISP=SHR,DSN=GENAPP.DDHORP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01YZG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN54 DD DISP=SHR,DSN=GENAPP.DDMAIN54.DATA
//DDMAOT54 DD DISP=SHR,DSN=GENAPP.DDMAOT54.DATA
//DDMARP54 DD DISP=SHR,DSN=GENAPP.DDMARP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
