//VJOB0047 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01V8E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN52 DD DISP=SHR,DSN=GENAPP.DDHOIN52.DATA
//DDHOOT52 DD DISP=SHR,DSN=GENAPP.DDHOOT52.DATA
//DDHORP52 DD DISP=SHR,DSN=GENAPP.DDHORP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR01V8F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN53 DD DISP=SHR,DSN=GENAPP.DDTRIN53.DATA
//DDTROT53 DD DISP=SHR,DSN=GENAPP.DDTROT53.DATA
//DDTRRP53 DD DISP=SHR,DSN=GENAPP.DDTRRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV01V8G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN54 DD DISP=SHR,DSN=GENAPP.DDIVIN54.DATA
//DDIVOT54 DD DISP=SHR,DSN=GENAPP.DDIVOT54.DATA
//DDIVRP54 DD DISP=SHR,DSN=GENAPP.DDIVRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
