//VJOB1302 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01Y4Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN37 DD DISP=SHR,DSN=GENAPP.DDBIIN37.DATA
//DDBIOT37 DD DISP=SHR,DSN=GENAPP.DDBIOT37.DATA
//DDBIRP37 DD DISP=SHR,DSN=GENAPP.DDBIRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA01Y50
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN38 DD DISP=SHR,DSN=GENAPP.DDMAIN38.DATA
//DDMAOT38 DD DISP=SHR,DSN=GENAPP.DDMAOT38.DATA
//DDMARP38 DD DISP=SHR,DSN=GENAPP.DDMARP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC01Y51
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN39 DD DISP=SHR,DSN=GENAPP.DDSCIN39.DATA
//DDSCOT39 DD DISP=SHR,DSN=GENAPP.DDSCOT39.DATA
//DDSCRP39 DD DISP=SHR,DSN=GENAPP.DDSCRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
