//VJOB0076 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC01VAT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN49 DD DISP=SHR,DSN=GENAPP.DDACIN49.DATA
//DDACOT49 DD DISP=SHR,DSN=GENAPP.DDACOT49.DATA
//DDACRP49 DD DISP=SHR,DSN=GENAPP.DDACRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZGW01VAU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN50 DD DISP=SHR,DSN=GENAPP.DDGWIN50.DATA
//DDGWOT50 DD DISP=SHR,DSN=GENAPP.DDGWOT50.DATA
//DDGWRP50 DD DISP=SHR,DSN=GENAPP.DDGWRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCR01VAV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN51 DD DISP=SHR,DSN=GENAPP.DDCRIN51.DATA
//DDCROT51 DD DISP=SHR,DSN=GENAPP.DDCROT51.DATA
//DDCRRP51 DD DISP=SHR,DSN=GENAPP.DDCRRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
