//VJOB0466 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01W7B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN49 DD DISP=SHR,DSN=GENAPP.DDAVIN49.DATA
//DDAVOT49 DD DISP=SHR,DSN=GENAPP.DDAVOT49.DATA
//DDAVRP49 DD DISP=SHR,DSN=GENAPP.DDAVRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01W7C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN50 DD DISP=SHR,DSN=GENAPP.DDHOIN50.DATA
//DDHOOT50 DD DISP=SHR,DSN=GENAPP.DDHOOT50.DATA
//DDHORP50 DD DISP=SHR,DSN=GENAPP.DDHORP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01W7D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN51 DD DISP=SHR,DSN=GENAPP.DDTRIN51.DATA
//DDTROT51 DD DISP=SHR,DSN=GENAPP.DDTROT51.DATA
//DDTRRP51 DD DISP=SHR,DSN=GENAPP.DDTRRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
