//VJOB3878 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSC0243N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN25 DD DISP=SHR,DSN=GENAPP.DDSCIN25.DATA
//DDSCOT25 DD DISP=SHR,DSN=GENAPP.DDSCOT25.DATA
//DDSCRP25 DD DISP=SHR,DSN=GENAPP.DDSCRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZQU0243O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN26 DD DISP=SHR,DSN=GENAPP.DDQUIN26.DATA
//DDQUOT26 DD DISP=SHR,DSN=GENAPP.DDQUOT26.DATA
//DDQURP26 DD DISP=SHR,DSN=GENAPP.DDQURP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR0243P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN27 DD DISP=SHR,DSN=GENAPP.DDTRIN27.DATA
//DDTROT27 DD DISP=SHR,DSN=GENAPP.DDTROT27.DATA
//DDTRRP27 DD DISP=SHR,DSN=GENAPP.DDTRRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
