//VJOB0341 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01VWW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN34 DD DISP=SHR,DSN=GENAPP.DDBIIN34.DATA
//DDBIOT34 DD DISP=SHR,DSN=GENAPP.DDBIOT34.DATA
//DDBIRP34 DD DISP=SHR,DSN=GENAPP.DDBIRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPT01VWX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN35 DD DISP=SHR,DSN=GENAPP.DDPTIN35.DATA
//DDPTOT35 DD DISP=SHR,DSN=GENAPP.DDPTOT35.DATA
//DDPTRP35 DD DISP=SHR,DSN=GENAPP.DDPTRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCP01VWY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN36 DD DISP=SHR,DSN=GENAPP.DDCPIN36.DATA
//DDCPOT36 DD DISP=SHR,DSN=GENAPP.DDCPOT36.DATA
//DDCPRP36 DD DISP=SHR,DSN=GENAPP.DDCPRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
