//VJOB0932 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01XA5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN07 DD DISP=SHR,DSN=GENAPP.DDHOIN07.DATA
//DDHOOT07 DD DISP=SHR,DSN=GENAPP.DDHOOT07.DATA
//DDHORP07 DD DISP=SHR,DSN=GENAPP.DDHORP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN01XA6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN08 DD DISP=SHR,DSN=GENAPP.DDRNIN08.DATA
//DDRNOT08 DD DISP=SHR,DSN=GENAPP.DDRNOT08.DATA
//DDRNRP08 DD DISP=SHR,DSN=GENAPP.DDRNRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01XA7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN09 DD DISP=SHR,DSN=GENAPP.DDTRIN09.DATA
//DDTROT09 DD DISP=SHR,DSN=GENAPP.DDTROT09.DATA
//DDTRRP09 DD DISP=SHR,DSN=GENAPP.DDTRRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
