//VJOB2774 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAU021JN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN43 DD DISP=SHR,DSN=GENAPP.DDAUIN43.DATA
//DDAUOT43 DD DISP=SHR,DSN=GENAPP.DDAUOT43.DATA
//DDAURP43 DD DISP=SHR,DSN=GENAPP.DDAURP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA021JO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN44 DD DISP=SHR,DSN=GENAPP.DDMAIN44.DATA
//DDMAOT44 DD DISP=SHR,DSN=GENAPP.DDMAOT44.DATA
//DDMARP44 DD DISP=SHR,DSN=GENAPP.DDMARP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR021JP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN45 DD DISP=SHR,DSN=GENAPP.DDBRIN45.DATA
//DDBROT45 DD DISP=SHR,DSN=GENAPP.DDBROT45.DATA
//DDBRRP45 DD DISP=SHR,DSN=GENAPP.DDBRRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
