//VJOB3982 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN024CB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN67 DD DISP=SHR,DSN=GENAPP.DDANIN67.DATA
//DDANOT67 DD DISP=SHR,DSN=GENAPP.DDANOT67.DATA
//DDANRP67 DD DISP=SHR,DSN=GENAPP.DDANRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCN024CC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN68 DD DISP=SHR,DSN=GENAPP.DDCNIN68.DATA
//DDCNOT68 DD DISP=SHR,DSN=GENAPP.DDCNOT68.DATA
//DDCNRP68 DD DISP=SHR,DSN=GENAPP.DDCNRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT024CD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN69 DD DISP=SHR,DSN=GENAPP.DDPTIN69.DATA
//DDPTOT69 DD DISP=SHR,DSN=GENAPP.DDPTOT69.DATA
//DDPTRP69 DD DISP=SHR,DSN=GENAPP.DDPTRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
