//VJOB0080 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSB01VB5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN61 DD DISP=SHR,DSN=GENAPP.DDSBIN61.DATA
//DDSBOT61 DD DISP=SHR,DSN=GENAPP.DDSBOT61.DATA
//DDSBRP61 DD DISP=SHR,DSN=GENAPP.DDSBRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR01VB6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN62 DD DISP=SHR,DSN=GENAPP.DDBRIN62.DATA
//DDBROT62 DD DISP=SHR,DSN=GENAPP.DDBROT62.DATA
//DDBRRP62 DD DISP=SHR,DSN=GENAPP.DDBRRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG01VB7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN63 DD DISP=SHR,DSN=GENAPP.DDRGIN63.DATA
//DDRGOT63 DD DISP=SHR,DSN=GENAPP.DDRGOT63.DATA
//DDRGRP63 DD DISP=SHR,DSN=GENAPP.DDRGRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
