//VJOB4333 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG0255K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN40 DD DISP=SHR,DSN=GENAPP.DDAGIN40.DATA
//DDAGOT40 DD DISP=SHR,DSN=GENAPP.DDAGOT40.DATA
//DDAGRP40 DD DISP=SHR,DSN=GENAPP.DDAGRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
