//VJOB3745 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL023SK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN76 DD DISP=SHR,DSN=GENAPP.DDCLIN76.DATA
//DDCLOT76 DD DISP=SHR,DSN=GENAPP.DDCLOT76.DATA
//DDCLRP76 DD DISP=SHR,DSN=GENAPP.DDCLRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE023SL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN77 DD DISP=SHR,DSN=GENAPP.DDPEIN77.DATA
//DDPEOT77 DD DISP=SHR,DSN=GENAPP.DDPEOT77.DATA
//DDPERP77 DD DISP=SHR,DSN=GENAPP.DDPERP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG023SM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN78 DD DISP=SHR,DSN=GENAPP.DDRGIN78.DATA
//DDRGOT78 DD DISP=SHR,DSN=GENAPP.DDRGOT78.DATA
//DDRGRP78 DD DISP=SHR,DSN=GENAPP.DDRGRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
