//VJOB1137 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN01XR8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN82 DD DISP=SHR,DSN=GENAPP.DDPNIN82.DATA
//DDPNOT82 DD DISP=SHR,DSN=GENAPP.DDPNOT82.DATA
//DDPNRP82 DD DISP=SHR,DSN=GENAPP.DDPNRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO01XR9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN83 DD DISP=SHR,DSN=GENAPP.DDCOIN83.DATA
//DDCOOT83 DD DISP=SHR,DSN=GENAPP.DDCOOT83.DATA
//DDCORP83 DD DISP=SHR,DSN=GENAPP.DDCORP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN01XRA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN84 DD DISP=SHR,DSN=GENAPP.DDPNIN84.DATA
//DDPNOT84 DD DISP=SHR,DSN=GENAPP.DDPNOT84.DATA
//DDPNRP84 DD DISP=SHR,DSN=GENAPP.DDPNRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
