//VJOB0106 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDO01VDB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN49 DD DISP=SHR,DSN=GENAPP.DDDOIN49.DATA
//DDDOOT49 DD DISP=SHR,DSN=GENAPP.DDDOOT49.DATA
//DDDORP49 DD DISP=SHR,DSN=GENAPP.DDDORP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT01VDC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN50 DD DISP=SHR,DSN=GENAPP.DDNTIN50.DATA
//DDNTOT50 DD DISP=SHR,DSN=GENAPP.DDNTOT50.DATA
//DDNTRP50 DD DISP=SHR,DSN=GENAPP.DDNTRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01VDD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN51 DD DISP=SHR,DSN=GENAPP.DDMTIN51.DATA
//DDMTOT51 DD DISP=SHR,DSN=GENAPP.DDMTOT51.DATA
//DDMTRP51 DD DISP=SHR,DSN=GENAPP.DDMTRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
