//VJOB0789 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01WY8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN28 DD DISP=SHR,DSN=GENAPP.DDCUIN28.DATA
//DDCUOT28 DD DISP=SHR,DSN=GENAPP.DDCUOT28.DATA
//DDCURP28 DD DISP=SHR,DSN=GENAPP.DDCURP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01WY9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN29 DD DISP=SHR,DSN=GENAPP.DDMTIN29.DATA
//DDMTOT29 DD DISP=SHR,DSN=GENAPP.DDMTOT29.DATA
//DDMTRP29 DD DISP=SHR,DSN=GENAPP.DDMTRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA01WYA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN30 DD DISP=SHR,DSN=GENAPP.DDPAIN30.DATA
//DDPAOT30 DD DISP=SHR,DSN=GENAPP.DDPAOT30.DATA
//DDPARP30 DD DISP=SHR,DSN=GENAPP.DDPARP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
