//VJOB3104 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRT022B5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN43 DD DISP=SHR,DSN=GENAPP.DDRTIN43.DATA
//DDRTOT43 DD DISP=SHR,DSN=GENAPP.DDRTOT43.DATA
//DDRTRP43 DD DISP=SHR,DSN=GENAPP.DDRTRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT022B6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN44 DD DISP=SHR,DSN=GENAPP.DDMTIN44.DATA
//DDMTOT44 DD DISP=SHR,DSN=GENAPP.DDMTOT44.DATA
//DDMTRP44 DD DISP=SHR,DSN=GENAPP.DDMTRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN022B7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN45 DD DISP=SHR,DSN=GENAPP.DDENIN45.DATA
//DDENOT45 DD DISP=SHR,DSN=GENAPP.DDENOT45.DATA
//DDENRP45 DD DISP=SHR,DSN=GENAPP.DDENRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
