//VJOB1935 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZQU01ZLQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN46 DD DISP=SHR,DSN=GENAPP.DDQUIN46.DATA
//DDQUOT46 DD DISP=SHR,DSN=GENAPP.DDQUOT46.DATA
//DDQURP46 DD DISP=SHR,DSN=GENAPP.DDQURP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR01ZLR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN47 DD DISP=SHR,DSN=GENAPP.DDBRIN47.DATA
//DDBROT47 DD DISP=SHR,DSN=GENAPP.DDBROT47.DATA
//DDBRRP47 DD DISP=SHR,DSN=GENAPP.DDBRRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCP01ZLS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN48 DD DISP=SHR,DSN=GENAPP.DDCPIN48.DATA
//DDCPOT48 DD DISP=SHR,DSN=GENAPP.DDCPOT48.DATA
//DDCPRP48 DD DISP=SHR,DSN=GENAPP.DDCPRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
