//VJOB3904 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL0245T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN13 DD DISP=SHR,DSN=GENAPP.DDCLIN13.DATA
//DDCLOT13 DD DISP=SHR,DSN=GENAPP.DDCLOT13.DATA
//DDCLRP13 DD DISP=SHR,DSN=GENAPP.DDCLRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDO0245U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN14 DD DISP=SHR,DSN=GENAPP.DDDOIN14.DATA
//DDDOOT14 DD DISP=SHR,DSN=GENAPP.DDDOOT14.DATA
//DDDORP14 DD DISP=SHR,DSN=GENAPP.DDDORP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSL0245V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN15 DD DISP=SHR,DSN=GENAPP.DDSLIN15.DATA
//DDSLOT15 DD DISP=SHR,DSN=GENAPP.DDSLOT15.DATA
//DDSLRP15 DD DISP=SHR,DSN=GENAPP.DDSLRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
