//VJOB0280 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPR01VRT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN31 DD DISP=SHR,DSN=GENAPP.DDPRIN31.DATA
//DDPROT31 DD DISP=SHR,DSN=GENAPP.DDPROT31.DATA
//DDPRRP31 DD DISP=SHR,DSN=GENAPP.DDPRRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZQU01VRU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN32 DD DISP=SHR,DSN=GENAPP.DDQUIN32.DATA
//DDQUOT32 DD DISP=SHR,DSN=GENAPP.DDQUOT32.DATA
//DDQURP32 DD DISP=SHR,DSN=GENAPP.DDQURP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01VRV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN33 DD DISP=SHR,DSN=GENAPP.DDPEIN33.DATA
//DDPEOT33 DD DISP=SHR,DSN=GENAPP.DDPEOT33.DATA
//DDPERP33 DD DISP=SHR,DSN=GENAPP.DDPERP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
