//VJOB0956 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01XC5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN79 DD DISP=SHR,DSN=GENAPP.DDCOIN79.DATA
//DDCOOT79 DD DISP=SHR,DSN=GENAPP.DDCOOT79.DATA
//DDCORP79 DD DISP=SHR,DSN=GENAPP.DDCORP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT01XC6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN80 DD DISP=SHR,DSN=GENAPP.DDNTIN80.DATA
//DDNTOT80 DD DISP=SHR,DSN=GENAPP.DDNTOT80.DATA
//DDNTRP80 DD DISP=SHR,DSN=GENAPP.DDNTRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01XC7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN81 DD DISP=SHR,DSN=GENAPP.DDCLIN81.DATA
//DDCLOT81 DD DISP=SHR,DSN=GENAPP.DDCLOT81.DATA
//DDCLRP81 DD DISP=SHR,DSN=GENAPP.DDCLRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
