//VJOB2940 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT021XH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN01 DD DISP=SHR,DSN=GENAPP.DDMTIN01.DATA
//DDMTOT01 DD DISP=SHR,DSN=GENAPP.DDMTOT01.DATA
//DDMTRP01 DD DISP=SHR,DSN=GENAPP.DDMTRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAC021XI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN02 DD DISP=SHR,DSN=GENAPP.DDACIN02.DATA
//DDACOT02 DD DISP=SHR,DSN=GENAPP.DDACOT02.DATA
//DDACRP02 DD DISP=SHR,DSN=GENAPP.DDACRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO021XJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN03 DD DISP=SHR,DSN=GENAPP.DDCOIN03.DATA
//DDCOOT03 DD DISP=SHR,DSN=GENAPP.DDCOOT03.DATA
//DDCORP03 DD DISP=SHR,DSN=GENAPP.DDCORP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
