//VJOB1941 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01ZM8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN64 DD DISP=SHR,DSN=GENAPP.DDRGIN64.DATA
//DDRGOT64 DD DISP=SHR,DSN=GENAPP.DDRGOT64.DATA
//DDRGRP64 DD DISP=SHR,DSN=GENAPP.DDRGRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA01ZM9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN65 DD DISP=SHR,DSN=GENAPP.DDBAIN65.DATA
//DDBAOT65 DD DISP=SHR,DSN=GENAPP.DDBAOT65.DATA
//DDBARP65 DD DISP=SHR,DSN=GENAPP.DDBARP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA01ZMA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN66 DD DISP=SHR,DSN=GENAPP.DDPAIN66.DATA
//DDPAOT66 DD DISP=SHR,DSN=GENAPP.DDPAOT66.DATA
//DDPARP66 DD DISP=SHR,DSN=GENAPP.DDPARP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
