//VJOB2574 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG0212Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN73 DD DISP=SHR,DSN=GENAPP.DDRGIN73.DATA
//DDRGOT73 DD DISP=SHR,DSN=GENAPP.DDRGOT73.DATA
//DDRGRP73 DD DISP=SHR,DSN=GENAPP.DDRGRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN02130
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN74 DD DISP=SHR,DSN=GENAPP.DDENIN74.DATA
//DDENOT74 DD DISP=SHR,DSN=GENAPP.DDENOT74.DATA
//DDENRP74 DD DISP=SHR,DSN=GENAPP.DDENRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT02131
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN75 DD DISP=SHR,DSN=GENAPP.DDMTIN75.DATA
//DDMTOT75 DD DISP=SHR,DSN=GENAPP.DDMTOT75.DATA
//DDMTRP75 DD DISP=SHR,DSN=GENAPP.DDMTRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
