//VJOB4275 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV0250Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN46 DD DISP=SHR,DSN=GENAPP.DDAVIN46.DATA
//DDAVOT46 DD DISP=SHR,DSN=GENAPP.DDAVOT46.DATA
//DDAVRP46 DD DISP=SHR,DSN=GENAPP.DDAVRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO0250R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN47 DD DISP=SHR,DSN=GENAPP.DDHOIN47.DATA
//DDHOOT47 DD DISP=SHR,DSN=GENAPP.DDHOOT47.DATA
//DDHORP47 DD DISP=SHR,DSN=GENAPP.DDHORP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR0250S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN48 DD DISP=SHR,DSN=GENAPP.DDTRIN48.DATA
//DDTROT48 DD DISP=SHR,DSN=GENAPP.DDTROT48.DATA
//DDTRRP48 DD DISP=SHR,DSN=GENAPP.DDTRRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
