//VJOB2941 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE021XK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN04 DD DISP=SHR,DSN=GENAPP.DDPEIN04.DATA
//DDPEOT04 DD DISP=SHR,DSN=GENAPP.DDPEOT04.DATA
//DDPERP04 DD DISP=SHR,DSN=GENAPP.DDPERP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL021XL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN05 DD DISP=SHR,DSN=GENAPP.DDCLIN05.DATA
//DDCLOT05 DD DISP=SHR,DSN=GENAPP.DDCLOT05.DATA
//DDCLRP05 DD DISP=SHR,DSN=GENAPP.DDCLRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC021XM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN06 DD DISP=SHR,DSN=GENAPP.DDACIN06.DATA
//DDACOT06 DD DISP=SHR,DSN=GENAPP.DDACOT06.DATA
//DDACRP06 DD DISP=SHR,DSN=GENAPP.DDACRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
