//VJOB2040 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA01ZUH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN01 DD DISP=SHR,DSN=GENAPP.DDMAIN01.DATA
//DDMAOT01 DD DISP=SHR,DSN=GENAPP.DDMAOT01.DATA
//DDMARP01 DD DISP=SHR,DSN=GENAPP.DDMARP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01ZUI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN02 DD DISP=SHR,DSN=GENAPP.DDHOIN02.DATA
//DDHOOT02 DD DISP=SHR,DSN=GENAPP.DDHOOT02.DATA
//DDHORP02 DD DISP=SHR,DSN=GENAPP.DDHORP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT01ZUJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN03 DD DISP=SHR,DSN=GENAPP.DDPTIN03.DATA
//DDPTOT03 DD DISP=SHR,DSN=GENAPP.DDPTOT03.DATA
//DDPTRP03 DD DISP=SHR,DSN=GENAPP.DDPTRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
