//VJOB0801 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01WZ8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN64 DD DISP=SHR,DSN=GENAPP.DDMTIN64.DATA
//DDMTOT64 DD DISP=SHR,DSN=GENAPP.DDMTOT64.DATA
//DDMTRP64 DD DISP=SHR,DSN=GENAPP.DDMTRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN01WZ9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN65 DD DISP=SHR,DSN=GENAPP.DDANIN65.DATA
//DDANOT65 DD DISP=SHR,DSN=GENAPP.DDANOT65.DATA
//DDANRP65 DD DISP=SHR,DSN=GENAPP.DDANRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01WZA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN66 DD DISP=SHR,DSN=GENAPP.DDBIIN66.DATA
//DDBIOT66 DD DISP=SHR,DSN=GENAPP.DDBIOT66.DATA
//DDBIRP66 DD DISP=SHR,DSN=GENAPP.DDBIRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
