//VJOB1516 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC01YMT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN49 DD DISP=SHR,DSN=GENAPP.DDACIN49.DATA
//DDACOT49 DD DISP=SHR,DSN=GENAPP.DDACOT49.DATA
//DDACRP49 DD DISP=SHR,DSN=GENAPP.DDACRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01YMU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN50 DD DISP=SHR,DSN=GENAPP.DDMTIN50.DATA
//DDMTOT50 DD DISP=SHR,DSN=GENAPP.DDMTOT50.DATA
//DDMTRP50 DD DISP=SHR,DSN=GENAPP.DDMTRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN01YMV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN51 DD DISP=SHR,DSN=GENAPP.DDPNIN51.DATA
//DDPNOT51 DD DISP=SHR,DSN=GENAPP.DDPNOT51.DATA
//DDPNRP51 DD DISP=SHR,DSN=GENAPP.DDPNRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
