//VJOB1387 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01YC2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN22 DD DISP=SHR,DSN=GENAPP.DDAVIN22.DATA
//DDAVOT22 DD DISP=SHR,DSN=GENAPP.DDAVOT22.DATA
//DDAVRP22 DD DISP=SHR,DSN=GENAPP.DDAVRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE01YC3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN23 DD DISP=SHR,DSN=GENAPP.DDREIN23.DATA
//DDREOT23 DD DISP=SHR,DSN=GENAPP.DDREOT23.DATA
//DDRERP23 DD DISP=SHR,DSN=GENAPP.DDRERP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCR01YC4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN24 DD DISP=SHR,DSN=GENAPP.DDCRIN24.DATA
//DDCROT24 DD DISP=SHR,DSN=GENAPP.DDCROT24.DATA
//DDCRRP24 DD DISP=SHR,DSN=GENAPP.DDCRRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
