//VJOB2418 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP020PZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN55 DD DISP=SHR,DSN=GENAPP.DDCPIN55.DATA
//DDCPOT55 DD DISP=SHR,DSN=GENAPP.DDCPOT55.DATA
//DDCPRP55 DD DISP=SHR,DSN=GENAPP.DDCPRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR020Q0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN56 DD DISP=SHR,DSN=GENAPP.DDTRIN56.DATA
//DDTROT56 DD DISP=SHR,DSN=GENAPP.DDTROT56.DATA
//DDTRRP56 DD DISP=SHR,DSN=GENAPP.DDTRRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT020Q1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN57 DD DISP=SHR,DSN=GENAPP.DDMTIN57.DATA
//DDMTOT57 DD DISP=SHR,DSN=GENAPP.DDMTOT57.DATA
//DDMTRP57 DD DISP=SHR,DSN=GENAPP.DDMTRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
