//VJOB4276 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN0250T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN49 DD DISP=SHR,DSN=GENAPP.DDPNIN49.DATA
//DDPNOT49 DD DISP=SHR,DSN=GENAPP.DDPNOT49.DATA
//DDPNRP49 DD DISP=SHR,DSN=GENAPP.DDPNRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE0250U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN50 DD DISP=SHR,DSN=GENAPP.DDSEIN50.DATA
//DDSEOT50 DD DISP=SHR,DSN=GENAPP.DDSEOT50.DATA
//DDSERP50 DD DISP=SHR,DSN=GENAPP.DDSERP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI0250V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN51 DD DISP=SHR,DSN=GENAPP.DDBIIN51.DATA
//DDBIOT51 DD DISP=SHR,DSN=GENAPP.DDBIOT51.DATA
//DDBIRP51 DD DISP=SHR,DSN=GENAPP.DDBIRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
