//VJOB3154 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB022FB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN13 DD DISP=SHR,DSN=GENAPP.DDMBIN13.DATA
//DDMBOT13 DD DISP=SHR,DSN=GENAPP.DDMBOT13.DATA
//DDMBRP13 DD DISP=SHR,DSN=GENAPP.DDMBRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA022FC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN14 DD DISP=SHR,DSN=GENAPP.DDMAIN14.DATA
//DDMAOT14 DD DISP=SHR,DSN=GENAPP.DDMAOT14.DATA
//DDMARP14 DD DISP=SHR,DSN=GENAPP.DDMARP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZGW022FD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN15 DD DISP=SHR,DSN=GENAPP.DDGWIN15.DATA
//DDGWOT15 DD DISP=SHR,DSN=GENAPP.DDGWOT15.DATA
//DDGWRP15 DD DISP=SHR,DSN=GENAPP.DDGWRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
