//VJOB4265 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF024ZW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN16 DD DISP=SHR,DSN=GENAPP.DDWFIN16.DATA
//DDWFOT16 DD DISP=SHR,DSN=GENAPP.DDWFOT16.DATA
//DDWFRP16 DD DISP=SHR,DSN=GENAPP.DDWFRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE024ZX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN17 DD DISP=SHR,DSN=GENAPP.DDREIN17.DATA
//DDREOT17 DD DISP=SHR,DSN=GENAPP.DDREOT17.DATA
//DDRERP17 DD DISP=SHR,DSN=GENAPP.DDRERP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV024ZY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN18 DD DISP=SHR,DSN=GENAPP.DDAVIN18.DATA
//DDAVOT18 DD DISP=SHR,DSN=GENAPP.DDAVOT18.DATA
//DDAVRP18 DD DISP=SHR,DSN=GENAPP.DDAVRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
