//VJOB2594 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE0214N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN43 DD DISP=SHR,DSN=GENAPP.DDPEIN43.DATA
//DDPEOT43 DD DISP=SHR,DSN=GENAPP.DDPEOT43.DATA
//DDPERP43 DD DISP=SHR,DSN=GENAPP.DDPERP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0214O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN44 DD DISP=SHR,DSN=GENAPP.DDMTIN44.DATA
//DDMTOT44 DD DISP=SHR,DSN=GENAPP.DDMTOT44.DATA
//DDMTRP44 DD DISP=SHR,DSN=GENAPP.DDMTRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU0214P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN45 DD DISP=SHR,DSN=GENAPP.DDCUIN45.DATA
//DDCUOT45 DD DISP=SHR,DSN=GENAPP.DDCUOT45.DATA
//DDCURP45 DD DISP=SHR,DSN=GENAPP.DDCURP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
