//VJOB0086 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT01VBN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN79 DD DISP=SHR,DSN=GENAPP.DDPTIN79.DATA
//DDPTOT79 DD DISP=SHR,DSN=GENAPP.DDPTOT79.DATA
//DDPTRP79 DD DISP=SHR,DSN=GENAPP.DDPTRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01VBO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN80 DD DISP=SHR,DSN=GENAPP.DDCLIN80.DATA
//DDCLOT80 DD DISP=SHR,DSN=GENAPP.DDCLOT80.DATA
//DDCLRP80 DD DISP=SHR,DSN=GENAPP.DDCLRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZQU01VBP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN81 DD DISP=SHR,DSN=GENAPP.DDQUIN81.DATA
//DDQUOT81 DD DISP=SHR,DSN=GENAPP.DDQUOT81.DATA
//DDQURP81 DD DISP=SHR,DSN=GENAPP.DDQURP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
