//VJOB2766 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSL021IZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN19 DD DISP=SHR,DSN=GENAPP.DDSLIN19.DATA
//DDSLOT19 DD DISP=SHR,DSN=GENAPP.DDSLOT19.DATA
//DDSLRP19 DD DISP=SHR,DSN=GENAPP.DDSLRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR021J0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN20 DD DISP=SHR,DSN=GENAPP.DDCRIN20.DATA
//DDCROT20 DD DISP=SHR,DSN=GENAPP.DDCROT20.DATA
//DDCRRP20 DD DISP=SHR,DSN=GENAPP.DDCRRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT021J1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN21 DD DISP=SHR,DSN=GENAPP.DDMTIN21.DATA
//DDMTOT21 DD DISP=SHR,DSN=GENAPP.DDMTOT21.DATA
//DDMTRP21 DD DISP=SHR,DSN=GENAPP.DDMTRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
