//VJOB4178 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPR024SN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN25 DD DISP=SHR,DSN=GENAPP.DDPRIN25.DATA
//DDPROT25 DD DISP=SHR,DSN=GENAPP.DDPROT25.DATA
//DDPRRP25 DD DISP=SHR,DSN=GENAPP.DDPRRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRT024SO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN26 DD DISP=SHR,DSN=GENAPP.DDRTIN26.DATA
//DDRTOT26 DD DISP=SHR,DSN=GENAPP.DDRTOT26.DATA
//DDRTRP26 DD DISP=SHR,DSN=GENAPP.DDRTRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE024SP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN27 DD DISP=SHR,DSN=GENAPP.DDPEIN27.DATA
//DDPEOT27 DD DISP=SHR,DSN=GENAPP.DDPEOT27.DATA
//DDPERP27 DD DISP=SHR,DSN=GENAPP.DDPERP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
