//VJOB0439 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDO01W52
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN58 DD DISP=SHR,DSN=GENAPP.DDDOIN58.DATA
//DDDOOT58 DD DISP=SHR,DSN=GENAPP.DDDOOT58.DATA
//DDDORP58 DD DISP=SHR,DSN=GENAPP.DDDORP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01W53
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN59 DD DISP=SHR,DSN=GENAPP.DDMTIN59.DATA
//DDMTOT59 DD DISP=SHR,DSN=GENAPP.DDMTOT59.DATA
//DDMTRP59 DD DISP=SHR,DSN=GENAPP.DDMTRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX01W54
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN60 DD DISP=SHR,DSN=GENAPP.DDTXIN60.DATA
//DDTXOT60 DD DISP=SHR,DSN=GENAPP.DDTXOT60.DATA
//DDTXRP60 DD DISP=SHR,DSN=GENAPP.DDTXRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
