//VJOB2822 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE021NN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN07 DD DISP=SHR,DSN=GENAPP.DDPEIN07.DATA
//DDPEOT07 DD DISP=SHR,DSN=GENAPP.DDPEOT07.DATA
//DDPERP07 DD DISP=SHR,DSN=GENAPP.DDPERP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL021NO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN08 DD DISP=SHR,DSN=GENAPP.DDCLIN08.DATA
//DDCLOT08 DD DISP=SHR,DSN=GENAPP.DDCLOT08.DATA
//DDCLRP08 DD DISP=SHR,DSN=GENAPP.DDCLRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA021NP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN09 DD DISP=SHR,DSN=GENAPP.DDPAIN09.DATA
//DDPAOT09 DD DISP=SHR,DSN=GENAPP.DDPAOT09.DATA
//DDPARP09 DD DISP=SHR,DSN=GENAPP.DDPARP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
