//VJOB0488 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX01W95
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN25 DD DISP=SHR,DSN=GENAPP.DDTXIN25.DATA
//DDTXOT25 DD DISP=SHR,DSN=GENAPP.DDTXOT25.DATA
//DDTXRP25 DD DISP=SHR,DSN=GENAPP.DDTXRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW01W96
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN26 DD DISP=SHR,DSN=GENAPP.DDUWIN26.DATA
//DDUWOT26 DD DISP=SHR,DSN=GENAPP.DDUWOT26.DATA
//DDUWRP26 DD DISP=SHR,DSN=GENAPP.DDUWRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG01W97
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN27 DD DISP=SHR,DSN=GENAPP.DDRGIN27.DATA
//DDRGOT27 DD DISP=SHR,DSN=GENAPP.DDRGOT27.DATA
//DDRGRP27 DD DISP=SHR,DSN=GENAPP.DDRGRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
