//VJOB1877 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01ZGW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN52 DD DISP=SHR,DSN=GENAPP.DDHOIN52.DATA
//DDHOOT52 DD DISP=SHR,DSN=GENAPP.DDHOOT52.DATA
//DDHORP52 DD DISP=SHR,DSN=GENAPP.DDHORP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01ZGX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN53 DD DISP=SHR,DSN=GENAPP.DDBIIN53.DATA
//DDBIOT53 DD DISP=SHR,DSN=GENAPP.DDBIOT53.DATA
//DDBIRP53 DD DISP=SHR,DSN=GENAPP.DDBIRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01ZGY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN54 DD DISP=SHR,DSN=GENAPP.DDPRIN54.DATA
//DDPROT54 DD DISP=SHR,DSN=GENAPP.DDPROT54.DATA
//DDPRRP54 DD DISP=SHR,DSN=GENAPP.DDPRRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
