//VJOB3048 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO0226H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN55 DD DISP=SHR,DSN=GENAPP.DDHOIN55.DATA
//DDHOOT55 DD DISP=SHR,DSN=GENAPP.DDHOOT55.DATA
//DDHORP55 DD DISP=SHR,DSN=GENAPP.DDHORP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEX0226I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN56 DD DISP=SHR,DSN=GENAPP.DDEXIN56.DATA
//DDEXOT56 DD DISP=SHR,DSN=GENAPP.DDEXOT56.DATA
//DDEXRP56 DD DISP=SHR,DSN=GENAPP.DDEXRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL0226J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN57 DD DISP=SHR,DSN=GENAPP.DDFLIN57.DATA
//DDFLOT57 DD DISP=SHR,DSN=GENAPP.DDFLOT57.DATA
//DDFLRP57 DD DISP=SHR,DSN=GENAPP.DDFLRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
