//VJOB1440 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZED01YGH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN01 DD DISP=SHR,DSN=GENAPP.DDEDIN01.DATA
//DDEDOT01 DD DISP=SHR,DSN=GENAPP.DDEDOT01.DATA
//DDEDRP01 DD DISP=SHR,DSN=GENAPP.DDEDRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN01YGI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN02 DD DISP=SHR,DSN=GENAPP.DDRNIN02.DATA
//DDRNOT02 DD DISP=SHR,DSN=GENAPP.DDRNOT02.DATA
//DDRNRP02 DD DISP=SHR,DSN=GENAPP.DDRNRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01YGJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN03 DD DISP=SHR,DSN=GENAPP.DDMTIN03.DATA
//DDMTOT03 DD DISP=SHR,DSN=GENAPP.DDMTOT03.DATA
//DDMTRP03 DD DISP=SHR,DSN=GENAPP.DDMTRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
