//VJOB3074 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIF0228N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN43 DD DISP=SHR,DSN=GENAPP.DDIFIN43.DATA
//DDIFOT43 DD DISP=SHR,DSN=GENAPP.DDIFOT43.DATA
//DDIFRP43 DD DISP=SHR,DSN=GENAPP.DDIFRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0228O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN44 DD DISP=SHR,DSN=GENAPP.DDMTIN44.DATA
//DDMTOT44 DD DISP=SHR,DSN=GENAPP.DDMTOT44.DATA
//DDMTRP44 DD DISP=SHR,DSN=GENAPP.DDMTRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO0228P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN45 DD DISP=SHR,DSN=GENAPP.DDHOIN45.DATA
//DDHOOT45 DD DISP=SHR,DSN=GENAPP.DDHOOT45.DATA
//DDHORP45 DD DISP=SHR,DSN=GENAPP.DDHORP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
