//VJOB3370 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG022XB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN31 DD DISP=SHR,DSN=GENAPP.DDRGIN31.DATA
//DDRGOT31 DD DISP=SHR,DSN=GENAPP.DDRGOT31.DATA
//DDRGRP31 DD DISP=SHR,DSN=GENAPP.DDRGRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL022XC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN32 DD DISP=SHR,DSN=GENAPP.DDCLIN32.DATA
//DDCLOT32 DD DISP=SHR,DSN=GENAPP.DDCLOT32.DATA
//DDCLRP32 DD DISP=SHR,DSN=GENAPP.DDCLRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO022XD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN33 DD DISP=SHR,DSN=GENAPP.DDCOIN33.DATA
//DDCOOT33 DD DISP=SHR,DSN=GENAPP.DDCOOT33.DATA
//DDCORP33 DD DISP=SHR,DSN=GENAPP.DDCORP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
