//VJOB4289 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN0251W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN88 DD DISP=SHR,DSN=GENAPP.DDPNIN88.DATA
//DDPNOT88 DD DISP=SHR,DSN=GENAPP.DDPNOT88.DATA
//DDPNRP88 DD DISP=SHR,DSN=GENAPP.DDPNRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL0251X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN89 DD DISP=SHR,DSN=GENAPP.DDCLIN89.DATA
//DDCLOT89 DD DISP=SHR,DSN=GENAPP.DDCLOT89.DATA
//DDCLRP89 DD DISP=SHR,DSN=GENAPP.DDCLRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT0251Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN90 DD DISP=SHR,DSN=GENAPP.DDMTIN90.DATA
//DDMTOT90 DD DISP=SHR,DSN=GENAPP.DDMTOT90.DATA
//DDMTRP90 DD DISP=SHR,DSN=GENAPP.DDMTRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
