//VJOB0763 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC01WW2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN40 DD DISP=SHR,DSN=GENAPP.DDRCIN40.DATA
//DDRCOT40 DD DISP=SHR,DSN=GENAPP.DDRCOT40.DATA
//DDRCRP40 DD DISP=SHR,DSN=GENAPP.DDRCRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01WW3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN41 DD DISP=SHR,DSN=GENAPP.DDFLIN41.DATA
//DDFLOT41 DD DISP=SHR,DSN=GENAPP.DDFLOT41.DATA
//DDFLRP41 DD DISP=SHR,DSN=GENAPP.DDFLRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01WW4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN42 DD DISP=SHR,DSN=GENAPP.DDPEIN42.DATA
//DDPEOT42 DD DISP=SHR,DSN=GENAPP.DDPEOT42.DATA
//DDPERP42 DD DISP=SHR,DSN=GENAPP.DDPERP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
