//VJOB0021 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01V68
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN64 DD DISP=SHR,DSN=GENAPP.DDMTIN64.DATA
//DDMTOT64 DD DISP=SHR,DSN=GENAPP.DDMTOT64.DATA
//DDMTRP64 DD DISP=SHR,DSN=GENAPP.DDMTRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01V69
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN65 DD DISP=SHR,DSN=GENAPP.DDTXIN65.DATA
//DDTXOT65 DD DISP=SHR,DSN=GENAPP.DDTXOT65.DATA
//DDTXRP65 DD DISP=SHR,DSN=GENAPP.DDTXRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01V6A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN66 DD DISP=SHR,DSN=GENAPP.DDHOIN66.DATA
//DDHOOT66 DD DISP=SHR,DSN=GENAPP.DDHOOT66.DATA
//DDHORP66 DD DISP=SHR,DSN=GENAPP.DDHORP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
