//VJOB0140 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01VG5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN61 DD DISP=SHR,DSN=GENAPP.DDHOIN61.DATA
//DDHOOT61 DD DISP=SHR,DSN=GENAPP.DDHOOT61.DATA
//DDHORP61 DD DISP=SHR,DSN=GENAPP.DDHORP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01VG6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN62 DD DISP=SHR,DSN=GENAPP.DDPAIN62.DATA
//DDPAOT62 DD DISP=SHR,DSN=GENAPP.DDPAOT62.DATA
//DDPARP62 DD DISP=SHR,DSN=GENAPP.DDPARP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCN01VG7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN63 DD DISP=SHR,DSN=GENAPP.DDCNIN63.DATA
//DDCNOT63 DD DISP=SHR,DSN=GENAPP.DDCNOT63.DATA
//DDCNRP63 DD DISP=SHR,DSN=GENAPP.DDCNRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
