//VJOB1042 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01XJB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN67 DD DISP=SHR,DSN=GENAPP.DDHOIN67.DATA
//DDHOOT67 DD DISP=SHR,DSN=GENAPP.DDHOOT67.DATA
//DDHORP67 DD DISP=SHR,DSN=GENAPP.DDHORP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01XJC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN68 DD DISP=SHR,DSN=GENAPP.DDPAIN68.DATA
//DDPAOT68 DD DISP=SHR,DSN=GENAPP.DDPAOT68.DATA
//DDPARP68 DD DISP=SHR,DSN=GENAPP.DDPARP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01XJD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN69 DD DISP=SHR,DSN=GENAPP.DDCUIN69.DATA
//DDCUOT69 DD DISP=SHR,DSN=GENAPP.DDCUOT69.DATA
//DDCURP69 DD DISP=SHR,DSN=GENAPP.DDCURP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
