//VJOB0915 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX01X8Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN46 DD DISP=SHR,DSN=GENAPP.DDTXIN46.DATA
//DDTXOT46 DD DISP=SHR,DSN=GENAPP.DDTXOT46.DATA
//DDTXRP46 DD DISP=SHR,DSN=GENAPP.DDTXRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCN01X8R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN47 DD DISP=SHR,DSN=GENAPP.DDCNIN47.DATA
//DDCNOT47 DD DISP=SHR,DSN=GENAPP.DDCNOT47.DATA
//DDCNRP47 DD DISP=SHR,DSN=GENAPP.DDCNRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN01X8S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN48 DD DISP=SHR,DSN=GENAPP.DDANIN48.DATA
//DDANOT48 DD DISP=SHR,DSN=GENAPP.DDANOT48.DATA
//DDANRP48 DD DISP=SHR,DSN=GENAPP.DDANRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
