//VJOB0485 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV01W8W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN16 DD DISP=SHR,DSN=GENAPP.DDIVIN16.DATA
//DDIVOT16 DD DISP=SHR,DSN=GENAPP.DDIVOT16.DATA
//DDIVRP16 DD DISP=SHR,DSN=GENAPP.DDIVRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01W8X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN17 DD DISP=SHR,DSN=GENAPP.DDMTIN17.DATA
//DDMTOT17 DD DISP=SHR,DSN=GENAPP.DDMTOT17.DATA
//DDMTRP17 DD DISP=SHR,DSN=GENAPP.DDMTRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZGW01W8Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN18 DD DISP=SHR,DSN=GENAPP.DDGWIN18.DATA
//DDGWOT18 DD DISP=SHR,DSN=GENAPP.DDGWOT18.DATA
//DDGWRP18 DD DISP=SHR,DSN=GENAPP.DDGWRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
