//VJOB0416 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE01W35
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN79 DD DISP=SHR,DSN=GENAPP.DDPEIN79.DATA
//DDPEOT79 DD DISP=SHR,DSN=GENAPP.DDPEOT79.DATA
//DDPERP79 DD DISP=SHR,DSN=GENAPP.DDPERP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN01W36
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN80 DD DISP=SHR,DSN=GENAPP.DDPNIN80.DATA
//DDPNOT80 DD DISP=SHR,DSN=GENAPP.DDPNOT80.DATA
//DDPNRP80 DD DISP=SHR,DSN=GENAPP.DDPNRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR01W37
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN81 DD DISP=SHR,DSN=GENAPP.DDFRIN81.DATA
//DDFROT81 DD DISP=SHR,DSN=GENAPP.DDFROT81.DATA
//DDFRRP81 DD DISP=SHR,DSN=GENAPP.DDFRRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
