//VJOB4318 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLT0254B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN85 DD DISP=SHR,DSN=GENAPP.DDLTIN85.DATA
//DDLTOT85 DD DISP=SHR,DSN=GENAPP.DDLTOT85.DATA
//DDLTRP85 DD DISP=SHR,DSN=GENAPP.DDLTRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA0254C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN86 DD DISP=SHR,DSN=GENAPP.DDMAIN86.DATA
//DDMAOT86 DD DISP=SHR,DSN=GENAPP.DDMAOT86.DATA
//DDMARP86 DD DISP=SHR,DSN=GENAPP.DDMARP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV0254D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN87 DD DISP=SHR,DSN=GENAPP.DDAVIN87.DATA
//DDAVOT87 DD DISP=SHR,DSN=GENAPP.DDAVOT87.DATA
//DDAVRP87 DD DISP=SHR,DSN=GENAPP.DDAVRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
