//VJOB1475 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01YJE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN16 DD DISP=SHR,DSN=GENAPP.DDCOIN16.DATA
//DDCOOT16 DD DISP=SHR,DSN=GENAPP.DDCOOT16.DATA
//DDCORP16 DD DISP=SHR,DSN=GENAPP.DDCORP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAC01YJF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN17 DD DISP=SHR,DSN=GENAPP.DDACIN17.DATA
//DDACOT17 DD DISP=SHR,DSN=GENAPP.DDACOT17.DATA
//DDACRP17 DD DISP=SHR,DSN=GENAPP.DDACRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT01YJG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN18 DD DISP=SHR,DSN=GENAPP.DDPTIN18.DATA
//DDPTOT18 DD DISP=SHR,DSN=GENAPP.DDPTOT18.DATA
//DDPTRP18 DD DISP=SHR,DSN=GENAPP.DDPTRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
