//VJOB0025 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01V6K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN76 DD DISP=SHR,DSN=GENAPP.DDHOIN76.DATA
//DDHOOT76 DD DISP=SHR,DSN=GENAPP.DDHOOT76.DATA
//DDHORP76 DD DISP=SHR,DSN=GENAPP.DDHORP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01V6L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN77 DD DISP=SHR,DSN=GENAPP.DDAGIN77.DATA
//DDAGOT77 DD DISP=SHR,DSN=GENAPP.DDAGOT77.DATA
//DDAGRP77 DD DISP=SHR,DSN=GENAPP.DDAGRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01V6M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN78 DD DISP=SHR,DSN=GENAPP.DDPEIN78.DATA
//DDPEOT78 DD DISP=SHR,DSN=GENAPP.DDPEOT78.DATA
//DDPERP78 DD DISP=SHR,DSN=GENAPP.DDPERP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
