//VJOB2360 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE020L5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN61 DD DISP=SHR,DSN=GENAPP.DDREIN61.DATA
//DDREOT61 DD DISP=SHR,DSN=GENAPP.DDREOT61.DATA
//DDRERP61 DD DISP=SHR,DSN=GENAPP.DDRERP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR020L6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN62 DD DISP=SHR,DSN=GENAPP.DDCRIN62.DATA
//DDCROT62 DD DISP=SHR,DSN=GENAPP.DDCROT62.DATA
//DDCRRP62 DD DISP=SHR,DSN=GENAPP.DDCRRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT020L7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN63 DD DISP=SHR,DSN=GENAPP.DDMTIN63.DATA
//DDMTOT63 DD DISP=SHR,DSN=GENAPP.DDMTOT63.DATA
//DDMTRP63 DD DISP=SHR,DSN=GENAPP.DDMTRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
