//VJOB3460 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA0234T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN31 DD DISP=SHR,DSN=GENAPP.DDBAIN31.DATA
//DDBAOT31 DD DISP=SHR,DSN=GENAPP.DDBAOT31.DATA
//DDBARP31 DD DISP=SHR,DSN=GENAPP.DDBARP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR0234U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN32 DD DISP=SHR,DSN=GENAPP.DDCRIN32.DATA
//DDCROT32 DD DISP=SHR,DSN=GENAPP.DDCROT32.DATA
//DDCRRP32 DD DISP=SHR,DSN=GENAPP.DDCRRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA0234V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN33 DD DISP=SHR,DSN=GENAPP.DDPAIN33.DATA
//DDPAOT33 DD DISP=SHR,DSN=GENAPP.DDPAOT33.DATA
//DDPARP33 DD DISP=SHR,DSN=GENAPP.DDPARP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
