//VJOB3665 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPR023LW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN16 DD DISP=SHR,DSN=GENAPP.DDPRIN16.DATA
//DDPROT16 DD DISP=SHR,DSN=GENAPP.DDPROT16.DATA
//DDPRRP16 DD DISP=SHR,DSN=GENAPP.DDPRRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI023LX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN17 DD DISP=SHR,DSN=GENAPP.DDBIIN17.DATA
//DDBIOT17 DD DISP=SHR,DSN=GENAPP.DDBIOT17.DATA
//DDBIRP17 DD DISP=SHR,DSN=GENAPP.DDBIRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDI023LY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN18 DD DISP=SHR,DSN=GENAPP.DDDIIN18.DATA
//DDDIOT18 DD DISP=SHR,DSN=GENAPP.DDDIOT18.DATA
//DDDIRP18 DD DISP=SHR,DSN=GENAPP.DDDIRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
