//VJOB2051 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA01ZVE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN34 DD DISP=SHR,DSN=GENAPP.DDPAIN34.DATA
//DDPAOT34 DD DISP=SHR,DSN=GENAPP.DDPAOT34.DATA
//DDPARP34 DD DISP=SHR,DSN=GENAPP.DDPARP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPL01ZVF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN35 DD DISP=SHR,DSN=GENAPP.DDPLIN35.DATA
//DDPLOT35 DD DISP=SHR,DSN=GENAPP.DDPLOT35.DATA
//DDPLRP35 DD DISP=SHR,DSN=GENAPP.DDPLRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG01ZVG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN36 DD DISP=SHR,DSN=GENAPP.DDRGIN36.DATA
//DDRGOT36 DD DISP=SHR,DSN=GENAPP.DDRGOT36.DATA
//DDRGRP36 DD DISP=SHR,DSN=GENAPP.DDRGRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
