//VJOB1936 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPL01ZLT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN49 DD DISP=SHR,DSN=GENAPP.DDPLIN49.DATA
//DDPLOT49 DD DISP=SHR,DSN=GENAPP.DDPLOT49.DATA
//DDPLRP49 DD DISP=SHR,DSN=GENAPP.DDPLRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR01ZLU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN50 DD DISP=SHR,DSN=GENAPP.DDBRIN50.DATA
//DDBROT50 DD DISP=SHR,DSN=GENAPP.DDBROT50.DATA
//DDBRRP50 DD DISP=SHR,DSN=GENAPP.DDBRRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZWF01ZLV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN51 DD DISP=SHR,DSN=GENAPP.DDWFIN51.DATA
//DDWFOT51 DD DISP=SHR,DSN=GENAPP.DDWFOT51.DATA
//DDWFRP51 DD DISP=SHR,DSN=GENAPP.DDWFRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
