//VJOB3271 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU022P2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN04 DD DISP=SHR,DSN=GENAPP.DDCUIN04.DATA
//DDCUOT04 DD DISP=SHR,DSN=GENAPP.DDCUOT04.DATA
//DDCURP04 DD DISP=SHR,DSN=GENAPP.DDCURP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU022P3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN05 DD DISP=SHR,DSN=GENAPP.DDCUIN05.DATA
//DDCUOT05 DD DISP=SHR,DSN=GENAPP.DDCUOT05.DATA
//DDCURP05 DD DISP=SHR,DSN=GENAPP.DDCURP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRC022P4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN06 DD DISP=SHR,DSN=GENAPP.DDRCIN06.DATA
//DDRCOT06 DD DISP=SHR,DSN=GENAPP.DDRCOT06.DATA
//DDRCRP06 DD DISP=SHR,DSN=GENAPP.DDRCRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
