//VJOB1109 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01XOW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN88 DD DISP=SHR,DSN=GENAPP.DDRGIN88.DATA
//DDRGOT88 DD DISP=SHR,DSN=GENAPP.DDRGOT88.DATA
//DDRGRP88 DD DISP=SHR,DSN=GENAPP.DDRGRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01XOX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN89 DD DISP=SHR,DSN=GENAPP.DDMTIN89.DATA
//DDMTOT89 DD DISP=SHR,DSN=GENAPP.DDMTOT89.DATA
//DDMTRP89 DD DISP=SHR,DSN=GENAPP.DDMTRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSE01XOY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN90 DD DISP=SHR,DSN=GENAPP.DDSEIN90.DATA
//DDSEOT90 DD DISP=SHR,DSN=GENAPP.DDSEOT90.DATA
//DDSERP90 DD DISP=SHR,DSN=GENAPP.DDSERP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
