//VJOB2855 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF021QE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN16 DD DISP=SHR,DSN=GENAPP.DDWFIN16.DATA
//DDWFOT16 DD DISP=SHR,DSN=GENAPP.DDWFOT16.DATA
//DDWFRP16 DD DISP=SHR,DSN=GENAPP.DDWFRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB021QF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN17 DD DISP=SHR,DSN=GENAPP.DDLBIN17.DATA
//DDLBOT17 DD DISP=SHR,DSN=GENAPP.DDLBOT17.DATA
//DDLBRP17 DD DISP=SHR,DSN=GENAPP.DDLBRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA021QG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN18 DD DISP=SHR,DSN=GENAPP.DDMAIN18.DATA
//DDMAOT18 DD DISP=SHR,DSN=GENAPP.DDMAOT18.DATA
//DDMARP18 DD DISP=SHR,DSN=GENAPP.DDMARP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
