//VJOB2349 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU020K8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN28 DD DISP=SHR,DSN=GENAPP.DDCUIN28.DATA
//DDCUOT28 DD DISP=SHR,DSN=GENAPP.DDCUOT28.DATA
//DDCURP28 DD DISP=SHR,DSN=GENAPP.DDCURP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN020K9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN29 DD DISP=SHR,DSN=GENAPP.DDANIN29.DATA
//DDANOT29 DD DISP=SHR,DSN=GENAPP.DDANOT29.DATA
//DDANRP29 DD DISP=SHR,DSN=GENAPP.DDANRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT020KA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN30 DD DISP=SHR,DSN=GENAPP.DDPTIN30.DATA
//DDPTOT30 DD DISP=SHR,DSN=GENAPP.DDPTOT30.DATA
//DDPTRP30 DD DISP=SHR,DSN=GENAPP.DDPTRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
