//VJOB0214 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01VMB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN13 DD DISP=SHR,DSN=GENAPP.DDENIN13.DATA
//DDENOT13 DD DISP=SHR,DSN=GENAPP.DDENOT13.DATA
//DDENRP13 DD DISP=SHR,DSN=GENAPP.DDENRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW01VMC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN14 DD DISP=SHR,DSN=GENAPP.DDUWIN14.DATA
//DDUWOT14 DD DISP=SHR,DSN=GENAPP.DDUWOT14.DATA
//DDUWRP14 DD DISP=SHR,DSN=GENAPP.DDUWRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV01VMD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN15 DD DISP=SHR,DSN=GENAPP.DDIVIN15.DATA
//DDIVOT15 DD DISP=SHR,DSN=GENAPP.DDIVOT15.DATA
//DDIVRP15 DD DISP=SHR,DSN=GENAPP.DDIVRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
