//VJOB1651 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT01YY2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN04 DD DISP=SHR,DSN=GENAPP.DDNTIN04.DATA
//DDNTOT04 DD DISP=SHR,DSN=GENAPP.DDNTOT04.DATA
//DDNTRP04 DD DISP=SHR,DSN=GENAPP.DDNTRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC01YY3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN05 DD DISP=SHR,DSN=GENAPP.DDSCIN05.DATA
//DDSCOT05 DD DISP=SHR,DSN=GENAPP.DDSCOT05.DATA
//DDSCRP05 DD DISP=SHR,DSN=GENAPP.DDSCRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBA01YY4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN06 DD DISP=SHR,DSN=GENAPP.DDBAIN06.DATA
//DDBAOT06 DD DISP=SHR,DSN=GENAPP.DDBAOT06.DATA
//DDBARP06 DD DISP=SHR,DSN=GENAPP.DDBARP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
