//VJOB1366 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB01YAB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN49 DD DISP=SHR,DSN=GENAPP.DDMBIN49.DATA
//DDMBOT49 DD DISP=SHR,DSN=GENAPP.DDMBOT49.DATA
//DDMBRP49 DD DISP=SHR,DSN=GENAPP.DDMBRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRC01YAC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN50 DD DISP=SHR,DSN=GENAPP.DDRCIN50.DATA
//DDRCOT50 DD DISP=SHR,DSN=GENAPP.DDRCOT50.DATA
//DDRCRP50 DD DISP=SHR,DSN=GENAPP.DDRCRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV01YAD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN51 DD DISP=SHR,DSN=GENAPP.DDIVIN51.DATA
//DDIVOT51 DD DISP=SHR,DSN=GENAPP.DDIVOT51.DATA
//DDIVRP51 DD DISP=SHR,DSN=GENAPP.DDIVRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
