//VJOB2885 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS021SW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN16 DD DISP=SHR,DSN=GENAPP.DDRSIN16.DATA
//DDRSOT16 DD DISP=SHR,DSN=GENAPP.DDRSOT16.DATA
//DDRSRP16 DD DISP=SHR,DSN=GENAPP.DDRSRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE021SX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN17 DD DISP=SHR,DSN=GENAPP.DDHEIN17.DATA
//DDHEOT17 DD DISP=SHR,DSN=GENAPP.DDHEOT17.DATA
//DDHERP17 DD DISP=SHR,DSN=GENAPP.DDHERP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR021SY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN18 DD DISP=SHR,DSN=GENAPP.DDFRIN18.DATA
//DDFROT18 DD DISP=SHR,DSN=GENAPP.DDFROT18.DATA
//DDFRRP18 DD DISP=SHR,DSN=GENAPP.DDFRRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
