//VJOB0830 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN01X1N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN61 DD DISP=SHR,DSN=GENAPP.DDPNIN61.DATA
//DDPNOT61 DD DISP=SHR,DSN=GENAPP.DDPNOT61.DATA
//DDPNRP61 DD DISP=SHR,DSN=GENAPP.DDPNRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAU01X1O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN62 DD DISP=SHR,DSN=GENAPP.DDAUIN62.DATA
//DDAUOT62 DD DISP=SHR,DSN=GENAPP.DDAUOT62.DATA
//DDAURP62 DD DISP=SHR,DSN=GENAPP.DDAURP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC01X1P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN63 DD DISP=SHR,DSN=GENAPP.DDSCIN63.DATA
//DDSCOT63 DD DISP=SHR,DSN=GENAPP.DDSCOT63.DATA
//DDSCRP63 DD DISP=SHR,DSN=GENAPP.DDSCRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
