//VJOB3613 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN023HK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN40 DD DISP=SHR,DSN=GENAPP.DDANIN40.DATA
//DDANOT40 DD DISP=SHR,DSN=GENAPP.DDANOT40.DATA
//DDANRP40 DD DISP=SHR,DSN=GENAPP.DDANRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCP023HL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN41 DD DISP=SHR,DSN=GENAPP.DDCPIN41.DATA
//DDCPOT41 DD DISP=SHR,DSN=GENAPP.DDCPOT41.DATA
//DDCPRP41 DD DISP=SHR,DSN=GENAPP.DDCPRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI023HM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN42 DD DISP=SHR,DSN=GENAPP.DDBIIN42.DATA
//DDBIOT42 DD DISP=SHR,DSN=GENAPP.DDBIOT42.DATA
//DDBIRP42 DD DISP=SHR,DSN=GENAPP.DDBIRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
