//VJOB0187 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01VK2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN22 DD DISP=SHR,DSN=GENAPP.DDCUIN22.DATA
//DDCUOT22 DD DISP=SHR,DSN=GENAPP.DDCUOT22.DATA
//DDCURP22 DD DISP=SHR,DSN=GENAPP.DDCURP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSL01VK3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN23 DD DISP=SHR,DSN=GENAPP.DDSLIN23.DATA
//DDSLOT23 DD DISP=SHR,DSN=GENAPP.DDSLOT23.DATA
//DDSLRP23 DD DISP=SHR,DSN=GENAPP.DDSLRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01VK4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN24 DD DISP=SHR,DSN=GENAPP.DDENIN24.DATA
//DDENOT24 DD DISP=SHR,DSN=GENAPP.DDENOT24.DATA
//DDENRP24 DD DISP=SHR,DSN=GENAPP.DDENRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
