//VJOB1135 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01XR2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN76 DD DISP=SHR,DSN=GENAPP.DDCOIN76.DATA
//DDCOOT76 DD DISP=SHR,DSN=GENAPP.DDCOOT76.DATA
//DDCORP76 DD DISP=SHR,DSN=GENAPP.DDCORP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR01XR3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN77 DD DISP=SHR,DSN=GENAPP.DDCRIN77.DATA
//DDCROT77 DD DISP=SHR,DSN=GENAPP.DDCROT77.DATA
//DDCRRP77 DD DISP=SHR,DSN=GENAPP.DDCRRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDI01XR4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN78 DD DISP=SHR,DSN=GENAPP.DDDIIN78.DATA
//DDDIOT78 DD DISP=SHR,DSN=GENAPP.DDDIOT78.DATA
//DDDIRP78 DD DISP=SHR,DSN=GENAPP.DDDIRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
