//VJOB0890 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV01X6N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN61 DD DISP=SHR,DSN=GENAPP.DDIVIN61.DATA
//DDIVOT61 DD DISP=SHR,DSN=GENAPP.DDIVOT61.DATA
//DDIVRP61 DD DISP=SHR,DSN=GENAPP.DDIVRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ01X6O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN62 DD DISP=SHR,DSN=GENAPP.DDAZIN62.DATA
//DDAZOT62 DD DISP=SHR,DSN=GENAPP.DDAZOT62.DATA
//DDAZRP62 DD DISP=SHR,DSN=GENAPP.DDAZRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01X6P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN63 DD DISP=SHR,DSN=GENAPP.DDHOIN63.DATA
//DDHOOT63 DD DISP=SHR,DSN=GENAPP.DDHOOT63.DATA
//DDHORP63 DD DISP=SHR,DSN=GENAPP.DDHORP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
