//VJOB1472 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC01YJ5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN07 DD DISP=SHR,DSN=GENAPP.DDACIN07.DATA
//DDACOT07 DD DISP=SHR,DSN=GENAPP.DDACOT07.DATA
//DDACRP07 DD DISP=SHR,DSN=GENAPP.DDACRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC01YJ6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN08 DD DISP=SHR,DSN=GENAPP.DDSCIN08.DATA
//DDSCOT08 DD DISP=SHR,DSN=GENAPP.DDSCOT08.DATA
//DDSCRP08 DD DISP=SHR,DSN=GENAPP.DDSCRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01YJ7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN09 DD DISP=SHR,DSN=GENAPP.DDMTIN09.DATA
//DDMTOT09 DD DISP=SHR,DSN=GENAPP.DDMTOT09.DATA
//DDMTRP09 DD DISP=SHR,DSN=GENAPP.DDMTRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
