//VJOB4140 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI024PH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN01 DD DISP=SHR,DSN=GENAPP.DDLIIN01.DATA
//DDLIOT01 DD DISP=SHR,DSN=GENAPP.DDLIOT01.DATA
//DDLIRP01 DD DISP=SHR,DSN=GENAPP.DDLIRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL024PI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN02 DD DISP=SHR,DSN=GENAPP.DDCLIN02.DATA
//DDCLOT02 DD DISP=SHR,DSN=GENAPP.DDCLOT02.DATA
//DDCLRP02 DD DISP=SHR,DSN=GENAPP.DDCLRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT024PJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN03 DD DISP=SHR,DSN=GENAPP.DDPTIN03.DATA
//DDPTOT03 DD DISP=SHR,DSN=GENAPP.DDPTOT03.DATA
//DDPTRP03 DD DISP=SHR,DSN=GENAPP.DDPTRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
