//VJOB2175 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA0205Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN46 DD DISP=SHR,DSN=GENAPP.DDBAIN46.DATA
//DDBAOT46 DD DISP=SHR,DSN=GENAPP.DDBAOT46.DATA
//DDBARP46 DD DISP=SHR,DSN=GENAPP.DDBARP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO0205R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN47 DD DISP=SHR,DSN=GENAPP.DDHOIN47.DATA
//DDHOOT47 DD DISP=SHR,DSN=GENAPP.DDHOOT47.DATA
//DDHORP47 DD DISP=SHR,DSN=GENAPP.DDHORP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRC0205S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN48 DD DISP=SHR,DSN=GENAPP.DDRCIN48.DATA
//DDRCOT48 DD DISP=SHR,DSN=GENAPP.DDRCOT48.DATA
//DDRCRP48 DD DISP=SHR,DSN=GENAPP.DDRCRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
