//VJOB0468 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY01W7H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN55 DD DISP=SHR,DSN=GENAPP.DDTYIN55.DATA
//DDTYOT55 DD DISP=SHR,DSN=GENAPP.DDTYOT55.DATA
//DDTYRP55 DD DISP=SHR,DSN=GENAPP.DDTYRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN01W7I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN56 DD DISP=SHR,DSN=GENAPP.DDENIN56.DATA
//DDENOT56 DD DISP=SHR,DSN=GENAPP.DDENOT56.DATA
//DDENRP56 DD DISP=SHR,DSN=GENAPP.DDENRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI01W7J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN57 DD DISP=SHR,DSN=GENAPP.DDLIIN57.DATA
//DDLIOT57 DD DISP=SHR,DSN=GENAPP.DDLIOT57.DATA
//DDLIRP57 DD DISP=SHR,DSN=GENAPP.DDLIRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
