//VJOB3087 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO0229Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN82 DD DISP=SHR,DSN=GENAPP.DDCOIN82.DATA
//DDCOOT82 DD DISP=SHR,DSN=GENAPP.DDCOOT82.DATA
//DDCORP82 DD DISP=SHR,DSN=GENAPP.DDCORP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZQU0229R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN83 DD DISP=SHR,DSN=GENAPP.DDQUIN83.DATA
//DDQUOT83 DD DISP=SHR,DSN=GENAPP.DDQUOT83.DATA
//DDQURP83 DD DISP=SHR,DSN=GENAPP.DDQURP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF0229S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN84 DD DISP=SHR,DSN=GENAPP.DDIFIN84.DATA
//DDIFOT84 DD DISP=SHR,DSN=GENAPP.DDIFOT84.DATA
//DDIFRP84 DD DISP=SHR,DSN=GENAPP.DDIFRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
