//VJOB1662 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSL01YYZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN37 DD DISP=SHR,DSN=GENAPP.DDSLIN37.DATA
//DDSLOT37 DD DISP=SHR,DSN=GENAPP.DDSLOT37.DATA
//DDSLRP37 DD DISP=SHR,DSN=GENAPP.DDSLRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE01YZ0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN38 DD DISP=SHR,DSN=GENAPP.DDHEIN38.DATA
//DDHEOT38 DD DISP=SHR,DSN=GENAPP.DDHEOT38.DATA
//DDHERP38 DD DISP=SHR,DSN=GENAPP.DDHERP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN01YZ1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN39 DD DISP=SHR,DSN=GENAPP.DDANIN39.DATA
//DDANOT39 DD DISP=SHR,DSN=GENAPP.DDANOT39.DATA
//DDANRP39 DD DISP=SHR,DSN=GENAPP.DDANRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
