//VJOB3732 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG023RH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN37 DD DISP=SHR,DSN=GENAPP.DDRGIN37.DATA
//DDRGOT37 DD DISP=SHR,DSN=GENAPP.DDRGOT37.DATA
//DDRGRP37 DD DISP=SHR,DSN=GENAPP.DDRGRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE023RI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN38 DD DISP=SHR,DSN=GENAPP.DDREIN38.DATA
//DDREOT38 DD DISP=SHR,DSN=GENAPP.DDREOT38.DATA
//DDRERP38 DD DISP=SHR,DSN=GENAPP.DDRERP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE023RJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN39 DD DISP=SHR,DSN=GENAPP.DDHEIN39.DATA
//DDHEOT39 DD DISP=SHR,DSN=GENAPP.DDHEOT39.DATA
//DDHERP39 DD DISP=SHR,DSN=GENAPP.DDHERP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
