//VJOB0610 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01WJB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN31 DD DISP=SHR,DSN=GENAPP.DDRGIN31.DATA
//DDRGOT31 DD DISP=SHR,DSN=GENAPP.DDRGOT31.DATA
//DDRGRP31 DD DISP=SHR,DSN=GENAPP.DDRGRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR01WJC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN32 DD DISP=SHR,DSN=GENAPP.DDTRIN32.DATA
//DDTROT32 DD DISP=SHR,DSN=GENAPP.DDTROT32.DATA
//DDTRRP32 DD DISP=SHR,DSN=GENAPP.DDTRRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01WJD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN33 DD DISP=SHR,DSN=GENAPP.DDHOIN33.DATA
//DDHOOT33 DD DISP=SHR,DSN=GENAPP.DDHOOT33.DATA
//DDHORP33 DD DISP=SHR,DSN=GENAPP.DDHORP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
