//VJOB0248 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY01VP5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN25 DD DISP=SHR,DSN=GENAPP.DDTYIN25.DATA
//DDTYOT25 DD DISP=SHR,DSN=GENAPP.DDTYOT25.DATA
//DDTYRP25 DD DISP=SHR,DSN=GENAPP.DDTYRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF01VP6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN26 DD DISP=SHR,DSN=GENAPP.DDIFIN26.DATA
//DDIFOT26 DD DISP=SHR,DSN=GENAPP.DDIFOT26.DATA
//DDIFRP26 DD DISP=SHR,DSN=GENAPP.DDIFRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI01VP7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN27 DD DISP=SHR,DSN=GENAPP.DDLIIN27.DATA
//DDLIOT27 DD DISP=SHR,DSN=GENAPP.DDLIOT27.DATA
//DDLIRP27 DD DISP=SHR,DSN=GENAPP.DDLIRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
