//VJOB4236 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA024XH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN19 DD DISP=SHR,DSN=GENAPP.DDMAIN19.DATA
//DDMAOT19 DD DISP=SHR,DSN=GENAPP.DDMAOT19.DATA
//DDMARP19 DD DISP=SHR,DSN=GENAPP.DDMARP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW024XI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN20 DD DISP=SHR,DSN=GENAPP.DDUWIN20.DATA
//DDUWOT20 DD DISP=SHR,DSN=GENAPP.DDUWOT20.DATA
//DDUWRP20 DD DISP=SHR,DSN=GENAPP.DDUWRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSU024XJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN21 DD DISP=SHR,DSN=GENAPP.DDSUIN21.DATA
//DDSUOT21 DD DISP=SHR,DSN=GENAPP.DDSUOT21.DATA
//DDSURP21 DD DISP=SHR,DSN=GENAPP.DDSURP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
