//VJOB0201 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE01VL8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN64 DD DISP=SHR,DSN=GENAPP.DDSEIN64.DATA
//DDSEOT64 DD DISP=SHR,DSN=GENAPP.DDSEOT64.DATA
//DDSERP64 DD DISP=SHR,DSN=GENAPP.DDSERP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG01VL9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN65 DD DISP=SHR,DSN=GENAPP.DDRGIN65.DATA
//DDRGOT65 DD DISP=SHR,DSN=GENAPP.DDRGOT65.DATA
//DDRGRP65 DD DISP=SHR,DSN=GENAPP.DDRGRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZWF01VLA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN66 DD DISP=SHR,DSN=GENAPP.DDWFIN66.DATA
//DDWFOT66 DD DISP=SHR,DSN=GENAPP.DDWFOT66.DATA
//DDWFRP66 DD DISP=SHR,DSN=GENAPP.DDWFRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
