//VJOB3150 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG022EZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN01 DD DISP=SHR,DSN=GENAPP.DDRGIN01.DATA
//DDRGOT01 DD DISP=SHR,DSN=GENAPP.DDRGOT01.DATA
//DDRGRP01 DD DISP=SHR,DSN=GENAPP.DDRGRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO022F0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN02 DD DISP=SHR,DSN=GENAPP.DDHOIN02.DATA
//DDHOOT02 DD DISP=SHR,DSN=GENAPP.DDHOOT02.DATA
//DDHORP02 DD DISP=SHR,DSN=GENAPP.DDHORP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU022F1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN03 DD DISP=SHR,DSN=GENAPP.DDCUIN03.DATA
//DDCUOT03 DD DISP=SHR,DSN=GENAPP.DDCUOT03.DATA
//DDCURP03 DD DISP=SHR,DSN=GENAPP.DDCURP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
