//VJOB1536 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01YOH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN19 DD DISP=SHR,DSN=GENAPP.DDCLIN19.DATA
//DDCLOT19 DD DISP=SHR,DSN=GENAPP.DDCLOT19.DATA
//DDCLRP19 DD DISP=SHR,DSN=GENAPP.DDCLRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01YOI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN20 DD DISP=SHR,DSN=GENAPP.DDTXIN20.DATA
//DDTXOT20 DD DISP=SHR,DSN=GENAPP.DDTXOT20.DATA
//DDTXRP20 DD DISP=SHR,DSN=GENAPP.DDTXRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT01YOJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN21 DD DISP=SHR,DSN=GENAPP.DDPTIN21.DATA
//DDPTOT21 DD DISP=SHR,DSN=GENAPP.DDPTOT21.DATA
//DDPTRP21 DD DISP=SHR,DSN=GENAPP.DDPTRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
