//VJOB2140 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN0202T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN31 DD DISP=SHR,DSN=GENAPP.DDENIN31.DATA
//DDENOT31 DD DISP=SHR,DSN=GENAPP.DDENOT31.DATA
//DDENRP31 DD DISP=SHR,DSN=GENAPP.DDENRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0202U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN32 DD DISP=SHR,DSN=GENAPP.DDMTIN32.DATA
//DDMTOT32 DD DISP=SHR,DSN=GENAPP.DDMTOT32.DATA
//DDMTRP32 DD DISP=SHR,DSN=GENAPP.DDMTRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRN0202V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN33 DD DISP=SHR,DSN=GENAPP.DDRNIN33.DATA
//DDRNOT33 DD DISP=SHR,DSN=GENAPP.DDRNOT33.DATA
//DDRNRP33 DD DISP=SHR,DSN=GENAPP.DDRNRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
