//VJOB3961 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE024AK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN04 DD DISP=SHR,DSN=GENAPP.DDPEIN04.DATA
//DDPEOT04 DD DISP=SHR,DSN=GENAPP.DDPEOT04.DATA
//DDPERP04 DD DISP=SHR,DSN=GENAPP.DDPERP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL024AL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN05 DD DISP=SHR,DSN=GENAPP.DDCLIN05.DATA
//DDCLOT05 DD DISP=SHR,DSN=GENAPP.DDCLOT05.DATA
//DDCLRP05 DD DISP=SHR,DSN=GENAPP.DDCLRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN024AM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN06 DD DISP=SHR,DSN=GENAPP.DDENIN06.DATA
//DDENOT06 DD DISP=SHR,DSN=GENAPP.DDENOT06.DATA
//DDENRP06 DD DISP=SHR,DSN=GENAPP.DDENRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
