//VJOB2558 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE0211N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN25 DD DISP=SHR,DSN=GENAPP.DDHEIN25.DATA
//DDHEOT25 DD DISP=SHR,DSN=GENAPP.DDHEOT25.DATA
//DDHERP25 DD DISP=SHR,DSN=GENAPP.DDHERP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN0211O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN26 DD DISP=SHR,DSN=GENAPP.DDENIN26.DATA
//DDENOT26 DD DISP=SHR,DSN=GENAPP.DDENOT26.DATA
//DDENRP26 DD DISP=SHR,DSN=GENAPP.DDENRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCR0211P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN27 DD DISP=SHR,DSN=GENAPP.DDCRIN27.DATA
//DDCROT27 DD DISP=SHR,DSN=GENAPP.DDCROT27.DATA
//DDCRRP27 DD DISP=SHR,DSN=GENAPP.DDCRRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
