//VJOB2413 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT020PK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN40 DD DISP=SHR,DSN=GENAPP.DDMTIN40.DATA
//DDMTOT40 DD DISP=SHR,DSN=GENAPP.DDMTOT40.DATA
//DDMTRP40 DD DISP=SHR,DSN=GENAPP.DDMTRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW020PL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN41 DD DISP=SHR,DSN=GENAPP.DDUWIN41.DATA
//DDUWOT41 DD DISP=SHR,DSN=GENAPP.DDUWOT41.DATA
//DDUWRP41 DD DISP=SHR,DSN=GENAPP.DDUWRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG020PM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN42 DD DISP=SHR,DSN=GENAPP.DDAGIN42.DATA
//DDAGOT42 DD DISP=SHR,DSN=GENAPP.DDAGOT42.DATA
//DDAGRP42 DD DISP=SHR,DSN=GENAPP.DDAGRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
