//VJOB1730 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZST01Z4N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN61 DD DISP=SHR,DSN=GENAPP.DDSTIN61.DATA
//DDSTOT61 DD DISP=SHR,DSN=GENAPP.DDSTOT61.DATA
//DDSTRP61 DD DISP=SHR,DSN=GENAPP.DDSTRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01Z4O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN62 DD DISP=SHR,DSN=GENAPP.DDAGIN62.DATA
//DDAGOT62 DD DISP=SHR,DSN=GENAPP.DDAGOT62.DATA
//DDAGRP62 DD DISP=SHR,DSN=GENAPP.DDAGRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC01Z4P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN63 DD DISP=SHR,DSN=GENAPP.DDACIN63.DATA
//DDACOT63 DD DISP=SHR,DSN=GENAPP.DDACOT63.DATA
//DDACRP63 DD DISP=SHR,DSN=GENAPP.DDACRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
