//VJOB2934 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB021WZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN73 DD DISP=SHR,DSN=GENAPP.DDMBIN73.DATA
//DDMBOT73 DD DISP=SHR,DSN=GENAPP.DDMBOT73.DATA
//DDMBRP73 DD DISP=SHR,DSN=GENAPP.DDMBRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU021X0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN74 DD DISP=SHR,DSN=GENAPP.DDCUIN74.DATA
//DDCUOT74 DD DISP=SHR,DSN=GENAPP.DDCUOT74.DATA
//DDCURP74 DD DISP=SHR,DSN=GENAPP.DDCURP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO021X1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN75 DD DISP=SHR,DSN=GENAPP.DDHOIN75.DATA
//DDHOOT75 DD DISP=SHR,DSN=GENAPP.DDHOOT75.DATA
//DDHORP75 DD DISP=SHR,DSN=GENAPP.DDHORP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
