//VJOB3996 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZGW024DH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN19 DD DISP=SHR,DSN=GENAPP.DDGWIN19.DATA
//DDGWOT19 DD DISP=SHR,DSN=GENAPP.DDGWOT19.DATA
//DDGWRP19 DD DISP=SHR,DSN=GENAPP.DDGWRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV024DI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN20 DD DISP=SHR,DSN=GENAPP.DDIVIN20.DATA
//DDIVOT20 DD DISP=SHR,DSN=GENAPP.DDIVOT20.DATA
//DDIVRP20 DD DISP=SHR,DSN=GENAPP.DDIVRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR024DJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN21 DD DISP=SHR,DSN=GENAPP.DDFRIN21.DATA
//DDFROT21 DD DISP=SHR,DSN=GENAPP.DDFROT21.DATA
//DDFRRP21 DD DISP=SHR,DSN=GENAPP.DDFRRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
