//VJOB1886 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA01ZHN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN79 DD DISP=SHR,DSN=GENAPP.DDPAIN79.DATA
//DDPAOT79 DD DISP=SHR,DSN=GENAPP.DDPAOT79.DATA
//DDPARP79 DD DISP=SHR,DSN=GENAPP.DDPARP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01ZHO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN80 DD DISP=SHR,DSN=GENAPP.DDTXIN80.DATA
//DDTXOT80 DD DISP=SHR,DSN=GENAPP.DDTXOT80.DATA
//DDTXRP80 DD DISP=SHR,DSN=GENAPP.DDTXRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA01ZHP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN81 DD DISP=SHR,DSN=GENAPP.DDPAIN81.DATA
//DDPAOT81 DD DISP=SHR,DSN=GENAPP.DDPAOT81.DATA
//DDPARP81 DD DISP=SHR,DSN=GENAPP.DDPARP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
