//VJOB4067 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZQU024JE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN52 DD DISP=SHR,DSN=GENAPP.DDQUIN52.DATA
//DDQUOT52 DD DISP=SHR,DSN=GENAPP.DDQUOT52.DATA
//DDQURP52 DD DISP=SHR,DSN=GENAPP.DDQURP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL024JF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN53 DD DISP=SHR,DSN=GENAPP.DDFLIN53.DATA
//DDFLOT53 DD DISP=SHR,DSN=GENAPP.DDFLOT53.DATA
//DDFLRP53 DD DISP=SHR,DSN=GENAPP.DDFLRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT024JG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN54 DD DISP=SHR,DSN=GENAPP.DDMTIN54.DATA
//DDMTOT54 DD DISP=SHR,DSN=GENAPP.DDMTOT54.DATA
//DDMTRP54 DD DISP=SHR,DSN=GENAPP.DDMTRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
