//VJOB4025 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW024FW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN16 DD DISP=SHR,DSN=GENAPP.DDUWIN16.DATA
//DDUWOT16 DD DISP=SHR,DSN=GENAPP.DDUWOT16.DATA
//DDUWRP16 DD DISP=SHR,DSN=GENAPP.DDUWRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL024FX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN17 DD DISP=SHR,DSN=GENAPP.DDCLIN17.DATA
//DDCLOT17 DD DISP=SHR,DSN=GENAPP.DDCLOT17.DATA
//DDCLRP17 DD DISP=SHR,DSN=GENAPP.DDCLRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSB024FY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN18 DD DISP=SHR,DSN=GENAPP.DDSBIN18.DATA
//DDSBOT18 DD DISP=SHR,DSN=GENAPP.DDSBOT18.DATA
//DDSBRP18 DD DISP=SHR,DSN=GENAPP.DDSBRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
