//VJOB3299 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI022RE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN88 DD DISP=SHR,DSN=GENAPP.DDBIIN88.DATA
//DDBIOT88 DD DISP=SHR,DSN=GENAPP.DDBIOT88.DATA
//DDBIRP88 DD DISP=SHR,DSN=GENAPP.DDBIRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT022RF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN89 DD DISP=SHR,DSN=GENAPP.DDMTIN89.DATA
//DDMTOT89 DD DISP=SHR,DSN=GENAPP.DDMTOT89.DATA
//DDMTRP89 DD DISP=SHR,DSN=GENAPP.DDMTRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU022RG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN90 DD DISP=SHR,DSN=GENAPP.DDCUIN90.DATA
//DDCUOT90 DD DISP=SHR,DSN=GENAPP.DDCUOT90.DATA
//DDCURP90 DD DISP=SHR,DSN=GENAPP.DDCURP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
