//VJOB0625 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01WKK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN76 DD DISP=SHR,DSN=GENAPP.DDHOIN76.DATA
//DDHOOT76 DD DISP=SHR,DSN=GENAPP.DDHOOT76.DATA
//DDHORP76 DD DISP=SHR,DSN=GENAPP.DDHORP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB01WKL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN77 DD DISP=SHR,DSN=GENAPP.DDLBIN77.DATA
//DDLBOT77 DD DISP=SHR,DSN=GENAPP.DDLBOT77.DATA
//DDLBRP77 DD DISP=SHR,DSN=GENAPP.DDLBRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01WKM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN78 DD DISP=SHR,DSN=GENAPP.DDMTIN78.DATA
//DDMTOT78 DD DISP=SHR,DSN=GENAPP.DDMTOT78.DATA
//DDMTRP78 DD DISP=SHR,DSN=GENAPP.DDMTRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
