//VJOB1749 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR01Z68
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN28 DD DISP=SHR,DSN=GENAPP.DDFRIN28.DATA
//DDFROT28 DD DISP=SHR,DSN=GENAPP.DDFROT28.DATA
//DDFRRP28 DD DISP=SHR,DSN=GENAPP.DDFRRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPT01Z69
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN29 DD DISP=SHR,DSN=GENAPP.DDPTIN29.DATA
//DDPTOT29 DD DISP=SHR,DSN=GENAPP.DDPTOT29.DATA
//DDPTRP29 DD DISP=SHR,DSN=GENAPP.DDPTRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR01Z6A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN30 DD DISP=SHR,DSN=GENAPP.DDFRIN30.DATA
//DDFROT30 DD DISP=SHR,DSN=GENAPP.DDFROT30.DATA
//DDFRRP30 DD DISP=SHR,DSN=GENAPP.DDFRRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
