//VJOB1520 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01YN5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN61 DD DISP=SHR,DSN=GENAPP.DDRGIN61.DATA
//DDRGOT61 DD DISP=SHR,DSN=GENAPP.DDRGOT61.DATA
//DDRGRP61 DD DISP=SHR,DSN=GENAPP.DDRGRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRC01YN6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN62 DD DISP=SHR,DSN=GENAPP.DDRCIN62.DATA
//DDRCOT62 DD DISP=SHR,DSN=GENAPP.DDRCOT62.DATA
//DDRCRP62 DD DISP=SHR,DSN=GENAPP.DDRCRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDO01YN7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN63 DD DISP=SHR,DSN=GENAPP.DDDOIN63.DATA
//DDDOOT63 DD DISP=SHR,DSN=GENAPP.DDDOOT63.DATA
//DDDORP63 DD DISP=SHR,DSN=GENAPP.DDDORP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
