//VJOB2507 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR020XE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN52 DD DISP=SHR,DSN=GENAPP.DDFRIN52.DATA
//DDFROT52 DD DISP=SHR,DSN=GENAPP.DDFROT52.DATA
//DDFRRP52 DD DISP=SHR,DSN=GENAPP.DDFRRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZED020XF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN53 DD DISP=SHR,DSN=GENAPP.DDEDIN53.DATA
//DDEDOT53 DD DISP=SHR,DSN=GENAPP.DDEDOT53.DATA
//DDEDRP53 DD DISP=SHR,DSN=GENAPP.DDEDRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU020XG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN54 DD DISP=SHR,DSN=GENAPP.DDCUIN54.DATA
//DDCUOT54 DD DISP=SHR,DSN=GENAPP.DDCUOT54.DATA
//DDCURP54 DD DISP=SHR,DSN=GENAPP.DDCURP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
