//VJOB0781 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAU01WXK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN04 DD DISP=SHR,DSN=GENAPP.DDAUIN04.DATA
//DDAUOT04 DD DISP=SHR,DSN=GENAPP.DDAUOT04.DATA
//DDAURP04 DD DISP=SHR,DSN=GENAPP.DDAURP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZST01WXL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN05 DD DISP=SHR,DSN=GENAPP.DDSTIN05.DATA
//DDSTOT05 DD DISP=SHR,DSN=GENAPP.DDSTOT05.DATA
//DDSTRP05 DD DISP=SHR,DSN=GENAPP.DDSTRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01WXM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN06 DD DISP=SHR,DSN=GENAPP.DDMTIN06.DATA
//DDMTOT06 DD DISP=SHR,DSN=GENAPP.DDMTOT06.DATA
//DDMTRP06 DD DISP=SHR,DSN=GENAPP.DDMTRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
