//VJOB1014 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX01XGZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN73 DD DISP=SHR,DSN=GENAPP.DDTXIN73.DATA
//DDTXOT73 DD DISP=SHR,DSN=GENAPP.DDTXOT73.DATA
//DDTXRP73 DD DISP=SHR,DSN=GENAPP.DDTXRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01XH0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN74 DD DISP=SHR,DSN=GENAPP.DDMTIN74.DATA
//DDMTOT74 DD DISP=SHR,DSN=GENAPP.DDMTOT74.DATA
//DDMTRP74 DD DISP=SHR,DSN=GENAPP.DDMTRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC01XH1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN75 DD DISP=SHR,DSN=GENAPP.DDSCIN75.DATA
//DDSCOT75 DD DISP=SHR,DSN=GENAPP.DDSCOT75.DATA
//DDSCRP75 DD DISP=SHR,DSN=GENAPP.DDSCRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
