//VJOB2756 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSL021I5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN79 DD DISP=SHR,DSN=GENAPP.DDSLIN79.DATA
//DDSLOT79 DD DISP=SHR,DSN=GENAPP.DDSLOT79.DATA
//DDSLRP79 DD DISP=SHR,DSN=GENAPP.DDSLRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW021I6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN80 DD DISP=SHR,DSN=GENAPP.DDUWIN80.DATA
//DDUWOT80 DD DISP=SHR,DSN=GENAPP.DDUWOT80.DATA
//DDUWRP80 DD DISP=SHR,DSN=GENAPP.DDUWRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU021I7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN81 DD DISP=SHR,DSN=GENAPP.DDCUIN81.DATA
//DDCUOT81 DD DISP=SHR,DSN=GENAPP.DDCUOT81.DATA
//DDCURP81 DD DISP=SHR,DSN=GENAPP.DDCURP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
