//VJOB2635 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT02182
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN76 DD DISP=SHR,DSN=GENAPP.DDPTIN76.DATA
//DDPTOT76 DD DISP=SHR,DSN=GENAPP.DDPTOT76.DATA
//DDPTRP76 DD DISP=SHR,DSN=GENAPP.DDPTRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ02183
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN77 DD DISP=SHR,DSN=GENAPP.DDAZIN77.DATA
//DDAZOT77 DD DISP=SHR,DSN=GENAPP.DDAZOT77.DATA
//DDAZRP77 DD DISP=SHR,DSN=GENAPP.DDAZRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR02184
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN78 DD DISP=SHR,DSN=GENAPP.DDPRIN78.DATA
//DDPROT78 DD DISP=SHR,DSN=GENAPP.DDPROT78.DATA
//DDPRRP78 DD DISP=SHR,DSN=GENAPP.DDPRRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
