//VJOB0250 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01VPB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN31 DD DISP=SHR,DSN=GENAPP.DDAVIN31.DATA
//DDAVOT31 DD DISP=SHR,DSN=GENAPP.DDAVOT31.DATA
//DDAVRP31 DD DISP=SHR,DSN=GENAPP.DDAVRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01VPC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN32 DD DISP=SHR,DSN=GENAPP.DDLIIN32.DATA
//DDLIOT32 DD DISP=SHR,DSN=GENAPP.DDLIOT32.DATA
//DDLIRP32 DD DISP=SHR,DSN=GENAPP.DDLIRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSE01VPD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN33 DD DISP=SHR,DSN=GENAPP.DDSEIN33.DATA
//DDSEOT33 DD DISP=SHR,DSN=GENAPP.DDSEOT33.DATA
//DDSERP33 DD DISP=SHR,DSN=GENAPP.DDSERP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
