//VJOB0856 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01X3T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN49 DD DISP=SHR,DSN=GENAPP.DDMTIN49.DATA
//DDMTOT49 DD DISP=SHR,DSN=GENAPP.DDMTOT49.DATA
//DDMTRP49 DD DISP=SHR,DSN=GENAPP.DDMTRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01X3U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN50 DD DISP=SHR,DSN=GENAPP.DDTXIN50.DATA
//DDTXOT50 DD DISP=SHR,DSN=GENAPP.DDTXOT50.DATA
//DDTXRP50 DD DISP=SHR,DSN=GENAPP.DDTXRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01X3V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN51 DD DISP=SHR,DSN=GENAPP.DDCLIN51.DATA
//DDCLOT51 DD DISP=SHR,DSN=GENAPP.DDCLOT51.DATA
//DDCLRP51 DD DISP=SHR,DSN=GENAPP.DDCLRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
