//VJOB2960 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO021Z5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN61 DD DISP=SHR,DSN=GENAPP.DDCOIN61.DATA
//DDCOOT61 DD DISP=SHR,DSN=GENAPP.DDCOOT61.DATA
//DDCORP61 DD DISP=SHR,DSN=GENAPP.DDCORP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR021Z6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN62 DD DISP=SHR,DSN=GENAPP.DDTRIN62.DATA
//DDTROT62 DD DISP=SHR,DSN=GENAPP.DDTROT62.DATA
//DDTRRP62 DD DISP=SHR,DSN=GENAPP.DDTRRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN021Z7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN63 DD DISP=SHR,DSN=GENAPP.DDENIN63.DATA
//DDENOT63 DD DISP=SHR,DSN=GENAPP.DDENOT63.DATA
//DDENRP63 DD DISP=SHR,DSN=GENAPP.DDENRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
