//VJOB0537 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01WD8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN82 DD DISP=SHR,DSN=GENAPP.DDUWIN82.DATA
//DDUWOT82 DD DISP=SHR,DSN=GENAPP.DDUWOT82.DATA
//DDUWRP82 DD DISP=SHR,DSN=GENAPP.DDUWRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE01WD9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN83 DD DISP=SHR,DSN=GENAPP.DDPEIN83.DATA
//DDPEOT83 DD DISP=SHR,DSN=GENAPP.DDPEOT83.DATA
//DDPERP83 DD DISP=SHR,DSN=GENAPP.DDPERP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01WDA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN84 DD DISP=SHR,DSN=GENAPP.DDMAIN84.DATA
//DDMAOT84 DD DISP=SHR,DSN=GENAPP.DDMAOT84.DATA
//DDMARP84 DD DISP=SHR,DSN=GENAPP.DDMARP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
