//VJOB0797 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCR01WYW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN52 DD DISP=SHR,DSN=GENAPP.DDCRIN52.DATA
//DDCROT52 DD DISP=SHR,DSN=GENAPP.DDCROT52.DATA
//DDCRRP52 DD DISP=SHR,DSN=GENAPP.DDCRRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC01WYX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN53 DD DISP=SHR,DSN=GENAPP.DDSCIN53.DATA
//DDSCOT53 DD DISP=SHR,DSN=GENAPP.DDSCOT53.DATA
//DDSCRP53 DD DISP=SHR,DSN=GENAPP.DDSCRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01WYY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN54 DD DISP=SHR,DSN=GENAPP.DDMTIN54.DATA
//DDMTOT54 DD DISP=SHR,DSN=GENAPP.DDMTOT54.DATA
//DDMTRP54 DD DISP=SHR,DSN=GENAPP.DDMTRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
