//VJOB0878 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEX01X5N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN25 DD DISP=SHR,DSN=GENAPP.DDEXIN25.DATA
//DDEXOT25 DD DISP=SHR,DSN=GENAPP.DDEXOT25.DATA
//DDEXRP25 DD DISP=SHR,DSN=GENAPP.DDEXRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDO01X5O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN26 DD DISP=SHR,DSN=GENAPP.DDDOIN26.DATA
//DDDOOT26 DD DISP=SHR,DSN=GENAPP.DDDOOT26.DATA
//DDDORP26 DD DISP=SHR,DSN=GENAPP.DDDORP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR01X5P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN27 DD DISP=SHR,DSN=GENAPP.DDBRIN27.DATA
//DDBROT27 DD DISP=SHR,DSN=GENAPP.DDBROT27.DATA
//DDBRRP27 DD DISP=SHR,DSN=GENAPP.DDBRRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
