//VJOB2297 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAZ020FW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN52 DD DISP=SHR,DSN=GENAPP.DDAZIN52.DATA
//DDAZOT52 DD DISP=SHR,DSN=GENAPP.DDAZOT52.DATA
//DDAZRP52 DD DISP=SHR,DSN=GENAPP.DDAZRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZVA020FX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN53 DD DISP=SHR,DSN=GENAPP.DDVAIN53.DATA
//DDVAOT53 DD DISP=SHR,DSN=GENAPP.DDVAOT53.DATA
//DDVARP53 DD DISP=SHR,DSN=GENAPP.DDVARP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL020FY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN54 DD DISP=SHR,DSN=GENAPP.DDCLIN54.DATA
//DDCLOT54 DD DISP=SHR,DSN=GENAPP.DDCLOT54.DATA
//DDCLRP54 DD DISP=SHR,DSN=GENAPP.DDCLRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
