//VJOB2087 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01ZYE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN52 DD DISP=SHR,DSN=GENAPP.DDRGIN52.DATA
//DDRGOT52 DD DISP=SHR,DSN=GENAPP.DDRGOT52.DATA
//DDRGRP52 DD DISP=SHR,DSN=GENAPP.DDRGRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN01ZYF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN53 DD DISP=SHR,DSN=GENAPP.DDANIN53.DATA
//DDANOT53 DD DISP=SHR,DSN=GENAPP.DDANOT53.DATA
//DDANRP53 DD DISP=SHR,DSN=GENAPP.DDANRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSB01ZYG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN54 DD DISP=SHR,DSN=GENAPP.DDSBIN54.DATA
//DDSBOT54 DD DISP=SHR,DSN=GENAPP.DDSBOT54.DATA
//DDSBRP54 DD DISP=SHR,DSN=GENAPP.DDSBRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
