//VJOB1642 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01YXB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN67 DD DISP=SHR,DSN=GENAPP.DDMTIN67.DATA
//DDMTOT67 DD DISP=SHR,DSN=GENAPP.DDMTOT67.DATA
//DDMTRP67 DD DISP=SHR,DSN=GENAPP.DDMTRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR01YXC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN68 DD DISP=SHR,DSN=GENAPP.DDBRIN68.DATA
//DDBROT68 DD DISP=SHR,DSN=GENAPP.DDBROT68.DATA
//DDBRRP68 DD DISP=SHR,DSN=GENAPP.DDBRRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG01YXD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN69 DD DISP=SHR,DSN=GENAPP.DDRGIN69.DATA
//DDRGOT69 DD DISP=SHR,DSN=GENAPP.DDRGOT69.DATA
//DDRGRP69 DD DISP=SHR,DSN=GENAPP.DDRGRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
