//VJOB4020 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW024FH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN01 DD DISP=SHR,DSN=GENAPP.DDUWIN01.DATA
//DDUWOT01 DD DISP=SHR,DSN=GENAPP.DDUWOT01.DATA
//DDUWRP01 DD DISP=SHR,DSN=GENAPP.DDUWRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZWF024FI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN02 DD DISP=SHR,DSN=GENAPP.DDWFIN02.DATA
//DDWFOT02 DD DISP=SHR,DSN=GENAPP.DDWFOT02.DATA
//DDWFRP02 DD DISP=SHR,DSN=GENAPP.DDWFRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE024FJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN03 DD DISP=SHR,DSN=GENAPP.DDPEIN03.DATA
//DDPEOT03 DD DISP=SHR,DSN=GENAPP.DDPEOT03.DATA
//DDPERP03 DD DISP=SHR,DSN=GENAPP.DDPERP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
