//VJOB3659 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC023LE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN88 DD DISP=SHR,DSN=GENAPP.DDRCIN88.DATA
//DDRCOT88 DD DISP=SHR,DSN=GENAPP.DDRCOT88.DATA
//DDRCRP88 DD DISP=SHR,DSN=GENAPP.DDRCRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU023LF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN89 DD DISP=SHR,DSN=GENAPP.DDCUIN89.DATA
//DDCUOT89 DD DISP=SHR,DSN=GENAPP.DDCUOT89.DATA
//DDCURP89 DD DISP=SHR,DSN=GENAPP.DDCURP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT023LG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN90 DD DISP=SHR,DSN=GENAPP.DDMTIN90.DATA
//DDMTOT90 DD DISP=SHR,DSN=GENAPP.DDMTOT90.DATA
//DDMTRP90 DD DISP=SHR,DSN=GENAPP.DDMTRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
