//VJOB2460 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC020TH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN01 DD DISP=SHR,DSN=GENAPP.DDRCIN01.DATA
//DDRCOT01 DD DISP=SHR,DSN=GENAPP.DDRCOT01.DATA
//DDRCRP01 DD DISP=SHR,DSN=GENAPP.DDRCRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW020TI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN02 DD DISP=SHR,DSN=GENAPP.DDUWIN02.DATA
//DDUWOT02 DD DISP=SHR,DSN=GENAPP.DDUWOT02.DATA
//DDUWRP02 DD DISP=SHR,DSN=GENAPP.DDUWRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW020TJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN03 DD DISP=SHR,DSN=GENAPP.DDUWIN03.DATA
//DDUWOT03 DD DISP=SHR,DSN=GENAPP.DDUWOT03.DATA
//DDUWRP03 DD DISP=SHR,DSN=GENAPP.DDUWRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
