//VJOB0120 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01VEH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN01 DD DISP=SHR,DSN=GENAPP.DDCLIN01.DATA
//DDCLOT01 DD DISP=SHR,DSN=GENAPP.DDCLOT01.DATA
//DDCLRP01 DD DISP=SHR,DSN=GENAPP.DDCLRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR01VEI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN02 DD DISP=SHR,DSN=GENAPP.DDBRIN02.DATA
//DDBROT02 DD DISP=SHR,DSN=GENAPP.DDBROT02.DATA
//DDBRRP02 DD DISP=SHR,DSN=GENAPP.DDBRRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01VEJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN03 DD DISP=SHR,DSN=GENAPP.DDMTIN03.DATA
//DDMTOT03 DD DISP=SHR,DSN=GENAPP.DDMTOT03.DATA
//DDMTRP03 DD DISP=SHR,DSN=GENAPP.DDMTRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
