//VJOB2770 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB021JB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN31 DD DISP=SHR,DSN=GENAPP.DDMBIN31.DATA
//DDMBOT31 DD DISP=SHR,DSN=GENAPP.DDMBOT31.DATA
//DDMBRP31 DD DISP=SHR,DSN=GENAPP.DDMBRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN021JC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN32 DD DISP=SHR,DSN=GENAPP.DDRNIN32.DATA
//DDRNOT32 DD DISP=SHR,DSN=GENAPP.DDRNOT32.DATA
//DDRNRP32 DD DISP=SHR,DSN=GENAPP.DDRNRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR021JD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN33 DD DISP=SHR,DSN=GENAPP.DDPRIN33.DATA
//DDPROT33 DD DISP=SHR,DSN=GENAPP.DDPROT33.DATA
//DDPRRP33 DD DISP=SHR,DSN=GENAPP.DDPRRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
