//VJOB3101 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO022AW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN34 DD DISP=SHR,DSN=GENAPP.DDCOIN34.DATA
//DDCOOT34 DD DISP=SHR,DSN=GENAPP.DDCOOT34.DATA
//DDCORP34 DD DISP=SHR,DSN=GENAPP.DDCORP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB022AX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN35 DD DISP=SHR,DSN=GENAPP.DDLBIN35.DATA
//DDLBOT35 DD DISP=SHR,DSN=GENAPP.DDLBOT35.DATA
//DDLBRP35 DD DISP=SHR,DSN=GENAPP.DDLBRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW022AY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN36 DD DISP=SHR,DSN=GENAPP.DDUWIN36.DATA
//DDUWOT36 DD DISP=SHR,DSN=GENAPP.DDUWOT36.DATA
//DDUWRP36 DD DISP=SHR,DSN=GENAPP.DDUWRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
