//VJOB1541 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01YOW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN34 DD DISP=SHR,DSN=GENAPP.DDRGIN34.DATA
//DDRGOT34 DD DISP=SHR,DSN=GENAPP.DDRGOT34.DATA
//DDRGRP34 DD DISP=SHR,DSN=GENAPP.DDRGRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01YOX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN35 DD DISP=SHR,DSN=GENAPP.DDFLIN35.DATA
//DDFLOT35 DD DISP=SHR,DSN=GENAPP.DDFLOT35.DATA
//DDFLRP35 DD DISP=SHR,DSN=GENAPP.DDFLRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01YOY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN36 DD DISP=SHR,DSN=GENAPP.DDREIN36.DATA
//DDREOT36 DD DISP=SHR,DSN=GENAPP.DDREOT36.DATA
//DDRERP36 DD DISP=SHR,DSN=GENAPP.DDRERP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
