//VJOB0160 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01VHT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN31 DD DISP=SHR,DSN=GENAPP.DDENIN31.DATA
//DDENOT31 DD DISP=SHR,DSN=GENAPP.DDENOT31.DATA
//DDENRP31 DD DISP=SHR,DSN=GENAPP.DDENRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN01VHU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN32 DD DISP=SHR,DSN=GENAPP.DDANIN32.DATA
//DDANOT32 DD DISP=SHR,DSN=GENAPP.DDANOT32.DATA
//DDANRP32 DD DISP=SHR,DSN=GENAPP.DDANRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01VHV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN33 DD DISP=SHR,DSN=GENAPP.DDCUIN33.DATA
//DDCUOT33 DD DISP=SHR,DSN=GENAPP.DDCUOT33.DATA
//DDCURP33 DD DISP=SHR,DSN=GENAPP.DDCURP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
