//VJOB3078 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT0228Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN55 DD DISP=SHR,DSN=GENAPP.DDMTIN55.DATA
//DDMTOT55 DD DISP=SHR,DSN=GENAPP.DDMTOT55.DATA
//DDMTRP55 DD DISP=SHR,DSN=GENAPP.DDMTRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA02290
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN56 DD DISP=SHR,DSN=GENAPP.DDBAIN56.DATA
//DDBAOT56 DD DISP=SHR,DSN=GENAPP.DDBAOT56.DATA
//DDBARP56 DD DISP=SHR,DSN=GENAPP.DDBARP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI02291
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN57 DD DISP=SHR,DSN=GENAPP.DDBIIN57.DATA
//DDBIOT57 DD DISP=SHR,DSN=GENAPP.DDBIOT57.DATA
//DDBIRP57 DD DISP=SHR,DSN=GENAPP.DDBIRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
