//VJOB3781 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG023VK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN04 DD DISP=SHR,DSN=GENAPP.DDAGIN04.DATA
//DDAGOT04 DD DISP=SHR,DSN=GENAPP.DDAGOT04.DATA
//DDAGRP04 DD DISP=SHR,DSN=GENAPP.DDAGRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU023VL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN05 DD DISP=SHR,DSN=GENAPP.DDCUIN05.DATA
//DDCUOT05 DD DISP=SHR,DSN=GENAPP.DDCUOT05.DATA
//DDCURP05 DD DISP=SHR,DSN=GENAPP.DDCURP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMB023VM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN06 DD DISP=SHR,DSN=GENAPP.DDMBIN06.DATA
//DDMBOT06 DD DISP=SHR,DSN=GENAPP.DDMBOT06.DATA
//DDMBRP06 DD DISP=SHR,DSN=GENAPP.DDMBRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
