//VJOB3412 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX0230T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN67 DD DISP=SHR,DSN=GENAPP.DDTXIN67.DATA
//DDTXOT67 DD DISP=SHR,DSN=GENAPP.DDTXOT67.DATA
//DDTXRP67 DD DISP=SHR,DSN=GENAPP.DDTXRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI0230U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN68 DD DISP=SHR,DSN=GENAPP.DDBIIN68.DATA
//DDBIOT68 DD DISP=SHR,DSN=GENAPP.DDBIOT68.DATA
//DDBIRP68 DD DISP=SHR,DSN=GENAPP.DDBIRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDO0230V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN69 DD DISP=SHR,DSN=GENAPP.DDDOIN69.DATA
//DDDOOT69 DD DISP=SHR,DSN=GENAPP.DDDOOT69.DATA
//DDDORP69 DD DISP=SHR,DSN=GENAPP.DDDORP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
