//VJOB2787 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC021KQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN82 DD DISP=SHR,DSN=GENAPP.DDRCIN82.DATA
//DDRCOT82 DD DISP=SHR,DSN=GENAPP.DDRCOT82.DATA
//DDRCRP82 DD DISP=SHR,DSN=GENAPP.DDRCRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR021KR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN83 DD DISP=SHR,DSN=GENAPP.DDPRIN83.DATA
//DDPROT83 DD DISP=SHR,DSN=GENAPP.DDPROT83.DATA
//DDPRRP83 DD DISP=SHR,DSN=GENAPP.DDPRRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF021KS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN84 DD DISP=SHR,DSN=GENAPP.DDIFIN84.DATA
//DDIFOT84 DD DISP=SHR,DSN=GENAPP.DDIFOT84.DATA
//DDIFRP84 DD DISP=SHR,DSN=GENAPP.DDIFRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
