//VJOB3301 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE022RK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN04 DD DISP=SHR,DSN=GENAPP.DDHEIN04.DATA
//DDHEOT04 DD DISP=SHR,DSN=GENAPP.DDHEOT04.DATA
//DDHERP04 DD DISP=SHR,DSN=GENAPP.DDHERP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN022RL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN05 DD DISP=SHR,DSN=GENAPP.DDENIN05.DATA
//DDENOT05 DD DISP=SHR,DSN=GENAPP.DDENOT05.DATA
//DDENRP05 DD DISP=SHR,DSN=GENAPP.DDENRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW022RM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN06 DD DISP=SHR,DSN=GENAPP.DDUWIN06.DATA
//DDUWOT06 DD DISP=SHR,DSN=GENAPP.DDUWOT06.DATA
//DDUWRP06 DD DISP=SHR,DSN=GENAPP.DDUWRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
