//VJOB0627 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01WKQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN82 DD DISP=SHR,DSN=GENAPP.DDCLIN82.DATA
//DDCLOT82 DD DISP=SHR,DSN=GENAPP.DDCLOT82.DATA
//DDCLRP82 DD DISP=SHR,DSN=GENAPP.DDCLRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01WKR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN83 DD DISP=SHR,DSN=GENAPP.DDMTIN83.DATA
//DDMTOT83 DD DISP=SHR,DSN=GENAPP.DDMTOT83.DATA
//DDMTRP83 DD DISP=SHR,DSN=GENAPP.DDMTRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDO01WKS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN84 DD DISP=SHR,DSN=GENAPP.DDDOIN84.DATA
//DDDOOT84 DD DISP=SHR,DSN=GENAPP.DDDOOT84.DATA
//DDDORP84 DD DISP=SHR,DSN=GENAPP.DDDORP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
