//VJOB3376 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI022XT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN49 DD DISP=SHR,DSN=GENAPP.DDBIIN49.DATA
//DDBIOT49 DD DISP=SHR,DSN=GENAPP.DDBIOT49.DATA
//DDBIRP49 DD DISP=SHR,DSN=GENAPP.DDBIRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ022XU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN50 DD DISP=SHR,DSN=GENAPP.DDAZIN50.DATA
//DDAZOT50 DD DISP=SHR,DSN=GENAPP.DDAZOT50.DATA
//DDAZRP50 DD DISP=SHR,DSN=GENAPP.DDAZRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX022XV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN51 DD DISP=SHR,DSN=GENAPP.DDTXIN51.DATA
//DDTXOT51 DD DISP=SHR,DSN=GENAPP.DDTXOT51.DATA
//DDTXRP51 DD DISP=SHR,DSN=GENAPP.DDTXRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
