//VJOB3180 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG022HH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN01 DD DISP=SHR,DSN=GENAPP.DDRGIN01.DATA
//DDRGOT01 DD DISP=SHR,DSN=GENAPP.DDRGOT01.DATA
//DDRGRP01 DD DISP=SHR,DSN=GENAPP.DDRGRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT022HI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN02 DD DISP=SHR,DSN=GENAPP.DDMTIN02.DATA
//DDMTOT02 DD DISP=SHR,DSN=GENAPP.DDMTOT02.DATA
//DDMTRP02 DD DISP=SHR,DSN=GENAPP.DDMTRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE022HJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN03 DD DISP=SHR,DSN=GENAPP.DDPEIN03.DATA
//DDPEOT03 DD DISP=SHR,DSN=GENAPP.DDPEOT03.DATA
//DDPERP03 DD DISP=SHR,DSN=GENAPP.DDPERP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
