//VJOB0156 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEX01VHH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN19 DD DISP=SHR,DSN=GENAPP.DDEXIN19.DATA
//DDEXOT19 DD DISP=SHR,DSN=GENAPP.DDEXOT19.DATA
//DDEXRP19 DD DISP=SHR,DSN=GENAPP.DDEXRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE01VHI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN20 DD DISP=SHR,DSN=GENAPP.DDPEIN20.DATA
//DDPEOT20 DD DISP=SHR,DSN=GENAPP.DDPEOT20.DATA
//DDPERP20 DD DISP=SHR,DSN=GENAPP.DDPERP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01VHJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN21 DD DISP=SHR,DSN=GENAPP.DDPRIN21.DATA
//DDPROT21 DD DISP=SHR,DSN=GENAPP.DDPROT21.DATA
//DDPRRP21 DD DISP=SHR,DSN=GENAPP.DDPRRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
