//VJOB3350 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL022VN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN61 DD DISP=SHR,DSN=GENAPP.DDFLIN61.DATA
//DDFLOT61 DD DISP=SHR,DSN=GENAPP.DDFLOT61.DATA
//DDFLRP61 DD DISP=SHR,DSN=GENAPP.DDFLRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR022VO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN62 DD DISP=SHR,DSN=GENAPP.DDPRIN62.DATA
//DDPROT62 DD DISP=SHR,DSN=GENAPP.DDPROT62.DATA
//DDPRRP62 DD DISP=SHR,DSN=GENAPP.DDPRRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR022VP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN63 DD DISP=SHR,DSN=GENAPP.DDPRIN63.DATA
//DDPROT63 DD DISP=SHR,DSN=GENAPP.DDPROT63.DATA
//DDPRRP63 DD DISP=SHR,DSN=GENAPP.DDPRRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
