//VJOB2720 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN021F5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN61 DD DISP=SHR,DSN=GENAPP.DDANIN61.DATA
//DDANOT61 DD DISP=SHR,DSN=GENAPP.DDANOT61.DATA
//DDANRP61 DD DISP=SHR,DSN=GENAPP.DDANRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE021F6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN62 DD DISP=SHR,DSN=GENAPP.DDREIN62.DATA
//DDREOT62 DD DISP=SHR,DSN=GENAPP.DDREOT62.DATA
//DDRERP62 DD DISP=SHR,DSN=GENAPP.DDRERP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU021F7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN63 DD DISP=SHR,DSN=GENAPP.DDCUIN63.DATA
//DDCUOT63 DD DISP=SHR,DSN=GENAPP.DDCUOT63.DATA
//DDCURP63 DD DISP=SHR,DSN=GENAPP.DDCURP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
