//VJOB3783 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT023VQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN10 DD DISP=SHR,DSN=GENAPP.DDMTIN10.DATA
//DDMTOT10 DD DISP=SHR,DSN=GENAPP.DDMTOT10.DATA
//DDMTRP10 DD DISP=SHR,DSN=GENAPP.DDMTRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN023VR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN11 DD DISP=SHR,DSN=GENAPP.DDRNIN11.DATA
//DDRNOT11 DD DISP=SHR,DSN=GENAPP.DDRNOT11.DATA
//DDRNRP11 DD DISP=SHR,DSN=GENAPP.DDRNRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZED023VS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN12 DD DISP=SHR,DSN=GENAPP.DDEDIN12.DATA
//DDEDOT12 DD DISP=SHR,DSN=GENAPP.DDEDOT12.DATA
//DDEDRP12 DD DISP=SHR,DSN=GENAPP.DDEDRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
