//VJOB0305 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRT01VTW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN16 DD DISP=SHR,DSN=GENAPP.DDRTIN16.DATA
//DDRTOT16 DD DISP=SHR,DSN=GENAPP.DDRTOT16.DATA
//DDRTRP16 DD DISP=SHR,DSN=GENAPP.DDRTRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAR01VTX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN17 DD DISP=SHR,DSN=GENAPP.DDARIN17.DATA
//DDAROT17 DD DISP=SHR,DSN=GENAPP.DDAROT17.DATA
//DDARRP17 DD DISP=SHR,DSN=GENAPP.DDARRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI01VTY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN18 DD DISP=SHR,DSN=GENAPP.DDLIIN18.DATA
//DDLIOT18 DD DISP=SHR,DSN=GENAPP.DDLIOT18.DATA
//DDLIRP18 DD DISP=SHR,DSN=GENAPP.DDLIRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
