//VJOB2739 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSB021GQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN28 DD DISP=SHR,DSN=GENAPP.DDSBIN28.DATA
//DDSBOT28 DD DISP=SHR,DSN=GENAPP.DDSBOT28.DATA
//DDSBRP28 DD DISP=SHR,DSN=GENAPP.DDSBRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDI021GR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN29 DD DISP=SHR,DSN=GENAPP.DDDIIN29.DATA
//DDDIOT29 DD DISP=SHR,DSN=GENAPP.DDDIOT29.DATA
//DDDIRP29 DD DISP=SHR,DSN=GENAPP.DDDIRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS021GS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN30 DD DISP=SHR,DSN=GENAPP.DDRSIN30.DATA
//DDRSOT30 DD DISP=SHR,DSN=GENAPP.DDRSOT30.DATA
//DDRSRP30 DD DISP=SHR,DSN=GENAPP.DDRSRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
