//VJOB0926 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT01X9N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN79 DD DISP=SHR,DSN=GENAPP.DDPTIN79.DATA
//DDPTOT79 DD DISP=SHR,DSN=GENAPP.DDPTOT79.DATA
//DDPTRP79 DD DISP=SHR,DSN=GENAPP.DDPTRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN01X9O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN80 DD DISP=SHR,DSN=GENAPP.DDRNIN80.DATA
//DDRNOT80 DD DISP=SHR,DSN=GENAPP.DDRNOT80.DATA
//DDRNRP80 DD DISP=SHR,DSN=GENAPP.DDRNRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZQU01X9P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN81 DD DISP=SHR,DSN=GENAPP.DDQUIN81.DATA
//DDQUOT81 DD DISP=SHR,DSN=GENAPP.DDQUOT81.DATA
//DDQURP81 DD DISP=SHR,DSN=GENAPP.DDQURP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
