//VJOB0945 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01XB8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN46 DD DISP=SHR,DSN=GENAPP.DDCOIN46.DATA
//DDCOOT46 DD DISP=SHR,DSN=GENAPP.DDCOOT46.DATA
//DDCORP46 DD DISP=SHR,DSN=GENAPP.DDCORP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZQU01XB9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN47 DD DISP=SHR,DSN=GENAPP.DDQUIN47.DATA
//DDQUOT47 DD DISP=SHR,DSN=GENAPP.DDQUOT47.DATA
//DDQURP47 DD DISP=SHR,DSN=GENAPP.DDQURP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01XBA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN48 DD DISP=SHR,DSN=GENAPP.DDREIN48.DATA
//DDREOT48 DD DISP=SHR,DSN=GENAPP.DDREOT48.DATA
//DDRERP48 DD DISP=SHR,DSN=GENAPP.DDRERP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
