//VJOB4200 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI024UH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN01 DD DISP=SHR,DSN=GENAPP.DDBIIN01.DATA
//DDBIOT01 DD DISP=SHR,DSN=GENAPP.DDBIOT01.DATA
//DDBIRP01 DD DISP=SHR,DSN=GENAPP.DDBIRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW024UI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN02 DD DISP=SHR,DSN=GENAPP.DDUWIN02.DATA
//DDUWOT02 DD DISP=SHR,DSN=GENAPP.DDUWOT02.DATA
//DDUWRP02 DD DISP=SHR,DSN=GENAPP.DDUWRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT024UJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN03 DD DISP=SHR,DSN=GENAPP.DDMTIN03.DATA
//DDMTOT03 DD DISP=SHR,DSN=GENAPP.DDMTOT03.DATA
//DDMTRP03 DD DISP=SHR,DSN=GENAPP.DDMTRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
