//VJOB1680 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPR01Z0H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN01 DD DISP=SHR,DSN=GENAPP.DDPRIN01.DATA
//DDPROT01 DD DISP=SHR,DSN=GENAPP.DDPROT01.DATA
//DDPRRP01 DD DISP=SHR,DSN=GENAPP.DDPRRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01Z0I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN02 DD DISP=SHR,DSN=GENAPP.DDBIIN02.DATA
//DDBIOT02 DD DISP=SHR,DSN=GENAPP.DDBIOT02.DATA
//DDBIRP02 DD DISP=SHR,DSN=GENAPP.DDBIRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR01Z0J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN03 DD DISP=SHR,DSN=GENAPP.DDFRIN03.DATA
//DDFROT03 DD DISP=SHR,DSN=GENAPP.DDFROT03.DATA
//DDFRRP03 DD DISP=SHR,DSN=GENAPP.DDFRRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
