//VJOB1290 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01Y3Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN01 DD DISP=SHR,DSN=GENAPP.DDHOIN01.DATA
//DDHOOT01 DD DISP=SHR,DSN=GENAPP.DDHOOT01.DATA
//DDHORP01 DD DISP=SHR,DSN=GENAPP.DDHORP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR01Y40
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN02 DD DISP=SHR,DSN=GENAPP.DDPRIN02.DATA
//DDPROT02 DD DISP=SHR,DSN=GENAPP.DDPROT02.DATA
//DDPRRP02 DD DISP=SHR,DSN=GENAPP.DDPRRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW01Y41
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN03 DD DISP=SHR,DSN=GENAPP.DDUWIN03.DATA
//DDUWOT03 DD DISP=SHR,DSN=GENAPP.DDUWOT03.DATA
//DDUWRP03 DD DISP=SHR,DSN=GENAPP.DDUWRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
