//VJOB1394 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01YCN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN43 DD DISP=SHR,DSN=GENAPP.DDMTIN43.DATA
//DDMTOT43 DD DISP=SHR,DSN=GENAPP.DDMTOT43.DATA
//DDMTRP43 DD DISP=SHR,DSN=GENAPP.DDMTRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPL01YCO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN44 DD DISP=SHR,DSN=GENAPP.DDPLIN44.DATA
//DDPLOT44 DD DISP=SHR,DSN=GENAPP.DDPLOT44.DATA
//DDPLRP44 DD DISP=SHR,DSN=GENAPP.DDPLRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW01YCP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN45 DD DISP=SHR,DSN=GENAPP.DDUWIN45.DATA
//DDUWOT45 DD DISP=SHR,DSN=GENAPP.DDUWOT45.DATA
//DDUWRP45 DD DISP=SHR,DSN=GENAPP.DDUWRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
