//VJOB1478 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01YJN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN25 DD DISP=SHR,DSN=GENAPP.DDENIN25.DATA
//DDENOT25 DD DISP=SHR,DSN=GENAPP.DDENOT25.DATA
//DDENRP25 DD DISP=SHR,DSN=GENAPP.DDENRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01YJO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN26 DD DISP=SHR,DSN=GENAPP.DDFLIN26.DATA
//DDFLOT26 DD DISP=SHR,DSN=GENAPP.DDFLOT26.DATA
//DDFLRP26 DD DISP=SHR,DSN=GENAPP.DDFLRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF01YJP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN27 DD DISP=SHR,DSN=GENAPP.DDIFIN27.DATA
//DDIFOT27 DD DISP=SHR,DSN=GENAPP.DDIFOT27.DATA
//DDIFRP27 DD DISP=SHR,DSN=GENAPP.DDIFRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
