//VJOB0743 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRN01WUE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN70 DD DISP=SHR,DSN=GENAPP.DDRNIN70.DATA
//DDRNOT70 DD DISP=SHR,DSN=GENAPP.DDRNOT70.DATA
//DDRNRP70 DD DISP=SHR,DSN=GENAPP.DDRNRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB01WUF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN71 DD DISP=SHR,DSN=GENAPP.DDLBIN71.DATA
//DDLBOT71 DD DISP=SHR,DSN=GENAPP.DDLBOT71.DATA
//DDLBRP71 DD DISP=SHR,DSN=GENAPP.DDLBRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMB01WUG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN72 DD DISP=SHR,DSN=GENAPP.DDMBIN72.DATA
//DDMBOT72 DD DISP=SHR,DSN=GENAPP.DDMBOT72.DATA
//DDMBRP72 DD DISP=SHR,DSN=GENAPP.DDMBRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
