//VJOB2277 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU020E8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN82 DD DISP=SHR,DSN=GENAPP.DDCUIN82.DATA
//DDCUOT82 DD DISP=SHR,DSN=GENAPP.DDCUOT82.DATA
//DDCURP82 DD DISP=SHR,DSN=GENAPP.DDCURP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU020E9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN83 DD DISP=SHR,DSN=GENAPP.DDCUIN83.DATA
//DDCUOT83 DD DISP=SHR,DSN=GENAPP.DDCUOT83.DATA
//DDCURP83 DD DISP=SHR,DSN=GENAPP.DDCURP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC020EA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN84 DD DISP=SHR,DSN=GENAPP.DDSCIN84.DATA
//DDSCOT84 DD DISP=SHR,DSN=GENAPP.DDSCOT84.DATA
//DDSCRP84 DD DISP=SHR,DSN=GENAPP.DDSCRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
