//VJOB3646 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSB023KB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN49 DD DISP=SHR,DSN=GENAPP.DDSBIN49.DATA
//DDSBOT49 DD DISP=SHR,DSN=GENAPP.DDSBOT49.DATA
//DDSBRP49 DD DISP=SHR,DSN=GENAPP.DDSBRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI023KC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN50 DD DISP=SHR,DSN=GENAPP.DDBIIN50.DATA
//DDBIOT50 DD DISP=SHR,DSN=GENAPP.DDBIOT50.DATA
//DDBIRP50 DD DISP=SHR,DSN=GENAPP.DDBIRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR023KD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN51 DD DISP=SHR,DSN=GENAPP.DDPRIN51.DATA
//DDPROT51 DD DISP=SHR,DSN=GENAPP.DDPROT51.DATA
//DDPRRP51 DD DISP=SHR,DSN=GENAPP.DDPRRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
