//VJOB3742 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA023SB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN67 DD DISP=SHR,DSN=GENAPP.DDPAIN67.DATA
//DDPAOT67 DD DISP=SHR,DSN=GENAPP.DDPAOT67.DATA
//DDPARP67 DD DISP=SHR,DSN=GENAPP.DDPARP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO023SC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN68 DD DISP=SHR,DSN=GENAPP.DDHOIN68.DATA
//DDHOOT68 DD DISP=SHR,DSN=GENAPP.DDHOOT68.DATA
//DDHORP68 DD DISP=SHR,DSN=GENAPP.DDHORP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN023SD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN69 DD DISP=SHR,DSN=GENAPP.DDENIN69.DATA
//DDENOT69 DD DISP=SHR,DSN=GENAPP.DDENOT69.DATA
//DDENRP69 DD DISP=SHR,DSN=GENAPP.DDENRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
