//VJOB2967 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB021ZQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN82 DD DISP=SHR,DSN=GENAPP.DDLBIN82.DATA
//DDLBOT82 DD DISP=SHR,DSN=GENAPP.DDLBOT82.DATA
//DDLBRP82 DD DISP=SHR,DSN=GENAPP.DDLBRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPL021ZR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN83 DD DISP=SHR,DSN=GENAPP.DDPLIN83.DATA
//DDPLOT83 DD DISP=SHR,DSN=GENAPP.DDPLOT83.DATA
//DDPLRP83 DD DISP=SHR,DSN=GENAPP.DDPLRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR021ZS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN84 DD DISP=SHR,DSN=GENAPP.DDTRIN84.DATA
//DDTROT84 DD DISP=SHR,DSN=GENAPP.DDTROT84.DATA
//DDTRRP84 DD DISP=SHR,DSN=GENAPP.DDTRRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
