//VJOB1374 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01YAZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN73 DD DISP=SHR,DSN=GENAPP.DDBIIN73.DATA
//DDBIOT73 DD DISP=SHR,DSN=GENAPP.DDBIOT73.DATA
//DDBIRP73 DD DISP=SHR,DSN=GENAPP.DDBIRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN01YB0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN74 DD DISP=SHR,DSN=GENAPP.DDPNIN74.DATA
//DDPNOT74 DD DISP=SHR,DSN=GENAPP.DDPNOT74.DATA
//DDPNRP74 DD DISP=SHR,DSN=GENAPP.DDPNRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBA01YB1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN75 DD DISP=SHR,DSN=GENAPP.DDBAIN75.DATA
//DDBAOT75 DD DISP=SHR,DSN=GENAPP.DDBAOT75.DATA
//DDBARP75 DD DISP=SHR,DSN=GENAPP.DDBARP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
