//VJOB2489 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW020VW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN88 DD DISP=SHR,DSN=GENAPP.DDUWIN88.DATA
//DDUWOT88 DD DISP=SHR,DSN=GENAPP.DDUWOT88.DATA
//DDUWRP88 DD DISP=SHR,DSN=GENAPP.DDUWRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA020VX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN89 DD DISP=SHR,DSN=GENAPP.DDPAIN89.DATA
//DDPAOT89 DD DISP=SHR,DSN=GENAPP.DDPAOT89.DATA
//DDPARP89 DD DISP=SHR,DSN=GENAPP.DDPARP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR020VY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN90 DD DISP=SHR,DSN=GENAPP.DDARIN90.DATA
//DDAROT90 DD DISP=SHR,DSN=GENAPP.DDAROT90.DATA
//DDARRP90 DD DISP=SHR,DSN=GENAPP.DDARRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
