//VJOB0957 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01XC8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN82 DD DISP=SHR,DSN=GENAPP.DDUWIN82.DATA
//DDUWOT82 DD DISP=SHR,DSN=GENAPP.DDUWOT82.DATA
//DDUWRP82 DD DISP=SHR,DSN=GENAPP.DDUWRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01XC9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN83 DD DISP=SHR,DSN=GENAPP.DDHOIN83.DATA
//DDHOOT83 DD DISP=SHR,DSN=GENAPP.DDHOOT83.DATA
//DDHORP83 DD DISP=SHR,DSN=GENAPP.DDHORP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSU01XCA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN84 DD DISP=SHR,DSN=GENAPP.DDSUIN84.DATA
//DDSUOT84 DD DISP=SHR,DSN=GENAPP.DDSUOT84.DATA
//DDSURP84 DD DISP=SHR,DSN=GENAPP.DDSURP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
