//VJOB2874 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV021RZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN73 DD DISP=SHR,DSN=GENAPP.DDAVIN73.DATA
//DDAVOT73 DD DISP=SHR,DSN=GENAPP.DDAVOT73.DATA
//DDAVRP73 DD DISP=SHR,DSN=GENAPP.DDAVRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE021S0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN74 DD DISP=SHR,DSN=GENAPP.DDHEIN74.DATA
//DDHEOT74 DD DISP=SHR,DSN=GENAPP.DDHEOT74.DATA
//DDHERP74 DD DISP=SHR,DSN=GENAPP.DDHERP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN021S1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN75 DD DISP=SHR,DSN=GENAPP.DDENIN75.DATA
//DDENOT75 DD DISP=SHR,DSN=GENAPP.DDENOT75.DATA
//DDENRP75 DD DISP=SHR,DSN=GENAPP.DDENRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
