//VJOB0987 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE01XEQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN82 DD DISP=SHR,DSN=GENAPP.DDHEIN82.DATA
//DDHEOT82 DD DISP=SHR,DSN=GENAPP.DDHEOT82.DATA
//DDHERP82 DD DISP=SHR,DSN=GENAPP.DDHERP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01XER
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN83 DD DISP=SHR,DSN=GENAPP.DDLIIN83.DATA
//DDLIOT83 DD DISP=SHR,DSN=GENAPP.DDLIOT83.DATA
//DDLIRP83 DD DISP=SHR,DSN=GENAPP.DDLIRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01XES
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN84 DD DISP=SHR,DSN=GENAPP.DDPRIN84.DATA
//DDPROT84 DD DISP=SHR,DSN=GENAPP.DDPROT84.DATA
//DDPRRP84 DD DISP=SHR,DSN=GENAPP.DDPRRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
