//VJOB1222 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR01XYB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN67 DD DISP=SHR,DSN=GENAPP.DDTRIN67.DATA
//DDTROT67 DD DISP=SHR,DSN=GENAPP.DDTROT67.DATA
//DDTRRP67 DD DISP=SHR,DSN=GENAPP.DDTRRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA01XYC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN68 DD DISP=SHR,DSN=GENAPP.DDBAIN68.DATA
//DDBAOT68 DD DISP=SHR,DSN=GENAPP.DDBAOT68.DATA
//DDBARP68 DD DISP=SHR,DSN=GENAPP.DDBARP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR01XYD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN69 DD DISP=SHR,DSN=GENAPP.DDARIN69.DATA
//DDAROT69 DD DISP=SHR,DSN=GENAPP.DDAROT69.DATA
//DDARRP69 DD DISP=SHR,DSN=GENAPP.DDARRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
