//VJOB1892 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS01ZI5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN07 DD DISP=SHR,DSN=GENAPP.DDRSIN07.DATA
//DDRSOT07 DD DISP=SHR,DSN=GENAPP.DDRSOT07.DATA
//DDRSRP07 DD DISP=SHR,DSN=GENAPP.DDRSRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFR01ZI6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN08 DD DISP=SHR,DSN=GENAPP.DDFRIN08.DATA
//DDFROT08 DD DISP=SHR,DSN=GENAPP.DDFROT08.DATA
//DDFRRP08 DD DISP=SHR,DSN=GENAPP.DDFRRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01ZI7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN09 DD DISP=SHR,DSN=GENAPP.DDTRIN09.DATA
//DDTROT09 DD DISP=SHR,DSN=GENAPP.DDTROT09.DATA
//DDTRRP09 DD DISP=SHR,DSN=GENAPP.DDTRRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
