//VJOB1341 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01Y88
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN64 DD DISP=SHR,DSN=GENAPP.DDMTIN64.DATA
//DDMTOT64 DD DISP=SHR,DSN=GENAPP.DDMTOT64.DATA
//DDMTRP64 DD DISP=SHR,DSN=GENAPP.DDMTRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA01Y89
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN65 DD DISP=SHR,DSN=GENAPP.DDMAIN65.DATA
//DDMAOT65 DD DISP=SHR,DSN=GENAPP.DDMAOT65.DATA
//DDMARP65 DD DISP=SHR,DSN=GENAPP.DDMARP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01Y8A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN66 DD DISP=SHR,DSN=GENAPP.DDHOIN66.DATA
//DDHOOT66 DD DISP=SHR,DSN=GENAPP.DDHOOT66.DATA
//DDHORP66 DD DISP=SHR,DSN=GENAPP.DDHORP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
