//VJOB3649 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSB023KK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN58 DD DISP=SHR,DSN=GENAPP.DDSBIN58.DATA
//DDSBOT58 DD DISP=SHR,DSN=GENAPP.DDSBOT58.DATA
//DDSBRP58 DD DISP=SHR,DSN=GENAPP.DDSBRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO023KL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN59 DD DISP=SHR,DSN=GENAPP.DDHOIN59.DATA
//DDHOOT59 DD DISP=SHR,DSN=GENAPP.DDHOOT59.DATA
//DDHORP59 DD DISP=SHR,DSN=GENAPP.DDHORP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCP023KM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN60 DD DISP=SHR,DSN=GENAPP.DDCPIN60.DATA
//DDCPOT60 DD DISP=SHR,DSN=GENAPP.DDCPOT60.DATA
//DDCPRP60 DD DISP=SHR,DSN=GENAPP.DDCPRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
