//VJOB0455 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSC01W6E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN16 DD DISP=SHR,DSN=GENAPP.DDSCIN16.DATA
//DDSCOT16 DD DISP=SHR,DSN=GENAPP.DDSCOT16.DATA
//DDSCRP16 DD DISP=SHR,DSN=GENAPP.DDSCRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01W6F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN17 DD DISP=SHR,DSN=GENAPP.DDMTIN17.DATA
//DDMTOT17 DD DISP=SHR,DSN=GENAPP.DDMTOT17.DATA
//DDMTRP17 DD DISP=SHR,DSN=GENAPP.DDMTRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL01W6G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN18 DD DISP=SHR,DSN=GENAPP.DDFLIN18.DATA
//DDFLOT18 DD DISP=SHR,DSN=GENAPP.DDFLOT18.DATA
//DDFLRP18 DD DISP=SHR,DSN=GENAPP.DDFLRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
