//VJOB4072 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZST024JT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN67 DD DISP=SHR,DSN=GENAPP.DDSTIN67.DATA
//DDSTOT67 DD DISP=SHR,DSN=GENAPP.DDSTOT67.DATA
//DDSTRP67 DD DISP=SHR,DSN=GENAPP.DDSTRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT024JU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN68 DD DISP=SHR,DSN=GENAPP.DDMTIN68.DATA
//DDMTOT68 DD DISP=SHR,DSN=GENAPP.DDMTOT68.DATA
//DDMTRP68 DD DISP=SHR,DSN=GENAPP.DDMTRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL024JV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN69 DD DISP=SHR,DSN=GENAPP.DDCLIN69.DATA
//DDCLOT69 DD DISP=SHR,DSN=GENAPP.DDCLOT69.DATA
//DDCLRP69 DD DISP=SHR,DSN=GENAPP.DDCLRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
