//VJOB0906 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA01X7Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN19 DD DISP=SHR,DSN=GENAPP.DDPAIN19.DATA
//DDPAOT19 DD DISP=SHR,DSN=GENAPP.DDPAOT19.DATA
//DDPARP19 DD DISP=SHR,DSN=GENAPP.DDPARP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01X80
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN20 DD DISP=SHR,DSN=GENAPP.DDHOIN20.DATA
//DDHOOT20 DD DISP=SHR,DSN=GENAPP.DDHOOT20.DATA
//DDHORP20 DD DISP=SHR,DSN=GENAPP.DDHORP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS01X81
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN21 DD DISP=SHR,DSN=GENAPP.DDRSIN21.DATA
//DDRSOT21 DD DISP=SHR,DSN=GENAPP.DDRSOT21.DATA
//DDRSRP21 DD DISP=SHR,DSN=GENAPP.DDRSRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
