//VJOB0594 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX01WHZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN73 DD DISP=SHR,DSN=GENAPP.DDTXIN73.DATA
//DDTXOT73 DD DISP=SHR,DSN=GENAPP.DDTXOT73.DATA
//DDTXRP73 DD DISP=SHR,DSN=GENAPP.DDTXRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE01WI0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN74 DD DISP=SHR,DSN=GENAPP.DDREIN74.DATA
//DDREOT74 DD DISP=SHR,DSN=GENAPP.DDREOT74.DATA
//DDRERP74 DD DISP=SHR,DSN=GENAPP.DDRERP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZST01WI1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN75 DD DISP=SHR,DSN=GENAPP.DDSTIN75.DATA
//DDSTOT75 DD DISP=SHR,DSN=GENAPP.DDSTOT75.DATA
//DDSTRP75 DD DISP=SHR,DSN=GENAPP.DDSTRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
