//VJOB1990 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA01ZQB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN31 DD DISP=SHR,DSN=GENAPP.DDBAIN31.DATA
//DDBAOT31 DD DISP=SHR,DSN=GENAPP.DDBAOT31.DATA
//DDBARP31 DD DISP=SHR,DSN=GENAPP.DDBARP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF01ZQC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN32 DD DISP=SHR,DSN=GENAPP.DDIFIN32.DATA
//DDIFOT32 DD DISP=SHR,DSN=GENAPP.DDIFOT32.DATA
//DDIFRP32 DD DISP=SHR,DSN=GENAPP.DDIFRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01ZQD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN33 DD DISP=SHR,DSN=GENAPP.DDCUIN33.DATA
//DDCUOT33 DD DISP=SHR,DSN=GENAPP.DDCUOT33.DATA
//DDCURP33 DD DISP=SHR,DSN=GENAPP.DDCURP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
