//VJOB2827 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZST021O2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN22 DD DISP=SHR,DSN=GENAPP.DDSTIN22.DATA
//DDSTOT22 DD DISP=SHR,DSN=GENAPP.DDSTOT22.DATA
//DDSTRP22 DD DISP=SHR,DSN=GENAPP.DDSTRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEX021O3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN23 DD DISP=SHR,DSN=GENAPP.DDEXIN23.DATA
//DDEXOT23 DD DISP=SHR,DSN=GENAPP.DDEXOT23.DATA
//DDEXRP23 DD DISP=SHR,DSN=GENAPP.DDEXRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE021O4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN24 DD DISP=SHR,DSN=GENAPP.DDPEIN24.DATA
//DDPEOT24 DD DISP=SHR,DSN=GENAPP.DDPEOT24.DATA
//DDPERP24 DD DISP=SHR,DSN=GENAPP.DDPERP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
