//VJOB3929 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN0247W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN88 DD DISP=SHR,DSN=GENAPP.DDENIN88.DATA
//DDENOT88 DD DISP=SHR,DSN=GENAPP.DDENOT88.DATA
//DDENRP88 DD DISP=SHR,DSN=GENAPP.DDENRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI0247X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN89 DD DISP=SHR,DSN=GENAPP.DDLIIN89.DATA
//DDLIOT89 DD DISP=SHR,DSN=GENAPP.DDLIOT89.DATA
//DDLIRP89 DD DISP=SHR,DSN=GENAPP.DDLIRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS0247Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN90 DD DISP=SHR,DSN=GENAPP.DDRSIN90.DATA
//DDRSOT90 DD DISP=SHR,DSN=GENAPP.DDRSOT90.DATA
//DDRSRP90 DD DISP=SHR,DSN=GENAPP.DDRSRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
