//VJOB2305 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZQU020GK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN76 DD DISP=SHR,DSN=GENAPP.DDQUIN76.DATA
//DDQUOT76 DD DISP=SHR,DSN=GENAPP.DDQUOT76.DATA
//DDQURP76 DD DISP=SHR,DSN=GENAPP.DDQURP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO020GL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN77 DD DISP=SHR,DSN=GENAPP.DDHOIN77.DATA
//DDHOOT77 DD DISP=SHR,DSN=GENAPP.DDHOOT77.DATA
//DDHORP77 DD DISP=SHR,DSN=GENAPP.DDHORP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAZ020GM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN78 DD DISP=SHR,DSN=GENAPP.DDAZIN78.DATA
//DDAZOT78 DD DISP=SHR,DSN=GENAPP.DDAZOT78.DATA
//DDAZRP78 DD DISP=SHR,DSN=GENAPP.DDAZRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
