//VJOB4292 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIF02525
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN07 DD DISP=SHR,DSN=GENAPP.DDIFIN07.DATA
//DDIFOT07 DD DISP=SHR,DSN=GENAPP.DDIFOT07.DATA
//DDIFRP07 DD DISP=SHR,DSN=GENAPP.DDIFRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG02526
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN08 DD DISP=SHR,DSN=GENAPP.DDAGIN08.DATA
//DDAGOT08 DD DISP=SHR,DSN=GENAPP.DDAGOT08.DATA
//DDAGRP08 DD DISP=SHR,DSN=GENAPP.DDAGRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSE02527
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN09 DD DISP=SHR,DSN=GENAPP.DDSEIN09.DATA
//DDSEOT09 DD DISP=SHR,DSN=GENAPP.DDSEOT09.DATA
//DDSERP09 DD DISP=SHR,DSN=GENAPP.DDSERP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
