//VJOB2521 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO020YK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN04 DD DISP=SHR,DSN=GENAPP.DDHOIN04.DATA
//DDHOOT04 DD DISP=SHR,DSN=GENAPP.DDHOOT04.DATA
//DDHORP04 DD DISP=SHR,DSN=GENAPP.DDHORP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE020YL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN05 DD DISP=SHR,DSN=GENAPP.DDREIN05.DATA
//DDREOT05 DD DISP=SHR,DSN=GENAPP.DDREOT05.DATA
//DDRERP05 DD DISP=SHR,DSN=GENAPP.DDRERP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBA020YM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN06 DD DISP=SHR,DSN=GENAPP.DDBAIN06.DATA
//DDBAOT06 DD DISP=SHR,DSN=GENAPP.DDBAOT06.DATA
//DDBARP06 DD DISP=SHR,DSN=GENAPP.DDBARP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
