//VJOB2045 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLT01ZUW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN16 DD DISP=SHR,DSN=GENAPP.DDLTIN16.DATA
//DDLTOT16 DD DISP=SHR,DSN=GENAPP.DDLTOT16.DATA
//DDLTRP16 DD DISP=SHR,DSN=GENAPP.DDLTRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF01ZUX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN17 DD DISP=SHR,DSN=GENAPP.DDIFIN17.DATA
//DDIFOT17 DD DISP=SHR,DSN=GENAPP.DDIFOT17.DATA
//DDIFRP17 DD DISP=SHR,DSN=GENAPP.DDIFRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZST01ZUY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN18 DD DISP=SHR,DSN=GENAPP.DDSTIN18.DATA
//DDSTOT18 DD DISP=SHR,DSN=GENAPP.DDSTOT18.DATA
//DDSTRP18 DD DISP=SHR,DSN=GENAPP.DDSTRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
