//VJOB2218 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO0209B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN85 DD DISP=SHR,DSN=GENAPP.DDHOIN85.DATA
//DDHOOT85 DD DISP=SHR,DSN=GENAPP.DDHOOT85.DATA
//DDHORP85 DD DISP=SHR,DSN=GENAPP.DDHORP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA0209C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN86 DD DISP=SHR,DSN=GENAPP.DDMAIN86.DATA
//DDMAOT86 DD DISP=SHR,DSN=GENAPP.DDMAOT86.DATA
//DDMARP86 DD DISP=SHR,DSN=GENAPP.DDMARP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV0209D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN87 DD DISP=SHR,DSN=GENAPP.DDIVIN87.DATA
//DDIVOT87 DD DISP=SHR,DSN=GENAPP.DDIVOT87.DATA
//DDIVRP87 DD DISP=SHR,DSN=GENAPP.DDIVRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
