//VJOB1031 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX01XIE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN34 DD DISP=SHR,DSN=GENAPP.DDTXIN34.DATA
//DDTXOT34 DD DISP=SHR,DSN=GENAPP.DDTXOT34.DATA
//DDTXRP34 DD DISP=SHR,DSN=GENAPP.DDTXRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB01XIF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN35 DD DISP=SHR,DSN=GENAPP.DDLBIN35.DATA
//DDLBOT35 DD DISP=SHR,DSN=GENAPP.DDLBOT35.DATA
//DDLBRP35 DD DISP=SHR,DSN=GENAPP.DDLBRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZQU01XIG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN36 DD DISP=SHR,DSN=GENAPP.DDQUIN36.DATA
//DDQUOT36 DD DISP=SHR,DSN=GENAPP.DDQUOT36.DATA
//DDQURP36 DD DISP=SHR,DSN=GENAPP.DDQURP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
