//VJOB1163 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01XTE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN70 DD DISP=SHR,DSN=GENAPP.DDUWIN70.DATA
//DDUWOT70 DD DISP=SHR,DSN=GENAPP.DDUWOT70.DATA
//DDUWRP70 DD DISP=SHR,DSN=GENAPP.DDUWRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01XTF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN71 DD DISP=SHR,DSN=GENAPP.DDLIIN71.DATA
//DDLIOT71 DD DISP=SHR,DSN=GENAPP.DDLIOT71.DATA
//DDLIRP71 DD DISP=SHR,DSN=GENAPP.DDLIRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01XTG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN72 DD DISP=SHR,DSN=GENAPP.DDCLIN72.DATA
//DDCLOT72 DD DISP=SHR,DSN=GENAPP.DDCLOT72.DATA
//DDCLRP72 DD DISP=SHR,DSN=GENAPP.DDCLRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
