//VJOB4037 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE024GW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN52 DD DISP=SHR,DSN=GENAPP.DDPEIN52.DATA
//DDPEOT52 DD DISP=SHR,DSN=GENAPP.DDPEOT52.DATA
//DDPERP52 DD DISP=SHR,DSN=GENAPP.DDPERP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO024GX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN53 DD DISP=SHR,DSN=GENAPP.DDHOIN53.DATA
//DDHOOT53 DD DISP=SHR,DSN=GENAPP.DDHOOT53.DATA
//DDHORP53 DD DISP=SHR,DSN=GENAPP.DDHORP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE024GY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN54 DD DISP=SHR,DSN=GENAPP.DDHEIN54.DATA
//DDHEOT54 DD DISP=SHR,DSN=GENAPP.DDHEOT54.DATA
//DDHERP54 DD DISP=SHR,DSN=GENAPP.DDHERP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
