//VJOB3394 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO022ZB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN13 DD DISP=SHR,DSN=GENAPP.DDHOIN13.DATA
//DDHOOT13 DD DISP=SHR,DSN=GENAPP.DDHOOT13.DATA
//DDHORP13 DD DISP=SHR,DSN=GENAPP.DDHORP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE022ZC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN14 DD DISP=SHR,DSN=GENAPP.DDHEIN14.DATA
//DDHEOT14 DD DISP=SHR,DSN=GENAPP.DDHEOT14.DATA
//DDHERP14 DD DISP=SHR,DSN=GENAPP.DDHERP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN022ZD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN15 DD DISP=SHR,DSN=GENAPP.DDPNIN15.DATA
//DDPNOT15 DD DISP=SHR,DSN=GENAPP.DDPNOT15.DATA
//DDPNRP15 DD DISP=SHR,DSN=GENAPP.DDPNRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
