//VJOB1307 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL01Y5E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN52 DD DISP=SHR,DSN=GENAPP.DDFLIN52.DATA
//DDFLOT52 DD DISP=SHR,DSN=GENAPP.DDFLOT52.DATA
//DDFLRP52 DD DISP=SHR,DSN=GENAPP.DDFLRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB01Y5F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN53 DD DISP=SHR,DSN=GENAPP.DDLBIN53.DATA
//DDLBOT53 DD DISP=SHR,DSN=GENAPP.DDLBOT53.DATA
//DDLBRP53 DD DISP=SHR,DSN=GENAPP.DDLBRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR01Y5G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN54 DD DISP=SHR,DSN=GENAPP.DDARIN54.DATA
//DDAROT54 DD DISP=SHR,DSN=GENAPP.DDAROT54.DATA
//DDARRP54 DD DISP=SHR,DSN=GENAPP.DDARRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
