//VJOB3913 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN0246K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN40 DD DISP=SHR,DSN=GENAPP.DDANIN40.DATA
//DDANOT40 DD DISP=SHR,DSN=GENAPP.DDANOT40.DATA
//DDANRP40 DD DISP=SHR,DSN=GENAPP.DDANRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN0246L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN41 DD DISP=SHR,DSN=GENAPP.DDENIN41.DATA
//DDENOT41 DD DISP=SHR,DSN=GENAPP.DDENOT41.DATA
//DDENRP41 DD DISP=SHR,DSN=GENAPP.DDENRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO0246M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN42 DD DISP=SHR,DSN=GENAPP.DDHOIN42.DATA
//DDHOOT42 DD DISP=SHR,DSN=GENAPP.DDHOOT42.DATA
//DDHORP42 DD DISP=SHR,DSN=GENAPP.DDHORP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
