//VJOB0905 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01X7W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN16 DD DISP=SHR,DSN=GENAPP.DDCUIN16.DATA
//DDCUOT16 DD DISP=SHR,DSN=GENAPP.DDCUOT16.DATA
//DDCURP16 DD DISP=SHR,DSN=GENAPP.DDCURP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE01X7X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN17 DD DISP=SHR,DSN=GENAPP.DDPEIN17.DATA
//DDPEOT17 DD DISP=SHR,DSN=GENAPP.DDPEOT17.DATA
//DDPERP17 DD DISP=SHR,DSN=GENAPP.DDPERP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01X7Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN18 DD DISP=SHR,DSN=GENAPP.DDBIIN18.DATA
//DDBIOT18 DD DISP=SHR,DSN=GENAPP.DDBIOT18.DATA
//DDBIRP18 DD DISP=SHR,DSN=GENAPP.DDBIRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
