//VJOB4130 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC024ON
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN61 DD DISP=SHR,DSN=GENAPP.DDACIN61.DATA
//DDACOT61 DD DISP=SHR,DSN=GENAPP.DDACOT61.DATA
//DDACRP61 DD DISP=SHR,DSN=GENAPP.DDACRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR024OO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN62 DD DISP=SHR,DSN=GENAPP.DDTRIN62.DATA
//DDTROT62 DD DISP=SHR,DSN=GENAPP.DDTROT62.DATA
//DDTRRP62 DD DISP=SHR,DSN=GENAPP.DDTRRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTY024OP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN63 DD DISP=SHR,DSN=GENAPP.DDTYIN63.DATA
//DDTYOT63 DD DISP=SHR,DSN=GENAPP.DDTYOT63.DATA
//DDTYRP63 DD DISP=SHR,DSN=GENAPP.DDTYRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
