//VJOB2119 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRN02012
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN58 DD DISP=SHR,DSN=GENAPP.DDRNIN58.DATA
//DDRNOT58 DD DISP=SHR,DSN=GENAPP.DDRNOT58.DATA
//DDRNRP58 DD DISP=SHR,DSN=GENAPP.DDRNRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN02013
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN59 DD DISP=SHR,DSN=GENAPP.DDENIN59.DATA
//DDENOT59 DD DISP=SHR,DSN=GENAPP.DDENOT59.DATA
//DDENRP59 DD DISP=SHR,DSN=GENAPP.DDENRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAU02014
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN60 DD DISP=SHR,DSN=GENAPP.DDAUIN60.DATA
//DDAUOT60 DD DISP=SHR,DSN=GENAPP.DDAUOT60.DATA
//DDAURP60 DD DISP=SHR,DSN=GENAPP.DDAURP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
