//VJOB0887 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01X6E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN52 DD DISP=SHR,DSN=GENAPP.DDBIIN52.DATA
//DDBIOT52 DD DISP=SHR,DSN=GENAPP.DDBIOT52.DATA
//DDBIRP52 DD DISP=SHR,DSN=GENAPP.DDBIRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ01X6F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN53 DD DISP=SHR,DSN=GENAPP.DDAZIN53.DATA
//DDAZOT53 DD DISP=SHR,DSN=GENAPP.DDAZOT53.DATA
//DDAZRP53 DD DISP=SHR,DSN=GENAPP.DDAZRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI01X6G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN54 DD DISP=SHR,DSN=GENAPP.DDLIIN54.DATA
//DDLIOT54 DD DISP=SHR,DSN=GENAPP.DDLIOT54.DATA
//DDLIRP54 DD DISP=SHR,DSN=GENAPP.DDLIRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
