//VJOB3893 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC0244W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN70 DD DISP=SHR,DSN=GENAPP.DDACIN70.DATA
//DDACOT70 DD DISP=SHR,DSN=GENAPP.DDACOT70.DATA
//DDACRP70 DD DISP=SHR,DSN=GENAPP.DDACRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG0244X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN71 DD DISP=SHR,DSN=GENAPP.DDRGIN71.DATA
//DDRGOT71 DD DISP=SHR,DSN=GENAPP.DDRGOT71.DATA
//DDRGRP71 DD DISP=SHR,DSN=GENAPP.DDRGRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI0244Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN72 DD DISP=SHR,DSN=GENAPP.DDBIIN72.DATA
//DDBIOT72 DD DISP=SHR,DSN=GENAPP.DDBIOT72.DATA
//DDBIRP72 DD DISP=SHR,DSN=GENAPP.DDBIRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
