//VJOB0358 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE01VYB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN85 DD DISP=SHR,DSN=GENAPP.DDHEIN85.DATA
//DDHEOT85 DD DISP=SHR,DSN=GENAPP.DDHEOT85.DATA
//DDHERP85 DD DISP=SHR,DSN=GENAPP.DDHERP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01VYC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN86 DD DISP=SHR,DSN=GENAPP.DDPAIN86.DATA
//DDPAOT86 DD DISP=SHR,DSN=GENAPP.DDPAOT86.DATA
//DDPARP86 DD DISP=SHR,DSN=GENAPP.DDPARP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01VYD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN87 DD DISP=SHR,DSN=GENAPP.DDREIN87.DATA
//DDREOT87 DD DISP=SHR,DSN=GENAPP.DDREOT87.DATA
//DDRERP87 DD DISP=SHR,DSN=GENAPP.DDRERP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
