//VJOB3466 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC0235B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN49 DD DISP=SHR,DSN=GENAPP.DDRCIN49.DATA
//DDRCOT49 DD DISP=SHR,DSN=GENAPP.DDRCOT49.DATA
//DDRCRP49 DD DISP=SHR,DSN=GENAPP.DDRCRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA0235C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN50 DD DISP=SHR,DSN=GENAPP.DDMAIN50.DATA
//DDMAOT50 DD DISP=SHR,DSN=GENAPP.DDMAOT50.DATA
//DDMARP50 DD DISP=SHR,DSN=GENAPP.DDMARP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC0235D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN51 DD DISP=SHR,DSN=GENAPP.DDACIN51.DATA
//DDACOT51 DD DISP=SHR,DSN=GENAPP.DDACOT51.DATA
//DDACRP51 DD DISP=SHR,DSN=GENAPP.DDACRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
