//VJOB0837 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC01X28
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN82 DD DISP=SHR,DSN=GENAPP.DDRCIN82.DATA
//DDRCOT82 DD DISP=SHR,DSN=GENAPP.DDRCOT82.DATA
//DDRCRP82 DD DISP=SHR,DSN=GENAPP.DDRCRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01X29
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN83 DD DISP=SHR,DSN=GENAPP.DDFLIN83.DATA
//DDFLOT83 DD DISP=SHR,DSN=GENAPP.DDFLOT83.DATA
//DDFLRP83 DD DISP=SHR,DSN=GENAPP.DDFLRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV01X2A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN84 DD DISP=SHR,DSN=GENAPP.DDIVIN84.DATA
//DDIVOT84 DD DISP=SHR,DSN=GENAPP.DDIVOT84.DATA
//DDIVRP84 DD DISP=SHR,DSN=GENAPP.DDIVRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
