//VJOB0048 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR01V8H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN55 DD DISP=SHR,DSN=GENAPP.DDFRIN55.DATA
//DDFROT55 DD DISP=SHR,DSN=GENAPP.DDFROT55.DATA
//DDFRRP55 DD DISP=SHR,DSN=GENAPP.DDFRRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01V8I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN56 DD DISP=SHR,DSN=GENAPP.DDFLIN56.DATA
//DDFLOT56 DD DISP=SHR,DSN=GENAPP.DDFLOT56.DATA
//DDFLRP56 DD DISP=SHR,DSN=GENAPP.DDFLRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA01V8J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN57 DD DISP=SHR,DSN=GENAPP.DDPAIN57.DATA
//DDPAOT57 DD DISP=SHR,DSN=GENAPP.DDPAOT57.DATA
//DDPARP57 DD DISP=SHR,DSN=GENAPP.DDPARP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
