//VJOB3792 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR023WH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN37 DD DISP=SHR,DSN=GENAPP.DDTRIN37.DATA
//DDTROT37 DD DISP=SHR,DSN=GENAPP.DDTROT37.DATA
//DDTRRP37 DD DISP=SHR,DSN=GENAPP.DDTRRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE023WI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN38 DD DISP=SHR,DSN=GENAPP.DDHEIN38.DATA
//DDHEOT38 DD DISP=SHR,DSN=GENAPP.DDHEOT38.DATA
//DDHERP38 DD DISP=SHR,DSN=GENAPP.DDHERP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL023WJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN39 DD DISP=SHR,DSN=GENAPP.DDCLIN39.DATA
//DDCLOT39 DD DISP=SHR,DSN=GENAPP.DDCLOT39.DATA
//DDCLRP39 DD DISP=SHR,DSN=GENAPP.DDCLRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
