//VJOB1370 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01YAN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN61 DD DISP=SHR,DSN=GENAPP.DDMTIN61.DATA
//DDMTOT61 DD DISP=SHR,DSN=GENAPP.DDMTOT61.DATA
//DDMTRP61 DD DISP=SHR,DSN=GENAPP.DDMTRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01YAO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN62 DD DISP=SHR,DSN=GENAPP.DDBIIN62.DATA
//DDBIOT62 DD DISP=SHR,DSN=GENAPP.DDBIOT62.DATA
//DDBIRP62 DD DISP=SHR,DSN=GENAPP.DDBIRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01YAP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN63 DD DISP=SHR,DSN=GENAPP.DDCLIN63.DATA
//DDCLOT63 DD DISP=SHR,DSN=GENAPP.DDCLOT63.DATA
//DDCLRP63 DD DISP=SHR,DSN=GENAPP.DDCLRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
