//VJOB4070 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC024JN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN61 DD DISP=SHR,DSN=GENAPP.DDRCIN61.DATA
//DDRCOT61 DD DISP=SHR,DSN=GENAPP.DDRCOT61.DATA
//DDRCRP61 DD DISP=SHR,DSN=GENAPP.DDRCRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZED024JO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN62 DD DISP=SHR,DSN=GENAPP.DDEDIN62.DATA
//DDEDOT62 DD DISP=SHR,DSN=GENAPP.DDEDOT62.DATA
//DDEDRP62 DD DISP=SHR,DSN=GENAPP.DDEDRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG024JP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN63 DD DISP=SHR,DSN=GENAPP.DDAGIN63.DATA
//DDAGOT63 DD DISP=SHR,DSN=GENAPP.DDAGOT63.DATA
//DDAGRP63 DD DISP=SHR,DSN=GENAPP.DDAGRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
