//VJOB2338 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG020JB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN85 DD DISP=SHR,DSN=GENAPP.DDAGIN85.DATA
//DDAGOT85 DD DISP=SHR,DSN=GENAPP.DDAGOT85.DATA
//DDAGRP85 DD DISP=SHR,DSN=GENAPP.DDAGRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC020JC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN86 DD DISP=SHR,DSN=GENAPP.DDSCIN86.DATA
//DDSCOT86 DD DISP=SHR,DSN=GENAPP.DDSCOT86.DATA
//DDSCRP86 DD DISP=SHR,DSN=GENAPP.DDSCRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG020JD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN87 DD DISP=SHR,DSN=GENAPP.DDAGIN87.DATA
//DDAGOT87 DD DISP=SHR,DSN=GENAPP.DDAGOT87.DATA
//DDAGRP87 DD DISP=SHR,DSN=GENAPP.DDAGRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
