//VJOB3016 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR0223T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN49 DD DISP=SHR,DSN=GENAPP.DDTRIN49.DATA
//DDTROT49 DD DISP=SHR,DSN=GENAPP.DDTROT49.DATA
//DDTRRP49 DD DISP=SHR,DSN=GENAPP.DDTRRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG0223U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN50 DD DISP=SHR,DSN=GENAPP.DDAGIN50.DATA
//DDAGOT50 DD DISP=SHR,DSN=GENAPP.DDAGOT50.DATA
//DDAGRP50 DD DISP=SHR,DSN=GENAPP.DDAGRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE0223V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN51 DD DISP=SHR,DSN=GENAPP.DDREIN51.DATA
//DDREOT51 DD DISP=SHR,DSN=GENAPP.DDREOT51.DATA
//DDRERP51 DD DISP=SHR,DSN=GENAPP.DDRERP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
