//VJOB2698 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV021DB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN85 DD DISP=SHR,DSN=GENAPP.DDAVIN85.DATA
//DDAVOT85 DD DISP=SHR,DSN=GENAPP.DDAVOT85.DATA
//DDAVRP85 DD DISP=SHR,DSN=GENAPP.DDAVRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY021DC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN86 DD DISP=SHR,DSN=GENAPP.DDTYIN86.DATA
//DDTYOT86 DD DISP=SHR,DSN=GENAPP.DDTYOT86.DATA
//DDTYRP86 DD DISP=SHR,DSN=GENAPP.DDTYRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLT021DD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN87 DD DISP=SHR,DSN=GENAPP.DDLTIN87.DATA
//DDLTOT87 DD DISP=SHR,DSN=GENAPP.DDLTOT87.DATA
//DDLTRP87 DD DISP=SHR,DSN=GENAPP.DDLTRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
