//VJOB1471 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT01YJ2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN04 DD DISP=SHR,DSN=GENAPP.DDPTIN04.DATA
//DDPTOT04 DD DISP=SHR,DSN=GENAPP.DDPTOT04.DATA
//DDPTRP04 DD DISP=SHR,DSN=GENAPP.DDPTRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01YJ3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN05 DD DISP=SHR,DSN=GENAPP.DDMTIN05.DATA
//DDMTOT05 DD DISP=SHR,DSN=GENAPP.DDMTOT05.DATA
//DDMTRP05 DD DISP=SHR,DSN=GENAPP.DDMTRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01YJ4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN06 DD DISP=SHR,DSN=GENAPP.DDHOIN06.DATA
//DDHOOT06 DD DISP=SHR,DSN=GENAPP.DDHOOT06.DATA
//DDHORP06 DD DISP=SHR,DSN=GENAPP.DDHORP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
