//VJOB2986 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO0221B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN49 DD DISP=SHR,DSN=GENAPP.DDHOIN49.DATA
//DDHOOT49 DD DISP=SHR,DSN=GENAPP.DDHOOT49.DATA
//DDHORP49 DD DISP=SHR,DSN=GENAPP.DDHORP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC0221C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN50 DD DISP=SHR,DSN=GENAPP.DDSCIN50.DATA
//DDSCOT50 DD DISP=SHR,DSN=GENAPP.DDSCOT50.DATA
//DDSCRP50 DD DISP=SHR,DSN=GENAPP.DDSCRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDI0221D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN51 DD DISP=SHR,DSN=GENAPP.DDDIIN51.DATA
//DDDIOT51 DD DISP=SHR,DSN=GENAPP.DDDIOT51.DATA
//DDDIRP51 DD DISP=SHR,DSN=GENAPP.DDDIRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
