//VJOB3823 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB023Z2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN40 DD DISP=SHR,DSN=GENAPP.DDLBIN40.DATA
//DDLBOT40 DD DISP=SHR,DSN=GENAPP.DDLBOT40.DATA
//DDLBRP40 DD DISP=SHR,DSN=GENAPP.DDLBRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX023Z3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN41 DD DISP=SHR,DSN=GENAPP.DDTXIN41.DATA
//DDTXOT41 DD DISP=SHR,DSN=GENAPP.DDTXOT41.DATA
//DDTXRP41 DD DISP=SHR,DSN=GENAPP.DDTXRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS023Z4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN42 DD DISP=SHR,DSN=GENAPP.DDRSIN42.DATA
//DDRSOT42 DD DISP=SHR,DSN=GENAPP.DDRSOT42.DATA
//DDRSRP42 DD DISP=SHR,DSN=GENAPP.DDRSRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
