//VJOB3425 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE0231W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN16 DD DISP=SHR,DSN=GENAPP.DDHEIN16.DATA
//DDHEOT16 DD DISP=SHR,DSN=GENAPP.DDHEOT16.DATA
//DDHERP16 DD DISP=SHR,DSN=GENAPP.DDHERP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN0231X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN17 DD DISP=SHR,DSN=GENAPP.DDPNIN17.DATA
//DDPNOT17 DD DISP=SHR,DSN=GENAPP.DDPNOT17.DATA
//DDPNRP17 DD DISP=SHR,DSN=GENAPP.DDPNRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSB0231Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN18 DD DISP=SHR,DSN=GENAPP.DDSBIN18.DATA
//DDSBOT18 DD DISP=SHR,DSN=GENAPP.DDSBOT18.DATA
//DDSBRP18 DD DISP=SHR,DSN=GENAPP.DDSBRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
