//VJOB1195 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01XW2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN76 DD DISP=SHR,DSN=GENAPP.DDMTIN76.DATA
//DDMTOT76 DD DISP=SHR,DSN=GENAPP.DDMTOT76.DATA
//DDMTRP76 DD DISP=SHR,DSN=GENAPP.DDMTRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR01XW3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN77 DD DISP=SHR,DSN=GENAPP.DDBRIN77.DATA
//DDBROT77 DD DISP=SHR,DSN=GENAPP.DDBROT77.DATA
//DDBRRP77 DD DISP=SHR,DSN=GENAPP.DDBRRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01XW4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN78 DD DISP=SHR,DSN=GENAPP.DDENIN78.DATA
//DDENOT78 DD DISP=SHR,DSN=GENAPP.DDENOT78.DATA
//DDENRP78 DD DISP=SHR,DSN=GENAPP.DDENRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
