//VJOB3571 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA023E2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN04 DD DISP=SHR,DSN=GENAPP.DDBAIN04.DATA
//DDBAOT04 DD DISP=SHR,DSN=GENAPP.DDBAOT04.DATA
//DDBARP04 DD DISP=SHR,DSN=GENAPP.DDBARP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZED023E3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN05 DD DISP=SHR,DSN=GENAPP.DDEDIN05.DATA
//DDEDOT05 DD DISP=SHR,DSN=GENAPP.DDEDOT05.DATA
//DDEDRP05 DD DISP=SHR,DSN=GENAPP.DDEDRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCP023E4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN06 DD DISP=SHR,DSN=GENAPP.DDCPIN06.DATA
//DDCPOT06 DD DISP=SHR,DSN=GENAPP.DDCPOT06.DATA
//DDCPRP06 DD DISP=SHR,DSN=GENAPP.DDCPRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
