//VJOB0107 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01VDE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN52 DD DISP=SHR,DSN=GENAPP.DDMTIN52.DATA
//DDMTOT52 DD DISP=SHR,DSN=GENAPP.DDMTOT52.DATA
//DDMTRP52 DD DISP=SHR,DSN=GENAPP.DDMTRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN01VDF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN53 DD DISP=SHR,DSN=GENAPP.DDENIN53.DATA
//DDENOT53 DD DISP=SHR,DSN=GENAPP.DDENOT53.DATA
//DDENRP53 DD DISP=SHR,DSN=GENAPP.DDENRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01VDG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN54 DD DISP=SHR,DSN=GENAPP.DDCUIN54.DATA
//DDCUOT54 DD DISP=SHR,DSN=GENAPP.DDCUOT54.DATA
//DDCURP54 DD DISP=SHR,DSN=GENAPP.DDCURP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
