//VJOB2315 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI020HE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN16 DD DISP=SHR,DSN=GENAPP.DDBIIN16.DATA
//DDBIOT16 DD DISP=SHR,DSN=GENAPP.DDBIOT16.DATA
//DDBIRP16 DD DISP=SHR,DSN=GENAPP.DDBIRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPT020HF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN17 DD DISP=SHR,DSN=GENAPP.DDPTIN17.DATA
//DDPTOT17 DD DISP=SHR,DSN=GENAPP.DDPTOT17.DATA
//DDPTRP17 DD DISP=SHR,DSN=GENAPP.DDPTRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU020HG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN18 DD DISP=SHR,DSN=GENAPP.DDCUIN18.DATA
//DDCUOT18 DD DISP=SHR,DSN=GENAPP.DDCUOT18.DATA
//DDCURP18 DD DISP=SHR,DSN=GENAPP.DDCURP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
