//VJOB3054 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC0226Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN73 DD DISP=SHR,DSN=GENAPP.DDRCIN73.DATA
//DDRCOT73 DD DISP=SHR,DSN=GENAPP.DDRCOT73.DATA
//DDRCRP73 DD DISP=SHR,DSN=GENAPP.DDRCRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA02270
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN74 DD DISP=SHR,DSN=GENAPP.DDBAIN74.DATA
//DDBAOT74 DD DISP=SHR,DSN=GENAPP.DDBAOT74.DATA
//DDBARP74 DD DISP=SHR,DSN=GENAPP.DDBARP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCP02271
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN75 DD DISP=SHR,DSN=GENAPP.DDCPIN75.DATA
//DDCPOT75 DD DISP=SHR,DSN=GENAPP.DDCPOT75.DATA
//DDCPRP75 DD DISP=SHR,DSN=GENAPP.DDCPRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
