//VJOB2189 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG0206W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN88 DD DISP=SHR,DSN=GENAPP.DDRGIN88.DATA
//DDRGOT88 DD DISP=SHR,DSN=GENAPP.DDRGOT88.DATA
//DDRGRP88 DD DISP=SHR,DSN=GENAPP.DDRGRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0206X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN89 DD DISP=SHR,DSN=GENAPP.DDMTIN89.DATA
//DDMTOT89 DD DISP=SHR,DSN=GENAPP.DDMTOT89.DATA
//DDMTRP89 DD DISP=SHR,DSN=GENAPP.DDMTRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPL0206Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN90 DD DISP=SHR,DSN=GENAPP.DDPLIN90.DATA
//DDPLOT90 DD DISP=SHR,DSN=GENAPP.DDPLOT90.DATA
//DDPLRP90 DD DISP=SHR,DSN=GENAPP.DDPLRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
