//VJOB1825 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01ZCK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN76 DD DISP=SHR,DSN=GENAPP.DDHOIN76.DATA
//DDHOOT76 DD DISP=SHR,DSN=GENAPP.DDHOOT76.DATA
//DDHORP76 DD DISP=SHR,DSN=GENAPP.DDHORP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN01ZCL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN77 DD DISP=SHR,DSN=GENAPP.DDENIN77.DATA
//DDENOT77 DD DISP=SHR,DSN=GENAPP.DDENOT77.DATA
//DDENRP77 DD DISP=SHR,DSN=GENAPP.DDENRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01ZCM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN78 DD DISP=SHR,DSN=GENAPP.DDREIN78.DATA
//DDREOT78 DD DISP=SHR,DSN=GENAPP.DDREOT78.DATA
//DDRERP78 DD DISP=SHR,DSN=GENAPP.DDRERP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
