//VJOB3385 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE022YK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN76 DD DISP=SHR,DSN=GENAPP.DDSEIN76.DATA
//DDSEOT76 DD DISP=SHR,DSN=GENAPP.DDSEOT76.DATA
//DDSERP76 DD DISP=SHR,DSN=GENAPP.DDSERP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL022YL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN77 DD DISP=SHR,DSN=GENAPP.DDCLIN77.DATA
//DDCLOT77 DD DISP=SHR,DSN=GENAPP.DDCLOT77.DATA
//DDCLRP77 DD DISP=SHR,DSN=GENAPP.DDCLRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV022YM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN78 DD DISP=SHR,DSN=GENAPP.DDAVIN78.DATA
//DDAVOT78 DD DISP=SHR,DSN=GENAPP.DDAVOT78.DATA
//DDAVRP78 DD DISP=SHR,DSN=GENAPP.DDAVRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
