//VJOB4044 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC024HH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN73 DD DISP=SHR,DSN=GENAPP.DDACIN73.DATA
//DDACOT73 DD DISP=SHR,DSN=GENAPP.DDACOT73.DATA
//DDACRP73 DD DISP=SHR,DSN=GENAPP.DDACRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO024HI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN74 DD DISP=SHR,DSN=GENAPP.DDHOIN74.DATA
//DDHOOT74 DD DISP=SHR,DSN=GENAPP.DDHOOT74.DATA
//DDHORP74 DD DISP=SHR,DSN=GENAPP.DDHORP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG024HJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN75 DD DISP=SHR,DSN=GENAPP.DDRGIN75.DATA
//DDRGOT75 DD DISP=SHR,DSN=GENAPP.DDRGOT75.DATA
//DDRGRP75 DD DISP=SHR,DSN=GENAPP.DDRGRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
