//VJOB1317 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS01Y68
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN82 DD DISP=SHR,DSN=GENAPP.DDRSIN82.DATA
//DDRSOT82 DD DISP=SHR,DSN=GENAPP.DDRSOT82.DATA
//DDRSRP82 DD DISP=SHR,DSN=GENAPP.DDRSRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01Y69
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN83 DD DISP=SHR,DSN=GENAPP.DDCLIN83.DATA
//DDCLOT83 DD DISP=SHR,DSN=GENAPP.DDCLOT83.DATA
//DDCLRP83 DD DISP=SHR,DSN=GENAPP.DDCLRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR01Y6A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN84 DD DISP=SHR,DSN=GENAPP.DDARIN84.DATA
//DDAROT84 DD DISP=SHR,DSN=GENAPP.DDAROT84.DATA
//DDARRP84 DD DISP=SHR,DSN=GENAPP.DDARRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
