//VJOB1871 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT01ZGE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN34 DD DISP=SHR,DSN=GENAPP.DDPTIN34.DATA
//DDPTOT34 DD DISP=SHR,DSN=GENAPP.DDPTOT34.DATA
//DDPTRP34 DD DISP=SHR,DSN=GENAPP.DDPTRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN01ZGF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN35 DD DISP=SHR,DSN=GENAPP.DDANIN35.DATA
//DDANOT35 DD DISP=SHR,DSN=GENAPP.DDANOT35.DATA
//DDANRP35 DD DISP=SHR,DSN=GENAPP.DDANRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL01ZGG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN36 DD DISP=SHR,DSN=GENAPP.DDFLIN36.DATA
//DDFLOT36 DD DISP=SHR,DSN=GENAPP.DDFLOT36.DATA
//DDFLRP36 DD DISP=SHR,DSN=GENAPP.DDFLRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
