//VJOB4175 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU024SE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN16 DD DISP=SHR,DSN=GENAPP.DDCUIN16.DATA
//DDCUOT16 DD DISP=SHR,DSN=GENAPP.DDCUOT16.DATA
//DDCURP16 DD DISP=SHR,DSN=GENAPP.DDCURP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW024SF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN17 DD DISP=SHR,DSN=GENAPP.DDUWIN17.DATA
//DDUWOT17 DD DISP=SHR,DSN=GENAPP.DDUWOT17.DATA
//DDUWRP17 DD DISP=SHR,DSN=GENAPP.DDUWRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDO024SG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN18 DD DISP=SHR,DSN=GENAPP.DDDOIN18.DATA
//DDDOOT18 DD DISP=SHR,DSN=GENAPP.DDDOOT18.DATA
//DDDORP18 DD DISP=SHR,DSN=GENAPP.DDDORP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
