//VJOB1548 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA01YPH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN55 DD DISP=SHR,DSN=GENAPP.DDMAIN55.DATA
//DDMAOT55 DD DISP=SHR,DSN=GENAPP.DDMAOT55.DATA
//DDMARP55 DD DISP=SHR,DSN=GENAPP.DDMARP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY01YPI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN56 DD DISP=SHR,DSN=GENAPP.DDTYIN56.DATA
//DDTYOT56 DD DISP=SHR,DSN=GENAPP.DDTYOT56.DATA
//DDTYRP56 DD DISP=SHR,DSN=GENAPP.DDTYRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01YPJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN57 DD DISP=SHR,DSN=GENAPP.DDHOIN57.DATA
//DDHOOT57 DD DISP=SHR,DSN=GENAPP.DDHOOT57.DATA
//DDHORP57 DD DISP=SHR,DSN=GENAPP.DDHORP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
