//VJOB3273 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE022P8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN10 DD DISP=SHR,DSN=GENAPP.DDREIN10.DATA
//DDREOT10 DD DISP=SHR,DSN=GENAPP.DDREOT10.DATA
//DDRERP10 DD DISP=SHR,DSN=GENAPP.DDRERP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO022P9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN11 DD DISP=SHR,DSN=GENAPP.DDHOIN11.DATA
//DDHOOT11 DD DISP=SHR,DSN=GENAPP.DDHOOT11.DATA
//DDHORP11 DD DISP=SHR,DSN=GENAPP.DDHORP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN022PA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN12 DD DISP=SHR,DSN=GENAPP.DDENIN12.DATA
//DDENOT12 DD DISP=SHR,DSN=GENAPP.DDENOT12.DATA
//DDENRP12 DD DISP=SHR,DSN=GENAPP.DDENRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
