//VJOB2431 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP020R2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN04 DD DISP=SHR,DSN=GENAPP.DDCPIN04.DATA
//DDCPOT04 DD DISP=SHR,DSN=GENAPP.DDCPOT04.DATA
//DDCPRP04 DD DISP=SHR,DSN=GENAPP.DDCPRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRC020R3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN05 DD DISP=SHR,DSN=GENAPP.DDRCIN05.DATA
//DDRCOT05 DD DISP=SHR,DSN=GENAPP.DDRCOT05.DATA
//DDRCRP05 DD DISP=SHR,DSN=GENAPP.DDRCRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO020R4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN06 DD DISP=SHR,DSN=GENAPP.DDHOIN06.DATA
//DDHOOT06 DD DISP=SHR,DSN=GENAPP.DDHOOT06.DATA
//DDHORP06 DD DISP=SHR,DSN=GENAPP.DDHORP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
