//VJOB2344 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO020JT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN13 DD DISP=SHR,DSN=GENAPP.DDHOIN13.DATA
//DDHOOT13 DD DISP=SHR,DSN=GENAPP.DDHOOT13.DATA
//DDHORP13 DD DISP=SHR,DSN=GENAPP.DDHORP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO020JU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN14 DD DISP=SHR,DSN=GENAPP.DDHOIN14.DATA
//DDHOOT14 DD DISP=SHR,DSN=GENAPP.DDHOOT14.DATA
//DDHORP14 DD DISP=SHR,DSN=GENAPP.DDHORP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCR020JV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN15 DD DISP=SHR,DSN=GENAPP.DDCRIN15.DATA
//DDCROT15 DD DISP=SHR,DSN=GENAPP.DDCROT15.DATA
//DDCRRP15 DD DISP=SHR,DSN=GENAPP.DDCRRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
