//VJOB2343 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLT020JQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN10 DD DISP=SHR,DSN=GENAPP.DDLTIN10.DATA
//DDLTOT10 DD DISP=SHR,DSN=GENAPP.DDLTOT10.DATA
//DDLTRP10 DD DISP=SHR,DSN=GENAPP.DDLTRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZED020JR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN11 DD DISP=SHR,DSN=GENAPP.DDEDIN11.DATA
//DDEDOT11 DD DISP=SHR,DSN=GENAPP.DDEDOT11.DATA
//DDEDRP11 DD DISP=SHR,DSN=GENAPP.DDEDRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR020JS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN12 DD DISP=SHR,DSN=GENAPP.DDTRIN12.DATA
//DDTROT12 DD DISP=SHR,DSN=GENAPP.DDTROT12.DATA
//DDTRRP12 DD DISP=SHR,DSN=GENAPP.DDTRRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
