//VJOB1989 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01ZQ8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN28 DD DISP=SHR,DSN=GENAPP.DDMTIN28.DATA
//DDMTOT28 DD DISP=SHR,DSN=GENAPP.DDMTOT28.DATA
//DDMTRP28 DD DISP=SHR,DSN=GENAPP.DDMTRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRS01ZQ9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN29 DD DISP=SHR,DSN=GENAPP.DDRSIN29.DATA
//DDRSOT29 DD DISP=SHR,DSN=GENAPP.DDRSOT29.DATA
//DDRSRP29 DD DISP=SHR,DSN=GENAPP.DDRSRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01ZQA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN30 DD DISP=SHR,DSN=GENAPP.DDREIN30.DATA
//DDREOT30 DD DISP=SHR,DSN=GENAPP.DDREOT30.DATA
//DDRERP30 DD DISP=SHR,DSN=GENAPP.DDRERP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
