//VJOB2257 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPR020CK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN22 DD DISP=SHR,DSN=GENAPP.DDPRIN22.DATA
//DDPROT22 DD DISP=SHR,DSN=GENAPP.DDPROT22.DATA
//DDPRRP22 DD DISP=SHR,DSN=GENAPP.DDPRRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV020CL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN23 DD DISP=SHR,DSN=GENAPP.DDIVIN23.DATA
//DDIVOT23 DD DISP=SHR,DSN=GENAPP.DDIVOT23.DATA
//DDIVRP23 DD DISP=SHR,DSN=GENAPP.DDIVRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI020CM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN24 DD DISP=SHR,DSN=GENAPP.DDBIIN24.DATA
//DDBIOT24 DD DISP=SHR,DSN=GENAPP.DDBIOT24.DATA
//DDBIRP24 DD DISP=SHR,DSN=GENAPP.DDBIRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
