//VJOB2101 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE01ZZK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN04 DD DISP=SHR,DSN=GENAPP.DDREIN04.DATA
//DDREOT04 DD DISP=SHR,DSN=GENAPP.DDREOT04.DATA
//DDRERP04 DD DISP=SHR,DSN=GENAPP.DDRERP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01ZZL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN05 DD DISP=SHR,DSN=GENAPP.DDCLIN05.DATA
//DDCLOT05 DD DISP=SHR,DSN=GENAPP.DDCLOT05.DATA
//DDCLRP05 DD DISP=SHR,DSN=GENAPP.DDCLRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR01ZZM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN06 DD DISP=SHR,DSN=GENAPP.DDBRIN06.DATA
//DDBROT06 DD DISP=SHR,DSN=GENAPP.DDBROT06.DATA
//DDBRRP06 DD DISP=SHR,DSN=GENAPP.DDBRRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
