//VJOB3542 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZED023BN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN07 DD DISP=SHR,DSN=GENAPP.DDEDIN07.DATA
//DDEDOT07 DD DISP=SHR,DSN=GENAPP.DDEDOT07.DATA
//DDEDRP07 DD DISP=SHR,DSN=GENAPP.DDEDRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPL023BO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN08 DD DISP=SHR,DSN=GENAPP.DDPLIN08.DATA
//DDPLOT08 DD DISP=SHR,DSN=GENAPP.DDPLOT08.DATA
//DDPLRP08 DD DISP=SHR,DSN=GENAPP.DDPLRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT023BP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN09 DD DISP=SHR,DSN=GENAPP.DDMTIN09.DATA
//DDMTOT09 DD DISP=SHR,DSN=GENAPP.DDMTOT09.DATA
//DDMTRP09 DD DISP=SHR,DSN=GENAPP.DDMTRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
