//VJOB1298 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA01Y4N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN25 DD DISP=SHR,DSN=GENAPP.DDPAIN25.DATA
//DDPAOT25 DD DISP=SHR,DSN=GENAPP.DDPAOT25.DATA
//DDPARP25 DD DISP=SHR,DSN=GENAPP.DDPARP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN01Y4O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN26 DD DISP=SHR,DSN=GENAPP.DDANIN26.DATA
//DDANOT26 DD DISP=SHR,DSN=GENAPP.DDANOT26.DATA
//DDANRP26 DD DISP=SHR,DSN=GENAPP.DDANRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSU01Y4P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN27 DD DISP=SHR,DSN=GENAPP.DDSUIN27.DATA
//DDSUOT27 DD DISP=SHR,DSN=GENAPP.DDSUOT27.DATA
//DDSURP27 DD DISP=SHR,DSN=GENAPP.DDSURP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
