//VJOB1427 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01YFE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN52 DD DISP=SHR,DSN=GENAPP.DDHOIN52.DATA
//DDHOOT52 DD DISP=SHR,DSN=GENAPP.DDHOOT52.DATA
//DDHORP52 DD DISP=SHR,DSN=GENAPP.DDHORP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01YFF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN53 DD DISP=SHR,DSN=GENAPP.DDMTIN53.DATA
//DDMTOT53 DD DISP=SHR,DSN=GENAPP.DDMTOT53.DATA
//DDMTRP53 DD DISP=SHR,DSN=GENAPP.DDMTRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01YFG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN54 DD DISP=SHR,DSN=GENAPP.DDHOIN54.DATA
//DDHOOT54 DD DISP=SHR,DSN=GENAPP.DDHOOT54.DATA
//DDHORP54 DD DISP=SHR,DSN=GENAPP.DDHORP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
