//VJOB2604 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT0215H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN73 DD DISP=SHR,DSN=GENAPP.DDMTIN73.DATA
//DDMTOT73 DD DISP=SHR,DSN=GENAPP.DDMTOT73.DATA
//DDMTRP73 DD DISP=SHR,DSN=GENAPP.DDMTRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN0215I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN74 DD DISP=SHR,DSN=GENAPP.DDENIN74.DATA
//DDENOT74 DD DISP=SHR,DSN=GENAPP.DDENOT74.DATA
//DDENRP74 DD DISP=SHR,DSN=GENAPP.DDENRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI0215J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN75 DD DISP=SHR,DSN=GENAPP.DDBIIN75.DATA
//DDBIOT75 DD DISP=SHR,DSN=GENAPP.DDBIOT75.DATA
//DDBIRP75 DD DISP=SHR,DSN=GENAPP.DDBIRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
