//VJOB3256 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV022NT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN49 DD DISP=SHR,DSN=GENAPP.DDAVIN49.DATA
//DDAVOT49 DD DISP=SHR,DSN=GENAPP.DDAVOT49.DATA
//DDAVRP49 DD DISP=SHR,DSN=GENAPP.DDAVRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT022NU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN50 DD DISP=SHR,DSN=GENAPP.DDNTIN50.DATA
//DDNTOT50 DD DISP=SHR,DSN=GENAPP.DDNTOT50.DATA
//DDNTRP50 DD DISP=SHR,DSN=GENAPP.DDNTRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR022NV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN51 DD DISP=SHR,DSN=GENAPP.DDPRIN51.DATA
//DDPROT51 DD DISP=SHR,DSN=GENAPP.DDPROT51.DATA
//DDPRRP51 DD DISP=SHR,DSN=GENAPP.DDPRRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
