//VJOB4310 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE0253N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN61 DD DISP=SHR,DSN=GENAPP.DDSEIN61.DATA
//DDSEOT61 DD DISP=SHR,DSN=GENAPP.DDSEOT61.DATA
//DDSERP61 DD DISP=SHR,DSN=GENAPP.DDSERP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE0253O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN62 DD DISP=SHR,DSN=GENAPP.DDREIN62.DATA
//DDREOT62 DD DISP=SHR,DSN=GENAPP.DDREOT62.DATA
//DDRERP62 DD DISP=SHR,DSN=GENAPP.DDRERP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAU0253P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN63 DD DISP=SHR,DSN=GENAPP.DDAUIN63.DATA
//DDAUOT63 DD DISP=SHR,DSN=GENAPP.DDAUOT63.DATA
//DDAURP63 DD DISP=SHR,DSN=GENAPP.DDAURP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
