//VJOB2841 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA021P8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN64 DD DISP=SHR,DSN=GENAPP.DDMAIN64.DATA
//DDMAOT64 DD DISP=SHR,DSN=GENAPP.DDMAOT64.DATA
//DDMARP64 DD DISP=SHR,DSN=GENAPP.DDMARP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN021P9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN65 DD DISP=SHR,DSN=GENAPP.DDENIN65.DATA
//DDENOT65 DD DISP=SHR,DSN=GENAPP.DDENOT65.DATA
//DDENRP65 DD DISP=SHR,DSN=GENAPP.DDENRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR021PA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN66 DD DISP=SHR,DSN=GENAPP.DDPRIN66.DATA
//DDPROT66 DD DISP=SHR,DSN=GENAPP.DDPROT66.DATA
//DDPRRP66 DD DISP=SHR,DSN=GENAPP.DDPRRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
