//VJOB0079 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB01VB2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN58 DD DISP=SHR,DSN=GENAPP.DDLBIN58.DATA
//DDLBOT58 DD DISP=SHR,DSN=GENAPP.DDLBOT58.DATA
//DDLBRP58 DD DISP=SHR,DSN=GENAPP.DDLBRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01VB3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN59 DD DISP=SHR,DSN=GENAPP.DDHOIN59.DATA
//DDHOOT59 DD DISP=SHR,DSN=GENAPP.DDHOOT59.DATA
//DDHORP59 DD DISP=SHR,DSN=GENAPP.DDHORP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR01VB4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN60 DD DISP=SHR,DSN=GENAPP.DDFRIN60.DATA
//DDFROT60 DD DISP=SHR,DSN=GENAPP.DDFROT60.DATA
//DDFRRP60 DD DISP=SHR,DSN=GENAPP.DDFRRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
