//VJOB2749 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO021HK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN58 DD DISP=SHR,DSN=GENAPP.DDHOIN58.DATA
//DDHOOT58 DD DISP=SHR,DSN=GENAPP.DDHOOT58.DATA
//DDHORP58 DD DISP=SHR,DSN=GENAPP.DDHORP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ021HL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN59 DD DISP=SHR,DSN=GENAPP.DDAZIN59.DATA
//DDAZOT59 DD DISP=SHR,DSN=GENAPP.DDAZOT59.DATA
//DDAZRP59 DD DISP=SHR,DSN=GENAPP.DDAZRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG021HM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN60 DD DISP=SHR,DSN=GENAPP.DDAGIN60.DATA
//DDAGOT60 DD DISP=SHR,DSN=GENAPP.DDAGOT60.DATA
//DDAGRP60 DD DISP=SHR,DSN=GENAPP.DDAGRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
