//VJOB1342 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV01Y8B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN67 DD DISP=SHR,DSN=GENAPP.DDIVIN67.DATA
//DDIVOT67 DD DISP=SHR,DSN=GENAPP.DDIVOT67.DATA
//DDIVRP67 DD DISP=SHR,DSN=GENAPP.DDIVRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01Y8C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN68 DD DISP=SHR,DSN=GENAPP.DDHOIN68.DATA
//DDHOOT68 DD DISP=SHR,DSN=GENAPP.DDHOOT68.DATA
//DDHORP68 DD DISP=SHR,DSN=GENAPP.DDHORP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW01Y8D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN69 DD DISP=SHR,DSN=GENAPP.DDUWIN69.DATA
//DDUWOT69 DD DISP=SHR,DSN=GENAPP.DDUWOT69.DATA
//DDUWRP69 DD DISP=SHR,DSN=GENAPP.DDUWRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
