//VJOB1468 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF01YIT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN85 DD DISP=SHR,DSN=GENAPP.DDWFIN85.DATA
//DDWFOT85 DD DISP=SHR,DSN=GENAPP.DDWFOT85.DATA
//DDWFRP85 DD DISP=SHR,DSN=GENAPP.DDWFRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE01YIU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN86 DD DISP=SHR,DSN=GENAPP.DDREIN86.DATA
//DDREOT86 DD DISP=SHR,DSN=GENAPP.DDREOT86.DATA
//DDRERP86 DD DISP=SHR,DSN=GENAPP.DDRERP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01YIV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN87 DD DISP=SHR,DSN=GENAPP.DDHOIN87.DATA
//DDHOOT87 DD DISP=SHR,DSN=GENAPP.DDHOOT87.DATA
//DDHORP87 DD DISP=SHR,DSN=GENAPP.DDHORP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
