//VJOB4217 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSU024VW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN52 DD DISP=SHR,DSN=GENAPP.DDSUIN52.DATA
//DDSUOT52 DD DISP=SHR,DSN=GENAPP.DDSUOT52.DATA
//DDSURP52 DD DISP=SHR,DSN=GENAPP.DDSURP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO024VX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN53 DD DISP=SHR,DSN=GENAPP.DDHOIN53.DATA
//DDHOOT53 DD DISP=SHR,DSN=GENAPP.DDHOOT53.DATA
//DDHORP53 DD DISP=SHR,DSN=GENAPP.DDHORP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG024VY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN54 DD DISP=SHR,DSN=GENAPP.DDAGIN54.DATA
//DDAGOT54 DD DISP=SHR,DSN=GENAPP.DDAGOT54.DATA
//DDAGRP54 DD DISP=SHR,DSN=GENAPP.DDAGRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
