//VJOB4241 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW024XW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN34 DD DISP=SHR,DSN=GENAPP.DDUWIN34.DATA
//DDUWOT34 DD DISP=SHR,DSN=GENAPP.DDUWOT34.DATA
//DDUWRP34 DD DISP=SHR,DSN=GENAPP.DDUWRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW024XX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN35 DD DISP=SHR,DSN=GENAPP.DDUWIN35.DATA
//DDUWOT35 DD DISP=SHR,DSN=GENAPP.DDUWOT35.DATA
//DDUWRP35 DD DISP=SHR,DSN=GENAPP.DDUWRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA024XY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN36 DD DISP=SHR,DSN=GENAPP.DDPAIN36.DATA
//DDPAOT36 DD DISP=SHR,DSN=GENAPP.DDPAOT36.DATA
//DDPARP36 DD DISP=SHR,DSN=GENAPP.DDPARP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
