//VJOB3762 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE023TZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN37 DD DISP=SHR,DSN=GENAPP.DDREIN37.DATA
//DDREOT37 DD DISP=SHR,DSN=GENAPP.DDREOT37.DATA
//DDRERP37 DD DISP=SHR,DSN=GENAPP.DDRERP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZWF023U0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN38 DD DISP=SHR,DSN=GENAPP.DDWFIN38.DATA
//DDWFOT38 DD DISP=SHR,DSN=GENAPP.DDWFOT38.DATA
//DDWFRP38 DD DISP=SHR,DSN=GENAPP.DDWFRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS023U1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN39 DD DISP=SHR,DSN=GENAPP.DDRSIN39.DATA
//DDRSOT39 DD DISP=SHR,DSN=GENAPP.DDRSOT39.DATA
//DDRSRP39 DD DISP=SHR,DSN=GENAPP.DDRSRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
