//VJOB1208 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAR01XX5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN25 DD DISP=SHR,DSN=GENAPP.DDARIN25.DATA
//DDAROT25 DD DISP=SHR,DSN=GENAPP.DDAROT25.DATA
//DDARRP25 DD DISP=SHR,DSN=GENAPP.DDARRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE01XX6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN26 DD DISP=SHR,DSN=GENAPP.DDHEIN26.DATA
//DDHEOT26 DD DISP=SHR,DSN=GENAPP.DDHEOT26.DATA
//DDHERP26 DD DISP=SHR,DSN=GENAPP.DDHERP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCN01XX7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN27 DD DISP=SHR,DSN=GENAPP.DDCNIN27.DATA
//DDCNOT27 DD DISP=SHR,DSN=GENAPP.DDCNOT27.DATA
//DDCNRP27 DD DISP=SHR,DSN=GENAPP.DDCNRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
