//VJOB1540 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR01YOT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN31 DD DISP=SHR,DSN=GENAPP.DDFRIN31.DATA
//DDFROT31 DD DISP=SHR,DSN=GENAPP.DDFROT31.DATA
//DDFRRP31 DD DISP=SHR,DSN=GENAPP.DDFRRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFR01YOU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN32 DD DISP=SHR,DSN=GENAPP.DDFRIN32.DATA
//DDFROT32 DD DISP=SHR,DSN=GENAPP.DDFROT32.DATA
//DDFRRP32 DD DISP=SHR,DSN=GENAPP.DDFRRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN01YOV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN33 DD DISP=SHR,DSN=GENAPP.DDANIN33.DATA
//DDANOT33 DD DISP=SHR,DSN=GENAPP.DDANOT33.DATA
//DDANRP33 DD DISP=SHR,DSN=GENAPP.DDANRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
