//VJOB1873 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01ZGK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN40 DD DISP=SHR,DSN=GENAPP.DDUWIN40.DATA
//DDUWOT40 DD DISP=SHR,DSN=GENAPP.DDUWOT40.DATA
//DDUWRP40 DD DISP=SHR,DSN=GENAPP.DDUWRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRC01ZGL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN41 DD DISP=SHR,DSN=GENAPP.DDRCIN41.DATA
//DDRCOT41 DD DISP=SHR,DSN=GENAPP.DDRCOT41.DATA
//DDRCRP41 DD DISP=SHR,DSN=GENAPP.DDRCRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT01ZGM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN42 DD DISP=SHR,DSN=GENAPP.DDPTIN42.DATA
//DDPTOT42 DD DISP=SHR,DSN=GENAPP.DDPTOT42.DATA
//DDPTRP42 DD DISP=SHR,DSN=GENAPP.DDPTRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
