//VJOB0901 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIF01X7K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN04 DD DISP=SHR,DSN=GENAPP.DDIFIN04.DATA
//DDIFOT04 DD DISP=SHR,DSN=GENAPP.DDIFOT04.DATA
//DDIFRP04 DD DISP=SHR,DSN=GENAPP.DDIFRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01X7L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN05 DD DISP=SHR,DSN=GENAPP.DDMTIN05.DATA
//DDMTOT05 DD DISP=SHR,DSN=GENAPP.DDMTOT05.DATA
//DDMTRP05 DD DISP=SHR,DSN=GENAPP.DDMTRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01X7M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN06 DD DISP=SHR,DSN=GENAPP.DDTRIN06.DATA
//DDTROT06 DD DISP=SHR,DSN=GENAPP.DDTROT06.DATA
//DDTRRP06 DD DISP=SHR,DSN=GENAPP.DDTRRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
