//VJOB1070 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN01XLN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN61 DD DISP=SHR,DSN=GENAPP.DDPNIN61.DATA
//DDPNOT61 DD DISP=SHR,DSN=GENAPP.DDPNOT61.DATA
//DDPNRP61 DD DISP=SHR,DSN=GENAPP.DDPNRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDO01XLO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN62 DD DISP=SHR,DSN=GENAPP.DDDOIN62.DATA
//DDDOOT62 DD DISP=SHR,DSN=GENAPP.DDDOOT62.DATA
//DDDORP62 DD DISP=SHR,DSN=GENAPP.DDDORP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01XLP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN63 DD DISP=SHR,DSN=GENAPP.DDENIN63.DATA
//DDENOT63 DD DISP=SHR,DSN=GENAPP.DDENOT63.DATA
//DDENRP63 DD DISP=SHR,DSN=GENAPP.DDENRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
