//VJOB2256 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO020CH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN19 DD DISP=SHR,DSN=GENAPP.DDHOIN19.DATA
//DDHOOT19 DD DISP=SHR,DSN=GENAPP.DDHOOT19.DATA
//DDHORP19 DD DISP=SHR,DSN=GENAPP.DDHORP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAC020CI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN20 DD DISP=SHR,DSN=GENAPP.DDACIN20.DATA
//DDACOT20 DD DISP=SHR,DSN=GENAPP.DDACOT20.DATA
//DDACRP20 DD DISP=SHR,DSN=GENAPP.DDACRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU020CJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN21 DD DISP=SHR,DSN=GENAPP.DDCUIN21.DATA
//DDCUOT21 DD DISP=SHR,DSN=GENAPP.DDCUOT21.DATA
//DDCURP21 DD DISP=SHR,DSN=GENAPP.DDCURP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
