//VJOB0210 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01VLZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN01 DD DISP=SHR,DSN=GENAPP.DDCLIN01.DATA
//DDCLOT01 DD DISP=SHR,DSN=GENAPP.DDCLOT01.DATA
//DDCLRP01 DD DISP=SHR,DSN=GENAPP.DDCLRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE01VM0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN02 DD DISP=SHR,DSN=GENAPP.DDSEIN02.DATA
//DDSEOT02 DD DISP=SHR,DSN=GENAPP.DDSEOT02.DATA
//DDSERP02 DD DISP=SHR,DSN=GENAPP.DDSERP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01VM1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN03 DD DISP=SHR,DSN=GENAPP.DDHOIN03.DATA
//DDHOOT03 DD DISP=SHR,DSN=GENAPP.DDHOOT03.DATA
//DDHORP03 DD DISP=SHR,DSN=GENAPP.DDHORP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
