//VJOB0513 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01WB8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN10 DD DISP=SHR,DSN=GENAPP.DDUWIN10.DATA
//DDUWOT10 DD DISP=SHR,DSN=GENAPP.DDUWOT10.DATA
//DDUWRP10 DD DISP=SHR,DSN=GENAPP.DDUWRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR01WB9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN11 DD DISP=SHR,DSN=GENAPP.DDTRIN11.DATA
//DDTROT11 DD DISP=SHR,DSN=GENAPP.DDTROT11.DATA
//DDTRRP11 DD DISP=SHR,DSN=GENAPP.DDTRRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01WBA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN12 DD DISP=SHR,DSN=GENAPP.DDCUIN12.DATA
//DDCUOT12 DD DISP=SHR,DSN=GENAPP.DDCUOT12.DATA
//DDCURP12 DD DISP=SHR,DSN=GENAPP.DDCURP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
