//VJOB2220 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAR0209H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN01 DD DISP=SHR,DSN=GENAPP.DDARIN01.DATA
//DDAROT01 DD DISP=SHR,DSN=GENAPP.DDAROT01.DATA
//DDARRP01 DD DISP=SHR,DSN=GENAPP.DDARRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG0209I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN02 DD DISP=SHR,DSN=GENAPP.DDAGIN02.DATA
//DDAGOT02 DD DISP=SHR,DSN=GENAPP.DDAGOT02.DATA
//DDAGRP02 DD DISP=SHR,DSN=GENAPP.DDAGRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT0209J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN03 DD DISP=SHR,DSN=GENAPP.DDMTIN03.DATA
//DDMTOT03 DD DISP=SHR,DSN=GENAPP.DDMTOT03.DATA
//DDMTRP03 DD DISP=SHR,DSN=GENAPP.DDMTRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
