//VJOB3414 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO0230Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN73 DD DISP=SHR,DSN=GENAPP.DDHOIN73.DATA
//DDHOOT73 DD DISP=SHR,DSN=GENAPP.DDHOOT73.DATA
//DDHORP73 DD DISP=SHR,DSN=GENAPP.DDHORP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL02310
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN74 DD DISP=SHR,DSN=GENAPP.DDFLIN74.DATA
//DDFLOT74 DD DISP=SHR,DSN=GENAPP.DDFLOT74.DATA
//DDFLRP74 DD DISP=SHR,DSN=GENAPP.DDFLRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDI02311
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN75 DD DISP=SHR,DSN=GENAPP.DDDIIN75.DATA
//DDDIOT75 DD DISP=SHR,DSN=GENAPP.DDDIOT75.DATA
//DDDIRP75 DD DISP=SHR,DSN=GENAPP.DDDIRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
