//VJOB1017 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBR01XH8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN82 DD DISP=SHR,DSN=GENAPP.DDBRIN82.DATA
//DDBROT82 DD DISP=SHR,DSN=GENAPP.DDBROT82.DATA
//DDBRRP82 DD DISP=SHR,DSN=GENAPP.DDBRRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO01XH9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN83 DD DISP=SHR,DSN=GENAPP.DDCOIN83.DATA
//DDCOOT83 DD DISP=SHR,DSN=GENAPP.DDCOOT83.DATA
//DDCORP83 DD DISP=SHR,DSN=GENAPP.DDCORP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01XHA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN84 DD DISP=SHR,DSN=GENAPP.DDHOIN84.DATA
//DDHOOT84 DD DISP=SHR,DSN=GENAPP.DDHOOT84.DATA
//DDHORP84 DD DISP=SHR,DSN=GENAPP.DDHORP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
