//VJOB3201 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBR022J8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN64 DD DISP=SHR,DSN=GENAPP.DDBRIN64.DATA
//DDBROT64 DD DISP=SHR,DSN=GENAPP.DDBROT64.DATA
//DDBRRP64 DD DISP=SHR,DSN=GENAPP.DDBRRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB022J9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN65 DD DISP=SHR,DSN=GENAPP.DDLBIN65.DATA
//DDLBOT65 DD DISP=SHR,DSN=GENAPP.DDLBOT65.DATA
//DDLBRP65 DD DISP=SHR,DSN=GENAPP.DDLBRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRC022JA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN66 DD DISP=SHR,DSN=GENAPP.DDRCIN66.DATA
//DDRCOT66 DD DISP=SHR,DSN=GENAPP.DDRCOT66.DATA
//DDRCRP66 DD DISP=SHR,DSN=GENAPP.DDRCRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
