//VJOB3671 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT023ME
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN34 DD DISP=SHR,DSN=GENAPP.DDMTIN34.DATA
//DDMTOT34 DD DISP=SHR,DSN=GENAPP.DDMTOT34.DATA
//DDMTRP34 DD DISP=SHR,DSN=GENAPP.DDMTRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT023MF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN35 DD DISP=SHR,DSN=GENAPP.DDMTIN35.DATA
//DDMTOT35 DD DISP=SHR,DSN=GENAPP.DDMTOT35.DATA
//DDMTRP35 DD DISP=SHR,DSN=GENAPP.DDMTRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC023MG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN36 DD DISP=SHR,DSN=GENAPP.DDSCIN36.DATA
//DDSCOT36 DD DISP=SHR,DSN=GENAPP.DDSCOT36.DATA
//DDSCRP36 DD DISP=SHR,DSN=GENAPP.DDSCRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
