//VJOB4303 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI02532
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN40 DD DISP=SHR,DSN=GENAPP.DDLIIN40.DATA
//DDLIOT40 DD DISP=SHR,DSN=GENAPP.DDLIOT40.DATA
//DDLIRP40 DD DISP=SHR,DSN=GENAPP.DDLIRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT02533
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN41 DD DISP=SHR,DSN=GENAPP.DDMTIN41.DATA
//DDMTOT41 DD DISP=SHR,DSN=GENAPP.DDMTOT41.DATA
//DDMTRP41 DD DISP=SHR,DSN=GENAPP.DDMTRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU02534
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN42 DD DISP=SHR,DSN=GENAPP.DDCUIN42.DATA
//DDCUOT42 DD DISP=SHR,DSN=GENAPP.DDCUOT42.DATA
//DDCURP42 DD DISP=SHR,DSN=GENAPP.DDCURP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
