//VJOB3262 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE022OB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN67 DD DISP=SHR,DSN=GENAPP.DDPEIN67.DATA
//DDPEOT67 DD DISP=SHR,DSN=GENAPP.DDPEOT67.DATA
//DDPERP67 DD DISP=SHR,DSN=GENAPP.DDPERP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL022OC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN68 DD DISP=SHR,DSN=GENAPP.DDCLIN68.DATA
//DDCLOT68 DD DISP=SHR,DSN=GENAPP.DDCLOT68.DATA
//DDCLRP68 DD DISP=SHR,DSN=GENAPP.DDCLRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR022OD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN69 DD DISP=SHR,DSN=GENAPP.DDPRIN69.DATA
//DDPROT69 DD DISP=SHR,DSN=GENAPP.DDPROT69.DATA
//DDPRRP69 DD DISP=SHR,DSN=GENAPP.DDPRRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
