//VJOB3136 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR022DT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN49 DD DISP=SHR,DSN=GENAPP.DDTRIN49.DATA
//DDTROT49 DD DISP=SHR,DSN=GENAPP.DDTROT49.DATA
//DDTRRP49 DD DISP=SHR,DSN=GENAPP.DDTRRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI022DU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN50 DD DISP=SHR,DSN=GENAPP.DDLIIN50.DATA
//DDLIOT50 DD DISP=SHR,DSN=GENAPP.DDLIOT50.DATA
//DDLIRP50 DD DISP=SHR,DSN=GENAPP.DDLIRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO022DV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN51 DD DISP=SHR,DSN=GENAPP.DDHOIN51.DATA
//DDHOOT51 DD DISP=SHR,DSN=GENAPP.DDHOOT51.DATA
//DDHORP51 DD DISP=SHR,DSN=GENAPP.DDHORP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
