//VJOB4250 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZQU024YN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN61 DD DISP=SHR,DSN=GENAPP.DDQUIN61.DATA
//DDQUOT61 DD DISP=SHR,DSN=GENAPP.DDQUOT61.DATA
//DDQURP61 DD DISP=SHR,DSN=GENAPP.DDQURP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE024YO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN62 DD DISP=SHR,DSN=GENAPP.DDREIN62.DATA
//DDREOT62 DD DISP=SHR,DSN=GENAPP.DDREOT62.DATA
//DDRERP62 DD DISP=SHR,DSN=GENAPP.DDRERP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU024YP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN63 DD DISP=SHR,DSN=GENAPP.DDCUIN63.DATA
//DDCUOT63 DD DISP=SHR,DSN=GENAPP.DDCUOT63.DATA
//DDCURP63 DD DISP=SHR,DSN=GENAPP.DDCURP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
