//VJOB1102 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE01XOB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN67 DD DISP=SHR,DSN=GENAPP.DDPEIN67.DATA
//DDPEOT67 DD DISP=SHR,DSN=GENAPP.DDPEOT67.DATA
//DDPERP67 DD DISP=SHR,DSN=GENAPP.DDPERP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCP01XOC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN68 DD DISP=SHR,DSN=GENAPP.DDCPIN68.DATA
//DDCPOT68 DD DISP=SHR,DSN=GENAPP.DDCPOT68.DATA
//DDCPRP68 DD DISP=SHR,DSN=GENAPP.DDCPRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRC01XOD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN69 DD DISP=SHR,DSN=GENAPP.DDRCIN69.DATA
//DDRCOT69 DD DISP=SHR,DSN=GENAPP.DDRCOT69.DATA
//DDRCRP69 DD DISP=SHR,DSN=GENAPP.DDRCRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
