//VJOB4231 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA024X2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN04 DD DISP=SHR,DSN=GENAPP.DDMAIN04.DATA
//DDMAOT04 DD DISP=SHR,DSN=GENAPP.DDMAOT04.DATA
//DDMARP04 DD DISP=SHR,DSN=GENAPP.DDMARP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI024X3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN05 DD DISP=SHR,DSN=GENAPP.DDLIIN05.DATA
//DDLIOT05 DD DISP=SHR,DSN=GENAPP.DDLIOT05.DATA
//DDLIRP05 DD DISP=SHR,DSN=GENAPP.DDLIRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT024X4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN06 DD DISP=SHR,DSN=GENAPP.DDMTIN06.DATA
//DDMTOT06 DD DISP=SHR,DSN=GENAPP.DDMTOT06.DATA
//DDMTRP06 DD DISP=SHR,DSN=GENAPP.DDMTRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
