//VJOB0649 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR01WMK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN58 DD DISP=SHR,DSN=GENAPP.DDTRIN58.DATA
//DDTROT58 DD DISP=SHR,DSN=GENAPP.DDTROT58.DATA
//DDTRRP58 DD DISP=SHR,DSN=GENAPP.DDTRRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAC01WML
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN59 DD DISP=SHR,DSN=GENAPP.DDACIN59.DATA
//DDACOT59 DD DISP=SHR,DSN=GENAPP.DDACOT59.DATA
//DDACRP59 DD DISP=SHR,DSN=GENAPP.DDACRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01WMM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN60 DD DISP=SHR,DSN=GENAPP.DDENIN60.DATA
//DDENOT60 DD DISP=SHR,DSN=GENAPP.DDENOT60.DATA
//DDENRP60 DD DISP=SHR,DSN=GENAPP.DDENRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
