//VJOB1869 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01ZG8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN28 DD DISP=SHR,DSN=GENAPP.DDCOIN28.DATA
//DDCOOT28 DD DISP=SHR,DSN=GENAPP.DDCOOT28.DATA
//DDCORP28 DD DISP=SHR,DSN=GENAPP.DDCORP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE01ZG9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN29 DD DISP=SHR,DSN=GENAPP.DDREIN29.DATA
//DDREOT29 DD DISP=SHR,DSN=GENAPP.DDREOT29.DATA
//DDRERP29 DD DISP=SHR,DSN=GENAPP.DDRERP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE01ZGA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN30 DD DISP=SHR,DSN=GENAPP.DDHEIN30.DATA
//DDHEOT30 DD DISP=SHR,DSN=GENAPP.DDHEOT30.DATA
//DDHERP30 DD DISP=SHR,DSN=GENAPP.DDHERP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
