//VJOB3225 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU022L8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN46 DD DISP=SHR,DSN=GENAPP.DDCUIN46.DATA
//DDCUOT46 DD DISP=SHR,DSN=GENAPP.DDCUOT46.DATA
//DDCURP46 DD DISP=SHR,DSN=GENAPP.DDCURP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPL022L9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN47 DD DISP=SHR,DSN=GENAPP.DDPLIN47.DATA
//DDPLOT47 DD DISP=SHR,DSN=GENAPP.DDPLOT47.DATA
//DDPLRP47 DD DISP=SHR,DSN=GENAPP.DDPLRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI022LA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN48 DD DISP=SHR,DSN=GENAPP.DDLIIN48.DATA
//DDLIOT48 DD DISP=SHR,DSN=GENAPP.DDLIOT48.DATA
//DDLIRP48 DD DISP=SHR,DSN=GENAPP.DDLIRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
