//VJOB2114 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT0200N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN43 DD DISP=SHR,DSN=GENAPP.DDMTIN43.DATA
//DDMTOT43 DD DISP=SHR,DSN=GENAPP.DDMTOT43.DATA
//DDMTRP43 DD DISP=SHR,DSN=GENAPP.DDMTRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR0200O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN44 DD DISP=SHR,DSN=GENAPP.DDTRIN44.DATA
//DDTROT44 DD DISP=SHR,DSN=GENAPP.DDTROT44.DATA
//DDTRRP44 DD DISP=SHR,DSN=GENAPP.DDTRRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN0200P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN45 DD DISP=SHR,DSN=GENAPP.DDANIN45.DATA
//DDANOT45 DD DISP=SHR,DSN=GENAPP.DDANOT45.DATA
//DDANRP45 DD DISP=SHR,DSN=GENAPP.DDANRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
