//VJOB0291 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA01VSQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN64 DD DISP=SHR,DSN=GENAPP.DDBAIN64.DATA
//DDBAOT64 DD DISP=SHR,DSN=GENAPP.DDBAOT64.DATA
//DDBARP64 DD DISP=SHR,DSN=GENAPP.DDBARP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFR01VSR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN65 DD DISP=SHR,DSN=GENAPP.DDFRIN65.DATA
//DDFROT65 DD DISP=SHR,DSN=GENAPP.DDFROT65.DATA
//DDFRRP65 DD DISP=SHR,DSN=GENAPP.DDFRRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01VSS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN66 DD DISP=SHR,DSN=GENAPP.DDPEIN66.DATA
//DDPEOT66 DD DISP=SHR,DSN=GENAPP.DDPEOT66.DATA
//DDPERP66 DD DISP=SHR,DSN=GENAPP.DDPERP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
