//VJOB3319 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBR022T2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN58 DD DISP=SHR,DSN=GENAPP.DDBRIN58.DATA
//DDBROT58 DD DISP=SHR,DSN=GENAPP.DDBROT58.DATA
//DDBRRP58 DD DISP=SHR,DSN=GENAPP.DDBRRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDI022T3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN59 DD DISP=SHR,DSN=GENAPP.DDDIIN59.DATA
//DDDIOT59 DD DISP=SHR,DSN=GENAPP.DDDIOT59.DATA
//DDDIRP59 DD DISP=SHR,DSN=GENAPP.DDDIRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC022T4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN60 DD DISP=SHR,DSN=GENAPP.DDACIN60.DATA
//DDACOT60 DD DISP=SHR,DSN=GENAPP.DDACOT60.DATA
//DDACRP60 DD DISP=SHR,DSN=GENAPP.DDACRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
