//VJOB2110 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU0200B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN31 DD DISP=SHR,DSN=GENAPP.DDCUIN31.DATA
//DDCUOT31 DD DISP=SHR,DSN=GENAPP.DDCUOT31.DATA
//DDCURP31 DD DISP=SHR,DSN=GENAPP.DDCURP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL0200C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN32 DD DISP=SHR,DSN=GENAPP.DDFLIN32.DATA
//DDFLOT32 DD DISP=SHR,DSN=GENAPP.DDFLOT32.DATA
//DDFLRP32 DD DISP=SHR,DSN=GENAPP.DDFLRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN0200D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN33 DD DISP=SHR,DSN=GENAPP.DDANIN33.DATA
//DDANOT33 DD DISP=SHR,DSN=GENAPP.DDANOT33.DATA
//DDANRP33 DD DISP=SHR,DSN=GENAPP.DDANRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
