//VJOB2857 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT021QK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN22 DD DISP=SHR,DSN=GENAPP.DDMTIN22.DATA
//DDMTOT22 DD DISP=SHR,DSN=GENAPP.DDMTOT22.DATA
//DDMTRP22 DD DISP=SHR,DSN=GENAPP.DDMTRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSU021QL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN23 DD DISP=SHR,DSN=GENAPP.DDSUIN23.DATA
//DDSUOT23 DD DISP=SHR,DSN=GENAPP.DDSUOT23.DATA
//DDSURP23 DD DISP=SHR,DSN=GENAPP.DDSURP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR021QM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN24 DD DISP=SHR,DSN=GENAPP.DDPRIN24.DATA
//DDPROT24 DD DISP=SHR,DSN=GENAPP.DDPROT24.DATA
//DDPRRP24 DD DISP=SHR,DSN=GENAPP.DDPRRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
