//VJOB3702 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCR023OZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN37 DD DISP=SHR,DSN=GENAPP.DDCRIN37.DATA
//DDCROT37 DD DISP=SHR,DSN=GENAPP.DDCROT37.DATA
//DDCRRP37 DD DISP=SHR,DSN=GENAPP.DDCRRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV023P0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN38 DD DISP=SHR,DSN=GENAPP.DDAVIN38.DATA
//DDAVOT38 DD DISP=SHR,DSN=GENAPP.DDAVOT38.DATA
//DDAVRP38 DD DISP=SHR,DSN=GENAPP.DDAVRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN023P1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN39 DD DISP=SHR,DSN=GENAPP.DDENIN39.DATA
//DDENOT39 DD DISP=SHR,DSN=GENAPP.DDENOT39.DATA
//DDENRP39 DD DISP=SHR,DSN=GENAPP.DDENRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
