//VJOB1466 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA01YIN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN79 DD DISP=SHR,DSN=GENAPP.DDPAIN79.DATA
//DDPAOT79 DD DISP=SHR,DSN=GENAPP.DDPAOT79.DATA
//DDPARP79 DD DISP=SHR,DSN=GENAPP.DDPARP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01YIO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN80 DD DISP=SHR,DSN=GENAPP.DDAGIN80.DATA
//DDAGOT80 DD DISP=SHR,DSN=GENAPP.DDAGOT80.DATA
//DDAGRP80 DD DISP=SHR,DSN=GENAPP.DDAGRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZGW01YIP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN81 DD DISP=SHR,DSN=GENAPP.DDGWIN81.DATA
//DDGWOT81 DD DISP=SHR,DSN=GENAPP.DDGWOT81.DATA
//DDGWRP81 DD DISP=SHR,DSN=GENAPP.DDGWRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
