//VJOB0971 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL01XDE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN34 DD DISP=SHR,DSN=GENAPP.DDFLIN34.DATA
//DDFLOT34 DD DISP=SHR,DSN=GENAPP.DDFLOT34.DATA
//DDFLRP34 DD DISP=SHR,DSN=GENAPP.DDFLRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01XDF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN35 DD DISP=SHR,DSN=GENAPP.DDLIIN35.DATA
//DDLIOT35 DD DISP=SHR,DSN=GENAPP.DDLIOT35.DATA
//DDLIRP35 DD DISP=SHR,DSN=GENAPP.DDLIRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01XDG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN36 DD DISP=SHR,DSN=GENAPP.DDCLIN36.DATA
//DDCLOT36 DD DISP=SHR,DSN=GENAPP.DDCLOT36.DATA
//DDCLRP36 DD DISP=SHR,DSN=GENAPP.DDCLRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
