//VJOB3892 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB0244T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN67 DD DISP=SHR,DSN=GENAPP.DDLBIN67.DATA
//DDLBOT67 DD DISP=SHR,DSN=GENAPP.DDLBOT67.DATA
//DDLBRP67 DD DISP=SHR,DSN=GENAPP.DDLBRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL0244U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN68 DD DISP=SHR,DSN=GENAPP.DDFLIN68.DATA
//DDFLOT68 DD DISP=SHR,DSN=GENAPP.DDFLOT68.DATA
//DDFLRP68 DD DISP=SHR,DSN=GENAPP.DDFLRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU0244V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN69 DD DISP=SHR,DSN=GENAPP.DDCUIN69.DATA
//DDCUOT69 DD DISP=SHR,DSN=GENAPP.DDCUOT69.DATA
//DDCURP69 DD DISP=SHR,DSN=GENAPP.DDCURP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
