//VJOB2765 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO021IW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN16 DD DISP=SHR,DSN=GENAPP.DDHOIN16.DATA
//DDHOOT16 DD DISP=SHR,DSN=GENAPP.DDHOOT16.DATA
//DDHORP16 DD DISP=SHR,DSN=GENAPP.DDHORP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV021IX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN17 DD DISP=SHR,DSN=GENAPP.DDIVIN17.DATA
//DDIVOT17 DD DISP=SHR,DSN=GENAPP.DDIVOT17.DATA
//DDIVRP17 DD DISP=SHR,DSN=GENAPP.DDIVRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO021IY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN18 DD DISP=SHR,DSN=GENAPP.DDHOIN18.DATA
//DDHOOT18 DD DISP=SHR,DSN=GENAPP.DDHOOT18.DATA
//DDHORP18 DD DISP=SHR,DSN=GENAPP.DDHORP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
