//VJOB3093 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX022A8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN10 DD DISP=SHR,DSN=GENAPP.DDTXIN10.DATA
//DDTXOT10 DD DISP=SHR,DSN=GENAPP.DDTXOT10.DATA
//DDTXRP10 DD DISP=SHR,DSN=GENAPP.DDTXRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW022A9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN11 DD DISP=SHR,DSN=GENAPP.DDUWIN11.DATA
//DDUWOT11 DD DISP=SHR,DSN=GENAPP.DDUWOT11.DATA
//DDUWRP11 DD DISP=SHR,DSN=GENAPP.DDUWRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV022AA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN12 DD DISP=SHR,DSN=GENAPP.DDAVIN12.DATA
//DDAVOT12 DD DISP=SHR,DSN=GENAPP.DDAVOT12.DATA
//DDAVRP12 DD DISP=SHR,DSN=GENAPP.DDAVRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
