//VJOB2158 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG0204B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN85 DD DISP=SHR,DSN=GENAPP.DDAGIN85.DATA
//DDAGOT85 DD DISP=SHR,DSN=GENAPP.DDAGOT85.DATA
//DDAGRP85 DD DISP=SHR,DSN=GENAPP.DDAGRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN0204C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN86 DD DISP=SHR,DSN=GENAPP.DDRNIN86.DATA
//DDRNOT86 DD DISP=SHR,DSN=GENAPP.DDRNOT86.DATA
//DDRNRP86 DD DISP=SHR,DSN=GENAPP.DDRNRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT0204D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN87 DD DISP=SHR,DSN=GENAPP.DDMTIN87.DATA
//DDMTOT87 DD DISP=SHR,DSN=GENAPP.DDMTOT87.DATA
//DDMTRP87 DD DISP=SHR,DSN=GENAPP.DDMTRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
