//VJOB0648 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01WMH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN55 DD DISP=SHR,DSN=GENAPP.DDMTIN55.DATA
//DDMTOT55 DD DISP=SHR,DSN=GENAPP.DDMTOT55.DATA
//DDMTRP55 DD DISP=SHR,DSN=GENAPP.DDMTRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG01WMI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN56 DD DISP=SHR,DSN=GENAPP.DDRGIN56.DATA
//DDRGOT56 DD DISP=SHR,DSN=GENAPP.DDRGOT56.DATA
//DDRGRP56 DD DISP=SHR,DSN=GENAPP.DDRGRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01WMJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN57 DD DISP=SHR,DSN=GENAPP.DDREIN57.DATA
//DDREOT57 DD DISP=SHR,DSN=GENAPP.DDREOT57.DATA
//DDRERP57 DD DISP=SHR,DSN=GENAPP.DDRERP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
