//VJOB0578 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01WGN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN25 DD DISP=SHR,DSN=GENAPP.DDENIN25.DATA
//DDENOT25 DD DISP=SHR,DSN=GENAPP.DDENOT25.DATA
//DDENRP25 DD DISP=SHR,DSN=GENAPP.DDENRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRS01WGO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN26 DD DISP=SHR,DSN=GENAPP.DDRSIN26.DATA
//DDRSOT26 DD DISP=SHR,DSN=GENAPP.DDRSOT26.DATA
//DDRSRP26 DD DISP=SHR,DSN=GENAPP.DDRSRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01WGP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN27 DD DISP=SHR,DSN=GENAPP.DDTRIN27.DATA
//DDTROT27 DD DISP=SHR,DSN=GENAPP.DDTROT27.DATA
//DDTRRP27 DD DISP=SHR,DSN=GENAPP.DDTRRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
