//VJOB2366 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV020LN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN79 DD DISP=SHR,DSN=GENAPP.DDAVIN79.DATA
//DDAVOT79 DD DISP=SHR,DSN=GENAPP.DDAVOT79.DATA
//DDAVRP79 DD DISP=SHR,DSN=GENAPP.DDAVRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX020LO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN80 DD DISP=SHR,DSN=GENAPP.DDTXIN80.DATA
//DDTXOT80 DD DISP=SHR,DSN=GENAPP.DDTXOT80.DATA
//DDTXRP80 DD DISP=SHR,DSN=GENAPP.DDTXRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZVA020LP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN81 DD DISP=SHR,DSN=GENAPP.DDVAIN81.DATA
//DDVAOT81 DD DISP=SHR,DSN=GENAPP.DDVAOT81.DATA
//DDVARP81 DD DISP=SHR,DSN=GENAPP.DDVARP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
