//VJOB3582 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL023EZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN37 DD DISP=SHR,DSN=GENAPP.DDCLIN37.DATA
//DDCLOT37 DD DISP=SHR,DSN=GENAPP.DDCLOT37.DATA
//DDCLRP37 DD DISP=SHR,DSN=GENAPP.DDCLRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA023F0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN38 DD DISP=SHR,DSN=GENAPP.DDPAIN38.DATA
//DDPAOT38 DD DISP=SHR,DSN=GENAPP.DDPAOT38.DATA
//DDPARP38 DD DISP=SHR,DSN=GENAPP.DDPARP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCN023F1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN39 DD DISP=SHR,DSN=GENAPP.DDCNIN39.DATA
//DDCNOT39 DD DISP=SHR,DSN=GENAPP.DDCNOT39.DATA
//DDCNRP39 DD DISP=SHR,DSN=GENAPP.DDCNRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
