//VJOB1550 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR01YPN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN61 DD DISP=SHR,DSN=GENAPP.DDFRIN61.DATA
//DDFROT61 DD DISP=SHR,DSN=GENAPP.DDFROT61.DATA
//DDFRRP61 DD DISP=SHR,DSN=GENAPP.DDFRRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01YPO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN62 DD DISP=SHR,DSN=GENAPP.DDHOIN62.DATA
//DDHOOT62 DD DISP=SHR,DSN=GENAPP.DDHOOT62.DATA
//DDHORP62 DD DISP=SHR,DSN=GENAPP.DDHORP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSB01YPP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN63 DD DISP=SHR,DSN=GENAPP.DDSBIN63.DATA
//DDSBOT63 DD DISP=SHR,DSN=GENAPP.DDSBOT63.DATA
//DDSBRP63 DD DISP=SHR,DSN=GENAPP.DDSBRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
