//VJOB3787 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT023W2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN22 DD DISP=SHR,DSN=GENAPP.DDPTIN22.DATA
//DDPTOT22 DD DISP=SHR,DSN=GENAPP.DDPTOT22.DATA
//DDPTRP22 DD DISP=SHR,DSN=GENAPP.DDPTRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL023W3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN23 DD DISP=SHR,DSN=GENAPP.DDCLIN23.DATA
//DDCLOT23 DD DISP=SHR,DSN=GENAPP.DDCLOT23.DATA
//DDCLRP23 DD DISP=SHR,DSN=GENAPP.DDCLRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL023W4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN24 DD DISP=SHR,DSN=GENAPP.DDFLIN24.DATA
//DDFLOT24 DD DISP=SHR,DSN=GENAPP.DDFLOT24.DATA
//DDFLRP24 DD DISP=SHR,DSN=GENAPP.DDFLRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
