//VJOB0365 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01VYW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN16 DD DISP=SHR,DSN=GENAPP.DDMTIN16.DATA
//DDMTOT16 DD DISP=SHR,DSN=GENAPP.DDMTOT16.DATA
//DDMTRP16 DD DISP=SHR,DSN=GENAPP.DDMTRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSB01VYX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN17 DD DISP=SHR,DSN=GENAPP.DDSBIN17.DATA
//DDSBOT17 DD DISP=SHR,DSN=GENAPP.DDSBOT17.DATA
//DDSBRP17 DD DISP=SHR,DSN=GENAPP.DDSBRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01VYY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN18 DD DISP=SHR,DSN=GENAPP.DDCUIN18.DATA
//DDCUOT18 DD DISP=SHR,DSN=GENAPP.DDCUOT18.DATA
//DDCURP18 DD DISP=SHR,DSN=GENAPP.DDCURP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
