//VJOB3885 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO02448
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN46 DD DISP=SHR,DSN=GENAPP.DDHOIN46.DATA
//DDHOOT46 DD DISP=SHR,DSN=GENAPP.DDHOOT46.DATA
//DDHORP46 DD DISP=SHR,DSN=GENAPP.DDHORP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB02449
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN47 DD DISP=SHR,DSN=GENAPP.DDLBIN47.DATA
//DDLBOT47 DD DISP=SHR,DSN=GENAPP.DDLBOT47.DATA
//DDLBRP47 DD DISP=SHR,DSN=GENAPP.DDLBRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN0244A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN48 DD DISP=SHR,DSN=GENAPP.DDENIN48.DATA
//DDENOT48 DD DISP=SHR,DSN=GENAPP.DDENOT48.DATA
//DDENRP48 DD DISP=SHR,DSN=GENAPP.DDENRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
