//VJOB4032 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA024GH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN37 DD DISP=SHR,DSN=GENAPP.DDMAIN37.DATA
//DDMAOT37 DD DISP=SHR,DSN=GENAPP.DDMAOT37.DATA
//DDMARP37 DD DISP=SHR,DSN=GENAPP.DDMARP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV024GI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN38 DD DISP=SHR,DSN=GENAPP.DDIVIN38.DATA
//DDIVOT38 DD DISP=SHR,DSN=GENAPP.DDIVOT38.DATA
//DDIVRP38 DD DISP=SHR,DSN=GENAPP.DDIVRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCN024GJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN39 DD DISP=SHR,DSN=GENAPP.DDCNIN39.DATA
//DDCNOT39 DD DISP=SHR,DSN=GENAPP.DDCNOT39.DATA
//DDCNRP39 DD DISP=SHR,DSN=GENAPP.DDCNRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
