//VJOB0760 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA01WVT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN31 DD DISP=SHR,DSN=GENAPP.DDBAIN31.DATA
//DDBAOT31 DD DISP=SHR,DSN=GENAPP.DDBAOT31.DATA
//DDBARP31 DD DISP=SHR,DSN=GENAPP.DDBARP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01WVU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN32 DD DISP=SHR,DSN=GENAPP.DDAGIN32.DATA
//DDAGOT32 DD DISP=SHR,DSN=GENAPP.DDAGOT32.DATA
//DDAGRP32 DD DISP=SHR,DSN=GENAPP.DDAGRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01WVV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN33 DD DISP=SHR,DSN=GENAPP.DDREIN33.DATA
//DDREOT33 DD DISP=SHR,DSN=GENAPP.DDREOT33.DATA
//DDRERP33 DD DISP=SHR,DSN=GENAPP.DDRERP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
