//VJOB4038 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBR024GZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN55 DD DISP=SHR,DSN=GENAPP.DDBRIN55.DATA
//DDBROT55 DD DISP=SHR,DSN=GENAPP.DDBROT55.DATA
//DDBRRP55 DD DISP=SHR,DSN=GENAPP.DDBRRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO024H0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN56 DD DISP=SHR,DSN=GENAPP.DDCOIN56.DATA
//DDCOOT56 DD DISP=SHR,DSN=GENAPP.DDCOOT56.DATA
//DDCORP56 DD DISP=SHR,DSN=GENAPP.DDCORP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCN024H1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN57 DD DISP=SHR,DSN=GENAPP.DDCNIN57.DATA
//DDCNOT57 DD DISP=SHR,DSN=GENAPP.DDCNOT57.DATA
//DDCNRP57 DD DISP=SHR,DSN=GENAPP.DDCNRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
