//VJOB0090 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL01VBZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN01 DD DISP=SHR,DSN=GENAPP.DDFLIN01.DATA
//DDFLOT01 DD DISP=SHR,DSN=GENAPP.DDFLOT01.DATA
//DDFLRP01 DD DISP=SHR,DSN=GENAPP.DDFLRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN01VC0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN02 DD DISP=SHR,DSN=GENAPP.DDENIN02.DATA
//DDENOT02 DD DISP=SHR,DSN=GENAPP.DDENOT02.DATA
//DDENRP02 DD DISP=SHR,DSN=GENAPP.DDENRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE01VC1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN03 DD DISP=SHR,DSN=GENAPP.DDHEIN03.DATA
//DDHEOT03 DD DISP=SHR,DSN=GENAPP.DDHEOT03.DATA
//DDHERP03 DD DISP=SHR,DSN=GENAPP.DDHERP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
