//VJOB1992 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01ZQH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN37 DD DISP=SHR,DSN=GENAPP.DDENIN37.DATA
//DDENOT37 DD DISP=SHR,DSN=GENAPP.DDENOT37.DATA
//DDENRP37 DD DISP=SHR,DSN=GENAPP.DDENRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01ZQI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN38 DD DISP=SHR,DSN=GENAPP.DDMTIN38.DATA
//DDMTOT38 DD DISP=SHR,DSN=GENAPP.DDMTOT38.DATA
//DDMTRP38 DD DISP=SHR,DSN=GENAPP.DDMTRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO01ZQJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN39 DD DISP=SHR,DSN=GENAPP.DDCOIN39.DATA
//DDCOOT39 DD DISP=SHR,DSN=GENAPP.DDCOOT39.DATA
//DDCORP39 DD DISP=SHR,DSN=GENAPP.DDCORP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
