//VJOB2099 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01ZZE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN88 DD DISP=SHR,DSN=GENAPP.DDCOIN88.DATA
//DDCOOT88 DD DISP=SHR,DSN=GENAPP.DDCOOT88.DATA
//DDCORP88 DD DISP=SHR,DSN=GENAPP.DDCORP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO01ZZF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN89 DD DISP=SHR,DSN=GENAPP.DDCOIN89.DATA
//DDCOOT89 DD DISP=SHR,DSN=GENAPP.DDCOOT89.DATA
//DDCORP89 DD DISP=SHR,DSN=GENAPP.DDCORP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01ZZG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN90 DD DISP=SHR,DSN=GENAPP.DDPRIN90.DATA
//DDPROT90 DD DISP=SHR,DSN=GENAPP.DDPROT90.DATA
//DDPRRP90 DD DISP=SHR,DSN=GENAPP.DDPRRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
