//VJOB3629 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI023IW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN88 DD DISP=SHR,DSN=GENAPP.DDLIIN88.DATA
//DDLIOT88 DD DISP=SHR,DSN=GENAPP.DDLIOT88.DATA
//DDLIRP88 DD DISP=SHR,DSN=GENAPP.DDLIRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAC023IX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN89 DD DISP=SHR,DSN=GENAPP.DDACIN89.DATA
//DDACOT89 DD DISP=SHR,DSN=GENAPP.DDACOT89.DATA
//DDACRP89 DD DISP=SHR,DSN=GENAPP.DDACRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT023IY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN90 DD DISP=SHR,DSN=GENAPP.DDMTIN90.DATA
//DDMTOT90 DD DISP=SHR,DSN=GENAPP.DDMTOT90.DATA
//DDMTRP90 DD DISP=SHR,DSN=GENAPP.DDMTRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
