//VJOB1840 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP01ZDT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN31 DD DISP=SHR,DSN=GENAPP.DDCPIN31.DATA
//DDCPOT31 DD DISP=SHR,DSN=GENAPP.DDCPOT31.DATA
//DDCPRP31 DD DISP=SHR,DSN=GENAPP.DDCPRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01ZDU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN32 DD DISP=SHR,DSN=GENAPP.DDMTIN32.DATA
//DDMTOT32 DD DISP=SHR,DSN=GENAPP.DDMTOT32.DATA
//DDMTRP32 DD DISP=SHR,DSN=GENAPP.DDMTRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZNT01ZDV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN33 DD DISP=SHR,DSN=GENAPP.DDNTIN33.DATA
//DDNTOT33 DD DISP=SHR,DSN=GENAPP.DDNTOT33.DATA
//DDNTRP33 DD DISP=SHR,DSN=GENAPP.DDNTRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
