//VJOB3244 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE022MT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN13 DD DISP=SHR,DSN=GENAPP.DDREIN13.DATA
//DDREOT13 DD DISP=SHR,DSN=GENAPP.DDREOT13.DATA
//DDRERP13 DD DISP=SHR,DSN=GENAPP.DDRERP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR022MU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN14 DD DISP=SHR,DSN=GENAPP.DDPRIN14.DATA
//DDPROT14 DD DISP=SHR,DSN=GENAPP.DDPROT14.DATA
//DDPRRP14 DD DISP=SHR,DSN=GENAPP.DDPRRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRT022MV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN15 DD DISP=SHR,DSN=GENAPP.DDRTIN15.DATA
//DDRTOT15 DD DISP=SHR,DSN=GENAPP.DDRTOT15.DATA
//DDRTRP15 DD DISP=SHR,DSN=GENAPP.DDRTRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
