//VJOB0017 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRT01V5W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN52 DD DISP=SHR,DSN=GENAPP.DDRTIN52.DATA
//DDRTOT52 DD DISP=SHR,DSN=GENAPP.DDRTOT52.DATA
//DDRTRP52 DD DISP=SHR,DSN=GENAPP.DDRTRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDI01V5X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN53 DD DISP=SHR,DSN=GENAPP.DDDIIN53.DATA
//DDDIOT53 DD DISP=SHR,DSN=GENAPP.DDDIOT53.DATA
//DDDIRP53 DD DISP=SHR,DSN=GENAPP.DDDIRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEX01V5Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN54 DD DISP=SHR,DSN=GENAPP.DDEXIN54.DATA
//DDEXOT54 DD DISP=SHR,DSN=GENAPP.DDEXOT54.DATA
//DDEXRP54 DD DISP=SHR,DSN=GENAPP.DDEXRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
