//VJOB3220 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF022KT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN31 DD DISP=SHR,DSN=GENAPP.DDWFIN31.DATA
//DDWFOT31 DD DISP=SHR,DSN=GENAPP.DDWFOT31.DATA
//DDWFRP31 DD DISP=SHR,DSN=GENAPP.DDWFRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN022KU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN32 DD DISP=SHR,DSN=GENAPP.DDANIN32.DATA
//DDANOT32 DD DISP=SHR,DSN=GENAPP.DDANOT32.DATA
//DDANRP32 DD DISP=SHR,DSN=GENAPP.DDANRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN022KV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN33 DD DISP=SHR,DSN=GENAPP.DDENIN33.DATA
//DDENOT33 DD DISP=SHR,DSN=GENAPP.DDENOT33.DATA
//DDENRP33 DD DISP=SHR,DSN=GENAPP.DDENRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
