//VJOB2274 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO020DZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN73 DD DISP=SHR,DSN=GENAPP.DDHOIN73.DATA
//DDHOOT73 DD DISP=SHR,DSN=GENAPP.DDHOOT73.DATA
//DDHORP73 DD DISP=SHR,DSN=GENAPP.DDHORP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA020E0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN74 DD DISP=SHR,DSN=GENAPP.DDBAIN74.DATA
//DDBAOT74 DD DISP=SHR,DSN=GENAPP.DDBAOT74.DATA
//DDBARP74 DD DISP=SHR,DSN=GENAPP.DDBARP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE020E1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN75 DD DISP=SHR,DSN=GENAPP.DDPEIN75.DATA
//DDPEOT75 DD DISP=SHR,DSN=GENAPP.DDPEOT75.DATA
//DDPERP75 DD DISP=SHR,DSN=GENAPP.DDPERP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
