//VJOB0313 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01VUK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN40 DD DISP=SHR,DSN=GENAPP.DDENIN40.DATA
//DDENOT40 DD DISP=SHR,DSN=GENAPP.DDENOT40.DATA
//DDENRP40 DD DISP=SHR,DSN=GENAPP.DDENRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01VUL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN41 DD DISP=SHR,DSN=GENAPP.DDPAIN41.DATA
//DDPAOT41 DD DISP=SHR,DSN=GENAPP.DDPAOT41.DATA
//DDPARP41 DD DISP=SHR,DSN=GENAPP.DDPARP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01VUM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN42 DD DISP=SHR,DSN=GENAPP.DDMTIN42.DATA
//DDMTOT42 DD DISP=SHR,DSN=GENAPP.DDMTOT42.DATA
//DDMTRP42 DD DISP=SHR,DSN=GENAPP.DDMTRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
