//VJOB1280 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE01Y35
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN61 DD DISP=SHR,DSN=GENAPP.DDPEIN61.DATA
//DDPEOT61 DD DISP=SHR,DSN=GENAPP.DDPEOT61.DATA
//DDPERP61 DD DISP=SHR,DSN=GENAPP.DDPERP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01Y36
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN62 DD DISP=SHR,DSN=GENAPP.DDHOIN62.DATA
//DDHOOT62 DD DISP=SHR,DSN=GENAPP.DDHOOT62.DATA
//DDHORP62 DD DISP=SHR,DSN=GENAPP.DDHORP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE01Y37
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN63 DD DISP=SHR,DSN=GENAPP.DDHEIN63.DATA
//DDHEOT63 DD DISP=SHR,DSN=GENAPP.DDHEOT63.DATA
//DDHERP63 DD DISP=SHR,DSN=GENAPP.DDHERP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
