//VJOB3580 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW023ET
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN31 DD DISP=SHR,DSN=GENAPP.DDUWIN31.DATA
//DDUWOT31 DD DISP=SHR,DSN=GENAPP.DDUWOT31.DATA
//DDUWRP31 DD DISP=SHR,DSN=GENAPP.DDUWRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPT023EU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN32 DD DISP=SHR,DSN=GENAPP.DDPTIN32.DATA
//DDPTOT32 DD DISP=SHR,DSN=GENAPP.DDPTOT32.DATA
//DDPTRP32 DD DISP=SHR,DSN=GENAPP.DDPTRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZST023EV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN33 DD DISP=SHR,DSN=GENAPP.DDSTIN33.DATA
//DDSTOT33 DD DISP=SHR,DSN=GENAPP.DDSTOT33.DATA
//DDSTRP33 DD DISP=SHR,DSN=GENAPP.DDSTRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
