//VJOB3391 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO022Z2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN04 DD DISP=SHR,DSN=GENAPP.DDHOIN04.DATA
//DDHOOT04 DD DISP=SHR,DSN=GENAPP.DDHOOT04.DATA
//DDHORP04 DD DISP=SHR,DSN=GENAPP.DDHORP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAC022Z3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN05 DD DISP=SHR,DSN=GENAPP.DDACIN05.DATA
//DDACOT05 DD DISP=SHR,DSN=GENAPP.DDACOT05.DATA
//DDACRP05 DD DISP=SHR,DSN=GENAPP.DDACRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI022Z4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN06 DD DISP=SHR,DSN=GENAPP.DDLIIN06.DATA
//DDLIOT06 DD DISP=SHR,DSN=GENAPP.DDLIOT06.DATA
//DDLIRP06 DD DISP=SHR,DSN=GENAPP.DDLIRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
