//VJOB3232 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEX022LT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN67 DD DISP=SHR,DSN=GENAPP.DDEXIN67.DATA
//DDEXOT67 DD DISP=SHR,DSN=GENAPP.DDEXOT67.DATA
//DDEXRP67 DD DISP=SHR,DSN=GENAPP.DDEXRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI022LU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN68 DD DISP=SHR,DSN=GENAPP.DDBIIN68.DATA
//DDBIOT68 DD DISP=SHR,DSN=GENAPP.DDBIOT68.DATA
//DDBIRP68 DD DISP=SHR,DSN=GENAPP.DDBIRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF022LV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN69 DD DISP=SHR,DSN=GENAPP.DDIFIN69.DATA
//DDIFOT69 DD DISP=SHR,DSN=GENAPP.DDIFOT69.DATA
//DDIFRP69 DD DISP=SHR,DSN=GENAPP.DDIFRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
