//VJOB0272 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPR01VR5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN07 DD DISP=SHR,DSN=GENAPP.DDPRIN07.DATA
//DDPROT07 DD DISP=SHR,DSN=GENAPP.DDPROT07.DATA
//DDPRRP07 DD DISP=SHR,DSN=GENAPP.DDPRRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRC01VR6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN08 DD DISP=SHR,DSN=GENAPP.DDRCIN08.DATA
//DDRCOT08 DD DISP=SHR,DSN=GENAPP.DDRCOT08.DATA
//DDRCRP08 DD DISP=SHR,DSN=GENAPP.DDRCRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDI01VR7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN09 DD DISP=SHR,DSN=GENAPP.DDDIIN09.DATA
//DDDIOT09 DD DISP=SHR,DSN=GENAPP.DDDIOT09.DATA
//DDDIRP09 DD DISP=SHR,DSN=GENAPP.DDDIRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
