//VJOB1723 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG01Z42
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN40 DD DISP=SHR,DSN=GENAPP.DDAGIN40.DATA
//DDAGOT40 DD DISP=SHR,DSN=GENAPP.DDAGOT40.DATA
//DDAGRP40 DD DISP=SHR,DSN=GENAPP.DDAGRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01Z43
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN41 DD DISP=SHR,DSN=GENAPP.DDPAIN41.DATA
//DDPAOT41 DD DISP=SHR,DSN=GENAPP.DDPAOT41.DATA
//DDPARP41 DD DISP=SHR,DSN=GENAPP.DDPARP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSU01Z44
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN42 DD DISP=SHR,DSN=GENAPP.DDSUIN42.DATA
//DDSUOT42 DD DISP=SHR,DSN=GENAPP.DDSUOT42.DATA
//DDSURP42 DD DISP=SHR,DSN=GENAPP.DDSURP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
