//VJOB1782 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN01Z8Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN37 DD DISP=SHR,DSN=GENAPP.DDANIN37.DATA
//DDANOT37 DD DISP=SHR,DSN=GENAPP.DDANOT37.DATA
//DDANRP37 DD DISP=SHR,DSN=GENAPP.DDANRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN01Z90
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN38 DD DISP=SHR,DSN=GENAPP.DDRNIN38.DATA
//DDRNOT38 DD DISP=SHR,DSN=GENAPP.DDRNOT38.DATA
//DDRNRP38 DD DISP=SHR,DSN=GENAPP.DDRNRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01Z91
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN39 DD DISP=SHR,DSN=GENAPP.DDHOIN39.DATA
//DDHOOT39 DD DISP=SHR,DSN=GENAPP.DDHOOT39.DATA
//DDHORP39 DD DISP=SHR,DSN=GENAPP.DDHORP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
