//VJOB2524 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRN020YT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN13 DD DISP=SHR,DSN=GENAPP.DDRNIN13.DATA
//DDRNOT13 DD DISP=SHR,DSN=GENAPP.DDRNOT13.DATA
//DDRNRP13 DD DISP=SHR,DSN=GENAPP.DDRNRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB020YU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN14 DD DISP=SHR,DSN=GENAPP.DDLBIN14.DATA
//DDLBOT14 DD DISP=SHR,DSN=GENAPP.DDLBOT14.DATA
//DDLBRP14 DD DISP=SHR,DSN=GENAPP.DDLBRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI020YV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN15 DD DISP=SHR,DSN=GENAPP.DDBIIN15.DATA
//DDBIOT15 DD DISP=SHR,DSN=GENAPP.DDBIOT15.DATA
//DDBIRP15 DD DISP=SHR,DSN=GENAPP.DDBIRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
