//VJOB2147 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRT0203E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN52 DD DISP=SHR,DSN=GENAPP.DDRTIN52.DATA
//DDRTOT52 DD DISP=SHR,DSN=GENAPP.DDRTOT52.DATA
//DDRTRP52 DD DISP=SHR,DSN=GENAPP.DDRTRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA0203F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN53 DD DISP=SHR,DSN=GENAPP.DDPAIN53.DATA
//DDPAOT53 DD DISP=SHR,DSN=GENAPP.DDPAOT53.DATA
//DDPARP53 DD DISP=SHR,DSN=GENAPP.DDPARP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSB0203G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN54 DD DISP=SHR,DSN=GENAPP.DDSBIN54.DATA
//DDSBOT54 DD DISP=SHR,DSN=GENAPP.DDSBOT54.DATA
//DDSBRP54 DD DISP=SHR,DSN=GENAPP.DDSBRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
