//VJOB2811 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL021MQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN64 DD DISP=SHR,DSN=GENAPP.DDCLIN64.DATA
//DDCLOT64 DD DISP=SHR,DSN=GENAPP.DDCLOT64.DATA
//DDCLRP64 DD DISP=SHR,DSN=GENAPP.DDCLRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMB021MR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN65 DD DISP=SHR,DSN=GENAPP.DDMBIN65.DATA
//DDMBOT65 DD DISP=SHR,DSN=GENAPP.DDMBOT65.DATA
//DDMBRP65 DD DISP=SHR,DSN=GENAPP.DDMBRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO021MS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN66 DD DISP=SHR,DSN=GENAPP.DDCOIN66.DATA
//DDCOOT66 DD DISP=SHR,DSN=GENAPP.DDCOOT66.DATA
//DDCORP66 DD DISP=SHR,DSN=GENAPP.DDCORP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
