//VJOB2000 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI01ZR5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN61 DD DISP=SHR,DSN=GENAPP.DDLIIN61.DATA
//DDLIOT61 DD DISP=SHR,DSN=GENAPP.DDLIOT61.DATA
//DDLIRP61 DD DISP=SHR,DSN=GENAPP.DDLIRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAU01ZR6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN62 DD DISP=SHR,DSN=GENAPP.DDAUIN62.DATA
//DDAUOT62 DD DISP=SHR,DSN=GENAPP.DDAUOT62.DATA
//DDAURP62 DD DISP=SHR,DSN=GENAPP.DDAURP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01ZR7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN63 DD DISP=SHR,DSN=GENAPP.DDPRIN63.DATA
//DDPROT63 DD DISP=SHR,DSN=GENAPP.DDPROT63.DATA
//DDPRRP63 DD DISP=SHR,DSN=GENAPP.DDPRRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
