//VJOB0848 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS01X35
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN25 DD DISP=SHR,DSN=GENAPP.DDRSIN25.DATA
//DDRSOT25 DD DISP=SHR,DSN=GENAPP.DDRSOT25.DATA
//DDRSRP25 DD DISP=SHR,DSN=GENAPP.DDRSRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA01X36
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN26 DD DISP=SHR,DSN=GENAPP.DDMAIN26.DATA
//DDMAOT26 DD DISP=SHR,DSN=GENAPP.DDMAOT26.DATA
//DDMARP26 DD DISP=SHR,DSN=GENAPP.DDMARP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01X37
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN27 DD DISP=SHR,DSN=GENAPP.DDCUIN27.DATA
//DDCUOT27 DD DISP=SHR,DSN=GENAPP.DDCUOT27.DATA
//DDCURP27 DD DISP=SHR,DSN=GENAPP.DDCURP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
