//VJOB3515 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO0239E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN16 DD DISP=SHR,DSN=GENAPP.DDHOIN16.DATA
//DDHOOT16 DD DISP=SHR,DSN=GENAPP.DDHOOT16.DATA
//DDHORP16 DD DISP=SHR,DSN=GENAPP.DDHORP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI0239F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN17 DD DISP=SHR,DSN=GENAPP.DDLIIN17.DATA
//DDLIOT17 DD DISP=SHR,DSN=GENAPP.DDLIOT17.DATA
//DDLIRP17 DD DISP=SHR,DSN=GENAPP.DDLIRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR0239G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN18 DD DISP=SHR,DSN=GENAPP.DDARIN18.DATA
//DDAROT18 DD DISP=SHR,DSN=GENAPP.DDAROT18.DATA
//DDARRP18 DD DISP=SHR,DSN=GENAPP.DDARRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
