//VJOB3672 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO023MH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN37 DD DISP=SHR,DSN=GENAPP.DDHOIN37.DATA
//DDHOOT37 DD DISP=SHR,DSN=GENAPP.DDHOOT37.DATA
//DDHORP37 DD DISP=SHR,DSN=GENAPP.DDHORP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR023MI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN38 DD DISP=SHR,DSN=GENAPP.DDPRIN38.DATA
//DDPROT38 DD DISP=SHR,DSN=GENAPP.DDPROT38.DATA
//DDPRRP38 DD DISP=SHR,DSN=GENAPP.DDPRRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSL023MJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN39 DD DISP=SHR,DSN=GENAPP.DDSLIN39.DATA
//DDSLOT39 DD DISP=SHR,DSN=GENAPP.DDSLOT39.DATA
//DDSLRP39 DD DISP=SHR,DSN=GENAPP.DDSLRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
