//VJOB3536 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT023B5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN79 DD DISP=SHR,DSN=GENAPP.DDMTIN79.DATA
//DDMTOT79 DD DISP=SHR,DSN=GENAPP.DDMTOT79.DATA
//DDMTRP79 DD DISP=SHR,DSN=GENAPP.DDMTRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO023B6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN80 DD DISP=SHR,DSN=GENAPP.DDHOIN80.DATA
//DDHOOT80 DD DISP=SHR,DSN=GENAPP.DDHOOT80.DATA
//DDHORP80 DD DISP=SHR,DSN=GENAPP.DDHORP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR023B7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN81 DD DISP=SHR,DSN=GENAPP.DDTRIN81.DATA
//DDTROT81 DD DISP=SHR,DSN=GENAPP.DDTROT81.DATA
//DDTRRP81 DD DISP=SHR,DSN=GENAPP.DDTRRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
