//VJOB2542 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE0210B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN67 DD DISP=SHR,DSN=GENAPP.DDSEIN67.DATA
//DDSEOT67 DD DISP=SHR,DSN=GENAPP.DDSEOT67.DATA
//DDSERP67 DD DISP=SHR,DSN=GENAPP.DDSERP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ0210C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN68 DD DISP=SHR,DSN=GENAPP.DDAZIN68.DATA
//DDAZOT68 DD DISP=SHR,DSN=GENAPP.DDAZOT68.DATA
//DDAZRP68 DD DISP=SHR,DSN=GENAPP.DDAZRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG0210D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN69 DD DISP=SHR,DSN=GENAPP.DDRGIN69.DATA
//DDRGOT69 DD DISP=SHR,DSN=GENAPP.DDRGOT69.DATA
//DDRGRP69 DD DISP=SHR,DSN=GENAPP.DDRGRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
