//VJOB1452 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP01YHH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN37 DD DISP=SHR,DSN=GENAPP.DDCPIN37.DATA
//DDCPOT37 DD DISP=SHR,DSN=GENAPP.DDCPOT37.DATA
//DDCPRP37 DD DISP=SHR,DSN=GENAPP.DDCPRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE01YHI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN38 DD DISP=SHR,DSN=GENAPP.DDHEIN38.DATA
//DDHEOT38 DD DISP=SHR,DSN=GENAPP.DDHEOT38.DATA
//DDHERP38 DD DISP=SHR,DSN=GENAPP.DDHERP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT01YHJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN39 DD DISP=SHR,DSN=GENAPP.DDPTIN39.DATA
//DDPTOT39 DD DISP=SHR,DSN=GENAPP.DDPTOT39.DATA
//DDPTRP39 DD DISP=SHR,DSN=GENAPP.DDPTRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
