//VJOB2976 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT0220H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN19 DD DISP=SHR,DSN=GENAPP.DDMTIN19.DATA
//DDMTOT19 DD DISP=SHR,DSN=GENAPP.DDMTOT19.DATA
//DDMTRP19 DD DISP=SHR,DSN=GENAPP.DDMTRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0220I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN20 DD DISP=SHR,DSN=GENAPP.DDMTIN20.DATA
//DDMTOT20 DD DISP=SHR,DSN=GENAPP.DDMTOT20.DATA
//DDMTRP20 DD DISP=SHR,DSN=GENAPP.DDMTRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC0220J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN21 DD DISP=SHR,DSN=GENAPP.DDSCIN21.DATA
//DDSCOT21 DD DISP=SHR,DSN=GENAPP.DDSCOT21.DATA
//DDSCRP21 DD DISP=SHR,DSN=GENAPP.DDSCRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
