//VJOB2655 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB0219Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN46 DD DISP=SHR,DSN=GENAPP.DDMBIN46.DATA
//DDMBOT46 DD DISP=SHR,DSN=GENAPP.DDMBOT46.DATA
//DDMBRP46 DD DISP=SHR,DSN=GENAPP.DDMBRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO0219R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN47 DD DISP=SHR,DSN=GENAPP.DDHOIN47.DATA
//DDHOOT47 DD DISP=SHR,DSN=GENAPP.DDHOOT47.DATA
//DDHORP47 DD DISP=SHR,DSN=GENAPP.DDHORP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCN0219S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN48 DD DISP=SHR,DSN=GENAPP.DDCNIN48.DATA
//DDCNOT48 DD DISP=SHR,DSN=GENAPP.DDCNOT48.DATA
//DDCNRP48 DD DISP=SHR,DSN=GENAPP.DDCNRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
