//VJOB0608 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC01WJ5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN25 DD DISP=SHR,DSN=GENAPP.DDACIN25.DATA
//DDACOT25 DD DISP=SHR,DSN=GENAPP.DDACOT25.DATA
//DDACRP25 DD DISP=SHR,DSN=GENAPP.DDACRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01WJ6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN26 DD DISP=SHR,DSN=GENAPP.DDBIIN26.DATA
//DDBIOT26 DD DISP=SHR,DSN=GENAPP.DDBIOT26.DATA
//DDBIRP26 DD DISP=SHR,DSN=GENAPP.DDBIRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR01WJ7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN27 DD DISP=SHR,DSN=GENAPP.DDBRIN27.DATA
//DDBROT27 DD DISP=SHR,DSN=GENAPP.DDBROT27.DATA
//DDBRRP27 DD DISP=SHR,DSN=GENAPP.DDBRRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
