//VJOB1266 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01Y1Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN19 DD DISP=SHR,DSN=GENAPP.DDCOIN19.DATA
//DDCOOT19 DD DISP=SHR,DSN=GENAPP.DDCOOT19.DATA
//DDCORP19 DD DISP=SHR,DSN=GENAPP.DDCORP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01Y20
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN20 DD DISP=SHR,DSN=GENAPP.DDMTIN20.DATA
//DDMTOT20 DD DISP=SHR,DSN=GENAPP.DDMTOT20.DATA
//DDMTRP20 DD DISP=SHR,DSN=GENAPP.DDMTRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCR01Y21
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN21 DD DISP=SHR,DSN=GENAPP.DDCRIN21.DATA
//DDCROT21 DD DISP=SHR,DSN=GENAPP.DDCROT21.DATA
//DDCRRP21 DD DISP=SHR,DSN=GENAPP.DDCRRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
