//VJOB1173 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSC01XU8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN10 DD DISP=SHR,DSN=GENAPP.DDSCIN10.DATA
//DDSCOT10 DD DISP=SHR,DSN=GENAPP.DDSCOT10.DATA
//DDSCRP10 DD DISP=SHR,DSN=GENAPP.DDSCRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE01XU9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN11 DD DISP=SHR,DSN=GENAPP.DDSEIN11.DATA
//DDSEOT11 DD DISP=SHR,DSN=GENAPP.DDSEOT11.DATA
//DDSERP11 DD DISP=SHR,DSN=GENAPP.DDSERP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01XUA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN12 DD DISP=SHR,DSN=GENAPP.DDMAIN12.DATA
//DDMAOT12 DD DISP=SHR,DSN=GENAPP.DDMAOT12.DATA
//DDMARP12 DD DISP=SHR,DSN=GENAPP.DDMARP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
