//VJOB1096 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP01XNT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN49 DD DISP=SHR,DSN=GENAPP.DDCPIN49.DATA
//DDCPOT49 DD DISP=SHR,DSN=GENAPP.DDCPOT49.DATA
//DDCPRP49 DD DISP=SHR,DSN=GENAPP.DDCPRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01XNU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN50 DD DISP=SHR,DSN=GENAPP.DDCUIN50.DATA
//DDCUOT50 DD DISP=SHR,DSN=GENAPP.DDCUOT50.DATA
//DDCURP50 DD DISP=SHR,DSN=GENAPP.DDCURP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDO01XNV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN51 DD DISP=SHR,DSN=GENAPP.DDDOIN51.DATA
//DDDOOT51 DD DISP=SHR,DSN=GENAPP.DDDOOT51.DATA
//DDDORP51 DD DISP=SHR,DSN=GENAPP.DDDORP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
