//VJOB1736 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRT01Z55
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN79 DD DISP=SHR,DSN=GENAPP.DDRTIN79.DATA
//DDRTOT79 DD DISP=SHR,DSN=GENAPP.DDRTOT79.DATA
//DDRTRP79 DD DISP=SHR,DSN=GENAPP.DDRTRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01Z56
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN80 DD DISP=SHR,DSN=GENAPP.DDPAIN80.DATA
//DDPAOT80 DD DISP=SHR,DSN=GENAPP.DDPAOT80.DATA
//DDPARP80 DD DISP=SHR,DSN=GENAPP.DDPARP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF01Z57
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN81 DD DISP=SHR,DSN=GENAPP.DDIFIN81.DATA
//DDIFOT81 DD DISP=SHR,DSN=GENAPP.DDIFOT81.DATA
//DDIFRP81 DD DISP=SHR,DSN=GENAPP.DDIFRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
