//VJOB1463 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEX01YIE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN70 DD DISP=SHR,DSN=GENAPP.DDEXIN70.DATA
//DDEXOT70 DD DISP=SHR,DSN=GENAPP.DDEXOT70.DATA
//DDEXRP70 DD DISP=SHR,DSN=GENAPP.DDEXRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01YIF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN71 DD DISP=SHR,DSN=GENAPP.DDMTIN71.DATA
//DDMTOT71 DD DISP=SHR,DSN=GENAPP.DDMTOT71.DATA
//DDMTRP71 DD DISP=SHR,DSN=GENAPP.DDMTRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRN01YIG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN72 DD DISP=SHR,DSN=GENAPP.DDRNIN72.DATA
//DDRNOT72 DD DISP=SHR,DSN=GENAPP.DDRNOT72.DATA
//DDRNRP72 DD DISP=SHR,DSN=GENAPP.DDRNRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
