//VJOB1784 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01Z95
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN43 DD DISP=SHR,DSN=GENAPP.DDUWIN43.DATA
//DDUWOT43 DD DISP=SHR,DSN=GENAPP.DDUWOT43.DATA
//DDUWRP43 DD DISP=SHR,DSN=GENAPP.DDUWRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDI01Z96
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN44 DD DISP=SHR,DSN=GENAPP.DDDIIN44.DATA
//DDDIOT44 DD DISP=SHR,DSN=GENAPP.DDDIOT44.DATA
//DDDIRP44 DD DISP=SHR,DSN=GENAPP.DDDIRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01Z97
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN45 DD DISP=SHR,DSN=GENAPP.DDCUIN45.DATA
//DDCUOT45 DD DISP=SHR,DSN=GENAPP.DDCUOT45.DATA
//DDCURP45 DD DISP=SHR,DSN=GENAPP.DDCURP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
