//VJOB2228 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY020A5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN25 DD DISP=SHR,DSN=GENAPP.DDTYIN25.DATA
//DDTYOT25 DD DISP=SHR,DSN=GENAPP.DDTYOT25.DATA
//DDTYRP25 DD DISP=SHR,DSN=GENAPP.DDTYRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ020A6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN26 DD DISP=SHR,DSN=GENAPP.DDAZIN26.DATA
//DDAZOT26 DD DISP=SHR,DSN=GENAPP.DDAZOT26.DATA
//DDAZRP26 DD DISP=SHR,DSN=GENAPP.DDAZRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLB020A7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN27 DD DISP=SHR,DSN=GENAPP.DDLBIN27.DATA
//DDLBOT27 DD DISP=SHR,DSN=GENAPP.DDLBOT27.DATA
//DDLBRP27 DD DISP=SHR,DSN=GENAPP.DDLBRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
