//VJOB2173 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE0205K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN40 DD DISP=SHR,DSN=GENAPP.DDHEIN40.DATA
//DDHEOT40 DD DISP=SHR,DSN=GENAPP.DDHEOT40.DATA
//DDHERP40 DD DISP=SHR,DSN=GENAPP.DDHERP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO0205L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN41 DD DISP=SHR,DSN=GENAPP.DDHOIN41.DATA
//DDHOOT41 DD DISP=SHR,DSN=GENAPP.DDHOOT41.DATA
//DDHORP41 DD DISP=SHR,DSN=GENAPP.DDHORP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZVA0205M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN42 DD DISP=SHR,DSN=GENAPP.DDVAIN42.DATA
//DDVAOT42 DD DISP=SHR,DSN=GENAPP.DDVAOT42.DATA
//DDVARP42 DD DISP=SHR,DSN=GENAPP.DDVARP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
