//VJOB1251 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE01Y0Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN64 DD DISP=SHR,DSN=GENAPP.DDHEIN64.DATA
//DDHEOT64 DD DISP=SHR,DSN=GENAPP.DDHEOT64.DATA
//DDHERP64 DD DISP=SHR,DSN=GENAPP.DDHERP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01Y0R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN65 DD DISP=SHR,DSN=GENAPP.DDTXIN65.DATA
//DDTXOT65 DD DISP=SHR,DSN=GENAPP.DDTXOT65.DATA
//DDTXRP65 DD DISP=SHR,DSN=GENAPP.DDTXRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01Y0S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN66 DD DISP=SHR,DSN=GENAPP.DDENIN66.DATA
//DDENOT66 DD DISP=SHR,DSN=GENAPP.DDENOT66.DATA
//DDENRP66 DD DISP=SHR,DSN=GENAPP.DDENRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
