//VJOB0653 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG01WMW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN70 DD DISP=SHR,DSN=GENAPP.DDAGIN70.DATA
//DDAGOT70 DD DISP=SHR,DSN=GENAPP.DDAGOT70.DATA
//DDAGRP70 DD DISP=SHR,DSN=GENAPP.DDAGRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01WMX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN71 DD DISP=SHR,DSN=GENAPP.DDAGIN71.DATA
//DDAGOT71 DD DISP=SHR,DSN=GENAPP.DDAGOT71.DATA
//DDAGRP71 DD DISP=SHR,DSN=GENAPP.DDAGRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01WMY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN72 DD DISP=SHR,DSN=GENAPP.DDCUIN72.DATA
//DDCUOT72 DD DISP=SHR,DSN=GENAPP.DDCUOT72.DATA
//DDCURP72 DD DISP=SHR,DSN=GENAPP.DDCURP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
