//VJOB1622 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIF01YVN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN07 DD DISP=SHR,DSN=GENAPP.DDIFIN07.DATA
//DDIFOT07 DD DISP=SHR,DSN=GENAPP.DDIFOT07.DATA
//DDIFRP07 DD DISP=SHR,DSN=GENAPP.DDIFRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR01YVO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN08 DD DISP=SHR,DSN=GENAPP.DDCRIN08.DATA
//DDCROT08 DD DISP=SHR,DSN=GENAPP.DDCROT08.DATA
//DDCRRP08 DD DISP=SHR,DSN=GENAPP.DDCRRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01YVP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN09 DD DISP=SHR,DSN=GENAPP.DDMAIN09.DATA
//DDMAOT09 DD DISP=SHR,DSN=GENAPP.DDMAOT09.DATA
//DDMARP09 DD DISP=SHR,DSN=GENAPP.DDMARP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
