//VJOB1633 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01YWK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN40 DD DISP=SHR,DSN=GENAPP.DDMTIN40.DATA
//DDMTOT40 DD DISP=SHR,DSN=GENAPP.DDMTOT40.DATA
//DDMTRP40 DD DISP=SHR,DSN=GENAPP.DDMTRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZGW01YWL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN41 DD DISP=SHR,DSN=GENAPP.DDGWIN41.DATA
//DDGWOT41 DD DISP=SHR,DSN=GENAPP.DDGWOT41.DATA
//DDGWRP41 DD DISP=SHR,DSN=GENAPP.DDGWRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01YWM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN42 DD DISP=SHR,DSN=GENAPP.DDCLIN42.DATA
//DDCLOT42 DD DISP=SHR,DSN=GENAPP.DDCLOT42.DATA
//DDCLRP42 DD DISP=SHR,DSN=GENAPP.DDCLRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
