//VJOB4183 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL024T2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN40 DD DISP=SHR,DSN=GENAPP.DDCLIN40.DATA
//DDCLOT40 DD DISP=SHR,DSN=GENAPP.DDCLOT40.DATA
//DDCLRP40 DD DISP=SHR,DSN=GENAPP.DDCLRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZQU024T3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN41 DD DISP=SHR,DSN=GENAPP.DDQUIN41.DATA
//DDQUOT41 DD DISP=SHR,DSN=GENAPP.DDQUOT41.DATA
//DDQURP41 DD DISP=SHR,DSN=GENAPP.DDQURP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT024T4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN42 DD DISP=SHR,DSN=GENAPP.DDMTIN42.DATA
//DDMTOT42 DD DISP=SHR,DSN=GENAPP.DDMTOT42.DATA
//DDMTRP42 DD DISP=SHR,DSN=GENAPP.DDMTRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
