//VJOB2852 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEX021Q5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN07 DD DISP=SHR,DSN=GENAPP.DDEXIN07.DATA
//DDEXOT07 DD DISP=SHR,DSN=GENAPP.DDEXOT07.DATA
//DDEXRP07 DD DISP=SHR,DSN=GENAPP.DDEXRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO021Q6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN08 DD DISP=SHR,DSN=GENAPP.DDCOIN08.DATA
//DDCOOT08 DD DISP=SHR,DSN=GENAPP.DDCOOT08.DATA
//DDCORP08 DD DISP=SHR,DSN=GENAPP.DDCORP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZED021Q7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN09 DD DISP=SHR,DSN=GENAPP.DDEDIN09.DATA
//DDEDOT09 DD DISP=SHR,DSN=GENAPP.DDEDOT09.DATA
//DDEDRP09 DD DISP=SHR,DSN=GENAPP.DDEDRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
