//VJOB0864 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01X4H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN73 DD DISP=SHR,DSN=GENAPP.DDBIIN73.DATA
//DDBIOT73 DD DISP=SHR,DSN=GENAPP.DDBIOT73.DATA
//DDBIRP73 DD DISP=SHR,DSN=GENAPP.DDBIRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01X4I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN74 DD DISP=SHR,DSN=GENAPP.DDCUIN74.DATA
//DDCUOT74 DD DISP=SHR,DSN=GENAPP.DDCUOT74.DATA
//DDCURP74 DD DISP=SHR,DSN=GENAPP.DDCURP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAZ01X4J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN75 DD DISP=SHR,DSN=GENAPP.DDAZIN75.DATA
//DDAZOT75 DD DISP=SHR,DSN=GENAPP.DDAZOT75.DATA
//DDAZRP75 DD DISP=SHR,DSN=GENAPP.DDAZRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
