//VJOB3723 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA023QQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN10 DD DISP=SHR,DSN=GENAPP.DDPAIN10.DATA
//DDPAOT10 DD DISP=SHR,DSN=GENAPP.DDPAOT10.DATA
//DDPARP10 DD DISP=SHR,DSN=GENAPP.DDPARP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDI023QR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN11 DD DISP=SHR,DSN=GENAPP.DDDIIN11.DATA
//DDDIOT11 DD DISP=SHR,DSN=GENAPP.DDDIOT11.DATA
//DDDIRP11 DD DISP=SHR,DSN=GENAPP.DDDIRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN023QS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN12 DD DISP=SHR,DSN=GENAPP.DDPNIN12.DATA
//DDPNOT12 DD DISP=SHR,DSN=GENAPP.DDPNOT12.DATA
//DDPNRP12 DD DISP=SHR,DSN=GENAPP.DDPNRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
