//VJOB3922 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCN0247B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN67 DD DISP=SHR,DSN=GENAPP.DDCNIN67.DATA
//DDCNOT67 DD DISP=SHR,DSN=GENAPP.DDCNOT67.DATA
//DDCNRP67 DD DISP=SHR,DSN=GENAPP.DDCNRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR0247C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN68 DD DISP=SHR,DSN=GENAPP.DDTRIN68.DATA
//DDTROT68 DD DISP=SHR,DSN=GENAPP.DDTROT68.DATA
//DDTRRP68 DD DISP=SHR,DSN=GENAPP.DDTRRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX0247D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN69 DD DISP=SHR,DSN=GENAPP.DDTXIN69.DATA
//DDTXOT69 DD DISP=SHR,DSN=GENAPP.DDTXOT69.DATA
//DDTXRP69 DD DISP=SHR,DSN=GENAPP.DDTXRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
