//VJOB2112 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT0200H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN37 DD DISP=SHR,DSN=GENAPP.DDPTIN37.DATA
//DDPTOT37 DD DISP=SHR,DSN=GENAPP.DDPTOT37.DATA
//DDPTRP37 DD DISP=SHR,DSN=GENAPP.DDPTRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX0200I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN38 DD DISP=SHR,DSN=GENAPP.DDTXIN38.DATA
//DDTXOT38 DD DISP=SHR,DSN=GENAPP.DDTXOT38.DATA
//DDTXRP38 DD DISP=SHR,DSN=GENAPP.DDTXRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEX0200J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN39 DD DISP=SHR,DSN=GENAPP.DDEXIN39.DATA
//DDEXOT39 DD DISP=SHR,DSN=GENAPP.DDEXOT39.DATA
//DDEXRP39 DD DISP=SHR,DSN=GENAPP.DDEXRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
