//VJOB1760 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV01Z75
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN61 DD DISP=SHR,DSN=GENAPP.DDIVIN61.DATA
//DDIVOT61 DD DISP=SHR,DSN=GENAPP.DDIVOT61.DATA
//DDIVRP61 DD DISP=SHR,DSN=GENAPP.DDIVRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSU01Z76
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN62 DD DISP=SHR,DSN=GENAPP.DDSUIN62.DATA
//DDSUOT62 DD DISP=SHR,DSN=GENAPP.DDSUOT62.DATA
//DDSURP62 DD DISP=SHR,DSN=GENAPP.DDSURP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01Z77
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN63 DD DISP=SHR,DSN=GENAPP.DDCUIN63.DATA
//DDCUOT63 DD DISP=SHR,DSN=GENAPP.DDCUOT63.DATA
//DDCURP63 DD DISP=SHR,DSN=GENAPP.DDCURP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
