//VJOB1942 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01ZMB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN67 DD DISP=SHR,DSN=GENAPP.DDHOIN67.DATA
//DDHOOT67 DD DISP=SHR,DSN=GENAPP.DDHOOT67.DATA
//DDHORP67 DD DISP=SHR,DSN=GENAPP.DDHORP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAU01ZMC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN68 DD DISP=SHR,DSN=GENAPP.DDAUIN68.DATA
//DDAUOT68 DD DISP=SHR,DSN=GENAPP.DDAUOT68.DATA
//DDAURP68 DD DISP=SHR,DSN=GENAPP.DDAURP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSB01ZMD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN69 DD DISP=SHR,DSN=GENAPP.DDSBIN69.DATA
//DDSBOT69 DD DISP=SHR,DSN=GENAPP.DDSBOT69.DATA
//DDSBRP69 DD DISP=SHR,DSN=GENAPP.DDSBRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
