//VJOB3863 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT0242E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN70 DD DISP=SHR,DSN=GENAPP.DDNTIN70.DATA
//DDNTOT70 DD DISP=SHR,DSN=GENAPP.DDNTOT70.DATA
//DDNTRP70 DD DISP=SHR,DSN=GENAPP.DDNTRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV0242F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN71 DD DISP=SHR,DSN=GENAPP.DDIVIN71.DATA
//DDIVOT71 DD DISP=SHR,DSN=GENAPP.DDIVOT71.DATA
//DDIVRP71 DD DISP=SHR,DSN=GENAPP.DDIVRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT0242G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN72 DD DISP=SHR,DSN=GENAPP.DDMTIN72.DATA
//DDMTOT72 DD DISP=SHR,DSN=GENAPP.DDMTOT72.DATA
//DDMTRP72 DD DISP=SHR,DSN=GENAPP.DDMTRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
