//VJOB4189 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT024TK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN58 DD DISP=SHR,DSN=GENAPP.DDMTIN58.DATA
//DDMTOT58 DD DISP=SHR,DSN=GENAPP.DDMTOT58.DATA
//DDMTRP58 DD DISP=SHR,DSN=GENAPP.DDMTRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV024TL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN59 DD DISP=SHR,DSN=GENAPP.DDIVIN59.DATA
//DDIVOT59 DD DISP=SHR,DSN=GENAPP.DDIVOT59.DATA
//DDIVRP59 DD DISP=SHR,DSN=GENAPP.DDIVRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT024TM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN60 DD DISP=SHR,DSN=GENAPP.DDMTIN60.DATA
//DDMTOT60 DD DISP=SHR,DSN=GENAPP.DDMTOT60.DATA
//DDMTRP60 DD DISP=SHR,DSN=GENAPP.DDMTRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
