//VJOB3507 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU0238Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN82 DD DISP=SHR,DSN=GENAPP.DDCUIN82.DATA
//DDCUOT82 DD DISP=SHR,DSN=GENAPP.DDCUOT82.DATA
//DDCURP82 DD DISP=SHR,DSN=GENAPP.DDCURP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI0238R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN83 DD DISP=SHR,DSN=GENAPP.DDBIIN83.DATA
//DDBIOT83 DD DISP=SHR,DSN=GENAPP.DDBIOT83.DATA
//DDBIRP83 DD DISP=SHR,DSN=GENAPP.DDBIRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG0238S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN84 DD DISP=SHR,DSN=GENAPP.DDAGIN84.DATA
//DDAGOT84 DD DISP=SHR,DSN=GENAPP.DDAGOT84.DATA
//DDAGRP84 DD DISP=SHR,DSN=GENAPP.DDAGRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
