//VJOB2272 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPR020DT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN67 DD DISP=SHR,DSN=GENAPP.DDPRIN67.DATA
//DDPROT67 DD DISP=SHR,DSN=GENAPP.DDPROT67.DATA
//DDPRRP67 DD DISP=SHR,DSN=GENAPP.DDPRRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZVA020DU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN68 DD DISP=SHR,DSN=GENAPP.DDVAIN68.DATA
//DDVAOT68 DD DISP=SHR,DSN=GENAPP.DDVAOT68.DATA
//DDVARP68 DD DISP=SHR,DSN=GENAPP.DDVARP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU020DV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN69 DD DISP=SHR,DSN=GENAPP.DDCUIN69.DATA
//DDCUOT69 DD DISP=SHR,DSN=GENAPP.DDCUOT69.DATA
//DDCURP69 DD DISP=SHR,DSN=GENAPP.DDCURP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
