//VJOB2821 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX021NK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN04 DD DISP=SHR,DSN=GENAPP.DDTXIN04.DATA
//DDTXOT04 DD DISP=SHR,DSN=GENAPP.DDTXOT04.DATA
//DDTXRP04 DD DISP=SHR,DSN=GENAPP.DDTXRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE021NL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN05 DD DISP=SHR,DSN=GENAPP.DDREIN05.DATA
//DDREOT05 DD DISP=SHR,DSN=GENAPP.DDREOT05.DATA
//DDRERP05 DD DISP=SHR,DSN=GENAPP.DDRERP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZQU021NM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN06 DD DISP=SHR,DSN=GENAPP.DDQUIN06.DATA
//DDQUOT06 DD DISP=SHR,DSN=GENAPP.DDQUOT06.DATA
//DDQURP06 DD DISP=SHR,DSN=GENAPP.DDQURP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
