//VJOB1838 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT01ZDN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN25 DD DISP=SHR,DSN=GENAPP.DDNTIN25.DATA
//DDNTOT25 DD DISP=SHR,DSN=GENAPP.DDNTOT25.DATA
//DDNTRP25 DD DISP=SHR,DSN=GENAPP.DDNTRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZQU01ZDO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN26 DD DISP=SHR,DSN=GENAPP.DDQUIN26.DATA
//DDQUOT26 DD DISP=SHR,DSN=GENAPP.DDQUOT26.DATA
//DDQURP26 DD DISP=SHR,DSN=GENAPP.DDQURP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01ZDP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN27 DD DISP=SHR,DSN=GENAPP.DDCUIN27.DATA
//DDCUOT27 DD DISP=SHR,DSN=GENAPP.DDCUOT27.DATA
//DDCURP27 DD DISP=SHR,DSN=GENAPP.DDCURP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
