//VJOB0785 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01WXW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN16 DD DISP=SHR,DSN=GENAPP.DDCUIN16.DATA
//DDCUOT16 DD DISP=SHR,DSN=GENAPP.DDCUOT16.DATA
//DDCURP16 DD DISP=SHR,DSN=GENAPP.DDCURP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE01WXX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN17 DD DISP=SHR,DSN=GENAPP.DDREIN17.DATA
//DDREOT17 DD DISP=SHR,DSN=GENAPP.DDREOT17.DATA
//DDRERP17 DD DISP=SHR,DSN=GENAPP.DDRERP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01WXY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN18 DD DISP=SHR,DSN=GENAPP.DDENIN18.DATA
//DDENOT18 DD DISP=SHR,DSN=GENAPP.DDENOT18.DATA
//DDENRP18 DD DISP=SHR,DSN=GENAPP.DDENRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
