//VJOB3991 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI024D2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN04 DD DISP=SHR,DSN=GENAPP.DDBIIN04.DATA
//DDBIOT04 DD DISP=SHR,DSN=GENAPP.DDBIOT04.DATA
//DDBIRP04 DD DISP=SHR,DSN=GENAPP.DDBIRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE024D3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN05 DD DISP=SHR,DSN=GENAPP.DDHEIN05.DATA
//DDHEOT05 DD DISP=SHR,DSN=GENAPP.DDHEOT05.DATA
//DDHERP05 DD DISP=SHR,DSN=GENAPP.DDHERP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL024D4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN06 DD DISP=SHR,DSN=GENAPP.DDCLIN06.DATA
//DDCLOT06 DD DISP=SHR,DSN=GENAPP.DDCLOT06.DATA
//DDCLRP06 DD DISP=SHR,DSN=GENAPP.DDCLRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
