//VJOB1196 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01XW5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN79 DD DISP=SHR,DSN=GENAPP.DDHOIN79.DATA
//DDHOOT79 DD DISP=SHR,DSN=GENAPP.DDHOOT79.DATA
//DDHORP79 DD DISP=SHR,DSN=GENAPP.DDHORP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC01XW6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN80 DD DISP=SHR,DSN=GENAPP.DDSCIN80.DATA
//DDSCOT80 DD DISP=SHR,DSN=GENAPP.DDSCOT80.DATA
//DDSCRP80 DD DISP=SHR,DSN=GENAPP.DDSCRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01XW7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN81 DD DISP=SHR,DSN=GENAPP.DDBIIN81.DATA
//DDBIOT81 DD DISP=SHR,DSN=GENAPP.DDBIOT81.DATA
//DDBIRP81 DD DISP=SHR,DSN=GENAPP.DDBIRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
