//VJOB4155 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPR024QQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN46 DD DISP=SHR,DSN=GENAPP.DDPRIN46.DATA
//DDPROT46 DD DISP=SHR,DSN=GENAPP.DDPROT46.DATA
//DDPRRP46 DD DISP=SHR,DSN=GENAPP.DDPRRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR024QR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN47 DD DISP=SHR,DSN=GENAPP.DDTRIN47.DATA
//DDTROT47 DD DISP=SHR,DSN=GENAPP.DDTROT47.DATA
//DDTRRP47 DD DISP=SHR,DSN=GENAPP.DDTRRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDO024QS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN48 DD DISP=SHR,DSN=GENAPP.DDDOIN48.DATA
//DDDOOT48 DD DISP=SHR,DSN=GENAPP.DDDOOT48.DATA
//DDDORP48 DD DISP=SHR,DSN=GENAPP.DDDORP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
