//VJOB2233 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAR020AK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN40 DD DISP=SHR,DSN=GENAPP.DDARIN40.DATA
//DDAROT40 DD DISP=SHR,DSN=GENAPP.DDAROT40.DATA
//DDARRP40 DD DISP=SHR,DSN=GENAPP.DDARRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI020AL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN41 DD DISP=SHR,DSN=GENAPP.DDLIIN41.DATA
//DDLIOT41 DD DISP=SHR,DSN=GENAPP.DDLIOT41.DATA
//DDLIRP41 DD DISP=SHR,DSN=GENAPP.DDLIRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL020AM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN42 DD DISP=SHR,DSN=GENAPP.DDCLIN42.DATA
//DDCLOT42 DD DISP=SHR,DSN=GENAPP.DDCLOT42.DATA
//DDCLRP42 DD DISP=SHR,DSN=GENAPP.DDCLRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
