//VJOB3302 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN022RN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN07 DD DISP=SHR,DSN=GENAPP.DDANIN07.DATA
//DDANOT07 DD DISP=SHR,DSN=GENAPP.DDANOT07.DATA
//DDANRP07 DD DISP=SHR,DSN=GENAPP.DDANRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT022RO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN08 DD DISP=SHR,DSN=GENAPP.DDMTIN08.DATA
//DDMTOT08 DD DISP=SHR,DSN=GENAPP.DDMTOT08.DATA
//DDMTRP08 DD DISP=SHR,DSN=GENAPP.DDMTRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT022RP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN09 DD DISP=SHR,DSN=GENAPP.DDPTIN09.DATA
//DDPTOT09 DD DISP=SHR,DSN=GENAPP.DDPTOT09.DATA
//DDPTRP09 DD DISP=SHR,DSN=GENAPP.DDPTRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
