//VJOB1984 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF01ZPT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN13 DD DISP=SHR,DSN=GENAPP.DDWFIN13.DATA
//DDWFOT13 DD DISP=SHR,DSN=GENAPP.DDWFOT13.DATA
//DDWFRP13 DD DISP=SHR,DSN=GENAPP.DDWFRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01ZPU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN14 DD DISP=SHR,DSN=GENAPP.DDHOIN14.DATA
//DDHOOT14 DD DISP=SHR,DSN=GENAPP.DDHOOT14.DATA
//DDHORP14 DD DISP=SHR,DSN=GENAPP.DDHORP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRN01ZPV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN15 DD DISP=SHR,DSN=GENAPP.DDRNIN15.DATA
//DDRNOT15 DD DISP=SHR,DSN=GENAPP.DDRNOT15.DATA
//DDRNRP15 DD DISP=SHR,DSN=GENAPP.DDRNRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
