//VJOB1864 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01ZFT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN13 DD DISP=SHR,DSN=GENAPP.DDUWIN13.DATA
//DDUWOT13 DD DISP=SHR,DSN=GENAPP.DDUWOT13.DATA
//DDUWRP13 DD DISP=SHR,DSN=GENAPP.DDUWRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01ZFU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN14 DD DISP=SHR,DSN=GENAPP.DDAGIN14.DATA
//DDAGOT14 DD DISP=SHR,DSN=GENAPP.DDAGOT14.DATA
//DDAGRP14 DD DISP=SHR,DSN=GENAPP.DDAGRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZVA01ZFV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN15 DD DISP=SHR,DSN=GENAPP.DDVAIN15.DATA
//DDVAOT15 DD DISP=SHR,DSN=GENAPP.DDVAOT15.DATA
//DDVARP15 DD DISP=SHR,DSN=GENAPP.DDVARP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
