//VJOB3532 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT023AT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN67 DD DISP=SHR,DSN=GENAPP.DDMTIN67.DATA
//DDMTOT67 DD DISP=SHR,DSN=GENAPP.DDMTOT67.DATA
//DDMTRP67 DD DISP=SHR,DSN=GENAPP.DDMTRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZQU023AU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN68 DD DISP=SHR,DSN=GENAPP.DDQUIN68.DATA
//DDQUOT68 DD DISP=SHR,DSN=GENAPP.DDQUOT68.DATA
//DDQURP68 DD DISP=SHR,DSN=GENAPP.DDQURP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDO023AV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN69 DD DISP=SHR,DSN=GENAPP.DDDOIN69.DATA
//DDDOOT69 DD DISP=SHR,DSN=GENAPP.DDDOOT69.DATA
//DDDORP69 DD DISP=SHR,DSN=GENAPP.DDDORP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
