//VJOB0181 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI01VJK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN04 DD DISP=SHR,DSN=GENAPP.DDLIIN04.DATA
//DDLIOT04 DD DISP=SHR,DSN=GENAPP.DDLIOT04.DATA
//DDLIRP04 DD DISP=SHR,DSN=GENAPP.DDLIRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN01VJL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN05 DD DISP=SHR,DSN=GENAPP.DDANIN05.DATA
//DDANOT05 DD DISP=SHR,DSN=GENAPP.DDANOT05.DATA
//DDANRP05 DD DISP=SHR,DSN=GENAPP.DDANRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC01VJM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN06 DD DISP=SHR,DSN=GENAPP.DDSCIN06.DATA
//DDSCOT06 DD DISP=SHR,DSN=GENAPP.DDSCOT06.DATA
//DDSCRP06 DD DISP=SHR,DSN=GENAPP.DDSCRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
