//VJOB1146 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE01XRZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN19 DD DISP=SHR,DSN=GENAPP.DDSEIN19.DATA
//DDSEOT19 DD DISP=SHR,DSN=GENAPP.DDSEOT19.DATA
//DDSERP19 DD DISP=SHR,DSN=GENAPP.DDSERP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01XS0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN20 DD DISP=SHR,DSN=GENAPP.DDLIIN20.DATA
//DDLIOT20 DD DISP=SHR,DSN=GENAPP.DDLIOT20.DATA
//DDLIRP20 DD DISP=SHR,DSN=GENAPP.DDLIRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW01XS1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN21 DD DISP=SHR,DSN=GENAPP.DDUWIN21.DATA
//DDUWOT21 DD DISP=SHR,DSN=GENAPP.DDUWOT21.DATA
//DDUWRP21 DD DISP=SHR,DSN=GENAPP.DDUWRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
