//VJOB3903 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO0245Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN10 DD DISP=SHR,DSN=GENAPP.DDHOIN10.DATA
//DDHOOT10 DD DISP=SHR,DSN=GENAPP.DDHOOT10.DATA
//DDHORP10 DD DISP=SHR,DSN=GENAPP.DDHORP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN0245R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN11 DD DISP=SHR,DSN=GENAPP.DDENIN11.DATA
//DDENOT11 DD DISP=SHR,DSN=GENAPP.DDENOT11.DATA
//DDENRP11 DD DISP=SHR,DSN=GENAPP.DDENRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE0245S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN12 DD DISP=SHR,DSN=GENAPP.DDREIN12.DATA
//DDREOT12 DD DISP=SHR,DSN=GENAPP.DDREOT12.DATA
//DDRERP12 DD DISP=SHR,DSN=GENAPP.DDRERP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
