//VJOB0775 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN01WX2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN76 DD DISP=SHR,DSN=GENAPP.DDPNIN76.DATA
//DDPNOT76 DD DISP=SHR,DSN=GENAPP.DDPNOT76.DATA
//DDPNRP76 DD DISP=SHR,DSN=GENAPP.DDPNRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN01WX3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN77 DD DISP=SHR,DSN=GENAPP.DDENIN77.DATA
//DDENOT77 DD DISP=SHR,DSN=GENAPP.DDENOT77.DATA
//DDENRP77 DD DISP=SHR,DSN=GENAPP.DDENRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01WX4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN78 DD DISP=SHR,DSN=GENAPP.DDTRIN78.DATA
//DDTROT78 DD DISP=SHR,DSN=GENAPP.DDTROT78.DATA
//DDTRRP78 DD DISP=SHR,DSN=GENAPP.DDTRRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
