//VJOB4324 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL0254T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN13 DD DISP=SHR,DSN=GENAPP.DDCLIN13.DATA
//DDCLOT13 DD DISP=SHR,DSN=GENAPP.DDCLOT13.DATA
//DDCLRP13 DD DISP=SHR,DSN=GENAPP.DDCLRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0254U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN14 DD DISP=SHR,DSN=GENAPP.DDMTIN14.DATA
//DDMTOT14 DD DISP=SHR,DSN=GENAPP.DDMTOT14.DATA
//DDMTRP14 DD DISP=SHR,DSN=GENAPP.DDMTRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO0254V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN15 DD DISP=SHR,DSN=GENAPP.DDCOIN15.DATA
//DDCOOT15 DD DISP=SHR,DSN=GENAPP.DDCOOT15.DATA
//DDCORP15 DD DISP=SHR,DSN=GENAPP.DDCORP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
