//VJOB3159 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX022FQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN28 DD DISP=SHR,DSN=GENAPP.DDTXIN28.DATA
//DDTXOT28 DD DISP=SHR,DSN=GENAPP.DDTXOT28.DATA
//DDTXRP28 DD DISP=SHR,DSN=GENAPP.DDTXRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN022FR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN29 DD DISP=SHR,DSN=GENAPP.DDPNIN29.DATA
//DDPNOT29 DD DISP=SHR,DSN=GENAPP.DDPNOT29.DATA
//DDPNRP29 DD DISP=SHR,DSN=GENAPP.DDPNRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR022FS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN30 DD DISP=SHR,DSN=GENAPP.DDFRIN30.DATA
//DDFROT30 DD DISP=SHR,DSN=GENAPP.DDFROT30.DATA
//DDFRRP30 DD DISP=SHR,DSN=GENAPP.DDFRRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
