//VJOB3812 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB023Y5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN07 DD DISP=SHR,DSN=GENAPP.DDLBIN07.DATA
//DDLBOT07 DD DISP=SHR,DSN=GENAPP.DDLBOT07.DATA
//DDLBRP07 DD DISP=SHR,DSN=GENAPP.DDLBRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO023Y6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN08 DD DISP=SHR,DSN=GENAPP.DDHOIN08.DATA
//DDHOOT08 DD DISP=SHR,DSN=GENAPP.DDHOOT08.DATA
//DDHORP08 DD DISP=SHR,DSN=GENAPP.DDHORP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN023Y7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN09 DD DISP=SHR,DSN=GENAPP.DDENIN09.DATA
//DDENOT09 DD DISP=SHR,DSN=GENAPP.DDENOT09.DATA
//DDENRP09 DD DISP=SHR,DSN=GENAPP.DDENRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
