//VJOB2906 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC021UN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN79 DD DISP=SHR,DSN=GENAPP.DDACIN79.DATA
//DDACOT79 DD DISP=SHR,DSN=GENAPP.DDACOT79.DATA
//DDACRP79 DD DISP=SHR,DSN=GENAPP.DDACRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO021UO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN80 DD DISP=SHR,DSN=GENAPP.DDCOIN80.DATA
//DDCOOT80 DD DISP=SHR,DSN=GENAPP.DDCOOT80.DATA
//DDCORP80 DD DISP=SHR,DSN=GENAPP.DDCORP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRN021UP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN81 DD DISP=SHR,DSN=GENAPP.DDRNIN81.DATA
//DDRNOT81 DD DISP=SHR,DSN=GENAPP.DDRNOT81.DATA
//DDRNRP81 DD DISP=SHR,DSN=GENAPP.DDRNRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
