//VJOB3292 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL022QT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN67 DD DISP=SHR,DSN=GENAPP.DDFLIN67.DATA
//DDFLOT67 DD DISP=SHR,DSN=GENAPP.DDFLOT67.DATA
//DDFLRP67 DD DISP=SHR,DSN=GENAPP.DDFLRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB022QU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN68 DD DISP=SHR,DSN=GENAPP.DDLBIN68.DATA
//DDLBOT68 DD DISP=SHR,DSN=GENAPP.DDLBOT68.DATA
//DDLBRP68 DD DISP=SHR,DSN=GENAPP.DDLBRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCP022QV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN69 DD DISP=SHR,DSN=GENAPP.DDCPIN69.DATA
//DDCPOT69 DD DISP=SHR,DSN=GENAPP.DDCPOT69.DATA
//DDCPRP69 DD DISP=SHR,DSN=GENAPP.DDCPRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
