//VJOB2473 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW020UK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN40 DD DISP=SHR,DSN=GENAPP.DDUWIN40.DATA
//DDUWOT40 DD DISP=SHR,DSN=GENAPP.DDUWOT40.DATA
//DDUWRP40 DD DISP=SHR,DSN=GENAPP.DDUWRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL020UL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN41 DD DISP=SHR,DSN=GENAPP.DDCLIN41.DATA
//DDCLOT41 DD DISP=SHR,DSN=GENAPP.DDCLOT41.DATA
//DDCLRP41 DD DISP=SHR,DSN=GENAPP.DDCLRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO020UM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN42 DD DISP=SHR,DSN=GENAPP.DDHOIN42.DATA
//DDHOOT42 DD DISP=SHR,DSN=GENAPP.DDHOOT42.DATA
//DDHORP42 DD DISP=SHR,DSN=GENAPP.DDHORP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
