//VJOB2056 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01ZVT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN49 DD DISP=SHR,DSN=GENAPP.DDCUIN49.DATA
//DDCUOT49 DD DISP=SHR,DSN=GENAPP.DDCUOT49.DATA
//DDCURP49 DD DISP=SHR,DSN=GENAPP.DDCURP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE01ZVU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN50 DD DISP=SHR,DSN=GENAPP.DDSEIN50.DATA
//DDSEOT50 DD DISP=SHR,DSN=GENAPP.DDSEOT50.DATA
//DDSERP50 DD DISP=SHR,DSN=GENAPP.DDSERP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01ZVV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN51 DD DISP=SHR,DSN=GENAPP.DDCLIN51.DATA
//DDCLOT51 DD DISP=SHR,DSN=GENAPP.DDCLOT51.DATA
//DDCLRP51 DD DISP=SHR,DSN=GENAPP.DDCLRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
