//VJOB0708 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA01WRH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN55 DD DISP=SHR,DSN=GENAPP.DDMAIN55.DATA
//DDMAOT55 DD DISP=SHR,DSN=GENAPP.DDMAOT55.DATA
//DDMARP55 DD DISP=SHR,DSN=GENAPP.DDMARP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA01WRI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN56 DD DISP=SHR,DSN=GENAPP.DDMAIN56.DATA
//DDMAOT56 DD DISP=SHR,DSN=GENAPP.DDMAOT56.DATA
//DDMARP56 DD DISP=SHR,DSN=GENAPP.DDMARP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01WRJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN57 DD DISP=SHR,DSN=GENAPP.DDREIN57.DATA
//DDREOT57 DD DISP=SHR,DSN=GENAPP.DDREOT57.DATA
//DDRERP57 DD DISP=SHR,DSN=GENAPP.DDRERP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
