//VJOB0846 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01X2Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN19 DD DISP=SHR,DSN=GENAPP.DDMTIN19.DATA
//DDMTOT19 DD DISP=SHR,DSN=GENAPP.DDMTOT19.DATA
//DDMTRP19 DD DISP=SHR,DSN=GENAPP.DDMTRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW01X30
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN20 DD DISP=SHR,DSN=GENAPP.DDUWIN20.DATA
//DDUWOT20 DD DISP=SHR,DSN=GENAPP.DDUWOT20.DATA
//DDUWRP20 DD DISP=SHR,DSN=GENAPP.DDUWRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX01X31
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN21 DD DISP=SHR,DSN=GENAPP.DDTXIN21.DATA
//DDTXOT21 DD DISP=SHR,DSN=GENAPP.DDTXOT21.DATA
//DDTXRP21 DD DISP=SHR,DSN=GENAPP.DDTXRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
