//VJOB0817 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRN01X0K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN22 DD DISP=SHR,DSN=GENAPP.DDRNIN22.DATA
//DDRNOT22 DD DISP=SHR,DSN=GENAPP.DDRNOT22.DATA
//DDRNRP22 DD DISP=SHR,DSN=GENAPP.DDRNRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRS01X0L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN23 DD DISP=SHR,DSN=GENAPP.DDRSIN23.DATA
//DDRSOT23 DD DISP=SHR,DSN=GENAPP.DDRSOT23.DATA
//DDRSRP23 DD DISP=SHR,DSN=GENAPP.DDRSRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR01X0M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN24 DD DISP=SHR,DSN=GENAPP.DDBRIN24.DATA
//DDBROT24 DD DISP=SHR,DSN=GENAPP.DDBROT24.DATA
//DDBRRP24 DD DISP=SHR,DSN=GENAPP.DDBRRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
