//VJOB0991 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01XF2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN04 DD DISP=SHR,DSN=GENAPP.DDMTIN04.DATA
//DDMTOT04 DD DISP=SHR,DSN=GENAPP.DDMTOT04.DATA
//DDMTRP04 DD DISP=SHR,DSN=GENAPP.DDMTRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01XF3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN05 DD DISP=SHR,DSN=GENAPP.DDPAIN05.DATA
//DDPAOT05 DD DISP=SHR,DSN=GENAPP.DDPAOT05.DATA
//DDPARP05 DD DISP=SHR,DSN=GENAPP.DDPARP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01XF4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN06 DD DISP=SHR,DSN=GENAPP.DDMAIN06.DATA
//DDMAOT06 DD DISP=SHR,DSN=GENAPP.DDMAOT06.DATA
//DDMARP06 DD DISP=SHR,DSN=GENAPP.DDMARP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
