//VJOB3451 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO02342
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN04 DD DISP=SHR,DSN=GENAPP.DDHOIN04.DATA
//DDHOOT04 DD DISP=SHR,DSN=GENAPP.DDHOOT04.DATA
//DDHORP04 DD DISP=SHR,DSN=GENAPP.DDHORP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR02343
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN05 DD DISP=SHR,DSN=GENAPP.DDBRIN05.DATA
//DDBROT05 DD DISP=SHR,DSN=GENAPP.DDBROT05.DATA
//DDBRRP05 DD DISP=SHR,DSN=GENAPP.DDBRRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW02344
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN06 DD DISP=SHR,DSN=GENAPP.DDUWIN06.DATA
//DDUWOT06 DD DISP=SHR,DSN=GENAPP.DDUWOT06.DATA
//DDUWRP06 DD DISP=SHR,DSN=GENAPP.DDUWRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
