//VJOB2518 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR020YB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN85 DD DISP=SHR,DSN=GENAPP.DDTRIN85.DATA
//DDTROT85 DD DISP=SHR,DSN=GENAPP.DDTROT85.DATA
//DDTRRP85 DD DISP=SHR,DSN=GENAPP.DDTRRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDO020YC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN86 DD DISP=SHR,DSN=GENAPP.DDDOIN86.DATA
//DDDOOT86 DD DISP=SHR,DSN=GENAPP.DDDOOT86.DATA
//DDDORP86 DD DISP=SHR,DSN=GENAPP.DDDORP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV020YD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN87 DD DISP=SHR,DSN=GENAPP.DDIVIN87.DATA
//DDIVOT87 DD DISP=SHR,DSN=GENAPP.DDIVOT87.DATA
//DDIVRP87 DD DISP=SHR,DSN=GENAPP.DDIVRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
