//VJOB1778 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE01Z8N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN25 DD DISP=SHR,DSN=GENAPP.DDHEIN25.DATA
//DDHEOT25 DD DISP=SHR,DSN=GENAPP.DDHEOT25.DATA
//DDHERP25 DD DISP=SHR,DSN=GENAPP.DDHERP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZED01Z8O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN26 DD DISP=SHR,DSN=GENAPP.DDEDIN26.DATA
//DDEDOT26 DD DISP=SHR,DSN=GENAPP.DDEDOT26.DATA
//DDEDRP26 DD DISP=SHR,DSN=GENAPP.DDEDRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX01Z8P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN27 DD DISP=SHR,DSN=GENAPP.DDTXIN27.DATA
//DDTXOT27 DD DISP=SHR,DSN=GENAPP.DDTXOT27.DATA
//DDTXRP27 DD DISP=SHR,DSN=GENAPP.DDTXRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
