//VJOB0306 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA01VTZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN19 DD DISP=SHR,DSN=GENAPP.DDMAIN19.DATA
//DDMAOT19 DD DISP=SHR,DSN=GENAPP.DDMAOT19.DATA
//DDMARP19 DD DISP=SHR,DSN=GENAPP.DDMARP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC01VU0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN20 DD DISP=SHR,DSN=GENAPP.DDSCIN20.DATA
//DDSCOT20 DD DISP=SHR,DSN=GENAPP.DDSCOT20.DATA
//DDSCRP20 DD DISP=SHR,DSN=GENAPP.DDSCRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN01VU1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN21 DD DISP=SHR,DSN=GENAPP.DDPNIN21.DATA
//DDPNOT21 DD DISP=SHR,DSN=GENAPP.DDPNOT21.DATA
//DDPNRP21 DD DISP=SHR,DSN=GENAPP.DDPNRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
