//VJOB2861 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB021QW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN34 DD DISP=SHR,DSN=GENAPP.DDLBIN34.DATA
//DDLBOT34 DD DISP=SHR,DSN=GENAPP.DDLBOT34.DATA
//DDLBRP34 DD DISP=SHR,DSN=GENAPP.DDLBRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR021QX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN35 DD DISP=SHR,DSN=GENAPP.DDBRIN35.DATA
//DDBROT35 DD DISP=SHR,DSN=GENAPP.DDBROT35.DATA
//DDBRRP35 DD DISP=SHR,DSN=GENAPP.DDBRRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL021QY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN36 DD DISP=SHR,DSN=GENAPP.DDCLIN36.DATA
//DDCLOT36 DD DISP=SHR,DSN=GENAPP.DDCLOT36.DATA
//DDCLRP36 DD DISP=SHR,DSN=GENAPP.DDCLRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
