//VJOB2546 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT0210N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN79 DD DISP=SHR,DSN=GENAPP.DDNTIN79.DATA
//DDNTOT79 DD DISP=SHR,DSN=GENAPP.DDNTOT79.DATA
//DDNTRP79 DD DISP=SHR,DSN=GENAPP.DDNTRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN0210O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN80 DD DISP=SHR,DSN=GENAPP.DDRNIN80.DATA
//DDRNOT80 DD DISP=SHR,DSN=GENAPP.DDRNOT80.DATA
//DDRNRP80 DD DISP=SHR,DSN=GENAPP.DDRNRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSL0210P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN81 DD DISP=SHR,DSN=GENAPP.DDSLIN81.DATA
//DDSLOT81 DD DISP=SHR,DSN=GENAPP.DDSLOT81.DATA
//DDSLRP81 DD DISP=SHR,DSN=GENAPP.DDSLRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
