//VJOB0893 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI01X6W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN70 DD DISP=SHR,DSN=GENAPP.DDLIIN70.DATA
//DDLIOT70 DD DISP=SHR,DSN=GENAPP.DDLIOT70.DATA
//DDLIRP70 DD DISP=SHR,DSN=GENAPP.DDLIRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01X6X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN71 DD DISP=SHR,DSN=GENAPP.DDCLIN71.DATA
//DDCLOT71 DD DISP=SHR,DSN=GENAPP.DDCLOT71.DATA
//DDCLRP71 DD DISP=SHR,DSN=GENAPP.DDCLRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZED01X6Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN72 DD DISP=SHR,DSN=GENAPP.DDEDIN72.DATA
//DDEDOT72 DD DISP=SHR,DSN=GENAPP.DDEDOT72.DATA
//DDEDRP72 DD DISP=SHR,DSN=GENAPP.DDEDRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
