//VJOB3556 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE023CT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN49 DD DISP=SHR,DSN=GENAPP.DDPEIN49.DATA
//DDPEOT49 DD DISP=SHR,DSN=GENAPP.DDPEOT49.DATA
//DDPERP49 DD DISP=SHR,DSN=GENAPP.DDPERP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPT023CU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN50 DD DISP=SHR,DSN=GENAPP.DDPTIN50.DATA
//DDPTOT50 DD DISP=SHR,DSN=GENAPP.DDPTOT50.DATA
//DDPTRP50 DD DISP=SHR,DSN=GENAPP.DDPTRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRC023CV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN51 DD DISP=SHR,DSN=GENAPP.DDRCIN51.DATA
//DDRCOT51 DD DISP=SHR,DSN=GENAPP.DDRCOT51.DATA
//DDRCRP51 DD DISP=SHR,DSN=GENAPP.DDRCRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
