//VJOB3288 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIF022QH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN55 DD DISP=SHR,DSN=GENAPP.DDIFIN55.DATA
//DDIFOT55 DD DISP=SHR,DSN=GENAPP.DDIFOT55.DATA
//DDIFRP55 DD DISP=SHR,DSN=GENAPP.DDIFRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAR022QI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN56 DD DISP=SHR,DSN=GENAPP.DDARIN56.DATA
//DDAROT56 DD DISP=SHR,DSN=GENAPP.DDAROT56.DATA
//DDARRP56 DD DISP=SHR,DSN=GENAPP.DDARRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT022QJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN57 DD DISP=SHR,DSN=GENAPP.DDMTIN57.DATA
//DDMTOT57 DD DISP=SHR,DSN=GENAPP.DDMTOT57.DATA
//DDMTRP57 DD DISP=SHR,DSN=GENAPP.DDMTRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
