//VJOB1310 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAU01Y5N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN61 DD DISP=SHR,DSN=GENAPP.DDAUIN61.DATA
//DDAUOT61 DD DISP=SHR,DSN=GENAPP.DDAUOT61.DATA
//DDAURP61 DD DISP=SHR,DSN=GENAPP.DDAURP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW01Y5O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN62 DD DISP=SHR,DSN=GENAPP.DDUWIN62.DATA
//DDUWOT62 DD DISP=SHR,DSN=GENAPP.DDUWOT62.DATA
//DDUWRP62 DD DISP=SHR,DSN=GENAPP.DDUWRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01Y5P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN63 DD DISP=SHR,DSN=GENAPP.DDCLIN63.DATA
//DDCLOT63 DD DISP=SHR,DSN=GENAPP.DDCLOT63.DATA
//DDCLRP63 DD DISP=SHR,DSN=GENAPP.DDCLRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
