//VJOB1297 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01Y4K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN22 DD DISP=SHR,DSN=GENAPP.DDUWIN22.DATA
//DDUWOT22 DD DISP=SHR,DSN=GENAPP.DDUWOT22.DATA
//DDUWRP22 DD DISP=SHR,DSN=GENAPP.DDUWRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDI01Y4L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN23 DD DISP=SHR,DSN=GENAPP.DDDIIN23.DATA
//DDDIOT23 DD DISP=SHR,DSN=GENAPP.DDDIOT23.DATA
//DDDIRP23 DD DISP=SHR,DSN=GENAPP.DDDIRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPL01Y4M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN24 DD DISP=SHR,DSN=GENAPP.DDPLIN24.DATA
//DDPLOT24 DD DISP=SHR,DSN=GENAPP.DDPLOT24.DATA
//DDPLRP24 DD DISP=SHR,DSN=GENAPP.DDPLRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
