//VJOB2515 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCR020Y2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN76 DD DISP=SHR,DSN=GENAPP.DDCRIN76.DATA
//DDCROT76 DD DISP=SHR,DSN=GENAPP.DDCROT76.DATA
//DDCRRP76 DD DISP=SHR,DSN=GENAPP.DDCRRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU020Y3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN77 DD DISP=SHR,DSN=GENAPP.DDCUIN77.DATA
//DDCUOT77 DD DISP=SHR,DSN=GENAPP.DDCUOT77.DATA
//DDCURP77 DD DISP=SHR,DSN=GENAPP.DDCURP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT020Y4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN78 DD DISP=SHR,DSN=GENAPP.DDMTIN78.DATA
//DDMTOT78 DD DISP=SHR,DSN=GENAPP.DDMTOT78.DATA
//DDMTRP78 DD DISP=SHR,DSN=GENAPP.DDMTRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
