//VJOB0528 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01WCH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN55 DD DISP=SHR,DSN=GENAPP.DDMTIN55.DATA
//DDMTOT55 DD DISP=SHR,DSN=GENAPP.DDMTOT55.DATA
//DDMTRP55 DD DISP=SHR,DSN=GENAPP.DDMTRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE01WCI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN56 DD DISP=SHR,DSN=GENAPP.DDHEIN56.DATA
//DDHEOT56 DD DISP=SHR,DSN=GENAPP.DDHEOT56.DATA
//DDHERP56 DD DISP=SHR,DSN=GENAPP.DDHERP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMB01WCJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN57 DD DISP=SHR,DSN=GENAPP.DDMBIN57.DATA
//DDMBOT57 DD DISP=SHR,DSN=GENAPP.DDMBOT57.DATA
//DDMBRP57 DD DISP=SHR,DSN=GENAPP.DDMBRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
