//VJOB1094 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN01XNN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN43 DD DISP=SHR,DSN=GENAPP.DDPNIN43.DATA
//DDPNOT43 DD DISP=SHR,DSN=GENAPP.DDPNOT43.DATA
//DDPNRP43 DD DISP=SHR,DSN=GENAPP.DDPNRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY01XNO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN44 DD DISP=SHR,DSN=GENAPP.DDTYIN44.DATA
//DDTYOT44 DD DISP=SHR,DSN=GENAPP.DDTYOT44.DATA
//DDTYRP44 DD DISP=SHR,DSN=GENAPP.DDTYRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO01XNP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN45 DD DISP=SHR,DSN=GENAPP.DDCOIN45.DATA
//DDCOOT45 DD DISP=SHR,DSN=GENAPP.DDCOOT45.DATA
//DDCORP45 DD DISP=SHR,DSN=GENAPP.DDCORP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
