//VJOB1508 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN01YM5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN25 DD DISP=SHR,DSN=GENAPP.DDPNIN25.DATA
//DDPNOT25 DD DISP=SHR,DSN=GENAPP.DDPNOT25.DATA
//DDPNRP25 DD DISP=SHR,DSN=GENAPP.DDPNRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01YM6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN26 DD DISP=SHR,DSN=GENAPP.DDMTIN26.DATA
//DDMTOT26 DD DISP=SHR,DSN=GENAPP.DDMTOT26.DATA
//DDMTRP26 DD DISP=SHR,DSN=GENAPP.DDMTRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01YM7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN27 DD DISP=SHR,DSN=GENAPP.DDCLIN27.DATA
//DDCLOT27 DD DISP=SHR,DSN=GENAPP.DDCLOT27.DATA
//DDCLRP27 DD DISP=SHR,DSN=GENAPP.DDCLRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
