//VJOB0499 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT01WA2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN58 DD DISP=SHR,DSN=GENAPP.DDNTIN58.DATA
//DDNTOT58 DD DISP=SHR,DSN=GENAPP.DDNTOT58.DATA
//DDNTRP58 DD DISP=SHR,DSN=GENAPP.DDNTRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01WA3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN59 DD DISP=SHR,DSN=GENAPP.DDTXIN59.DATA
//DDTXOT59 DD DISP=SHR,DSN=GENAPP.DDTXOT59.DATA
//DDTXRP59 DD DISP=SHR,DSN=GENAPP.DDTXRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01WA4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN60 DD DISP=SHR,DSN=GENAPP.DDCUIN60.DATA
//DDCUOT60 DD DISP=SHR,DSN=GENAPP.DDCUOT60.DATA
//DDCURP60 DD DISP=SHR,DSN=GENAPP.DDCURP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
