//VJOB3143 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO022EE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN70 DD DISP=SHR,DSN=GENAPP.DDCOIN70.DATA
//DDCOOT70 DD DISP=SHR,DSN=GENAPP.DDCOOT70.DATA
//DDCORP70 DD DISP=SHR,DSN=GENAPP.DDCORP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN022EF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN71 DD DISP=SHR,DSN=GENAPP.DDENIN71.DATA
//DDENOT71 DD DISP=SHR,DSN=GENAPP.DDENOT71.DATA
//DDENRP71 DD DISP=SHR,DSN=GENAPP.DDENRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE022EG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN72 DD DISP=SHR,DSN=GENAPP.DDPEIN72.DATA
//DDPEOT72 DD DISP=SHR,DSN=GENAPP.DDPEOT72.DATA
//DDPERP72 DD DISP=SHR,DSN=GENAPP.DDPERP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
