//VJOB3833 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN023ZW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN70 DD DISP=SHR,DSN=GENAPP.DDANIN70.DATA
//DDANOT70 DD DISP=SHR,DSN=GENAPP.DDANOT70.DATA
//DDANRP70 DD DISP=SHR,DSN=GENAPP.DDANRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI023ZX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN71 DD DISP=SHR,DSN=GENAPP.DDLIIN71.DATA
//DDLIOT71 DD DISP=SHR,DSN=GENAPP.DDLIOT71.DATA
//DDLIRP71 DD DISP=SHR,DSN=GENAPP.DDLIRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS023ZY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN72 DD DISP=SHR,DSN=GENAPP.DDRSIN72.DATA
//DDRSOT72 DD DISP=SHR,DSN=GENAPP.DDRSOT72.DATA
//DDRSRP72 DD DISP=SHR,DSN=GENAPP.DDRSRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
