//VJOB0207 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01VLQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN82 DD DISP=SHR,DSN=GENAPP.DDAVIN82.DATA
//DDAVOT82 DD DISP=SHR,DSN=GENAPP.DDAVOT82.DATA
//DDAVRP82 DD DISP=SHR,DSN=GENAPP.DDAVRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE01VLR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN83 DD DISP=SHR,DSN=GENAPP.DDPEIN83.DATA
//DDPEOT83 DD DISP=SHR,DSN=GENAPP.DDPEOT83.DATA
//DDPERP83 DD DISP=SHR,DSN=GENAPP.DDPERP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01VLS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN84 DD DISP=SHR,DSN=GENAPP.DDHOIN84.DATA
//DDHOOT84 DD DISP=SHR,DSN=GENAPP.DDHOOT84.DATA
//DDHORP84 DD DISP=SHR,DSN=GENAPP.DDHORP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
