//VJOB1073 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01XLW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN70 DD DISP=SHR,DSN=GENAPP.DDHOIN70.DATA
//DDHOOT70 DD DISP=SHR,DSN=GENAPP.DDHOOT70.DATA
//DDHORP70 DD DISP=SHR,DSN=GENAPP.DDHORP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01XLX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN71 DD DISP=SHR,DSN=GENAPP.DDPAIN71.DATA
//DDPAOT71 DD DISP=SHR,DSN=GENAPP.DDPAOT71.DATA
//DDPARP71 DD DISP=SHR,DSN=GENAPP.DDPARP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01XLY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN72 DD DISP=SHR,DSN=GENAPP.DDTRIN72.DATA
//DDTROT72 DD DISP=SHR,DSN=GENAPP.DDTROT72.DATA
//DDTRRP72 DD DISP=SHR,DSN=GENAPP.DDTRRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
