//VJOB2519 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO020YE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN88 DD DISP=SHR,DSN=GENAPP.DDHOIN88.DATA
//DDHOOT88 DD DISP=SHR,DSN=GENAPP.DDHOOT88.DATA
//DDHORP88 DD DISP=SHR,DSN=GENAPP.DDHORP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU020YF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN89 DD DISP=SHR,DSN=GENAPP.DDCUIN89.DATA
//DDCUOT89 DD DISP=SHR,DSN=GENAPP.DDCUOT89.DATA
//DDCURP89 DD DISP=SHR,DSN=GENAPP.DDCURP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG020YG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN90 DD DISP=SHR,DSN=GENAPP.DDRGIN90.DATA
//DDRGOT90 DD DISP=SHR,DSN=GENAPP.DDRGOT90.DATA
//DDRGRP90 DD DISP=SHR,DSN=GENAPP.DDRGRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
