//VJOB1051 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01XK2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN04 DD DISP=SHR,DSN=GENAPP.DDHOIN04.DATA
//DDHOOT04 DD DISP=SHR,DSN=GENAPP.DDHOOT04.DATA
//DDHORP04 DD DISP=SHR,DSN=GENAPP.DDHORP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01XK3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN05 DD DISP=SHR,DSN=GENAPP.DDFLIN05.DATA
//DDFLOT05 DD DISP=SHR,DSN=GENAPP.DDFLOT05.DATA
//DDFLRP05 DD DISP=SHR,DSN=GENAPP.DDFLRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01XK4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN06 DD DISP=SHR,DSN=GENAPP.DDTRIN06.DATA
//DDTROT06 DD DISP=SHR,DSN=GENAPP.DDTROT06.DATA
//DDTRRP06 DD DISP=SHR,DSN=GENAPP.DDTRRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
