//VJOB3163 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB022G2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN40 DD DISP=SHR,DSN=GENAPP.DDMBIN40.DATA
//DDMBOT40 DD DISP=SHR,DSN=GENAPP.DDMBOT40.DATA
//DDMBRP40 DD DISP=SHR,DSN=GENAPP.DDMBRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA022G3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN41 DD DISP=SHR,DSN=GENAPP.DDPAIN41.DATA
//DDPAOT41 DD DISP=SHR,DSN=GENAPP.DDPAOT41.DATA
//DDPARP41 DD DISP=SHR,DSN=GENAPP.DDPARP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSL022G4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN42 DD DISP=SHR,DSN=GENAPP.DDSLIN42.DATA
//DDSLOT42 DD DISP=SHR,DSN=GENAPP.DDSLOT42.DATA
//DDSLRP42 DD DISP=SHR,DSN=GENAPP.DDSLRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
