//VJOB2557 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR0211K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN22 DD DISP=SHR,DSN=GENAPP.DDFRIN22.DATA
//DDFROT22 DD DISP=SHR,DSN=GENAPP.DDFROT22.DATA
//DDFRRP22 DD DISP=SHR,DSN=GENAPP.DDFRRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE0211L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN23 DD DISP=SHR,DSN=GENAPP.DDREIN23.DATA
//DDREOT23 DD DISP=SHR,DSN=GENAPP.DDREOT23.DATA
//DDRERP23 DD DISP=SHR,DSN=GENAPP.DDRERP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN0211M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN24 DD DISP=SHR,DSN=GENAPP.DDPNIN24.DATA
//DDPNOT24 DD DISP=SHR,DSN=GENAPP.DDPNOT24.DATA
//DDPNRP24 DD DISP=SHR,DSN=GENAPP.DDPNRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
