//VJOB0133 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN01VFK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN40 DD DISP=SHR,DSN=GENAPP.DDANIN40.DATA
//DDANOT40 DD DISP=SHR,DSN=GENAPP.DDANOT40.DATA
//DDANRP40 DD DISP=SHR,DSN=GENAPP.DDANRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01VFL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN41 DD DISP=SHR,DSN=GENAPP.DDMTIN41.DATA
//DDMTOT41 DD DISP=SHR,DSN=GENAPP.DDMTOT41.DATA
//DDMTRP41 DD DISP=SHR,DSN=GENAPP.DDMTRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW01VFM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN42 DD DISP=SHR,DSN=GENAPP.DDUWIN42.DATA
//DDUWOT42 DD DISP=SHR,DSN=GENAPP.DDUWOT42.DATA
//DDUWRP42 DD DISP=SHR,DSN=GENAPP.DDUWRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
