//VJOB1822 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01ZCB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN67 DD DISP=SHR,DSN=GENAPP.DDUWIN67.DATA
//DDUWOT67 DD DISP=SHR,DSN=GENAPP.DDUWOT67.DATA
//DDUWRP67 DD DISP=SHR,DSN=GENAPP.DDUWRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01ZCC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN68 DD DISP=SHR,DSN=GENAPP.DDMTIN68.DATA
//DDMTOT68 DD DISP=SHR,DSN=GENAPP.DDMTOT68.DATA
//DDMTRP68 DD DISP=SHR,DSN=GENAPP.DDMTRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX01ZCD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN69 DD DISP=SHR,DSN=GENAPP.DDTXIN69.DATA
//DDTXOT69 DD DISP=SHR,DSN=GENAPP.DDTXOT69.DATA
//DDTXRP69 DD DISP=SHR,DSN=GENAPP.DDTXRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
