//VJOB2775 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL021JQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN46 DD DISP=SHR,DSN=GENAPP.DDCLIN46.DATA
//DDCLOT46 DD DISP=SHR,DSN=GENAPP.DDCLOT46.DATA
//DDCLRP46 DD DISP=SHR,DSN=GENAPP.DDCLRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT021JR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN47 DD DISP=SHR,DSN=GENAPP.DDNTIN47.DATA
//DDNTOT47 DD DISP=SHR,DSN=GENAPP.DDNTOT47.DATA
//DDNTRP47 DD DISP=SHR,DSN=GENAPP.DDNTRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN021JS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN48 DD DISP=SHR,DSN=GENAPP.DDENIN48.DATA
//DDENOT48 DD DISP=SHR,DSN=GENAPP.DDENOT48.DATA
//DDENRP48 DD DISP=SHR,DSN=GENAPP.DDENRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
