//VJOB0947 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRT01XBE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN52 DD DISP=SHR,DSN=GENAPP.DDRTIN52.DATA
//DDRTOT52 DD DISP=SHR,DSN=GENAPP.DDRTOT52.DATA
//DDRTRP52 DD DISP=SHR,DSN=GENAPP.DDRTRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01XBF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN53 DD DISP=SHR,DSN=GENAPP.DDMTIN53.DATA
//DDMTOT53 DD DISP=SHR,DSN=GENAPP.DDMTOT53.DATA
//DDMTRP53 DD DISP=SHR,DSN=GENAPP.DDMTRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC01XBG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN54 DD DISP=SHR,DSN=GENAPP.DDACIN54.DATA
//DDACOT54 DD DISP=SHR,DSN=GENAPP.DDACOT54.DATA
//DDACRP54 DD DISP=SHR,DSN=GENAPP.DDACRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
