//VJOB1967 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF01ZOE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN52 DD DISP=SHR,DSN=GENAPP.DDWFIN52.DATA
//DDWFOT52 DD DISP=SHR,DSN=GENAPP.DDWFOT52.DATA
//DDWFRP52 DD DISP=SHR,DSN=GENAPP.DDWFRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV01ZOF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN53 DD DISP=SHR,DSN=GENAPP.DDAVIN53.DATA
//DDAVOT53 DD DISP=SHR,DSN=GENAPP.DDAVOT53.DATA
//DDAVRP53 DD DISP=SHR,DSN=GENAPP.DDAVRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF01ZOG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN54 DD DISP=SHR,DSN=GENAPP.DDIFIN54.DATA
//DDIFOT54 DD DISP=SHR,DSN=GENAPP.DDIFOT54.DATA
//DDIFRP54 DD DISP=SHR,DSN=GENAPP.DDIFRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
