//VJOB0103 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01VD2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN40 DD DISP=SHR,DSN=GENAPP.DDMTIN40.DATA
//DDMTOT40 DD DISP=SHR,DSN=GENAPP.DDMTOT40.DATA
//DDMTRP40 DD DISP=SHR,DSN=GENAPP.DDMTRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01VD3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN41 DD DISP=SHR,DSN=GENAPP.DDBIIN41.DATA
//DDBIOT41 DD DISP=SHR,DSN=GENAPP.DDBIOT41.DATA
//DDBIRP41 DD DISP=SHR,DSN=GENAPP.DDBIRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01VD4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN42 DD DISP=SHR,DSN=GENAPP.DDCUIN42.DATA
//DDCUOT42 DD DISP=SHR,DSN=GENAPP.DDCUOT42.DATA
//DDCURP42 DD DISP=SHR,DSN=GENAPP.DDCURP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
