//VJOB1772 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01Z85
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN07 DD DISP=SHR,DSN=GENAPP.DDHOIN07.DATA
//DDHOOT07 DD DISP=SHR,DSN=GENAPP.DDHOOT07.DATA
//DDHORP07 DD DISP=SHR,DSN=GENAPP.DDHORP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01Z86
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN08 DD DISP=SHR,DSN=GENAPP.DDCUIN08.DATA
//DDCUOT08 DD DISP=SHR,DSN=GENAPP.DDCUOT08.DATA
//DDCURP08 DD DISP=SHR,DSN=GENAPP.DDCURP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPL01Z87
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN09 DD DISP=SHR,DSN=GENAPP.DDPLIN09.DATA
//DDPLOT09 DD DISP=SHR,DSN=GENAPP.DDPLOT09.DATA
//DDPLRP09 DD DISP=SHR,DSN=GENAPP.DDPLRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
