//VJOB2727 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL021FQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN82 DD DISP=SHR,DSN=GENAPP.DDCLIN82.DATA
//DDCLOT82 DD DISP=SHR,DSN=GENAPP.DDCLOT82.DATA
//DDCLRP82 DD DISP=SHR,DSN=GENAPP.DDCLRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO021FR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN83 DD DISP=SHR,DSN=GENAPP.DDHOIN83.DATA
//DDHOOT83 DD DISP=SHR,DSN=GENAPP.DDHOOT83.DATA
//DDHORP83 DD DISP=SHR,DSN=GENAPP.DDHORP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW021FS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN84 DD DISP=SHR,DSN=GENAPP.DDUWIN84.DATA
//DDUWOT84 DD DISP=SHR,DSN=GENAPP.DDUWOT84.DATA
//DDUWRP84 DD DISP=SHR,DSN=GENAPP.DDUWRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
