//VJOB1582 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE01YSB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN67 DD DISP=SHR,DSN=GENAPP.DDREIN67.DATA
//DDREOT67 DD DISP=SHR,DSN=GENAPP.DDREOT67.DATA
//DDRERP67 DD DISP=SHR,DSN=GENAPP.DDRERP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR01YSC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN68 DD DISP=SHR,DSN=GENAPP.DDPRIN68.DATA
//DDPROT68 DD DISP=SHR,DSN=GENAPP.DDPROT68.DATA
//DDPRRP68 DD DISP=SHR,DSN=GENAPP.DDPRRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01YSD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN69 DD DISP=SHR,DSN=GENAPP.DDCLIN69.DATA
//DDCLOT69 DD DISP=SHR,DSN=GENAPP.DDCLOT69.DATA
//DDCLRP69 DD DISP=SHR,DSN=GENAPP.DDCLRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
