//VJOB1436 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC01YG5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN79 DD DISP=SHR,DSN=GENAPP.DDRCIN79.DATA
//DDRCOT79 DD DISP=SHR,DSN=GENAPP.DDRCOT79.DATA
//DDRCRP79 DD DISP=SHR,DSN=GENAPP.DDRCRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01YG6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN80 DD DISP=SHR,DSN=GENAPP.DDHOIN80.DATA
//DDHOOT80 DD DISP=SHR,DSN=GENAPP.DDHOOT80.DATA
//DDHORP80 DD DISP=SHR,DSN=GENAPP.DDHORP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01YG7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN81 DD DISP=SHR,DSN=GENAPP.DDMTIN81.DATA
//DDMTOT81 DD DISP=SHR,DSN=GENAPP.DDMTOT81.DATA
//DDMTRP81 DD DISP=SHR,DSN=GENAPP.DDMTRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
