//VJOB2180 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB02065
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN61 DD DISP=SHR,DSN=GENAPP.DDMBIN61.DATA
//DDMBOT61 DD DISP=SHR,DSN=GENAPP.DDMBOT61.DATA
//DDMBRP61 DD DISP=SHR,DSN=GENAPP.DDMBRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW02066
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN62 DD DISP=SHR,DSN=GENAPP.DDUWIN62.DATA
//DDUWOT62 DD DISP=SHR,DSN=GENAPP.DDUWOT62.DATA
//DDUWRP62 DD DISP=SHR,DSN=GENAPP.DDUWRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR02067
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN63 DD DISP=SHR,DSN=GENAPP.DDPRIN63.DATA
//DDPROT63 DD DISP=SHR,DSN=GENAPP.DDPROT63.DATA
//DDPRRP63 DD DISP=SHR,DSN=GENAPP.DDPRRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
