//VJOB0071 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZVA01VAE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN34 DD DISP=SHR,DSN=GENAPP.DDVAIN34.DATA
//DDVAOT34 DD DISP=SHR,DSN=GENAPP.DDVAOT34.DATA
//DDVARP34 DD DISP=SHR,DSN=GENAPP.DDVARP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG01VAF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN35 DD DISP=SHR,DSN=GENAPP.DDRGIN35.DATA
//DDRGOT35 DD DISP=SHR,DSN=GENAPP.DDRGOT35.DATA
//DDRGRP35 DD DISP=SHR,DSN=GENAPP.DDRGRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRT01VAG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN36 DD DISP=SHR,DSN=GENAPP.DDRTIN36.DATA
//DDRTOT36 DD DISP=SHR,DSN=GENAPP.DDRTOT36.DATA
//DDRTRP36 DD DISP=SHR,DSN=GENAPP.DDRTRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
