//VJOB3704 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN023P5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN43 DD DISP=SHR,DSN=GENAPP.DDENIN43.DATA
//DDENOT43 DD DISP=SHR,DSN=GENAPP.DDENOT43.DATA
//DDENRP43 DD DISP=SHR,DSN=GENAPP.DDENRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR023P6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN44 DD DISP=SHR,DSN=GENAPP.DDTRIN44.DATA
//DDTROT44 DD DISP=SHR,DSN=GENAPP.DDTROT44.DATA
//DDTRRP44 DD DISP=SHR,DSN=GENAPP.DDTRRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG023P7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN45 DD DISP=SHR,DSN=GENAPP.DDAGIN45.DATA
//DDAGOT45 DD DISP=SHR,DSN=GENAPP.DDAGOT45.DATA
//DDAGRP45 DD DISP=SHR,DSN=GENAPP.DDAGRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
