//VJOB2819 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE021NE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN88 DD DISP=SHR,DSN=GENAPP.DDHEIN88.DATA
//DDHEOT88 DD DISP=SHR,DSN=GENAPP.DDHEOT88.DATA
//DDHERP88 DD DISP=SHR,DSN=GENAPP.DDHERP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR021NF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN89 DD DISP=SHR,DSN=GENAPP.DDBRIN89.DATA
//DDBROT89 DD DISP=SHR,DSN=GENAPP.DDBROT89.DATA
//DDBRRP89 DD DISP=SHR,DSN=GENAPP.DDBRRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI021NG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN90 DD DISP=SHR,DSN=GENAPP.DDLIIN90.DATA
//DDLIOT90 DD DISP=SHR,DSN=GENAPP.DDLIOT90.DATA
//DDLIRP90 DD DISP=SHR,DSN=GENAPP.DDLIRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
