//VJOB1149 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR01XS8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN28 DD DISP=SHR,DSN=GENAPP.DDFRIN28.DATA
//DDFROT28 DD DISP=SHR,DSN=GENAPP.DDFROT28.DATA
//DDFRRP28 DD DISP=SHR,DSN=GENAPP.DDFRRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRC01XS9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN29 DD DISP=SHR,DSN=GENAPP.DDRCIN29.DATA
//DDRCOT29 DD DISP=SHR,DSN=GENAPP.DDRCOT29.DATA
//DDRCRP29 DD DISP=SHR,DSN=GENAPP.DDRCRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSL01XSA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN30 DD DISP=SHR,DSN=GENAPP.DDSLIN30.DATA
//DDSLOT30 DD DISP=SHR,DSN=GENAPP.DDSLOT30.DATA
//DDSLRP30 DD DISP=SHR,DSN=GENAPP.DDSLRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
