//VJOB1503 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF01YLQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN10 DD DISP=SHR,DSN=GENAPP.DDWFIN10.DATA
//DDWFOT10 DD DISP=SHR,DSN=GENAPP.DDWFOT10.DATA
//DDWFRP10 DD DISP=SHR,DSN=GENAPP.DDWFRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01YLR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN11 DD DISP=SHR,DSN=GENAPP.DDMTIN11.DATA
//DDMTOT11 DD DISP=SHR,DSN=GENAPP.DDMTOT11.DATA
//DDMTRP11 DD DISP=SHR,DSN=GENAPP.DDMTRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLB01YLS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN12 DD DISP=SHR,DSN=GENAPP.DDLBIN12.DATA
//DDLBOT12 DD DISP=SHR,DSN=GENAPP.DDLBOT12.DATA
//DDLBRP12 DD DISP=SHR,DSN=GENAPP.DDLBRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
