//VJOB1923 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01ZKQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN10 DD DISP=SHR,DSN=GENAPP.DDRGIN10.DATA
//DDRGOT10 DD DISP=SHR,DSN=GENAPP.DDRGOT10.DATA
//DDRGRP10 DD DISP=SHR,DSN=GENAPP.DDRGRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01ZKR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN11 DD DISP=SHR,DSN=GENAPP.DDFLIN11.DATA
//DDFLOT11 DD DISP=SHR,DSN=GENAPP.DDFLOT11.DATA
//DDFLRP11 DD DISP=SHR,DSN=GENAPP.DDFLRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01ZKS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN12 DD DISP=SHR,DSN=GENAPP.DDBIIN12.DATA
//DDBIOT12 DD DISP=SHR,DSN=GENAPP.DDBIOT12.DATA
//DDBIRP12 DD DISP=SHR,DSN=GENAPP.DDBIRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
