//VJOB1015 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01XH2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN76 DD DISP=SHR,DSN=GENAPP.DDBIIN76.DATA
//DDBIOT76 DD DISP=SHR,DSN=GENAPP.DDBIOT76.DATA
//DDBIRP76 DD DISP=SHR,DSN=GENAPP.DDBIRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01XH3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN77 DD DISP=SHR,DSN=GENAPP.DDTXIN77.DATA
//DDTXOT77 DD DISP=SHR,DSN=GENAPP.DDTXOT77.DATA
//DDTXRP77 DD DISP=SHR,DSN=GENAPP.DDTXRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01XH4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN78 DD DISP=SHR,DSN=GENAPP.DDMTIN78.DATA
//DDMTOT78 DD DISP=SHR,DSN=GENAPP.DDMTOT78.DATA
//DDMTRP78 DD DISP=SHR,DSN=GENAPP.DDMTRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
