//VJOB1551 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01YPQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN64 DD DISP=SHR,DSN=GENAPP.DDCLIN64.DATA
//DDCLOT64 DD DISP=SHR,DSN=GENAPP.DDCLOT64.DATA
//DDCLRP64 DD DISP=SHR,DSN=GENAPP.DDCLRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01YPR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN65 DD DISP=SHR,DSN=GENAPP.DDHOIN65.DATA
//DDHOOT65 DD DISP=SHR,DSN=GENAPP.DDHOOT65.DATA
//DDHORP65 DD DISP=SHR,DSN=GENAPP.DDHORP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01YPS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN66 DD DISP=SHR,DSN=GENAPP.DDMTIN66.DATA
//DDMTOT66 DD DISP=SHR,DSN=GENAPP.DDMTOT66.DATA
//DDMTRP66 DD DISP=SHR,DSN=GENAPP.DDMTRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
