//VJOB1580 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01YS5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN61 DD DISP=SHR,DSN=GENAPP.DDENIN61.DATA
//DDENOT61 DD DISP=SHR,DSN=GENAPP.DDENOT61.DATA
//DDENRP61 DD DISP=SHR,DSN=GENAPP.DDENRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01YS6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN62 DD DISP=SHR,DSN=GENAPP.DDCUIN62.DATA
//DDCUOT62 DD DISP=SHR,DSN=GENAPP.DDCUOT62.DATA
//DDCURP62 DD DISP=SHR,DSN=GENAPP.DDCURP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG01YS7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN63 DD DISP=SHR,DSN=GENAPP.DDRGIN63.DATA
//DDRGOT63 DD DISP=SHR,DSN=GENAPP.DDRGOT63.DATA
//DDRGRP63 DD DISP=SHR,DSN=GENAPP.DDRGRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
