//VJOB3071 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI0228E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN34 DD DISP=SHR,DSN=GENAPP.DDBIIN34.DATA
//DDBIOT34 DD DISP=SHR,DSN=GENAPP.DDBIOT34.DATA
//DDBIRP34 DD DISP=SHR,DSN=GENAPP.DDBIRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV0228F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN35 DD DISP=SHR,DSN=GENAPP.DDAVIN35.DATA
//DDAVOT35 DD DISP=SHR,DSN=GENAPP.DDAVOT35.DATA
//DDAVRP35 DD DISP=SHR,DSN=GENAPP.DDAVRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT0228G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN36 DD DISP=SHR,DSN=GENAPP.DDPTIN36.DATA
//DDPTOT36 DD DISP=SHR,DSN=GENAPP.DDPTOT36.DATA
//DDPTRP36 DD DISP=SHR,DSN=GENAPP.DDPTRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
