//VJOB1966 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01ZOB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN49 DD DISP=SHR,DSN=GENAPP.DDCLIN49.DATA
//DDCLOT49 DD DISP=SHR,DSN=GENAPP.DDCLOT49.DATA
//DDCLRP49 DD DISP=SHR,DSN=GENAPP.DDCLRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW01ZOC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN50 DD DISP=SHR,DSN=GENAPP.DDUWIN50.DATA
//DDUWOT50 DD DISP=SHR,DSN=GENAPP.DDUWOT50.DATA
//DDUWRP50 DD DISP=SHR,DSN=GENAPP.DDUWRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01ZOD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN51 DD DISP=SHR,DSN=GENAPP.DDCLIN51.DATA
//DDCLOT51 DD DISP=SHR,DSN=GENAPP.DDCLOT51.DATA
//DDCLRP51 DD DISP=SHR,DSN=GENAPP.DDCLRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
