//VJOB0700 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE01WQT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN31 DD DISP=SHR,DSN=GENAPP.DDHEIN31.DATA
//DDHEOT31 DD DISP=SHR,DSN=GENAPP.DDHEOT31.DATA
//DDHERP31 DD DISP=SHR,DSN=GENAPP.DDHERP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE01WQU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN32 DD DISP=SHR,DSN=GENAPP.DDSEIN32.DATA
//DDSEOT32 DD DISP=SHR,DSN=GENAPP.DDSEOT32.DATA
//DDSERP32 DD DISP=SHR,DSN=GENAPP.DDSERP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI01WQV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN33 DD DISP=SHR,DSN=GENAPP.DDLIIN33.DATA
//DDLIOT33 DD DISP=SHR,DSN=GENAPP.DDLIOT33.DATA
//DDLIRP33 DD DISP=SHR,DSN=GENAPP.DDLIRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
