//VJOB2419 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU020Q2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN58 DD DISP=SHR,DSN=GENAPP.DDCUIN58.DATA
//DDCUOT58 DD DISP=SHR,DSN=GENAPP.DDCUOT58.DATA
//DDCURP58 DD DISP=SHR,DSN=GENAPP.DDCURP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE020Q3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN59 DD DISP=SHR,DSN=GENAPP.DDSEIN59.DATA
//DDSEOT59 DD DISP=SHR,DSN=GENAPP.DDSEOT59.DATA
//DDSERP59 DD DISP=SHR,DSN=GENAPP.DDSERP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR020Q4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN60 DD DISP=SHR,DSN=GENAPP.DDTRIN60.DATA
//DDTROT60 DD DISP=SHR,DSN=GENAPP.DDTROT60.DATA
//DDTRRP60 DD DISP=SHR,DSN=GENAPP.DDTRRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
