//VJOB1915 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE01ZK2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN76 DD DISP=SHR,DSN=GENAPP.DDREIN76.DATA
//DDREOT76 DD DISP=SHR,DSN=GENAPP.DDREOT76.DATA
//DDRERP76 DD DISP=SHR,DSN=GENAPP.DDRERP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01ZK3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN77 DD DISP=SHR,DSN=GENAPP.DDAGIN77.DATA
//DDAGOT77 DD DISP=SHR,DSN=GENAPP.DDAGOT77.DATA
//DDAGRP77 DD DISP=SHR,DSN=GENAPP.DDAGRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW01ZK4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN78 DD DISP=SHR,DSN=GENAPP.DDUWIN78.DATA
//DDUWOT78 DD DISP=SHR,DSN=GENAPP.DDUWOT78.DATA
//DDUWRP78 DD DISP=SHR,DSN=GENAPP.DDUWRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
