//VJOB1276 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV01Y2T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN49 DD DISP=SHR,DSN=GENAPP.DDIVIN49.DATA
//DDIVOT49 DD DISP=SHR,DSN=GENAPP.DDIVOT49.DATA
//DDIVRP49 DD DISP=SHR,DSN=GENAPP.DDIVRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01Y2U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN50 DD DISP=SHR,DSN=GENAPP.DDFLIN50.DATA
//DDFLOT50 DD DISP=SHR,DSN=GENAPP.DDFLOT50.DATA
//DDFLRP50 DD DISP=SHR,DSN=GENAPP.DDFLRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV01Y2V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN51 DD DISP=SHR,DSN=GENAPP.DDAVIN51.DATA
//DDAVOT51 DD DISP=SHR,DSN=GENAPP.DDAVOT51.DATA
//DDAVRP51 DD DISP=SHR,DSN=GENAPP.DDAVRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
