//VJOB1884 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01ZHH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN73 DD DISP=SHR,DSN=GENAPP.DDCUIN73.DATA
//DDCUOT73 DD DISP=SHR,DSN=GENAPP.DDCUOT73.DATA
//DDCURP73 DD DISP=SHR,DSN=GENAPP.DDCURP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01ZHI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN74 DD DISP=SHR,DSN=GENAPP.DDHOIN74.DATA
//DDHOOT74 DD DISP=SHR,DSN=GENAPP.DDHOOT74.DATA
//DDHORP74 DD DISP=SHR,DSN=GENAPP.DDHORP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI01ZHJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN75 DD DISP=SHR,DSN=GENAPP.DDLIIN75.DATA
//DDLIOT75 DD DISP=SHR,DSN=GENAPP.DDLIOT75.DATA
//DDLIRP75 DD DISP=SHR,DSN=GENAPP.DDLIRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
