//VJOB0506 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT01WAN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN79 DD DISP=SHR,DSN=GENAPP.DDNTIN79.DATA
//DDNTOT79 DD DISP=SHR,DSN=GENAPP.DDNTOT79.DATA
//DDNTRP79 DD DISP=SHR,DSN=GENAPP.DDNTRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV01WAO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN80 DD DISP=SHR,DSN=GENAPP.DDAVIN80.DATA
//DDAVOT80 DD DISP=SHR,DSN=GENAPP.DDAVOT80.DATA
//DDAVRP80 DD DISP=SHR,DSN=GENAPP.DDAVRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV01WAP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN81 DD DISP=SHR,DSN=GENAPP.DDIVIN81.DATA
//DDIVOT81 DD DISP=SHR,DSN=GENAPP.DDIVOT81.DATA
//DDIVRP81 DD DISP=SHR,DSN=GENAPP.DDIVRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
