//VJOB3610 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB023HB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN31 DD DISP=SHR,DSN=GENAPP.DDLBIN31.DATA
//DDLBOT31 DD DISP=SHR,DSN=GENAPP.DDLBOT31.DATA
//DDLBRP31 DD DISP=SHR,DSN=GENAPP.DDLBRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN023HC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN32 DD DISP=SHR,DSN=GENAPP.DDENIN32.DATA
//DDENOT32 DD DISP=SHR,DSN=GENAPP.DDENOT32.DATA
//DDENRP32 DD DISP=SHR,DSN=GENAPP.DDENRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZED023HD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN33 DD DISP=SHR,DSN=GENAPP.DDEDIN33.DATA
//DDEDOT33 DD DISP=SHR,DSN=GENAPP.DDEDOT33.DATA
//DDEDRP33 DD DISP=SHR,DSN=GENAPP.DDEDRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
