//VJOB1431 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01YFQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN64 DD DISP=SHR,DSN=GENAPP.DDMTIN64.DATA
//DDMTOT64 DD DISP=SHR,DSN=GENAPP.DDMTOT64.DATA
//DDMTRP64 DD DISP=SHR,DSN=GENAPP.DDMTRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN01YFR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN65 DD DISP=SHR,DSN=GENAPP.DDRNIN65.DATA
//DDRNOT65 DD DISP=SHR,DSN=GENAPP.DDRNOT65.DATA
//DDRNRP65 DD DISP=SHR,DSN=GENAPP.DDRNRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZVA01YFS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN66 DD DISP=SHR,DSN=GENAPP.DDVAIN66.DATA
//DDVAOT66 DD DISP=SHR,DSN=GENAPP.DDVAOT66.DATA
//DDVARP66 DD DISP=SHR,DSN=GENAPP.DDVARP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
