//VJOB2881 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS021SK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN04 DD DISP=SHR,DSN=GENAPP.DDRSIN04.DATA
//DDRSOT04 DD DISP=SHR,DSN=GENAPP.DDRSOT04.DATA
//DDRSRP04 DD DISP=SHR,DSN=GENAPP.DDRSRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZGW021SL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN05 DD DISP=SHR,DSN=GENAPP.DDGWIN05.DATA
//DDGWOT05 DD DISP=SHR,DSN=GENAPP.DDGWOT05.DATA
//DDGWRP05 DD DISP=SHR,DSN=GENAPP.DDGWRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE021SM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN06 DD DISP=SHR,DSN=GENAPP.DDREIN06.DATA
//DDREOT06 DD DISP=SHR,DSN=GENAPP.DDREOT06.DATA
//DDRERP06 DD DISP=SHR,DSN=GENAPP.DDRERP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
