//VJOB2482 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT020VB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN67 DD DISP=SHR,DSN=GENAPP.DDMTIN67.DATA
//DDMTOT67 DD DISP=SHR,DSN=GENAPP.DDMTOT67.DATA
//DDMTRP67 DD DISP=SHR,DSN=GENAPP.DDMTRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO020VC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN68 DD DISP=SHR,DSN=GENAPP.DDHOIN68.DATA
//DDHOOT68 DD DISP=SHR,DSN=GENAPP.DDHOOT68.DATA
//DDHORP68 DD DISP=SHR,DSN=GENAPP.DDHORP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN020VD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN69 DD DISP=SHR,DSN=GENAPP.DDENIN69.DATA
//DDENOT69 DD DISP=SHR,DSN=GENAPP.DDENOT69.DATA
//DDENRP69 DD DISP=SHR,DSN=GENAPP.DDENRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
