//VJOB0057 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZGW01V98
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN82 DD DISP=SHR,DSN=GENAPP.DDGWIN82.DATA
//DDGWOT82 DD DISP=SHR,DSN=GENAPP.DDGWOT82.DATA
//DDGWRP82 DD DISP=SHR,DSN=GENAPP.DDGWRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE01V99
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN83 DD DISP=SHR,DSN=GENAPP.DDREIN83.DATA
//DDREOT83 DD DISP=SHR,DSN=GENAPP.DDREOT83.DATA
//DDRERP83 DD DISP=SHR,DSN=GENAPP.DDRERP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS01V9A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN84 DD DISP=SHR,DSN=GENAPP.DDRSIN84.DATA
//DDRSOT84 DD DISP=SHR,DSN=GENAPP.DDRSOT84.DATA
//DDRSRP84 DD DISP=SHR,DSN=GENAPP.DDRSRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
