//VJOB2192 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY02075
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN07 DD DISP=SHR,DSN=GENAPP.DDTYIN07.DATA
//DDTYOT07 DD DISP=SHR,DSN=GENAPP.DDTYOT07.DATA
//DDTYRP07 DD DISP=SHR,DSN=GENAPP.DDTYRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB02076
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN08 DD DISP=SHR,DSN=GENAPP.DDLBIN08.DATA
//DDLBOT08 DD DISP=SHR,DSN=GENAPP.DDLBOT08.DATA
//DDLBRP08 DD DISP=SHR,DSN=GENAPP.DDLBRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI02077
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN09 DD DISP=SHR,DSN=GENAPP.DDBIIN09.DATA
//DDBIOT09 DD DISP=SHR,DSN=GENAPP.DDBIOT09.DATA
//DDBIRP09 DD DISP=SHR,DSN=GENAPP.DDBIRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
