//VJOB1407 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI01YDQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN82 DD DISP=SHR,DSN=GENAPP.DDLIIN82.DATA
//DDLIOT82 DD DISP=SHR,DSN=GENAPP.DDLIOT82.DATA
//DDLIRP82 DD DISP=SHR,DSN=GENAPP.DDLIRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRC01YDR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN83 DD DISP=SHR,DSN=GENAPP.DDRCIN83.DATA
//DDRCOT83 DD DISP=SHR,DSN=GENAPP.DDRCOT83.DATA
//DDRCRP83 DD DISP=SHR,DSN=GENAPP.DDRCRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSL01YDS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN84 DD DISP=SHR,DSN=GENAPP.DDSLIN84.DATA
//DDSLOT84 DD DISP=SHR,DSN=GENAPP.DDSLOT84.DATA
//DDSLRP84 DD DISP=SHR,DSN=GENAPP.DDSLRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
