//VJOB0687 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA01WPQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN82 DD DISP=SHR,DSN=GENAPP.DDBAIN82.DATA
//DDBAOT82 DD DISP=SHR,DSN=GENAPP.DDBAOT82.DATA
//DDBARP82 DD DISP=SHR,DSN=GENAPP.DDBARP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN01WPR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN83 DD DISP=SHR,DSN=GENAPP.DDENIN83.DATA
//DDENOT83 DD DISP=SHR,DSN=GENAPP.DDENOT83.DATA
//DDENRP83 DD DISP=SHR,DSN=GENAPP.DDENRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01WPS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN84 DD DISP=SHR,DSN=GENAPP.DDMTIN84.DATA
//DDMTOT84 DD DISP=SHR,DSN=GENAPP.DDMTOT84.DATA
//DDMTRP84 DD DISP=SHR,DSN=GENAPP.DDMTRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
