//VJOB0548 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA01WE5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN25 DD DISP=SHR,DSN=GENAPP.DDMAIN25.DATA
//DDMAOT25 DD DISP=SHR,DSN=GENAPP.DDMAOT25.DATA
//DDMARP25 DD DISP=SHR,DSN=GENAPP.DDMARP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01WE6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN26 DD DISP=SHR,DSN=GENAPP.DDTXIN26.DATA
//DDTXOT26 DD DISP=SHR,DSN=GENAPP.DDTXOT26.DATA
//DDTXRP26 DD DISP=SHR,DSN=GENAPP.DDTXRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS01WE7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN27 DD DISP=SHR,DSN=GENAPP.DDRSIN27.DATA
//DDRSOT27 DD DISP=SHR,DSN=GENAPP.DDRSOT27.DATA
//DDRSRP27 DD DISP=SHR,DSN=GENAPP.DDRSRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
