//VJOB2141 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO0202W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN34 DD DISP=SHR,DSN=GENAPP.DDHOIN34.DATA
//DDHOOT34 DD DISP=SHR,DSN=GENAPP.DDHOOT34.DATA
//DDHORP34 DD DISP=SHR,DSN=GENAPP.DDHORP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPL0202X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN35 DD DISP=SHR,DSN=GENAPP.DDPLIN35.DATA
//DDPLOT35 DD DISP=SHR,DSN=GENAPP.DDPLOT35.DATA
//DDPLRP35 DD DISP=SHR,DSN=GENAPP.DDPLRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR0202Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN36 DD DISP=SHR,DSN=GENAPP.DDTRIN36.DATA
//DDTROT36 DD DISP=SHR,DSN=GENAPP.DDTROT36.DATA
//DDTRRP36 DD DISP=SHR,DSN=GENAPP.DDTRRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
