//VJOB2373 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG020M8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN10 DD DISP=SHR,DSN=GENAPP.DDRGIN10.DATA
//DDRGOT10 DD DISP=SHR,DSN=GENAPP.DDRGOT10.DATA
//DDRGRP10 DD DISP=SHR,DSN=GENAPP.DDRGRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT020M9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN11 DD DISP=SHR,DSN=GENAPP.DDMTIN11.DATA
//DDMTOT11 DD DISP=SHR,DSN=GENAPP.DDMTOT11.DATA
//DDMTRP11 DD DISP=SHR,DSN=GENAPP.DDMTRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR020MA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN12 DD DISP=SHR,DSN=GENAPP.DDTRIN12.DATA
//DDTROT12 DD DISP=SHR,DSN=GENAPP.DDTROT12.DATA
//DDTRRP12 DD DISP=SHR,DSN=GENAPP.DDTRRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
