//VJOB2996 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEX02225
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN79 DD DISP=SHR,DSN=GENAPP.DDEXIN79.DATA
//DDEXOT79 DD DISP=SHR,DSN=GENAPP.DDEXOT79.DATA
//DDEXRP79 DD DISP=SHR,DSN=GENAPP.DDEXRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZQU02226
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN80 DD DISP=SHR,DSN=GENAPP.DDQUIN80.DATA
//DDQUOT80 DD DISP=SHR,DSN=GENAPP.DDQUOT80.DATA
//DDQURP80 DD DISP=SHR,DSN=GENAPP.DDQURP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL02227
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN81 DD DISP=SHR,DSN=GENAPP.DDFLIN81.DATA
//DDFLOT81 DD DISP=SHR,DSN=GENAPP.DDFLOT81.DATA
//DDFLRP81 DD DISP=SHR,DSN=GENAPP.DDFLRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
