//VJOB2627 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT0217E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN52 DD DISP=SHR,DSN=GENAPP.DDMTIN52.DATA
//DDMTOT52 DD DISP=SHR,DSN=GENAPP.DDMTOT52.DATA
//DDMTRP52 DD DISP=SHR,DSN=GENAPP.DDMTRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0217F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN53 DD DISP=SHR,DSN=GENAPP.DDMTIN53.DATA
//DDMTOT53 DD DISP=SHR,DSN=GENAPP.DDMTOT53.DATA
//DDMTRP53 DD DISP=SHR,DSN=GENAPP.DDMTRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE0217G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN54 DD DISP=SHR,DSN=GENAPP.DDPEIN54.DATA
//DDPEOT54 DD DISP=SHR,DSN=GENAPP.DDPEOT54.DATA
//DDPERP54 DD DISP=SHR,DSN=GENAPP.DDPERP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
