//VJOB3496 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRN0237T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN49 DD DISP=SHR,DSN=GENAPP.DDRNIN49.DATA
//DDRNOT49 DD DISP=SHR,DSN=GENAPP.DDRNOT49.DATA
//DDRNRP49 DD DISP=SHR,DSN=GENAPP.DDRNRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN0237U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN50 DD DISP=SHR,DSN=GENAPP.DDPNIN50.DATA
//DDPNOT50 DD DISP=SHR,DSN=GENAPP.DDPNOT50.DATA
//DDPNRP50 DD DISP=SHR,DSN=GENAPP.DDPNRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR0237V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN51 DD DISP=SHR,DSN=GENAPP.DDBRIN51.DATA
//DDBROT51 DD DISP=SHR,DSN=GENAPP.DDBROT51.DATA
//DDBRRP51 DD DISP=SHR,DSN=GENAPP.DDBRRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
