//VJOB2506 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO020XB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN49 DD DISP=SHR,DSN=GENAPP.DDCOIN49.DATA
//DDCOOT49 DD DISP=SHR,DSN=GENAPP.DDCOOT49.DATA
//DDCORP49 DD DISP=SHR,DSN=GENAPP.DDCORP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCN020XC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN50 DD DISP=SHR,DSN=GENAPP.DDCNIN50.DATA
//DDCNOT50 DD DISP=SHR,DSN=GENAPP.DDCNOT50.DATA
//DDCNRP50 DD DISP=SHR,DSN=GENAPP.DDCNRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCN020XD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN51 DD DISP=SHR,DSN=GENAPP.DDCNIN51.DATA
//DDCNOT51 DD DISP=SHR,DSN=GENAPP.DDCNOT51.DATA
//DDCNRP51 DD DISP=SHR,DSN=GENAPP.DDCNRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
