//VJOB3416 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG02315
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN79 DD DISP=SHR,DSN=GENAPP.DDRGIN79.DATA
//DDRGOT79 DD DISP=SHR,DSN=GENAPP.DDRGOT79.DATA
//DDRGRP79 DD DISP=SHR,DSN=GENAPP.DDRGRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN02316
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN80 DD DISP=SHR,DSN=GENAPP.DDENIN80.DATA
//DDENOT80 DD DISP=SHR,DSN=GENAPP.DDENOT80.DATA
//DDENRP80 DD DISP=SHR,DSN=GENAPP.DDENRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN02317
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN81 DD DISP=SHR,DSN=GENAPP.DDENIN81.DATA
//DDENOT81 DD DISP=SHR,DSN=GENAPP.DDENOT81.DATA
//DDENRP81 DD DISP=SHR,DSN=GENAPP.DDENRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
