//VJOB1976 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01ZP5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN79 DD DISP=SHR,DSN=GENAPP.DDCUIN79.DATA
//DDCUOT79 DD DISP=SHR,DSN=GENAPP.DDCUOT79.DATA
//DDCURP79 DD DISP=SHR,DSN=GENAPP.DDCURP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01ZP6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN80 DD DISP=SHR,DSN=GENAPP.DDBIIN80.DATA
//DDBIOT80 DD DISP=SHR,DSN=GENAPP.DDBIOT80.DATA
//DDBIRP80 DD DISP=SHR,DSN=GENAPP.DDBIRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01ZP7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN81 DD DISP=SHR,DSN=GENAPP.DDHOIN81.DATA
//DDHOOT81 DD DISP=SHR,DSN=GENAPP.DDHOOT81.DATA
//DDHORP81 DD DISP=SHR,DSN=GENAPP.DDHORP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
