//VJOB0909 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE01X88
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN28 DD DISP=SHR,DSN=GENAPP.DDHEIN28.DATA
//DDHEOT28 DD DISP=SHR,DSN=GENAPP.DDHEOT28.DATA
//DDHERP28 DD DISP=SHR,DSN=GENAPP.DDHERP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY01X89
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN29 DD DISP=SHR,DSN=GENAPP.DDTYIN29.DATA
//DDTYOT29 DD DISP=SHR,DSN=GENAPP.DDTYOT29.DATA
//DDTYRP29 DD DISP=SHR,DSN=GENAPP.DDTYRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01X8A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN30 DD DISP=SHR,DSN=GENAPP.DDBIIN30.DATA
//DDBIOT30 DD DISP=SHR,DSN=GENAPP.DDBIOT30.DATA
//DDBIRP30 DD DISP=SHR,DSN=GENAPP.DDBIRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
