//VJOB4046 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIF024HN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN79 DD DISP=SHR,DSN=GENAPP.DDIFIN79.DATA
//DDIFOT79 DD DISP=SHR,DSN=GENAPP.DDIFOT79.DATA
//DDIFRP79 DD DISP=SHR,DSN=GENAPP.DDIFRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA024HO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN80 DD DISP=SHR,DSN=GENAPP.DDBAIN80.DATA
//DDBAOT80 DD DISP=SHR,DSN=GENAPP.DDBAOT80.DATA
//DDBARP80 DD DISP=SHR,DSN=GENAPP.DDBARP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT024HP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN81 DD DISP=SHR,DSN=GENAPP.DDMTIN81.DATA
//DDMTOT81 DD DISP=SHR,DSN=GENAPP.DDMTOT81.DATA
//DDMTRP81 DD DISP=SHR,DSN=GENAPP.DDMTRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
