//VJOB3778 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO023VB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN85 DD DISP=SHR,DSN=GENAPP.DDHOIN85.DATA
//DDHOOT85 DD DISP=SHR,DSN=GENAPP.DDHOOT85.DATA
//DDHORP85 DD DISP=SHR,DSN=GENAPP.DDHORP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL023VC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN86 DD DISP=SHR,DSN=GENAPP.DDCLIN86.DATA
//DDCLOT86 DD DISP=SHR,DSN=GENAPP.DDCLOT86.DATA
//DDCLRP86 DD DISP=SHR,DSN=GENAPP.DDCLRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN023VD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN87 DD DISP=SHR,DSN=GENAPP.DDPNIN87.DATA
//DDPNOT87 DD DISP=SHR,DSN=GENAPP.DDPNOT87.DATA
//DDPNRP87 DD DISP=SHR,DSN=GENAPP.DDPNRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
