//VJOB0605 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE01WIW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN16 DD DISP=SHR,DSN=GENAPP.DDREIN16.DATA
//DDREOT16 DD DISP=SHR,DSN=GENAPP.DDREOT16.DATA
//DDRERP16 DD DISP=SHR,DSN=GENAPP.DDRERP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA01WIX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN17 DD DISP=SHR,DSN=GENAPP.DDBAIN17.DATA
//DDBAOT17 DD DISP=SHR,DSN=GENAPP.DDBAOT17.DATA
//DDBARP17 DD DISP=SHR,DSN=GENAPP.DDBARP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01WIY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN18 DD DISP=SHR,DSN=GENAPP.DDMTIN18.DATA
//DDMTOT18 DD DISP=SHR,DSN=GENAPP.DDMTOT18.DATA
//DDMTRP18 DD DISP=SHR,DSN=GENAPP.DDMTRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
