//VJOB0518 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA01WBN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN25 DD DISP=SHR,DSN=GENAPP.DDPAIN25.DATA
//DDPAOT25 DD DISP=SHR,DSN=GENAPP.DDPAOT25.DATA
//DDPARP25 DD DISP=SHR,DSN=GENAPP.DDPARP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE01WBO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN26 DD DISP=SHR,DSN=GENAPP.DDREIN26.DATA
//DDREOT26 DD DISP=SHR,DSN=GENAPP.DDREOT26.DATA
//DDRERP26 DD DISP=SHR,DSN=GENAPP.DDRERP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01WBP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN27 DD DISP=SHR,DSN=GENAPP.DDHOIN27.DATA
//DDHOOT27 DD DISP=SHR,DSN=GENAPP.DDHOOT27.DATA
//DDHORP27 DD DISP=SHR,DSN=GENAPP.DDHORP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
