//VJOB0260 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAZ01VQ5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN61 DD DISP=SHR,DSN=GENAPP.DDAZIN61.DATA
//DDAZOT61 DD DISP=SHR,DSN=GENAPP.DDAZOT61.DATA
//DDAZRP61 DD DISP=SHR,DSN=GENAPP.DDAZRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG01VQ6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN62 DD DISP=SHR,DSN=GENAPP.DDRGIN62.DATA
//DDRGOT62 DD DISP=SHR,DSN=GENAPP.DDRGOT62.DATA
//DDRGRP62 DD DISP=SHR,DSN=GENAPP.DDRGRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01VQ7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN63 DD DISP=SHR,DSN=GENAPP.DDENIN63.DATA
//DDENOT63 DD DISP=SHR,DSN=GENAPP.DDENOT63.DATA
//DDENRP63 DD DISP=SHR,DSN=GENAPP.DDENRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
