//VJOB0121 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01VEK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN04 DD DISP=SHR,DSN=GENAPP.DDCLIN04.DATA
//DDCLOT04 DD DISP=SHR,DSN=GENAPP.DDCLOT04.DATA
//DDCLRP04 DD DISP=SHR,DSN=GENAPP.DDCLRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01VEL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN05 DD DISP=SHR,DSN=GENAPP.DDMTIN05.DATA
//DDMTOT05 DD DISP=SHR,DSN=GENAPP.DDMTOT05.DATA
//DDMTRP05 DD DISP=SHR,DSN=GENAPP.DDMTRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSU01VEM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN06 DD DISP=SHR,DSN=GENAPP.DDSUIN06.DATA
//DDSUOT06 DD DISP=SHR,DSN=GENAPP.DDSUOT06.DATA
//DDSURP06 DD DISP=SHR,DSN=GENAPP.DDSURP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
