//VJOB3171 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG022GQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN64 DD DISP=SHR,DSN=GENAPP.DDAGIN64.DATA
//DDAGOT64 DD DISP=SHR,DSN=GENAPP.DDAGOT64.DATA
//DDAGRP64 DD DISP=SHR,DSN=GENAPP.DDAGRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC022GR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN65 DD DISP=SHR,DSN=GENAPP.DDSCIN65.DATA
//DDSCOT65 DD DISP=SHR,DSN=GENAPP.DDSCOT65.DATA
//DDSCRP65 DD DISP=SHR,DSN=GENAPP.DDSCRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN022GS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN66 DD DISP=SHR,DSN=GENAPP.DDENIN66.DATA
//DDENOT66 DD DISP=SHR,DSN=GENAPP.DDENOT66.DATA
//DDENRP66 DD DISP=SHR,DSN=GENAPP.DDENRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
