//VJOB1820 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE01ZC5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN61 DD DISP=SHR,DSN=GENAPP.DDSEIN61.DATA
//DDSEOT61 DD DISP=SHR,DSN=GENAPP.DDSEOT61.DATA
//DDSERP61 DD DISP=SHR,DSN=GENAPP.DDSERP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ01ZC6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN62 DD DISP=SHR,DSN=GENAPP.DDAZIN62.DATA
//DDAZOT62 DD DISP=SHR,DSN=GENAPP.DDAZOT62.DATA
//DDAZRP62 DD DISP=SHR,DSN=GENAPP.DDAZRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01ZC7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN63 DD DISP=SHR,DSN=GENAPP.DDBIIN63.DATA
//DDBIOT63 DD DISP=SHR,DSN=GENAPP.DDBIOT63.DATA
//DDBIRP63 DD DISP=SHR,DSN=GENAPP.DDBIRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
