//VJOB1994 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL01ZQN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN43 DD DISP=SHR,DSN=GENAPP.DDFLIN43.DATA
//DDFLOT43 DD DISP=SHR,DSN=GENAPP.DDFLOT43.DATA
//DDFLRP43 DD DISP=SHR,DSN=GENAPP.DDFLRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01ZQO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN44 DD DISP=SHR,DSN=GENAPP.DDMTIN44.DATA
//DDMTOT44 DD DISP=SHR,DSN=GENAPP.DDMTOT44.DATA
//DDMTRP44 DD DISP=SHR,DSN=GENAPP.DDMTRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS01ZQP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN45 DD DISP=SHR,DSN=GENAPP.DDRSIN45.DATA
//DDRSOT45 DD DISP=SHR,DSN=GENAPP.DDRSOT45.DATA
//DDRSRP45 DD DISP=SHR,DSN=GENAPP.DDRSRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
