//VJOB4000 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB024DT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN31 DD DISP=SHR,DSN=GENAPP.DDLBIN31.DATA
//DDLBOT31 DD DISP=SHR,DSN=GENAPP.DDLBOT31.DATA
//DDLBRP31 DD DISP=SHR,DSN=GENAPP.DDLBRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO024DU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN32 DD DISP=SHR,DSN=GENAPP.DDCOIN32.DATA
//DDCOOT32 DD DISP=SHR,DSN=GENAPP.DDCOOT32.DATA
//DDCORP32 DD DISP=SHR,DSN=GENAPP.DDCORP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN024DV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN33 DD DISP=SHR,DSN=GENAPP.DDENIN33.DATA
//DDENOT33 DD DISP=SHR,DSN=GENAPP.DDENOT33.DATA
//DDENRP33 DD DISP=SHR,DSN=GENAPP.DDENRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
