//VJOB2634 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAZ0217Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN73 DD DISP=SHR,DSN=GENAPP.DDAZIN73.DATA
//DDAZOT73 DD DISP=SHR,DSN=GENAPP.DDAZOT73.DATA
//DDAZRP73 DD DISP=SHR,DSN=GENAPP.DDAZRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO02180
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN74 DD DISP=SHR,DSN=GENAPP.DDHOIN74.DATA
//DDHOOT74 DD DISP=SHR,DSN=GENAPP.DDHOOT74.DATA
//DDHORP74 DD DISP=SHR,DSN=GENAPP.DDHORP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI02181
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN75 DD DISP=SHR,DSN=GENAPP.DDLIIN75.DATA
//DDLIOT75 DD DISP=SHR,DSN=GENAPP.DDLIOT75.DATA
//DDLIRP75 DD DISP=SHR,DSN=GENAPP.DDLIRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
