//VJOB0245 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01VOW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN16 DD DISP=SHR,DSN=GENAPP.DDENIN16.DATA
//DDENOT16 DD DISP=SHR,DSN=GENAPP.DDENOT16.DATA
//DDENRP16 DD DISP=SHR,DSN=GENAPP.DDENRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR01VOX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN17 DD DISP=SHR,DSN=GENAPP.DDCRIN17.DATA
//DDCROT17 DD DISP=SHR,DSN=GENAPP.DDCROT17.DATA
//DDCRRP17 DD DISP=SHR,DSN=GENAPP.DDCRRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01VOY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN18 DD DISP=SHR,DSN=GENAPP.DDBIIN18.DATA
//DDBIOT18 DD DISP=SHR,DSN=GENAPP.DDBIOT18.DATA
//DDBIRP18 DD DISP=SHR,DSN=GENAPP.DDBIRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
