//VJOB4326 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB0254Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN19 DD DISP=SHR,DSN=GENAPP.DDLBIN19.DATA
//DDLBOT19 DD DISP=SHR,DSN=GENAPP.DDLBOT19.DATA
//DDLBRP19 DD DISP=SHR,DSN=GENAPP.DDLBRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCN02550
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN20 DD DISP=SHR,DSN=GENAPP.DDCNIN20.DATA
//DDCNOT20 DD DISP=SHR,DSN=GENAPP.DDCNOT20.DATA
//DDCNRP20 DD DISP=SHR,DSN=GENAPP.DDCNRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT02551
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN21 DD DISP=SHR,DSN=GENAPP.DDMTIN21.DATA
//DDMTOT21 DD DISP=SHR,DSN=GENAPP.DDMTOT21.DATA
//DDMTRP21 DD DISP=SHR,DSN=GENAPP.DDMTRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
