//VJOB2826 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA021NZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN19 DD DISP=SHR,DSN=GENAPP.DDPAIN19.DATA
//DDPAOT19 DD DISP=SHR,DSN=GENAPP.DDPAOT19.DATA
//DDPARP19 DD DISP=SHR,DSN=GENAPP.DDPARP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT021O0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN20 DD DISP=SHR,DSN=GENAPP.DDMTIN20.DATA
//DDMTOT20 DD DISP=SHR,DSN=GENAPP.DDMTOT20.DATA
//DDMTRP20 DD DISP=SHR,DSN=GENAPP.DDMTRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO021O1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN21 DD DISP=SHR,DSN=GENAPP.DDHOIN21.DATA
//DDHOOT21 DD DISP=SHR,DSN=GENAPP.DDHOOT21.DATA
//DDHORP21 DD DISP=SHR,DSN=GENAPP.DDHORP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
