//VJOB1000 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY01XFT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN31 DD DISP=SHR,DSN=GENAPP.DDTYIN31.DATA
//DDTYOT31 DD DISP=SHR,DSN=GENAPP.DDTYOT31.DATA
//DDTYRP31 DD DISP=SHR,DSN=GENAPP.DDTYRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01XFU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN32 DD DISP=SHR,DSN=GENAPP.DDMTIN32.DATA
//DDMTOT32 DD DISP=SHR,DSN=GENAPP.DDMTOT32.DATA
//DDMTRP32 DD DISP=SHR,DSN=GENAPP.DDMTRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01XFV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN33 DD DISP=SHR,DSN=GENAPP.DDCUIN33.DATA
//DDCUOT33 DD DISP=SHR,DSN=GENAPP.DDCUOT33.DATA
//DDCURP33 DD DISP=SHR,DSN=GENAPP.DDCURP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
