//VJOB4305 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO02538
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN46 DD DISP=SHR,DSN=GENAPP.DDHOIN46.DATA
//DDHOOT46 DD DISP=SHR,DSN=GENAPP.DDHOOT46.DATA
//DDHORP46 DD DISP=SHR,DSN=GENAPP.DDHORP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT02539
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN47 DD DISP=SHR,DSN=GENAPP.DDLTIN47.DATA
//DDLTOT47 DD DISP=SHR,DSN=GENAPP.DDLTOT47.DATA
//DDLTRP47 DD DISP=SHR,DSN=GENAPP.DDLTRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU0253A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN48 DD DISP=SHR,DSN=GENAPP.DDCUIN48.DATA
//DDCUOT48 DD DISP=SHR,DSN=GENAPP.DDCUOT48.DATA
//DDCURP48 DD DISP=SHR,DSN=GENAPP.DDCURP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
