//VJOB2745 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW021H8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN46 DD DISP=SHR,DSN=GENAPP.DDUWIN46.DATA
//DDUWOT46 DD DISP=SHR,DSN=GENAPP.DDUWOT46.DATA
//DDUWRP46 DD DISP=SHR,DSN=GENAPP.DDUWRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG021H9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN47 DD DISP=SHR,DSN=GENAPP.DDAGIN47.DATA
//DDAGOT47 DD DISP=SHR,DSN=GENAPP.DDAGOT47.DATA
//DDAGRP47 DD DISP=SHR,DSN=GENAPP.DDAGRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI021HA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN48 DD DISP=SHR,DSN=GENAPP.DDBIIN48.DATA
//DDBIOT48 DD DISP=SHR,DSN=GENAPP.DDBIOT48.DATA
//DDBIRP48 DD DISP=SHR,DSN=GENAPP.DDBIRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
