//VJOB3920 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZST02475
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN61 DD DISP=SHR,DSN=GENAPP.DDSTIN61.DATA
//DDSTOT61 DD DISP=SHR,DSN=GENAPP.DDSTOT61.DATA
//DDSTRP61 DD DISP=SHR,DSN=GENAPP.DDSTRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO02476
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN62 DD DISP=SHR,DSN=GENAPP.DDCOIN62.DATA
//DDCOOT62 DD DISP=SHR,DSN=GENAPP.DDCOOT62.DATA
//DDCORP62 DD DISP=SHR,DSN=GENAPP.DDCORP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC02477
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN63 DD DISP=SHR,DSN=GENAPP.DDACIN63.DATA
//DDACOT63 DD DISP=SHR,DSN=GENAPP.DDACOT63.DATA
//DDACRP63 DD DISP=SHR,DSN=GENAPP.DDACRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
