//VJOB0724 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC01WST
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN13 DD DISP=SHR,DSN=GENAPP.DDACIN13.DATA
//DDACOT13 DD DISP=SHR,DSN=GENAPP.DDACOT13.DATA
//DDACRP13 DD DISP=SHR,DSN=GENAPP.DDACRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSU01WSU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN14 DD DISP=SHR,DSN=GENAPP.DDSUIN14.DATA
//DDSUOT14 DD DISP=SHR,DSN=GENAPP.DDSUOT14.DATA
//DDSURP14 DD DISP=SHR,DSN=GENAPP.DDSURP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS01WSV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN15 DD DISP=SHR,DSN=GENAPP.DDRSIN15.DATA
//DDRSOT15 DD DISP=SHR,DSN=GENAPP.DDRSOT15.DATA
//DDRSRP15 DD DISP=SHR,DSN=GENAPP.DDRSRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
