//VJOB2935 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT021X2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN76 DD DISP=SHR,DSN=GENAPP.DDNTIN76.DATA
//DDNTOT76 DD DISP=SHR,DSN=GENAPP.DDNTOT76.DATA
//DDNTRP76 DD DISP=SHR,DSN=GENAPP.DDNTRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR021X3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN77 DD DISP=SHR,DSN=GENAPP.DDBRIN77.DATA
//DDBROT77 DD DISP=SHR,DSN=GENAPP.DDBROT77.DATA
//DDBRRP77 DD DISP=SHR,DSN=GENAPP.DDBRRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN021X4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN78 DD DISP=SHR,DSN=GENAPP.DDANIN78.DATA
//DDANOT78 DD DISP=SHR,DSN=GENAPP.DDANOT78.DATA
//DDANRP78 DD DISP=SHR,DSN=GENAPP.DDANRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
