//VJOB4092 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO024LH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN37 DD DISP=SHR,DSN=GENAPP.DDHOIN37.DATA
//DDHOOT37 DD DISP=SHR,DSN=GENAPP.DDHOOT37.DATA
//DDHORP37 DD DISP=SHR,DSN=GENAPP.DDHORP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR024LI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN38 DD DISP=SHR,DSN=GENAPP.DDBRIN38.DATA
//DDBROT38 DD DISP=SHR,DSN=GENAPP.DDBROT38.DATA
//DDBRRP38 DD DISP=SHR,DSN=GENAPP.DDBRRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW024LJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN39 DD DISP=SHR,DSN=GENAPP.DDUWIN39.DATA
//DDUWOT39 DD DISP=SHR,DSN=GENAPP.DDUWOT39.DATA
//DDUWRP39 DD DISP=SHR,DSN=GENAPP.DDUWRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
