//VJOB1487 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZED01YKE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN52 DD DISP=SHR,DSN=GENAPP.DDEDIN52.DATA
//DDEDOT52 DD DISP=SHR,DSN=GENAPP.DDEDOT52.DATA
//DDEDRP52 DD DISP=SHR,DSN=GENAPP.DDEDRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA01YKF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN53 DD DISP=SHR,DSN=GENAPP.DDMAIN53.DATA
//DDMAOT53 DD DISP=SHR,DSN=GENAPP.DDMAOT53.DATA
//DDMARP53 DD DISP=SHR,DSN=GENAPP.DDMARP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01YKG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN54 DD DISP=SHR,DSN=GENAPP.DDCUIN54.DATA
//DDCUOT54 DD DISP=SHR,DSN=GENAPP.DDCUOT54.DATA
//DDCURP54 DD DISP=SHR,DSN=GENAPP.DDCURP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
