//VJOB3056 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG02275
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN79 DD DISP=SHR,DSN=GENAPP.DDAGIN79.DATA
//DDAGOT79 DD DISP=SHR,DSN=GENAPP.DDAGOT79.DATA
//DDAGRP79 DD DISP=SHR,DSN=GENAPP.DDAGRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN02276
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN80 DD DISP=SHR,DSN=GENAPP.DDPNIN80.DATA
//DDPNOT80 DD DISP=SHR,DSN=GENAPP.DDPNOT80.DATA
//DDPNRP80 DD DISP=SHR,DSN=GENAPP.DDPNRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF02277
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN81 DD DISP=SHR,DSN=GENAPP.DDIFIN81.DATA
//DDIFOT81 DD DISP=SHR,DSN=GENAPP.DDIFOT81.DATA
//DDIFRP81 DD DISP=SHR,DSN=GENAPP.DDIFRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
