//VJOB0889 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01X6K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN58 DD DISP=SHR,DSN=GENAPP.DDCLIN58.DATA
//DDCLOT58 DD DISP=SHR,DSN=GENAPP.DDCLOT58.DATA
//DDCLRP58 DD DISP=SHR,DSN=GENAPP.DDCLRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE01X6L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN59 DD DISP=SHR,DSN=GENAPP.DDSEIN59.DATA
//DDSEOT59 DD DISP=SHR,DSN=GENAPP.DDSEOT59.DATA
//DDSERP59 DD DISP=SHR,DSN=GENAPP.DDSERP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS01X6M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN60 DD DISP=SHR,DSN=GENAPP.DDRSIN60.DATA
//DDRSOT60 DD DISP=SHR,DSN=GENAPP.DDRSOT60.DATA
//DDRSRP60 DD DISP=SHR,DSN=GENAPP.DDRSRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
