//VJOB0275 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDO01VRE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN16 DD DISP=SHR,DSN=GENAPP.DDDOIN16.DATA
//DDDOOT16 DD DISP=SHR,DSN=GENAPP.DDDOOT16.DATA
//DDDORP16 DD DISP=SHR,DSN=GENAPP.DDDORP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE01VRF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN17 DD DISP=SHR,DSN=GENAPP.DDHEIN17.DATA
//DDHEOT17 DD DISP=SHR,DSN=GENAPP.DDHEOT17.DATA
//DDHERP17 DD DISP=SHR,DSN=GENAPP.DDHERP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN01VRG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN18 DD DISP=SHR,DSN=GENAPP.DDANIN18.DATA
//DDANOT18 DD DISP=SHR,DSN=GENAPP.DDANOT18.DATA
//DDANRP18 DD DISP=SHR,DSN=GENAPP.DDANRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
