//VJOB1729 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01Z4K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN58 DD DISP=SHR,DSN=GENAPP.DDCOIN58.DATA
//DDCOOT58 DD DISP=SHR,DSN=GENAPP.DDCOOT58.DATA
//DDCORP58 DD DISP=SHR,DSN=GENAPP.DDCORP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB01Z4L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN59 DD DISP=SHR,DSN=GENAPP.DDLBIN59.DATA
//DDLBOT59 DD DISP=SHR,DSN=GENAPP.DDLBOT59.DATA
//DDLBRP59 DD DISP=SHR,DSN=GENAPP.DDLBRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01Z4M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN60 DD DISP=SHR,DSN=GENAPP.DDHOIN60.DATA
//DDHOOT60 DD DISP=SHR,DSN=GENAPP.DDHOOT60.DATA
//DDHORP60 DD DISP=SHR,DSN=GENAPP.DDHORP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
