//VJOB0173 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAU01VIW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN70 DD DISP=SHR,DSN=GENAPP.DDAUIN70.DATA
//DDAUOT70 DD DISP=SHR,DSN=GENAPP.DDAUOT70.DATA
//DDAURP70 DD DISP=SHR,DSN=GENAPP.DDAURP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01VIX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN71 DD DISP=SHR,DSN=GENAPP.DDLIIN71.DATA
//DDLIOT71 DD DISP=SHR,DSN=GENAPP.DDLIOT71.DATA
//DDLIRP71 DD DISP=SHR,DSN=GENAPP.DDLIRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01VIY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN72 DD DISP=SHR,DSN=GENAPP.DDPEIN72.DATA
//DDPEOT72 DD DISP=SHR,DSN=GENAPP.DDPEOT72.DATA
//DDPERP72 DD DISP=SHR,DSN=GENAPP.DDPERP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
