//VJOB1894 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01ZIB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN13 DD DISP=SHR,DSN=GENAPP.DDCLIN13.DATA
//DDCLOT13 DD DISP=SHR,DSN=GENAPP.DDCLOT13.DATA
//DDCLRP13 DD DISP=SHR,DSN=GENAPP.DDCLRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR01ZIC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN14 DD DISP=SHR,DSN=GENAPP.DDTRIN14.DATA
//DDTROT14 DD DISP=SHR,DSN=GENAPP.DDTROT14.DATA
//DDTRRP14 DD DISP=SHR,DSN=GENAPP.DDTRRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01ZID
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN15 DD DISP=SHR,DSN=GENAPP.DDBIIN15.DATA
//DDBIOT15 DD DISP=SHR,DSN=GENAPP.DDBIOT15.DATA
//DDBIRP15 DD DISP=SHR,DSN=GENAPP.DDBIRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
