//VJOB2872 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX021RT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN67 DD DISP=SHR,DSN=GENAPP.DDTXIN67.DATA
//DDTXOT67 DD DISP=SHR,DSN=GENAPP.DDTXOT67.DATA
//DDTXRP67 DD DISP=SHR,DSN=GENAPP.DDTXRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE021RU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN68 DD DISP=SHR,DSN=GENAPP.DDSEIN68.DATA
//DDSEOT68 DD DISP=SHR,DSN=GENAPP.DDSEOT68.DATA
//DDSERP68 DD DISP=SHR,DSN=GENAPP.DDSERP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA021RV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN69 DD DISP=SHR,DSN=GENAPP.DDMAIN69.DATA
//DDMAOT69 DD DISP=SHR,DSN=GENAPP.DDMAOT69.DATA
//DDMARP69 DD DISP=SHR,DSN=GENAPP.DDMARP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
