//VJOB0042 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01V7Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN37 DD DISP=SHR,DSN=GENAPP.DDMTIN37.DATA
//DDMTOT37 DD DISP=SHR,DSN=GENAPP.DDMTOT37.DATA
//DDMTRP37 DD DISP=SHR,DSN=GENAPP.DDMTRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF01V80
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN38 DD DISP=SHR,DSN=GENAPP.DDIFIN38.DATA
//DDIFOT38 DD DISP=SHR,DSN=GENAPP.DDIFOT38.DATA
//DDIFRP38 DD DISP=SHR,DSN=GENAPP.DDIFRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA01V81
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN39 DD DISP=SHR,DSN=GENAPP.DDPAIN39.DATA
//DDPAOT39 DD DISP=SHR,DSN=GENAPP.DDPAOT39.DATA
//DDPARP39 DD DISP=SHR,DSN=GENAPP.DDPARP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
