//VJOB2899 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB021U2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN58 DD DISP=SHR,DSN=GENAPP.DDMBIN58.DATA
//DDMBOT58 DD DISP=SHR,DSN=GENAPP.DDMBOT58.DATA
//DDMBRP58 DD DISP=SHR,DSN=GENAPP.DDMBRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN021U3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN59 DD DISP=SHR,DSN=GENAPP.DDENIN59.DATA
//DDENOT59 DD DISP=SHR,DSN=GENAPP.DDENOT59.DATA
//DDENRP59 DD DISP=SHR,DSN=GENAPP.DDENRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN021U4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN60 DD DISP=SHR,DSN=GENAPP.DDENIN60.DATA
//DDENOT60 DD DISP=SHR,DSN=GENAPP.DDENOT60.DATA
//DDENRP60 DD DISP=SHR,DSN=GENAPP.DDENRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
