//VJOB1605 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01YU8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN46 DD DISP=SHR,DSN=GENAPP.DDCUIN46.DATA
//DDCUOT46 DD DISP=SHR,DSN=GENAPP.DDCUOT46.DATA
//DDCURP46 DD DISP=SHR,DSN=GENAPP.DDCURP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01YU9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN47 DD DISP=SHR,DSN=GENAPP.DDHOIN47.DATA
//DDHOOT47 DD DISP=SHR,DSN=GENAPP.DDHOOT47.DATA
//DDHORP47 DD DISP=SHR,DSN=GENAPP.DDHORP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01YUA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN48 DD DISP=SHR,DSN=GENAPP.DDBIIN48.DATA
//DDBIOT48 DD DISP=SHR,DSN=GENAPP.DDBIOT48.DATA
//DDBIRP48 DD DISP=SHR,DSN=GENAPP.DDBIRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
