//VJOB2629 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC0217K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN58 DD DISP=SHR,DSN=GENAPP.DDACIN58.DATA
//DDACOT58 DD DISP=SHR,DSN=GENAPP.DDACOT58.DATA
//DDACRP58 DD DISP=SHR,DSN=GENAPP.DDACRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN0217L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN59 DD DISP=SHR,DSN=GENAPP.DDRNIN59.DATA
//DDRNOT59 DD DISP=SHR,DSN=GENAPP.DDRNOT59.DATA
//DDRNRP59 DD DISP=SHR,DSN=GENAPP.DDRNRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA0217M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN60 DD DISP=SHR,DSN=GENAPP.DDMAIN60.DATA
//DDMAOT60 DD DISP=SHR,DSN=GENAPP.DDMAOT60.DATA
//DDMARP60 DD DISP=SHR,DSN=GENAPP.DDMARP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
