//VJOB0979 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS01XE2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN58 DD DISP=SHR,DSN=GENAPP.DDRSIN58.DATA
//DDRSOT58 DD DISP=SHR,DSN=GENAPP.DDRSOT58.DATA
//DDRSRP58 DD DISP=SHR,DSN=GENAPP.DDRSRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01XE3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN59 DD DISP=SHR,DSN=GENAPP.DDMTIN59.DATA
//DDMTOT59 DD DISP=SHR,DSN=GENAPP.DDMTOT59.DATA
//DDMTRP59 DD DISP=SHR,DSN=GENAPP.DDMTRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01XE4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN60 DD DISP=SHR,DSN=GENAPP.DDMTIN60.DATA
//DDMTOT60 DD DISP=SHR,DSN=GENAPP.DDMTOT60.DATA
//DDMTRP60 DD DISP=SHR,DSN=GENAPP.DDMTRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
