//VJOB4041 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR024H8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN64 DD DISP=SHR,DSN=GENAPP.DDTRIN64.DATA
//DDTROT64 DD DISP=SHR,DSN=GENAPP.DDTROT64.DATA
//DDTRRP64 DD DISP=SHR,DSN=GENAPP.DDTRRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN024H9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN65 DD DISP=SHR,DSN=GENAPP.DDENIN65.DATA
//DDENOT65 DD DISP=SHR,DSN=GENAPP.DDENOT65.DATA
//DDENRP65 DD DISP=SHR,DSN=GENAPP.DDENRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV024HA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN66 DD DISP=SHR,DSN=GENAPP.DDIVIN66.DATA
//DDIVOT66 DD DISP=SHR,DSN=GENAPP.DDIVOT66.DATA
//DDIVRP66 DD DISP=SHR,DSN=GENAPP.DDIVRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
