//VJOB0927 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01X9Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN82 DD DISP=SHR,DSN=GENAPP.DDENIN82.DATA
//DDENOT82 DD DISP=SHR,DSN=GENAPP.DDENOT82.DATA
//DDENRP82 DD DISP=SHR,DSN=GENAPP.DDENRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPL01X9R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN83 DD DISP=SHR,DSN=GENAPP.DDPLIN83.DATA
//DDPLOT83 DD DISP=SHR,DSN=GENAPP.DDPLOT83.DATA
//DDPLRP83 DD DISP=SHR,DSN=GENAPP.DDPLRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSL01X9S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN84 DD DISP=SHR,DSN=GENAPP.DDSLIN84.DATA
//DDSLOT84 DD DISP=SHR,DSN=GENAPP.DDSLOT84.DATA
//DDSLRP84 DD DISP=SHR,DSN=GENAPP.DDSLRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
