//VJOB3974 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI024BN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN43 DD DISP=SHR,DSN=GENAPP.DDBIIN43.DATA
//DDBIOT43 DD DISP=SHR,DSN=GENAPP.DDBIOT43.DATA
//DDBIRP43 DD DISP=SHR,DSN=GENAPP.DDBIRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA024BO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN44 DD DISP=SHR,DSN=GENAPP.DDMAIN44.DATA
//DDMAOT44 DD DISP=SHR,DSN=GENAPP.DDMAOT44.DATA
//DDMARP44 DD DISP=SHR,DSN=GENAPP.DDMARP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZGW024BP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN45 DD DISP=SHR,DSN=GENAPP.DDGWIN45.DATA
//DDGWOT45 DD DISP=SHR,DSN=GENAPP.DDGWOT45.DATA
//DDGWRP45 DD DISP=SHR,DSN=GENAPP.DDGWRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
