//VJOB0151 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01VH2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN04 DD DISP=SHR,DSN=GENAPP.DDBIIN04.DATA
//DDBIOT04 DD DISP=SHR,DSN=GENAPP.DDBIOT04.DATA
//DDBIRP04 DD DISP=SHR,DSN=GENAPP.DDBIRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY01VH3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN05 DD DISP=SHR,DSN=GENAPP.DDTYIN05.DATA
//DDTYOT05 DD DISP=SHR,DSN=GENAPP.DDTYOT05.DATA
//DDTYRP05 DD DISP=SHR,DSN=GENAPP.DDTYRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC01VH4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN06 DD DISP=SHR,DSN=GENAPP.DDSCIN06.DATA
//DDSCOT06 DD DISP=SHR,DSN=GENAPP.DDSCOT06.DATA
//DDSCRP06 DD DISP=SHR,DSN=GENAPP.DDSCRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
