//VJOB1142 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL01XRN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN07 DD DISP=SHR,DSN=GENAPP.DDFLIN07.DATA
//DDFLOT07 DD DISP=SHR,DSN=GENAPP.DDFLOT07.DATA
//DDFLRP07 DD DISP=SHR,DSN=GENAPP.DDFLRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRS01XRO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN08 DD DISP=SHR,DSN=GENAPP.DDRSIN08.DATA
//DDRSOT08 DD DISP=SHR,DSN=GENAPP.DDRSOT08.DATA
//DDRSRP08 DD DISP=SHR,DSN=GENAPP.DDRSRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01XRP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN09 DD DISP=SHR,DSN=GENAPP.DDMTIN09.DATA
//DDMTOT09 DD DISP=SHR,DSN=GENAPP.DDMTOT09.DATA
//DDMTRP09 DD DISP=SHR,DSN=GENAPP.DDMTRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
