//VJOB1701 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSL01Z28
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN64 DD DISP=SHR,DSN=GENAPP.DDSLIN64.DATA
//DDSLOT64 DD DISP=SHR,DSN=GENAPP.DDSLOT64.DATA
//DDSLRP64 DD DISP=SHR,DSN=GENAPP.DDSLRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA01Z29
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN65 DD DISP=SHR,DSN=GENAPP.DDMAIN65.DATA
//DDMAOT65 DD DISP=SHR,DSN=GENAPP.DDMAOT65.DATA
//DDMARP65 DD DISP=SHR,DSN=GENAPP.DDMARP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01Z2A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN66 DD DISP=SHR,DSN=GENAPP.DDCUIN66.DATA
//DDCUOT66 DD DISP=SHR,DSN=GENAPP.DDCUOT66.DATA
//DDCURP66 DD DISP=SHR,DSN=GENAPP.DDCURP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
