//VJOB2829 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC021O8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN28 DD DISP=SHR,DSN=GENAPP.DDRCIN28.DATA
//DDRCOT28 DD DISP=SHR,DSN=GENAPP.DDRCOT28.DATA
//DDRCRP28 DD DISP=SHR,DSN=GENAPP.DDRCRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMB021O9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN29 DD DISP=SHR,DSN=GENAPP.DDMBIN29.DATA
//DDMBOT29 DD DISP=SHR,DSN=GENAPP.DDMBOT29.DATA
//DDMBRP29 DD DISP=SHR,DSN=GENAPP.DDMBRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI021OA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN30 DD DISP=SHR,DSN=GENAPP.DDLIIN30.DATA
//DDLIOT30 DD DISP=SHR,DSN=GENAPP.DDLIOT30.DATA
//DDLIRP30 DD DISP=SHR,DSN=GENAPP.DDLIRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
