//VJOB3083 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI0229E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN70 DD DISP=SHR,DSN=GENAPP.DDLIIN70.DATA
//DDLIOT70 DD DISP=SHR,DSN=GENAPP.DDLIOT70.DATA
//DDLIRP70 DD DISP=SHR,DSN=GENAPP.DDLIRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZST0229F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN71 DD DISP=SHR,DSN=GENAPP.DDSTIN71.DATA
//DDSTOT71 DD DISP=SHR,DSN=GENAPP.DDSTOT71.DATA
//DDSTRP71 DD DISP=SHR,DSN=GENAPP.DDSTRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO0229G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN72 DD DISP=SHR,DSN=GENAPP.DDHOIN72.DATA
//DDHOOT72 DD DISP=SHR,DSN=GENAPP.DDHOOT72.DATA
//DDHORP72 DD DISP=SHR,DSN=GENAPP.DDHORP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
