//VJOB3230 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAU022LN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN61 DD DISP=SHR,DSN=GENAPP.DDAUIN61.DATA
//DDAUOT61 DD DISP=SHR,DSN=GENAPP.DDAUOT61.DATA
//DDAURP61 DD DISP=SHR,DSN=GENAPP.DDAURP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA022LO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN62 DD DISP=SHR,DSN=GENAPP.DDPAIN62.DATA
//DDPAOT62 DD DISP=SHR,DSN=GENAPP.DDPAOT62.DATA
//DDPARP62 DD DISP=SHR,DSN=GENAPP.DDPARP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE022LP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN63 DD DISP=SHR,DSN=GENAPP.DDREIN63.DATA
//DDREOT63 DD DISP=SHR,DSN=GENAPP.DDREOT63.DATA
//DDRERP63 DD DISP=SHR,DSN=GENAPP.DDRERP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
