//VJOB3475 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAR02362
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN76 DD DISP=SHR,DSN=GENAPP.DDARIN76.DATA
//DDAROT76 DD DISP=SHR,DSN=GENAPP.DDAROT76.DATA
//DDARRP76 DD DISP=SHR,DSN=GENAPP.DDARRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN02363
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN77 DD DISP=SHR,DSN=GENAPP.DDENIN77.DATA
//DDENOT77 DD DISP=SHR,DSN=GENAPP.DDENOT77.DATA
//DDENRP77 DD DISP=SHR,DSN=GENAPP.DDENRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA02364
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN78 DD DISP=SHR,DSN=GENAPP.DDMAIN78.DATA
//DDMAOT78 DD DISP=SHR,DSN=GENAPP.DDMAOT78.DATA
//DDMARP78 DD DISP=SHR,DSN=GENAPP.DDMARP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
