//VJOB1156 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZQU01XST
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN49 DD DISP=SHR,DSN=GENAPP.DDQUIN49.DATA
//DDQUOT49 DD DISP=SHR,DSN=GENAPP.DDQUOT49.DATA
//DDQURP49 DD DISP=SHR,DSN=GENAPP.DDQURP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01XSU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN50 DD DISP=SHR,DSN=GENAPP.DDLIIN50.DATA
//DDLIOT50 DD DISP=SHR,DSN=GENAPP.DDLIOT50.DATA
//DDLIRP50 DD DISP=SHR,DSN=GENAPP.DDLIRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE01XSV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN51 DD DISP=SHR,DSN=GENAPP.DDHEIN51.DATA
//DDHEOT51 DD DISP=SHR,DSN=GENAPP.DDHEOT51.DATA
//DDHERP51 DD DISP=SHR,DSN=GENAPP.DDHERP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
