//VJOB3976 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBR024BT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN49 DD DISP=SHR,DSN=GENAPP.DDBRIN49.DATA
//DDBROT49 DD DISP=SHR,DSN=GENAPP.DDBROT49.DATA
//DDBRRP49 DD DISP=SHR,DSN=GENAPP.DDBRRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI024BU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN50 DD DISP=SHR,DSN=GENAPP.DDLIIN50.DATA
//DDLIOT50 DD DISP=SHR,DSN=GENAPP.DDLIOT50.DATA
//DDLIRP50 DD DISP=SHR,DSN=GENAPP.DDLIRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV024BV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN51 DD DISP=SHR,DSN=GENAPP.DDAVIN51.DATA
//DDAVOT51 DD DISP=SHR,DSN=GENAPP.DDAVOT51.DATA
//DDAVRP51 DD DISP=SHR,DSN=GENAPP.DDAVRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
