//VJOB2639 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI0218E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN88 DD DISP=SHR,DSN=GENAPP.DDBIIN88.DATA
//DDBIOT88 DD DISP=SHR,DSN=GENAPP.DDBIOT88.DATA
//DDBIRP88 DD DISP=SHR,DSN=GENAPP.DDBIRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG0218F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN89 DD DISP=SHR,DSN=GENAPP.DDAGIN89.DATA
//DDAGOT89 DD DISP=SHR,DSN=GENAPP.DDAGOT89.DATA
//DDAGRP89 DD DISP=SHR,DSN=GENAPP.DDAGRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRN0218G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN90 DD DISP=SHR,DSN=GENAPP.DDRNIN90.DATA
//DDRNOT90 DD DISP=SHR,DSN=GENAPP.DDRNOT90.DATA
//DDRNRP90 DD DISP=SHR,DSN=GENAPP.DDRNRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
