//VJOB1326 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPL01Y6Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN19 DD DISP=SHR,DSN=GENAPP.DDPLIN19.DATA
//DDPLOT19 DD DISP=SHR,DSN=GENAPP.DDPLOT19.DATA
//DDPLRP19 DD DISP=SHR,DSN=GENAPP.DDPLRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01Y70
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN20 DD DISP=SHR,DSN=GENAPP.DDFLIN20.DATA
//DDFLOT20 DD DISP=SHR,DSN=GENAPP.DDFLOT20.DATA
//DDFLRP20 DD DISP=SHR,DSN=GENAPP.DDFLRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01Y71
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN21 DD DISP=SHR,DSN=GENAPP.DDPEIN21.DATA
//DDPEOT21 DD DISP=SHR,DSN=GENAPP.DDPEOT21.DATA
//DDPERP21 DD DISP=SHR,DSN=GENAPP.DDPERP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
