//VJOB0577 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01WGK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN22 DD DISP=SHR,DSN=GENAPP.DDHOIN22.DATA
//DDHOOT22 DD DISP=SHR,DSN=GENAPP.DDHOOT22.DATA
//DDHORP22 DD DISP=SHR,DSN=GENAPP.DDHORP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPT01WGL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN23 DD DISP=SHR,DSN=GENAPP.DDPTIN23.DATA
//DDPTOT23 DD DISP=SHR,DSN=GENAPP.DDPTOT23.DATA
//DDPTRP23 DD DISP=SHR,DSN=GENAPP.DDPTRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01WGM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN24 DD DISP=SHR,DSN=GENAPP.DDPEIN24.DATA
//DDPEOT24 DD DISP=SHR,DSN=GENAPP.DDPEOT24.DATA
//DDPERP24 DD DISP=SHR,DSN=GENAPP.DDPERP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
