//VJOB2357 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIF020KW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN52 DD DISP=SHR,DSN=GENAPP.DDIFIN52.DATA
//DDIFOT52 DD DISP=SHR,DSN=GENAPP.DDIFOT52.DATA
//DDIFRP52 DD DISP=SHR,DSN=GENAPP.DDIFRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE020KX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN53 DD DISP=SHR,DSN=GENAPP.DDHEIN53.DATA
//DDHEOT53 DD DISP=SHR,DSN=GENAPP.DDHEOT53.DATA
//DDHERP53 DD DISP=SHR,DSN=GENAPP.DDHERP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZQU020KY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN54 DD DISP=SHR,DSN=GENAPP.DDQUIN54.DATA
//DDQUOT54 DD DISP=SHR,DSN=GENAPP.DDQUOT54.DATA
//DDQURP54 DD DISP=SHR,DSN=GENAPP.DDQURP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
