//VJOB4269 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSC02508
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN28 DD DISP=SHR,DSN=GENAPP.DDSCIN28.DATA
//DDSCOT28 DD DISP=SHR,DSN=GENAPP.DDSCOT28.DATA
//DDSCRP28 DD DISP=SHR,DSN=GENAPP.DDSCRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU02509
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN29 DD DISP=SHR,DSN=GENAPP.DDCUIN29.DATA
//DDCUOT29 DD DISP=SHR,DSN=GENAPP.DDCUOT29.DATA
//DDCURP29 DD DISP=SHR,DSN=GENAPP.DDCURP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU0250A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN30 DD DISP=SHR,DSN=GENAPP.DDCUIN30.DATA
//DDCUOT30 DD DISP=SHR,DSN=GENAPP.DDCUOT30.DATA
//DDCURP30 DD DISP=SHR,DSN=GENAPP.DDCURP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
