//VJOB3449 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCR0233W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN88 DD DISP=SHR,DSN=GENAPP.DDCRIN88.DATA
//DDCROT88 DD DISP=SHR,DSN=GENAPP.DDCROT88.DATA
//DDCRRP88 DD DISP=SHR,DSN=GENAPP.DDCRRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA0233X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN89 DD DISP=SHR,DSN=GENAPP.DDPAIN89.DATA
//DDPAOT89 DD DISP=SHR,DSN=GENAPP.DDPAOT89.DATA
//DDPARP89 DD DISP=SHR,DSN=GENAPP.DDPARP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF0233Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN90 DD DISP=SHR,DSN=GENAPP.DDIFIN90.DATA
//DDIFOT90 DD DISP=SHR,DSN=GENAPP.DDIFOT90.DATA
//DDIFRP90 DD DISP=SHR,DSN=GENAPP.DDIFRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
