//VJOB1553 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01YPW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN70 DD DISP=SHR,DSN=GENAPP.DDBIIN70.DATA
//DDBIOT70 DD DISP=SHR,DSN=GENAPP.DDBIOT70.DATA
//DDBIRP70 DD DISP=SHR,DSN=GENAPP.DDBIRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFR01YPX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN71 DD DISP=SHR,DSN=GENAPP.DDFRIN71.DATA
//DDFROT71 DD DISP=SHR,DSN=GENAPP.DDFROT71.DATA
//DDFRRP71 DD DISP=SHR,DSN=GENAPP.DDFRRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV01YPY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN72 DD DISP=SHR,DSN=GENAPP.DDAVIN72.DATA
//DDAVOT72 DD DISP=SHR,DSN=GENAPP.DDAVOT72.DATA
//DDAVRP72 DD DISP=SHR,DSN=GENAPP.DDAVRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
