//VJOB4228 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT024WT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN85 DD DISP=SHR,DSN=GENAPP.DDMTIN85.DATA
//DDMTOT85 DD DISP=SHR,DSN=GENAPP.DDMTOT85.DATA
//DDMTRP85 DD DISP=SHR,DSN=GENAPP.DDMTRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEX024WU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN86 DD DISP=SHR,DSN=GENAPP.DDEXIN86.DATA
//DDEXOT86 DD DISP=SHR,DSN=GENAPP.DDEXOT86.DATA
//DDEXRP86 DD DISP=SHR,DSN=GENAPP.DDEXRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG024WV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN87 DD DISP=SHR,DSN=GENAPP.DDRGIN87.DATA
//DDRGOT87 DD DISP=SHR,DSN=GENAPP.DDRGOT87.DATA
//DDRGRP87 DD DISP=SHR,DSN=GENAPP.DDRGRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
