//VJOB3744 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE023SH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN73 DD DISP=SHR,DSN=GENAPP.DDREIN73.DATA
//DDREOT73 DD DISP=SHR,DSN=GENAPP.DDREOT73.DATA
//DDRERP73 DD DISP=SHR,DSN=GENAPP.DDRERP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN023SI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN74 DD DISP=SHR,DSN=GENAPP.DDPNIN74.DATA
//DDPNOT74 DD DISP=SHR,DSN=GENAPP.DDPNOT74.DATA
//DDPNRP74 DD DISP=SHR,DSN=GENAPP.DDPNRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE023SJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN75 DD DISP=SHR,DSN=GENAPP.DDHEIN75.DATA
//DDHEOT75 DD DISP=SHR,DSN=GENAPP.DDHEOT75.DATA
//DDHERP75 DD DISP=SHR,DSN=GENAPP.DDHERP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
