//VJOB3038 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLT0225N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN25 DD DISP=SHR,DSN=GENAPP.DDLTIN25.DATA
//DDLTOT25 DD DISP=SHR,DSN=GENAPP.DDLTOT25.DATA
//DDLTRP25 DD DISP=SHR,DSN=GENAPP.DDLTRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSB0225O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN26 DD DISP=SHR,DSN=GENAPP.DDSBIN26.DATA
//DDSBOT26 DD DISP=SHR,DSN=GENAPP.DDSBOT26.DATA
//DDSBRP26 DD DISP=SHR,DSN=GENAPP.DDSBRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN0225P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN27 DD DISP=SHR,DSN=GENAPP.DDANIN27.DATA
//DDANOT27 DD DISP=SHR,DSN=GENAPP.DDANOT27.DATA
//DDANRP27 DD DISP=SHR,DSN=GENAPP.DDANRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
