//VJOB4093 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT024LK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN40 DD DISP=SHR,DSN=GENAPP.DDMTIN40.DATA
//DDMTOT40 DD DISP=SHR,DSN=GENAPP.DDMTOT40.DATA
//DDMTRP40 DD DISP=SHR,DSN=GENAPP.DDMTRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE024LL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN41 DD DISP=SHR,DSN=GENAPP.DDREIN41.DATA
//DDREOT41 DD DISP=SHR,DSN=GENAPP.DDREOT41.DATA
//DDRERP41 DD DISP=SHR,DSN=GENAPP.DDRERP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL024LM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN42 DD DISP=SHR,DSN=GENAPP.DDCLIN42.DATA
//DDCLOT42 DD DISP=SHR,DSN=GENAPP.DDCLOT42.DATA
//DDCLRP42 DD DISP=SHR,DSN=GENAPP.DDCLRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
