//VJOB3393 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN022Z8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN10 DD DISP=SHR,DSN=GENAPP.DDPNIN10.DATA
//DDPNOT10 DD DISP=SHR,DSN=GENAPP.DDPNOT10.DATA
//DDPNRP10 DD DISP=SHR,DSN=GENAPP.DDPNRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB022Z9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN11 DD DISP=SHR,DSN=GENAPP.DDLBIN11.DATA
//DDLBOT11 DD DISP=SHR,DSN=GENAPP.DDLBOT11.DATA
//DDLBRP11 DD DISP=SHR,DSN=GENAPP.DDLBRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU022ZA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN12 DD DISP=SHR,DSN=GENAPP.DDCUIN12.DATA
//DDCUOT12 DD DISP=SHR,DSN=GENAPP.DDCUOT12.DATA
//DDCURP12 DD DISP=SHR,DSN=GENAPP.DDCURP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
