//VJOB3405 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA02308
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN46 DD DISP=SHR,DSN=GENAPP.DDMAIN46.DATA
//DDMAOT46 DD DISP=SHR,DSN=GENAPP.DDMAOT46.DATA
//DDMARP46 DD DISP=SHR,DSN=GENAPP.DDMARP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN02309
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN47 DD DISP=SHR,DSN=GENAPP.DDENIN47.DATA
//DDENOT47 DD DISP=SHR,DSN=GENAPP.DDENOT47.DATA
//DDENRP47 DD DISP=SHR,DSN=GENAPP.DDENRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSE0230A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN48 DD DISP=SHR,DSN=GENAPP.DDSEIN48.DATA
//DDSEOT48 DD DISP=SHR,DSN=GENAPP.DDSEOT48.DATA
//DDSERP48 DD DISP=SHR,DSN=GENAPP.DDSERP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
