//VJOB3403 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT02302
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN40 DD DISP=SHR,DSN=GENAPP.DDMTIN40.DATA
//DDMTOT40 DD DISP=SHR,DSN=GENAPP.DDMTOT40.DATA
//DDMTRP40 DD DISP=SHR,DSN=GENAPP.DDMTRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA02303
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN41 DD DISP=SHR,DSN=GENAPP.DDPAIN41.DATA
//DDPAOT41 DD DISP=SHR,DSN=GENAPP.DDPAOT41.DATA
//DDPARP41 DD DISP=SHR,DSN=GENAPP.DDPARP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLB02304
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN42 DD DISP=SHR,DSN=GENAPP.DDLBIN42.DATA
//DDLBOT42 DD DISP=SHR,DSN=GENAPP.DDLBOT42.DATA
//DDLBRP42 DD DISP=SHR,DSN=GENAPP.DDLBRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
