//VJOB0576 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01WGH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN19 DD DISP=SHR,DSN=GENAPP.DDCUIN19.DATA
//DDCUOT19 DD DISP=SHR,DSN=GENAPP.DDCUOT19.DATA
//DDCURP19 DD DISP=SHR,DSN=GENAPP.DDCURP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO01WGI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN20 DD DISP=SHR,DSN=GENAPP.DDCOIN20.DATA
//DDCOOT20 DD DISP=SHR,DSN=GENAPP.DDCOOT20.DATA
//DDCORP20 DD DISP=SHR,DSN=GENAPP.DDCORP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01WGJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN21 DD DISP=SHR,DSN=GENAPP.DDENIN21.DATA
//DDENOT21 DD DISP=SHR,DSN=GENAPP.DDENOT21.DATA
//DDENRP21 DD DISP=SHR,DSN=GENAPP.DDENRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
