//VJOB2982 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC0220Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN37 DD DISP=SHR,DSN=GENAPP.DDRCIN37.DATA
//DDRCOT37 DD DISP=SHR,DSN=GENAPP.DDRCOT37.DATA
//DDRCRP37 DD DISP=SHR,DSN=GENAPP.DDRCRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO02210
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN38 DD DISP=SHR,DSN=GENAPP.DDHOIN38.DATA
//DDHOOT38 DD DISP=SHR,DSN=GENAPP.DDHOOT38.DATA
//DDHORP38 DD DISP=SHR,DSN=GENAPP.DDHORP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN02211
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN39 DD DISP=SHR,DSN=GENAPP.DDENIN39.DATA
//DDENOT39 DD DISP=SHR,DSN=GENAPP.DDENOT39.DATA
//DDENRP39 DD DISP=SHR,DSN=GENAPP.DDENRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
