//VJOB1933 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRT01ZLK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN40 DD DISP=SHR,DSN=GENAPP.DDRTIN40.DATA
//DDRTOT40 DD DISP=SHR,DSN=GENAPP.DDRTOT40.DATA
//DDRTRP40 DD DISP=SHR,DSN=GENAPP.DDRTRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE01ZLL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN41 DD DISP=SHR,DSN=GENAPP.DDPEIN41.DATA
//DDPEOT41 DD DISP=SHR,DSN=GENAPP.DDPEOT41.DATA
//DDPERP41 DD DISP=SHR,DSN=GENAPP.DDPERP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC01ZLM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN42 DD DISP=SHR,DSN=GENAPP.DDSCIN42.DATA
//DDSCOT42 DD DISP=SHR,DSN=GENAPP.DDSCOT42.DATA
//DDSCRP42 DD DISP=SHR,DSN=GENAPP.DDSCRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
