//VJOB1459 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSL01YI2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN58 DD DISP=SHR,DSN=GENAPP.DDSLIN58.DATA
//DDSLOT58 DD DISP=SHR,DSN=GENAPP.DDSLOT58.DATA
//DDSLRP58 DD DISP=SHR,DSN=GENAPP.DDSLRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZWF01YI3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN59 DD DISP=SHR,DSN=GENAPP.DDWFIN59.DATA
//DDWFOT59 DD DISP=SHR,DSN=GENAPP.DDWFOT59.DATA
//DDWFRP59 DD DISP=SHR,DSN=GENAPP.DDWFRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01YI4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN60 DD DISP=SHR,DSN=GENAPP.DDCLIN60.DATA
//DDCLOT60 DD DISP=SHR,DSN=GENAPP.DDCLOT60.DATA
//DDCLRP60 DD DISP=SHR,DSN=GENAPP.DDCLRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
