//VJOB3060 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP0227H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN01 DD DISP=SHR,DSN=GENAPP.DDCPIN01.DATA
//DDCPOT01 DD DISP=SHR,DSN=GENAPP.DDCPOT01.DATA
//DDCPRP01 DD DISP=SHR,DSN=GENAPP.DDCPRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW0227I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN02 DD DISP=SHR,DSN=GENAPP.DDUWIN02.DATA
//DDUWOT02 DD DISP=SHR,DSN=GENAPP.DDUWOT02.DATA
//DDUWRP02 DD DISP=SHR,DSN=GENAPP.DDUWRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTY0227J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN03 DD DISP=SHR,DSN=GENAPP.DDTYIN03.DATA
//DDTYOT03 DD DISP=SHR,DSN=GENAPP.DDTYOT03.DATA
//DDTYRP03 DD DISP=SHR,DSN=GENAPP.DDTYRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
