//VJOB0322 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCN01VVB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN67 DD DISP=SHR,DSN=GENAPP.DDCNIN67.DATA
//DDCNOT67 DD DISP=SHR,DSN=GENAPP.DDCNOT67.DATA
//DDCNRP67 DD DISP=SHR,DSN=GENAPP.DDCNRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01VVC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN68 DD DISP=SHR,DSN=GENAPP.DDPAIN68.DATA
//DDPAOT68 DD DISP=SHR,DSN=GENAPP.DDPAOT68.DATA
//DDPARP68 DD DISP=SHR,DSN=GENAPP.DDPARP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO01VVD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN69 DD DISP=SHR,DSN=GENAPP.DDCOIN69.DATA
//DDCOOT69 DD DISP=SHR,DSN=GENAPP.DDCOOT69.DATA
//DDCORP69 DD DISP=SHR,DSN=GENAPP.DDCORP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
