//VJOB3458 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR0234N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN25 DD DISP=SHR,DSN=GENAPP.DDFRIN25.DATA
//DDFROT25 DD DISP=SHR,DSN=GENAPP.DDFROT25.DATA
//DDFRRP25 DD DISP=SHR,DSN=GENAPP.DDFRRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDO0234O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN26 DD DISP=SHR,DSN=GENAPP.DDDOIN26.DATA
//DDDOOT26 DD DISP=SHR,DSN=GENAPP.DDDOOT26.DATA
//DDDORP26 DD DISP=SHR,DSN=GENAPP.DDDORP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA0234P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN27 DD DISP=SHR,DSN=GENAPP.DDPAIN27.DATA
//DDPAOT27 DD DISP=SHR,DSN=GENAPP.DDPAOT27.DATA
//DDPARP27 DD DISP=SHR,DSN=GENAPP.DDPARP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
