//VJOB0643 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE01WM2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN40 DD DISP=SHR,DSN=GENAPP.DDREIN40.DATA
//DDREOT40 DD DISP=SHR,DSN=GENAPP.DDREOT40.DATA
//DDRERP40 DD DISP=SHR,DSN=GENAPP.DDRERP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN01WM3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN41 DD DISP=SHR,DSN=GENAPP.DDRNIN41.DATA
//DDRNOT41 DD DISP=SHR,DSN=GENAPP.DDRNOT41.DATA
//DDRNRP41 DD DISP=SHR,DSN=GENAPP.DDRNRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSL01WM4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN42 DD DISP=SHR,DSN=GENAPP.DDSLIN42.DATA
//DDSLOT42 DD DISP=SHR,DSN=GENAPP.DDSLOT42.DATA
//DDSLRP42 DD DISP=SHR,DSN=GENAPP.DDSLRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
