//VJOB0356 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSC01VY5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN79 DD DISP=SHR,DSN=GENAPP.DDSCIN79.DATA
//DDSCOT79 DD DISP=SHR,DSN=GENAPP.DDSCOT79.DATA
//DDSCRP79 DD DISP=SHR,DSN=GENAPP.DDSCRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE01VY6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN80 DD DISP=SHR,DSN=GENAPP.DDPEIN80.DATA
//DDPEOT80 DD DISP=SHR,DSN=GENAPP.DDPEOT80.DATA
//DDPERP80 DD DISP=SHR,DSN=GENAPP.DDPERP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA01VY7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN81 DD DISP=SHR,DSN=GENAPP.DDPAIN81.DATA
//DDPAOT81 DD DISP=SHR,DSN=GENAPP.DDPAOT81.DATA
//DDPARP81 DD DISP=SHR,DSN=GENAPP.DDPARP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
