//VJOB0150 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV01VGZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN01 DD DISP=SHR,DSN=GENAPP.DDIVIN01.DATA
//DDIVOT01 DD DISP=SHR,DSN=GENAPP.DDIVOT01.DATA
//DDIVRP01 DD DISP=SHR,DSN=GENAPP.DDIVRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT01VH0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN02 DD DISP=SHR,DSN=GENAPP.DDLTIN02.DATA
//DDLTOT02 DD DISP=SHR,DSN=GENAPP.DDLTOT02.DATA
//DDLTRP02 DD DISP=SHR,DSN=GENAPP.DDLTRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01VH1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN03 DD DISP=SHR,DSN=GENAPP.DDMTIN03.DATA
//DDMTOT03 DD DISP=SHR,DSN=GENAPP.DDMTOT03.DATA
//DDMTRP03 DD DISP=SHR,DSN=GENAPP.DDMTRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
