//VJOB3384 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR022YH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN73 DD DISP=SHR,DSN=GENAPP.DDTRIN73.DATA
//DDTROT73 DD DISP=SHR,DSN=GENAPP.DDTROT73.DATA
//DDTRRP73 DD DISP=SHR,DSN=GENAPP.DDTRRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT022YI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN74 DD DISP=SHR,DSN=GENAPP.DDMTIN74.DATA
//DDMTOT74 DD DISP=SHR,DSN=GENAPP.DDMTOT74.DATA
//DDMTRP74 DD DISP=SHR,DSN=GENAPP.DDMTRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPL022YJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN75 DD DISP=SHR,DSN=GENAPP.DDPLIN75.DATA
//DDPLOT75 DD DISP=SHR,DSN=GENAPP.DDPLOT75.DATA
//DDPLRP75 DD DISP=SHR,DSN=GENAPP.DDPLRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
