//VJOB3703 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE023P2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN40 DD DISP=SHR,DSN=GENAPP.DDREIN40.DATA
//DDREOT40 DD DISP=SHR,DSN=GENAPP.DDREOT40.DATA
//DDRERP40 DD DISP=SHR,DSN=GENAPP.DDRERP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT023P3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN41 DD DISP=SHR,DSN=GENAPP.DDLTIN41.DATA
//DDLTOT41 DD DISP=SHR,DSN=GENAPP.DDLTOT41.DATA
//DDLTRP41 DD DISP=SHR,DSN=GENAPP.DDLTRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRS023P4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN42 DD DISP=SHR,DSN=GENAPP.DDRSIN42.DATA
//DDRSOT42 DD DISP=SHR,DSN=GENAPP.DDRSOT42.DATA
//DDRSRP42 DD DISP=SHR,DSN=GENAPP.DDRSRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
