//VJOB3243 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRN022MQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN10 DD DISP=SHR,DSN=GENAPP.DDRNIN10.DATA
//DDRNOT10 DD DISP=SHR,DSN=GENAPP.DDRNOT10.DATA
//DDRNRP10 DD DISP=SHR,DSN=GENAPP.DDRNRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE022MR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN11 DD DISP=SHR,DSN=GENAPP.DDHEIN11.DATA
//DDHEOT11 DD DISP=SHR,DSN=GENAPP.DDHEOT11.DATA
//DDHERP11 DD DISP=SHR,DSN=GENAPP.DDHERP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX022MS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN12 DD DISP=SHR,DSN=GENAPP.DDTXIN12.DATA
//DDTXOT12 DD DISP=SHR,DSN=GENAPP.DDTXOT12.DATA
//DDTXRP12 DD DISP=SHR,DSN=GENAPP.DDTXRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
