//VJOB1958 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01ZNN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN25 DD DISP=SHR,DSN=GENAPP.DDMTIN25.DATA
//DDMTOT25 DD DISP=SHR,DSN=GENAPP.DDMTOT25.DATA
//DDMTRP25 DD DISP=SHR,DSN=GENAPP.DDMTRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF01ZNO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN26 DD DISP=SHR,DSN=GENAPP.DDIFIN26.DATA
//DDIFOT26 DD DISP=SHR,DSN=GENAPP.DDIFOT26.DATA
//DDIFRP26 DD DISP=SHR,DSN=GENAPP.DDIFRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF01ZNP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN27 DD DISP=SHR,DSN=GENAPP.DDIFIN27.DATA
//DDIFOT27 DD DISP=SHR,DSN=GENAPP.DDIFOT27.DATA
//DDIFRP27 DD DISP=SHR,DSN=GENAPP.DDIFRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
