//VJOB4212 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA024VH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN37 DD DISP=SHR,DSN=GENAPP.DDMAIN37.DATA
//DDMAOT37 DD DISP=SHR,DSN=GENAPP.DDMAOT37.DATA
//DDMARP37 DD DISP=SHR,DSN=GENAPP.DDMARP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZVA024VI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN38 DD DISP=SHR,DSN=GENAPP.DDVAIN38.DATA
//DDVAOT38 DD DISP=SHR,DSN=GENAPP.DDVAOT38.DATA
//DDVARP38 DD DISP=SHR,DSN=GENAPP.DDVARP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW024VJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN39 DD DISP=SHR,DSN=GENAPP.DDUWIN39.DATA
//DDUWOT39 DD DISP=SHR,DSN=GENAPP.DDUWOT39.DATA
//DDUWRP39 DD DISP=SHR,DSN=GENAPP.DDUWRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
