//VJOB1022 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE01XHN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN07 DD DISP=SHR,DSN=GENAPP.DDPEIN07.DATA
//DDPEOT07 DD DISP=SHR,DSN=GENAPP.DDPEOT07.DATA
//DDPERP07 DD DISP=SHR,DSN=GENAPP.DDPERP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN01XHO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN08 DD DISP=SHR,DSN=GENAPP.DDPNIN08.DATA
//DDPNOT08 DD DISP=SHR,DSN=GENAPP.DDPNOT08.DATA
//DDPNRP08 DD DISP=SHR,DSN=GENAPP.DDPNRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV01XHP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN09 DD DISP=SHR,DSN=GENAPP.DDAVIN09.DATA
//DDAVOT09 DD DISP=SHR,DSN=GENAPP.DDAVOT09.DATA
//DDAVRP09 DD DISP=SHR,DSN=GENAPP.DDAVRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
