//VJOB4012 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA024ET
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN67 DD DISP=SHR,DSN=GENAPP.DDMAIN67.DATA
//DDMAOT67 DD DISP=SHR,DSN=GENAPP.DDMAOT67.DATA
//DDMARP67 DD DISP=SHR,DSN=GENAPP.DDMARP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO024EU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN68 DD DISP=SHR,DSN=GENAPP.DDHOIN68.DATA
//DDHOOT68 DD DISP=SHR,DSN=GENAPP.DDHOOT68.DATA
//DDHORP68 DD DISP=SHR,DSN=GENAPP.DDHORP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC024EV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN69 DD DISP=SHR,DSN=GENAPP.DDSCIN69.DATA
//DDSCOT69 DD DISP=SHR,DSN=GENAPP.DDSCOT69.DATA
//DDSCRP69 DD DISP=SHR,DSN=GENAPP.DDSCRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
