//VJOB1303 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01Y52
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN40 DD DISP=SHR,DSN=GENAPP.DDBIIN40.DATA
//DDBIOT40 DD DISP=SHR,DSN=GENAPP.DDBIOT40.DATA
//DDBIRP40 DD DISP=SHR,DSN=GENAPP.DDBIRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSL01Y53
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN41 DD DISP=SHR,DSN=GENAPP.DDSLIN41.DATA
//DDSLOT41 DD DISP=SHR,DSN=GENAPP.DDSLOT41.DATA
//DDSLRP41 DD DISP=SHR,DSN=GENAPP.DDSLRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAZ01Y54
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN42 DD DISP=SHR,DSN=GENAPP.DDAZIN42.DATA
//DDAZOT42 DD DISP=SHR,DSN=GENAPP.DDAZOT42.DATA
//DDAZRP42 DD DISP=SHR,DSN=GENAPP.DDAZRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
