//VJOB1292 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAZ01Y45
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN07 DD DISP=SHR,DSN=GENAPP.DDAZIN07.DATA
//DDAZOT07 DD DISP=SHR,DSN=GENAPP.DDAZOT07.DATA
//DDAZRP07 DD DISP=SHR,DSN=GENAPP.DDAZRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01Y46
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN08 DD DISP=SHR,DSN=GENAPP.DDLIIN08.DATA
//DDLIOT08 DD DISP=SHR,DSN=GENAPP.DDLIOT08.DATA
//DDLIRP08 DD DISP=SHR,DSN=GENAPP.DDLIRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01Y47
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN09 DD DISP=SHR,DSN=GENAPP.DDHOIN09.DATA
//DDHOOT09 DD DISP=SHR,DSN=GENAPP.DDHOOT09.DATA
//DDHORP09 DD DISP=SHR,DSN=GENAPP.DDHORP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
