//VJOB1159 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS01XT2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN58 DD DISP=SHR,DSN=GENAPP.DDRSIN58.DATA
//DDRSOT58 DD DISP=SHR,DSN=GENAPP.DDRSOT58.DATA
//DDRSRP58 DD DISP=SHR,DSN=GENAPP.DDRSRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN01XT3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN59 DD DISP=SHR,DSN=GENAPP.DDENIN59.DATA
//DDENOT59 DD DISP=SHR,DSN=GENAPP.DDENOT59.DATA
//DDENRP59 DD DISP=SHR,DSN=GENAPP.DDENRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRC01XT4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN60 DD DISP=SHR,DSN=GENAPP.DDRCIN60.DATA
//DDRCOT60 DD DISP=SHR,DSN=GENAPP.DDRCOT60.DATA
//DDRCRP60 DD DISP=SHR,DSN=GENAPP.DDRCRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
