//VJOB1616 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZED01YV5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN79 DD DISP=SHR,DSN=GENAPP.DDEDIN79.DATA
//DDEDOT79 DD DISP=SHR,DSN=GENAPP.DDEDOT79.DATA
//DDEDRP79 DD DISP=SHR,DSN=GENAPP.DDEDRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZGW01YV6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN80 DD DISP=SHR,DSN=GENAPP.DDGWIN80.DATA
//DDGWOT80 DD DISP=SHR,DSN=GENAPP.DDGWOT80.DATA
//DDGWRP80 DD DISP=SHR,DSN=GENAPP.DDGWRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01YV7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN81 DD DISP=SHR,DSN=GENAPP.DDHOIN81.DATA
//DDHOOT81 DD DISP=SHR,DSN=GENAPP.DDHOOT81.DATA
//DDHORP81 DD DISP=SHR,DSN=GENAPP.DDHORP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
