//VJOB0007 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN01V52
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN22 DD DISP=SHR,DSN=GENAPP.DDPNIN22.DATA
//DDPNOT22 DD DISP=SHR,DSN=GENAPP.DDPNOT22.DATA
//DDPNRP22 DD DISP=SHR,DSN=GENAPP.DDPNRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV01V53
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN23 DD DISP=SHR,DSN=GENAPP.DDIVIN23.DATA
//DDIVOT23 DD DISP=SHR,DSN=GENAPP.DDIVOT23.DATA
//DDIVRP23 DD DISP=SHR,DSN=GENAPP.DDIVRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX01V54
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN24 DD DISP=SHR,DSN=GENAPP.DDTXIN24.DATA
//DDTXOT24 DD DISP=SHR,DSN=GENAPP.DDTXOT24.DATA
//DDTXRP24 DD DISP=SHR,DSN=GENAPP.DDTXRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
