//VJOB1636 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01YWT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN49 DD DISP=SHR,DSN=GENAPP.DDBIIN49.DATA
//DDBIOT49 DD DISP=SHR,DSN=GENAPP.DDBIOT49.DATA
//DDBIRP49 DD DISP=SHR,DSN=GENAPP.DDBIRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01YWU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN50 DD DISP=SHR,DSN=GENAPP.DDCUIN50.DATA
//DDCUOT50 DD DISP=SHR,DSN=GENAPP.DDCUOT50.DATA
//DDCURP50 DD DISP=SHR,DSN=GENAPP.DDCURP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01YWV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN51 DD DISP=SHR,DSN=GENAPP.DDMTIN51.DATA
//DDMTOT51 DD DISP=SHR,DSN=GENAPP.DDMTOT51.DATA
//DDMTRP51 DD DISP=SHR,DSN=GENAPP.DDMTRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
