//VJOB2649 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//RUNPROC  PROC MEM=DEFAULT
//*
//STEP01   EXEC PGM=ZAZ02198
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDAZIN28 DD DISP=SHR,DSN=GENAPP.DDAZIN28.DATA
//DDAZOT28 DD DISP=SHR,DSN=GENAPP.DDAZOT28.DATA
//DDAZRP28 DD DISP=SHR,DSN=GENAPP.DDAZRP28.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCN02199
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDCNIN29 DD DISP=SHR,DSN=GENAPP.DDCNIN29.DATA
//DDCNOT29 DD DISP=SHR,DSN=GENAPP.DDCNOT29.DATA
//DDCNRP29 DD DISP=SHR,DSN=GENAPP.DDCNRP29.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO0219A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDHOIN30 DD DISP=SHR,DSN=GENAPP.DDHOIN30.DATA
//DDHOOT30 DD DISP=SHR,DSN=GENAPP.DDHOOT30.DATA
//DDHORP30 DD DISP=SHR,DSN=GENAPP.DDHORP30.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//         PEND
//RUN      EXEC RUNPROC,MEM=VOLTEST
//
