//VJOB1843 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01ZE2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN40 DD DISP=SHR,DSN=GENAPP.DDHOIN40.DATA
//DDHOOT40 DD DISP=SHR,DSN=GENAPP.DDHOOT40.DATA
//DDHORP40 DD DISP=SHR,DSN=GENAPP.DDHORP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE01ZE3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN41 DD DISP=SHR,DSN=GENAPP.DDSEIN41.DATA
//DDSEOT41 DD DISP=SHR,DSN=GENAPP.DDSEOT41.DATA
//DDSERP41 DD DISP=SHR,DSN=GENAPP.DDSERP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSE01ZE4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN42 DD DISP=SHR,DSN=GENAPP.DDSEIN42.DATA
//DDSEOT42 DD DISP=SHR,DSN=GENAPP.DDSEOT42.DATA
//DDSERP42 DD DISP=SHR,DSN=GENAPP.DDSERP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
