//VJOB3209 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL022JW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN88 DD DISP=SHR,DSN=GENAPP.DDCLIN88.DATA
//DDCLOT88 DD DISP=SHR,DSN=GENAPP.DDCLOT88.DATA
//DDCLRP88 DD DISP=SHR,DSN=GENAPP.DDCLRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN022JX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN89 DD DISP=SHR,DSN=GENAPP.DDENIN89.DATA
//DDENOT89 DD DISP=SHR,DSN=GENAPP.DDENOT89.DATA
//DDENRP89 DD DISP=SHR,DSN=GENAPP.DDENRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA022JY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN90 DD DISP=SHR,DSN=GENAPP.DDPAIN90.DATA
//DDPAOT90 DD DISP=SHR,DSN=GENAPP.DDPAOT90.DATA
//DDPARP90 DD DISP=SHR,DSN=GENAPP.DDPARP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
