//VJOB4010 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG024EN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN61 DD DISP=SHR,DSN=GENAPP.DDAGIN61.DATA
//DDAGOT61 DD DISP=SHR,DSN=GENAPP.DDAGOT61.DATA
//DDAGRP61 DD DISP=SHR,DSN=GENAPP.DDAGRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE024EO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN62 DD DISP=SHR,DSN=GENAPP.DDSEIN62.DATA
//DDSEOT62 DD DISP=SHR,DSN=GENAPP.DDSEOT62.DATA
//DDSERP62 DD DISP=SHR,DSN=GENAPP.DDSERP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC024EP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN63 DD DISP=SHR,DSN=GENAPP.DDSCIN63.DATA
//DDSCOT63 DD DISP=SHR,DSN=GENAPP.DDSCOT63.DATA
//DDSCRP63 DD DISP=SHR,DSN=GENAPP.DDSCRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
