//VJOB0395 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZQU01W1E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN16 DD DISP=SHR,DSN=GENAPP.DDQUIN16.DATA
//DDQUOT16 DD DISP=SHR,DSN=GENAPP.DDQUOT16.DATA
//DDQURP16 DD DISP=SHR,DSN=GENAPP.DDQURP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV01W1F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN17 DD DISP=SHR,DSN=GENAPP.DDAVIN17.DATA
//DDAVOT17 DD DISP=SHR,DSN=GENAPP.DDAVOT17.DATA
//DDAVRP17 DD DISP=SHR,DSN=GENAPP.DDAVRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZED01W1G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN18 DD DISP=SHR,DSN=GENAPP.DDEDIN18.DATA
//DDEDOT18 DD DISP=SHR,DSN=GENAPP.DDEDOT18.DATA
//DDEDRP18 DD DISP=SHR,DSN=GENAPP.DDEDRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
