//VJOB2426 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAR020QN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN79 DD DISP=SHR,DSN=GENAPP.DDARIN79.DATA
//DDAROT79 DD DISP=SHR,DSN=GENAPP.DDAROT79.DATA
//DDARRP79 DD DISP=SHR,DSN=GENAPP.DDARRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL020QO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN80 DD DISP=SHR,DSN=GENAPP.DDCLIN80.DATA
//DDCLOT80 DD DISP=SHR,DSN=GENAPP.DDCLOT80.DATA
//DDCLRP80 DD DISP=SHR,DSN=GENAPP.DDCLRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN020QP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN81 DD DISP=SHR,DSN=GENAPP.DDENIN81.DATA
//DDENOT81 DD DISP=SHR,DSN=GENAPP.DDENOT81.DATA
//DDENRP81 DD DISP=SHR,DSN=GENAPP.DDENRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
