//VJOB3156 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW022FH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN19 DD DISP=SHR,DSN=GENAPP.DDUWIN19.DATA
//DDUWOT19 DD DISP=SHR,DSN=GENAPP.DDUWOT19.DATA
//DDUWRP19 DD DISP=SHR,DSN=GENAPP.DDUWRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAU022FI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN20 DD DISP=SHR,DSN=GENAPP.DDAUIN20.DATA
//DDAUOT20 DD DISP=SHR,DSN=GENAPP.DDAUOT20.DATA
//DDAURP20 DD DISP=SHR,DSN=GENAPP.DDAURP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLB022FJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN21 DD DISP=SHR,DSN=GENAPP.DDLBIN21.DATA
//DDLBOT21 DD DISP=SHR,DSN=GENAPP.DDLBOT21.DATA
//DDLBRP21 DD DISP=SHR,DSN=GENAPP.DDLBRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
