//VJOB3950 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSL0249N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN61 DD DISP=SHR,DSN=GENAPP.DDSLIN61.DATA
//DDSLOT61 DD DISP=SHR,DSN=GENAPP.DDSLOT61.DATA
//DDSLRP61 DD DISP=SHR,DSN=GENAPP.DDSLRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBA0249O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN62 DD DISP=SHR,DSN=GENAPP.DDBAIN62.DATA
//DDBAOT62 DD DISP=SHR,DSN=GENAPP.DDBAOT62.DATA
//DDBARP62 DD DISP=SHR,DSN=GENAPP.DDBARP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCR0249P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN63 DD DISP=SHR,DSN=GENAPP.DDCRIN63.DATA
//DDCROT63 DD DISP=SHR,DSN=GENAPP.DDCROT63.DATA
//DDCRRP63 DD DISP=SHR,DSN=GENAPP.DDCRRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
