//VJOB2401 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE020OK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN04 DD DISP=SHR,DSN=GENAPP.DDSEIN04.DATA
//DDSEOT04 DD DISP=SHR,DSN=GENAPP.DDSEOT04.DATA
//DDSERP04 DD DISP=SHR,DSN=GENAPP.DDSERP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT020OL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN05 DD DISP=SHR,DSN=GENAPP.DDLTIN05.DATA
//DDLTOT05 DD DISP=SHR,DSN=GENAPP.DDLTOT05.DATA
//DDLTRP05 DD DISP=SHR,DSN=GENAPP.DDLTRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT020OM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN06 DD DISP=SHR,DSN=GENAPP.DDMTIN06.DATA
//DDMTOT06 DD DISP=SHR,DSN=GENAPP.DDMTOT06.DATA
//DDMTRP06 DD DISP=SHR,DSN=GENAPP.DDMTRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
