//VJOB1804 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE01ZAT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN13 DD DISP=SHR,DSN=GENAPP.DDREIN13.DATA
//DDREOT13 DD DISP=SHR,DSN=GENAPP.DDREOT13.DATA
//DDRERP13 DD DISP=SHR,DSN=GENAPP.DDRERP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSU01ZAU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN14 DD DISP=SHR,DSN=GENAPP.DDSUIN14.DATA
//DDSUOT14 DD DISP=SHR,DSN=GENAPP.DDSUOT14.DATA
//DDSURP14 DD DISP=SHR,DSN=GENAPP.DDSURP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA01ZAV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN15 DD DISP=SHR,DSN=GENAPP.DDPAIN15.DATA
//DDPAOT15 DD DISP=SHR,DSN=GENAPP.DDPAOT15.DATA
//DDPARP15 DD DISP=SHR,DSN=GENAPP.DDPARP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
