//VJOB0552 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG01WEH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN37 DD DISP=SHR,DSN=GENAPP.DDAGIN37.DATA
//DDAGOT37 DD DISP=SHR,DSN=GENAPP.DDAGOT37.DATA
//DDAGRP37 DD DISP=SHR,DSN=GENAPP.DDAGRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR01WEI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN38 DD DISP=SHR,DSN=GENAPP.DDTRIN38.DATA
//DDTROT38 DD DISP=SHR,DSN=GENAPP.DDTROT38.DATA
//DDTRRP38 DD DISP=SHR,DSN=GENAPP.DDTRRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01WEJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN39 DD DISP=SHR,DSN=GENAPP.DDTRIN39.DATA
//DDTROT39 DD DISP=SHR,DSN=GENAPP.DDTROT39.DATA
//DDTRRP39 DD DISP=SHR,DSN=GENAPP.DDTRRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
