//VJOB1397 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01YCW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN52 DD DISP=SHR,DSN=GENAPP.DDBIIN52.DATA
//DDBIOT52 DD DISP=SHR,DSN=GENAPP.DDBIOT52.DATA
//DDBIRP52 DD DISP=SHR,DSN=GENAPP.DDBIRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01YCX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN53 DD DISP=SHR,DSN=GENAPP.DDFLIN53.DATA
//DDFLOT53 DD DISP=SHR,DSN=GENAPP.DDFLOT53.DATA
//DDFLRP53 DD DISP=SHR,DSN=GENAPP.DDFLRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01YCY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN54 DD DISP=SHR,DSN=GENAPP.DDENIN54.DATA
//DDENOT54 DD DISP=SHR,DSN=GENAPP.DDENOT54.DATA
//DDENRP54 DD DISP=SHR,DSN=GENAPP.DDENRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
