//VJOB2254 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO020CB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN13 DD DISP=SHR,DSN=GENAPP.DDHOIN13.DATA
//DDHOOT13 DD DISP=SHR,DSN=GENAPP.DDHOOT13.DATA
//DDHORP13 DD DISP=SHR,DSN=GENAPP.DDHORP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE020CC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN14 DD DISP=SHR,DSN=GENAPP.DDSEIN14.DATA
//DDSEOT14 DD DISP=SHR,DSN=GENAPP.DDSEOT14.DATA
//DDSERP14 DD DISP=SHR,DSN=GENAPP.DDSERP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC020CD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN15 DD DISP=SHR,DSN=GENAPP.DDACIN15.DATA
//DDACOT15 DD DISP=SHR,DSN=GENAPP.DDACOT15.DATA
//DDACRP15 DD DISP=SHR,DSN=GENAPP.DDACRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
