//VJOB4222 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB024WB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN67 DD DISP=SHR,DSN=GENAPP.DDLBIN67.DATA
//DDLBOT67 DD DISP=SHR,DSN=GENAPP.DDLBOT67.DATA
//DDLBRP67 DD DISP=SHR,DSN=GENAPP.DDLBRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU024WC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN68 DD DISP=SHR,DSN=GENAPP.DDCUIN68.DATA
//DDCUOT68 DD DISP=SHR,DSN=GENAPP.DDCUOT68.DATA
//DDCURP68 DD DISP=SHR,DSN=GENAPP.DDCURP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW024WD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN69 DD DISP=SHR,DSN=GENAPP.DDUWIN69.DATA
//DDUWOT69 DD DISP=SHR,DSN=GENAPP.DDUWOT69.DATA
//DDUWRP69 DD DISP=SHR,DSN=GENAPP.DDUWRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
