//VJOB4281 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE02518
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN64 DD DISP=SHR,DSN=GENAPP.DDREIN64.DATA
//DDREOT64 DD DISP=SHR,DSN=GENAPP.DDREOT64.DATA
//DDRERP64 DD DISP=SHR,DSN=GENAPP.DDRERP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV02519
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN65 DD DISP=SHR,DSN=GENAPP.DDAVIN65.DATA
//DDAVOT65 DD DISP=SHR,DSN=GENAPP.DDAVOT65.DATA
//DDAVRP65 DD DISP=SHR,DSN=GENAPP.DDAVRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSE0251A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN66 DD DISP=SHR,DSN=GENAPP.DDSEIN66.DATA
//DDSEOT66 DD DISP=SHR,DSN=GENAPP.DDSEOT66.DATA
//DDSERP66 DD DISP=SHR,DSN=GENAPP.DDSERP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
