//VJOB1339 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN01Y82
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN58 DD DISP=SHR,DSN=GENAPP.DDANIN58.DATA
//DDANOT58 DD DISP=SHR,DSN=GENAPP.DDANOT58.DATA
//DDANRP58 DD DISP=SHR,DSN=GENAPP.DDANRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG01Y83
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN59 DD DISP=SHR,DSN=GENAPP.DDRGIN59.DATA
//DDRGOT59 DD DISP=SHR,DSN=GENAPP.DDRGOT59.DATA
//DDRGRP59 DD DISP=SHR,DSN=GENAPP.DDRGRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV01Y84
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN60 DD DISP=SHR,DSN=GENAPP.DDAVIN60.DATA
//DDAVOT60 DD DISP=SHR,DSN=GENAPP.DDAVOT60.DATA
//DDAVRP60 DD DISP=SHR,DSN=GENAPP.DDAVRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
