//VJOB2483 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS020VE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN70 DD DISP=SHR,DSN=GENAPP.DDRSIN70.DATA
//DDRSOT70 DD DISP=SHR,DSN=GENAPP.DDRSOT70.DATA
//DDRSRP70 DD DISP=SHR,DSN=GENAPP.DDRSRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG020VF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN71 DD DISP=SHR,DSN=GENAPP.DDAGIN71.DATA
//DDAGOT71 DD DISP=SHR,DSN=GENAPP.DDAGOT71.DATA
//DDAGRP71 DD DISP=SHR,DSN=GENAPP.DDAGRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO020VG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN72 DD DISP=SHR,DSN=GENAPP.DDHOIN72.DATA
//DDHOOT72 DD DISP=SHR,DSN=GENAPP.DDHOOT72.DATA
//DDHORP72 DD DISP=SHR,DSN=GENAPP.DDHORP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
