//VJOB2354 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX020KN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN43 DD DISP=SHR,DSN=GENAPP.DDTXIN43.DATA
//DDTXOT43 DD DISP=SHR,DSN=GENAPP.DDTXOT43.DATA
//DDTXRP43 DD DISP=SHR,DSN=GENAPP.DDTXRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR020KO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN44 DD DISP=SHR,DSN=GENAPP.DDTRIN44.DATA
//DDTROT44 DD DISP=SHR,DSN=GENAPP.DDTROT44.DATA
//DDTRRP44 DD DISP=SHR,DSN=GENAPP.DDTRRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBA020KP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN45 DD DISP=SHR,DSN=GENAPP.DDBAIN45.DATA
//DDBAOT45 DD DISP=SHR,DSN=GENAPP.DDBAOT45.DATA
//DDBARP45 DD DISP=SHR,DSN=GENAPP.DDBARP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
