//VJOB2742 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO021GZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN37 DD DISP=SHR,DSN=GENAPP.DDHOIN37.DATA
//DDHOOT37 DD DISP=SHR,DSN=GENAPP.DDHOOT37.DATA
//DDHORP37 DD DISP=SHR,DSN=GENAPP.DDHORP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZWF021H0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN38 DD DISP=SHR,DSN=GENAPP.DDWFIN38.DATA
//DDWFOT38 DD DISP=SHR,DSN=GENAPP.DDWFOT38.DATA
//DDWFRP38 DD DISP=SHR,DSN=GENAPP.DDWFRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEX021H1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN39 DD DISP=SHR,DSN=GENAPP.DDEXIN39.DATA
//DDEXOT39 DD DISP=SHR,DSN=GENAPP.DDEXOT39.DATA
//DDEXRP39 DD DISP=SHR,DSN=GENAPP.DDEXRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
