//VJOB1482 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01YJZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN37 DD DISP=SHR,DSN=GENAPP.DDMTIN37.DATA
//DDMTOT37 DD DISP=SHR,DSN=GENAPP.DDMTOT37.DATA
//DDMTRP37 DD DISP=SHR,DSN=GENAPP.DDMTRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO01YK0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN38 DD DISP=SHR,DSN=GENAPP.DDCOIN38.DATA
//DDCOOT38 DD DISP=SHR,DSN=GENAPP.DDCOOT38.DATA
//DDCORP38 DD DISP=SHR,DSN=GENAPP.DDCORP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCN01YK1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN39 DD DISP=SHR,DSN=GENAPP.DDCNIN39.DATA
//DDCNOT39 DD DISP=SHR,DSN=GENAPP.DDCNOT39.DATA
//DDCNRP39 DD DISP=SHR,DSN=GENAPP.DDCNRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
