//VJOB0530 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV01WCN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN61 DD DISP=SHR,DSN=GENAPP.DDIVIN61.DATA
//DDIVOT61 DD DISP=SHR,DSN=GENAPP.DDIVOT61.DATA
//DDIVRP61 DD DISP=SHR,DSN=GENAPP.DDIVRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01WCO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN62 DD DISP=SHR,DSN=GENAPP.DDHOIN62.DATA
//DDHOOT62 DD DISP=SHR,DSN=GENAPP.DDHOOT62.DATA
//DDHORP62 DD DISP=SHR,DSN=GENAPP.DDHORP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG01WCP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN63 DD DISP=SHR,DSN=GENAPP.DDRGIN63.DATA
//DDRGOT63 DD DISP=SHR,DSN=GENAPP.DDRGOT63.DATA
//DDRGRP63 DD DISP=SHR,DSN=GENAPP.DDRGRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
