//VJOB1650 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL01YXZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN01 DD DISP=SHR,DSN=GENAPP.DDFLIN01.DATA
//DDFLOT01 DD DISP=SHR,DSN=GENAPP.DDFLOT01.DATA
//DDFLRP01 DD DISP=SHR,DSN=GENAPP.DDFLRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01YY0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN02 DD DISP=SHR,DSN=GENAPP.DDMTIN02.DATA
//DDMTOT02 DD DISP=SHR,DSN=GENAPP.DDMTOT02.DATA
//DDMTRP02 DD DISP=SHR,DSN=GENAPP.DDMTRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01YY1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN03 DD DISP=SHR,DSN=GENAPP.DDPEIN03.DATA
//DDPEOT03 DD DISP=SHR,DSN=GENAPP.DDPEOT03.DATA
//DDPERP03 DD DISP=SHR,DSN=GENAPP.DDPERP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
