//VJOB0931 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01XA2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN04 DD DISP=SHR,DSN=GENAPP.DDCUIN04.DATA
//DDCUOT04 DD DISP=SHR,DSN=GENAPP.DDCUOT04.DATA
//DDCURP04 DD DISP=SHR,DSN=GENAPP.DDCURP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01XA3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN05 DD DISP=SHR,DSN=GENAPP.DDCUIN05.DATA
//DDCUOT05 DD DISP=SHR,DSN=GENAPP.DDCUOT05.DATA
//DDCURP05 DD DISP=SHR,DSN=GENAPP.DDCURP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR01XA4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN06 DD DISP=SHR,DSN=GENAPP.DDBRIN06.DATA
//DDBROT06 DD DISP=SHR,DSN=GENAPP.DDBROT06.DATA
//DDBRRP06 DD DISP=SHR,DSN=GENAPP.DDBRRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
