//VJOB1975 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01ZP2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN76 DD DISP=SHR,DSN=GENAPP.DDENIN76.DATA
//DDENOT76 DD DISP=SHR,DSN=GENAPP.DDENOT76.DATA
//DDENRP76 DD DISP=SHR,DSN=GENAPP.DDENRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01ZP3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN77 DD DISP=SHR,DSN=GENAPP.DDMTIN77.DATA
//DDMTOT77 DD DISP=SHR,DSN=GENAPP.DDMTOT77.DATA
//DDMTRP77 DD DISP=SHR,DSN=GENAPP.DDMTRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAZ01ZP4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN78 DD DISP=SHR,DSN=GENAPP.DDAZIN78.DATA
//DDAZOT78 DD DISP=SHR,DSN=GENAPP.DDAZOT78.DATA
//DDAZRP78 DD DISP=SHR,DSN=GENAPP.DDAZRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
