//VJOB0154 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC01VHB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN13 DD DISP=SHR,DSN=GENAPP.DDRCIN13.DATA
//DDRCOT13 DD DISP=SHR,DSN=GENAPP.DDRCOT13.DATA
//DDRCRP13 DD DISP=SHR,DSN=GENAPP.DDRCRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN01VHC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN14 DD DISP=SHR,DSN=GENAPP.DDANIN14.DATA
//DDANOT14 DD DISP=SHR,DSN=GENAPP.DDANOT14.DATA
//DDANRP14 DD DISP=SHR,DSN=GENAPP.DDANRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRG01VHD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN15 DD DISP=SHR,DSN=GENAPP.DDRGIN15.DATA
//DDRGOT15 DD DISP=SHR,DSN=GENAPP.DDRGOT15.DATA
//DDRGRP15 DD DISP=SHR,DSN=GENAPP.DDRGRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
