//VJOB4206 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO024UZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN19 DD DISP=SHR,DSN=GENAPP.DDHOIN19.DATA
//DDHOOT19 DD DISP=SHR,DSN=GENAPP.DDHOOT19.DATA
//DDHORP19 DD DISP=SHR,DSN=GENAPP.DDHORP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPT024V0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN20 DD DISP=SHR,DSN=GENAPP.DDPTIN20.DATA
//DDPTOT20 DD DISP=SHR,DSN=GENAPP.DDPTOT20.DATA
//DDPTRP20 DD DISP=SHR,DSN=GENAPP.DDPTRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC024V1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN21 DD DISP=SHR,DSN=GENAPP.DDACIN21.DATA
//DDACOT21 DD DISP=SHR,DSN=GENAPP.DDACOT21.DATA
//DDACRP21 DD DISP=SHR,DSN=GENAPP.DDACRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
