//VJOB2134 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU0202B
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN13 DD DISP=SHR,DSN=GENAPP.DDCUIN13.DATA
//DDCUOT13 DD DISP=SHR,DSN=GENAPP.DDCUOT13.DATA
//DDCURP13 DD DISP=SHR,DSN=GENAPP.DDCURP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG0202C
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN14 DD DISP=SHR,DSN=GENAPP.DDAGIN14.DATA
//DDAGOT14 DD DISP=SHR,DSN=GENAPP.DDAGOT14.DATA
//DDAGRP14 DD DISP=SHR,DSN=GENAPP.DDAGRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT0202D
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN15 DD DISP=SHR,DSN=GENAPP.DDMTIN15.DATA
//DDMTOT15 DD DISP=SHR,DSN=GENAPP.DDMTOT15.DATA
//DDMTRP15 DD DISP=SHR,DSN=GENAPP.DDMTRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
