//VJOB0413 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01W2W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN70 DD DISP=SHR,DSN=GENAPP.DDENIN70.DATA
//DDENOT70 DD DISP=SHR,DSN=GENAPP.DDENOT70.DATA
//DDENRP70 DD DISP=SHR,DSN=GENAPP.DDENRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01W2X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN71 DD DISP=SHR,DSN=GENAPP.DDCUIN71.DATA
//DDCUOT71 DD DISP=SHR,DSN=GENAPP.DDCUOT71.DATA
//DDCURP71 DD DISP=SHR,DSN=GENAPP.DDCURP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCP01W2Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN72 DD DISP=SHR,DSN=GENAPP.DDCPIN72.DATA
//DDCPOT72 DD DISP=SHR,DSN=GENAPP.DDCPOT72.DATA
//DDCPRP72 DD DISP=SHR,DSN=GENAPP.DDCPRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
