//VJOB2296 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA020FT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN49 DD DISP=SHR,DSN=GENAPP.DDPAIN49.DATA
//DDPAOT49 DD DISP=SHR,DSN=GENAPP.DDPAOT49.DATA
//DDPARP49 DD DISP=SHR,DSN=GENAPP.DDPARP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR020FU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN50 DD DISP=SHR,DSN=GENAPP.DDPRIN50.DATA
//DDPROT50 DD DISP=SHR,DSN=GENAPP.DDPROT50.DATA
//DDPRRP50 DD DISP=SHR,DSN=GENAPP.DDPRRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAU020FV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN51 DD DISP=SHR,DSN=GENAPP.DDAUIN51.DATA
//DDAUOT51 DD DISP=SHR,DSN=GENAPP.DDAUOT51.DATA
//DDAURP51 DD DISP=SHR,DSN=GENAPP.DDAURP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
