//VJOB0973 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01XDK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN40 DD DISP=SHR,DSN=GENAPP.DDMTIN40.DATA
//DDMTOT40 DD DISP=SHR,DSN=GENAPP.DDMTOT40.DATA
//DDMTRP40 DD DISP=SHR,DSN=GENAPP.DDMTRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW01XDL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN41 DD DISP=SHR,DSN=GENAPP.DDUWIN41.DATA
//DDUWOT41 DD DISP=SHR,DSN=GENAPP.DDUWOT41.DATA
//DDUWRP41 DD DISP=SHR,DSN=GENAPP.DDUWRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPL01XDM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN42 DD DISP=SHR,DSN=GENAPP.DDPLIN42.DATA
//DDPLOT42 DD DISP=SHR,DSN=GENAPP.DDPLOT42.DATA
//DDPLRP42 DD DISP=SHR,DSN=GENAPP.DDPLRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
