//VJOB0477 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRN01W88
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN82 DD DISP=SHR,DSN=GENAPP.DDRNIN82.DATA
//DDRNOT82 DD DISP=SHR,DSN=GENAPP.DDRNOT82.DATA
//DDRNRP82 DD DISP=SHR,DSN=GENAPP.DDRNRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01W89
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN83 DD DISP=SHR,DSN=GENAPP.DDCLIN83.DATA
//DDCLOT83 DD DISP=SHR,DSN=GENAPP.DDCLOT83.DATA
//DDCLRP83 DD DISP=SHR,DSN=GENAPP.DDCLRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01W8A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN84 DD DISP=SHR,DSN=GENAPP.DDCUIN84.DATA
//DDCUOT84 DD DISP=SHR,DSN=GENAPP.DDCUOT84.DATA
//DDCURP84 DD DISP=SHR,DSN=GENAPP.DDCURP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
