//VJOB1578 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC01YRZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN55 DD DISP=SHR,DSN=GENAPP.DDACIN55.DATA
//DDACOT55 DD DISP=SHR,DSN=GENAPP.DDACOT55.DATA
//DDACRP55 DD DISP=SHR,DSN=GENAPP.DDACRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01YS0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN56 DD DISP=SHR,DSN=GENAPP.DDHOIN56.DATA
//DDHOOT56 DD DISP=SHR,DSN=GENAPP.DDHOOT56.DATA
//DDHORP56 DD DISP=SHR,DSN=GENAPP.DDHORP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZED01YS1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN57 DD DISP=SHR,DSN=GENAPP.DDEDIN57.DATA
//DDEDOT57 DD DISP=SHR,DSN=GENAPP.DDEDOT57.DATA
//DDEDRP57 DD DISP=SHR,DSN=GENAPP.DDEDRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
