//VJOB0126 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF01VEZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN19 DD DISP=SHR,DSN=GENAPP.DDWFIN19.DATA
//DDWFOT19 DD DISP=SHR,DSN=GENAPP.DDWFOT19.DATA
//DDWFRP19 DD DISP=SHR,DSN=GENAPP.DDWFRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01VF0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN20 DD DISP=SHR,DSN=GENAPP.DDCUIN20.DATA
//DDCUOT20 DD DISP=SHR,DSN=GENAPP.DDCUOT20.DATA
//DDCURP20 DD DISP=SHR,DSN=GENAPP.DDCURP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG01VF1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN21 DD DISP=SHR,DSN=GENAPP.DDAGIN21.DATA
//DDAGOT21 DD DISP=SHR,DSN=GENAPP.DDAGOT21.DATA
//DDAGRP21 DD DISP=SHR,DSN=GENAPP.DDAGRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
