//VJOB2858 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLT021QN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN25 DD DISP=SHR,DSN=GENAPP.DDLTIN25.DATA
//DDLTOT25 DD DISP=SHR,DSN=GENAPP.DDLTOT25.DATA
//DDLTRP25 DD DISP=SHR,DSN=GENAPP.DDLTRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV021QO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN26 DD DISP=SHR,DSN=GENAPP.DDAVIN26.DATA
//DDAVOT26 DD DISP=SHR,DSN=GENAPP.DDAVOT26.DATA
//DDAVRP26 DD DISP=SHR,DSN=GENAPP.DDAVRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI021QP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN27 DD DISP=SHR,DSN=GENAPP.DDLIIN27.DATA
//DDLIOT27 DD DISP=SHR,DSN=GENAPP.DDLIOT27.DATA
//DDLIRP27 DD DISP=SHR,DSN=GENAPP.DDLIRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
