//VJOB3368 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT022X5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN25 DD DISP=SHR,DSN=GENAPP.DDMTIN25.DATA
//DDMTOT25 DD DISP=SHR,DSN=GENAPP.DDMTOT25.DATA
//DDMTRP25 DD DISP=SHR,DSN=GENAPP.DDMTRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMB022X6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN26 DD DISP=SHR,DSN=GENAPP.DDMBIN26.DATA
//DDMBOT26 DD DISP=SHR,DSN=GENAPP.DDMBOT26.DATA
//DDMBRP26 DD DISP=SHR,DSN=GENAPP.DDMBRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO022X7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN27 DD DISP=SHR,DSN=GENAPP.DDHOIN27.DATA
//DDHOOT27 DD DISP=SHR,DSN=GENAPP.DDHOOT27.DATA
//DDHORP27 DD DISP=SHR,DSN=GENAPP.DDHORP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
