//VJOB3633 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO023J8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN10 DD DISP=SHR,DSN=GENAPP.DDHOIN10.DATA
//DDHOOT10 DD DISP=SHR,DSN=GENAPP.DDHOOT10.DATA
//DDHORP10 DD DISP=SHR,DSN=GENAPP.DDHORP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAC023J9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN11 DD DISP=SHR,DSN=GENAPP.DDACIN11.DATA
//DDACOT11 DD DISP=SHR,DSN=GENAPP.DDACOT11.DATA
//DDACRP11 DD DISP=SHR,DSN=GENAPP.DDACRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW023JA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN12 DD DISP=SHR,DSN=GENAPP.DDUWIN12.DATA
//DDUWOT12 DD DISP=SHR,DSN=GENAPP.DDUWOT12.DATA
//DDUWRP12 DD DISP=SHR,DSN=GENAPP.DDUWRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
