//VJOB1157 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC01XSW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN52 DD DISP=SHR,DSN=GENAPP.DDACIN52.DATA
//DDACOT52 DD DISP=SHR,DSN=GENAPP.DDACOT52.DATA
//DDACRP52 DD DISP=SHR,DSN=GENAPP.DDACRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE01XSX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN53 DD DISP=SHR,DSN=GENAPP.DDHEIN53.DATA
//DDHEOT53 DD DISP=SHR,DSN=GENAPP.DDHEOT53.DATA
//DDHERP53 DD DISP=SHR,DSN=GENAPP.DDHERP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA01XSY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN54 DD DISP=SHR,DSN=GENAPP.DDPAIN54.DATA
//DDPAOT54 DD DISP=SHR,DSN=GENAPP.DDPAOT54.DATA
//DDPARP54 DD DISP=SHR,DSN=GENAPP.DDPARP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
