//VJOB0381 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG01W08
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN64 DD DISP=SHR,DSN=GENAPP.DDRGIN64.DATA
//DDRGOT64 DD DISP=SHR,DSN=GENAPP.DDRGOT64.DATA
//DDRGRP64 DD DISP=SHR,DSN=GENAPP.DDRGRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR01W09
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN65 DD DISP=SHR,DSN=GENAPP.DDBRIN65.DATA
//DDBROT65 DD DISP=SHR,DSN=GENAPP.DDBROT65.DATA
//DDBRRP65 DD DISP=SHR,DSN=GENAPP.DDBRRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF01W0A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN66 DD DISP=SHR,DSN=GENAPP.DDIFIN66.DATA
//DDIFOT66 DD DISP=SHR,DSN=GENAPP.DDIFOT66.DATA
//DDIFRP66 DD DISP=SHR,DSN=GENAPP.DDIFRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
