//VJOB1136 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW01XR5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN79 DD DISP=SHR,DSN=GENAPP.DDUWIN79.DATA
//DDUWOT79 DD DISP=SHR,DSN=GENAPP.DDUWOT79.DATA
//DDUWRP79 DD DISP=SHR,DSN=GENAPP.DDUWRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV01XR6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN80 DD DISP=SHR,DSN=GENAPP.DDAVIN80.DATA
//DDAVOT80 DD DISP=SHR,DSN=GENAPP.DDAVOT80.DATA
//DDAVRP80 DD DISP=SHR,DSN=GENAPP.DDAVRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01XR7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN81 DD DISP=SHR,DSN=GENAPP.DDMAIN81.DATA
//DDMAOT81 DD DISP=SHR,DSN=GENAPP.DDMAOT81.DATA
//DDMARP81 DD DISP=SHR,DSN=GENAPP.DDMARP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
