//VJOB2232 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSC020AH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN37 DD DISP=SHR,DSN=GENAPP.DDSCIN37.DATA
//DDSCOT37 DD DISP=SHR,DSN=GENAPP.DDSCOT37.DATA
//DDSCRP37 DD DISP=SHR,DSN=GENAPP.DDSCRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU020AI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN38 DD DISP=SHR,DSN=GENAPP.DDCUIN38.DATA
//DDCUOT38 DD DISP=SHR,DSN=GENAPP.DDCUOT38.DATA
//DDCURP38 DD DISP=SHR,DSN=GENAPP.DDCURP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN020AJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN39 DD DISP=SHR,DSN=GENAPP.DDENIN39.DATA
//DDENOT39 DD DISP=SHR,DSN=GENAPP.DDENOT39.DATA
//DDENRP39 DD DISP=SHR,DSN=GENAPP.DDENRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
