//VJOB0517 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSL01WBK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN22 DD DISP=SHR,DSN=GENAPP.DDSLIN22.DATA
//DDSLOT22 DD DISP=SHR,DSN=GENAPP.DDSLOT22.DATA
//DDSLRP22 DD DISP=SHR,DSN=GENAPP.DDSLRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA01WBL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN23 DD DISP=SHR,DSN=GENAPP.DDMAIN23.DATA
//DDMAOT23 DD DISP=SHR,DSN=GENAPP.DDMAOT23.DATA
//DDMARP23 DD DISP=SHR,DSN=GENAPP.DDMARP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC01WBM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN24 DD DISP=SHR,DSN=GENAPP.DDACIN24.DATA
//DDACOT24 DD DISP=SHR,DSN=GENAPP.DDACOT24.DATA
//DDACRP24 DD DISP=SHR,DSN=GENAPP.DDACRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
