//VJOB2508 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR020XH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN55 DD DISP=SHR,DSN=GENAPP.DDTRIN55.DATA
//DDTROT55 DD DISP=SHR,DSN=GENAPP.DDTROT55.DATA
//DDTRRP55 DD DISP=SHR,DSN=GENAPP.DDTRRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE020XI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN56 DD DISP=SHR,DSN=GENAPP.DDSEIN56.DATA
//DDSEOT56 DD DISP=SHR,DSN=GENAPP.DDSEOT56.DATA
//DDSERP56 DD DISP=SHR,DSN=GENAPP.DDSERP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV020XJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN57 DD DISP=SHR,DSN=GENAPP.DDAVIN57.DATA
//DDAVOT57 DD DISP=SHR,DSN=GENAPP.DDAVOT57.DATA
//DDAVRP57 DD DISP=SHR,DSN=GENAPP.DDAVRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
