//VJOB0818 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR01X0N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN25 DD DISP=SHR,DSN=GENAPP.DDFRIN25.DATA
//DDFROT25 DD DISP=SHR,DSN=GENAPP.DDFROT25.DATA
//DDFRRP25 DD DISP=SHR,DSN=GENAPP.DDFRRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01X0O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN26 DD DISP=SHR,DSN=GENAPP.DDLIIN26.DATA
//DDLIOT26 DD DISP=SHR,DSN=GENAPP.DDLIOT26.DATA
//DDLIRP26 DD DISP=SHR,DSN=GENAPP.DDLIRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01X0P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN27 DD DISP=SHR,DSN=GENAPP.DDCLIN27.DATA
//DDCLOT27 DD DISP=SHR,DSN=GENAPP.DDCLOT27.DATA
//DDCLRP27 DD DISP=SHR,DSN=GENAPP.DDCLRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
