//VJOB2804 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA021M5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN43 DD DISP=SHR,DSN=GENAPP.DDPAIN43.DATA
//DDPAOT43 DD DISP=SHR,DSN=GENAPP.DDPAOT43.DATA
//DDPARP43 DD DISP=SHR,DSN=GENAPP.DDPARP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSL021M6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN44 DD DISP=SHR,DSN=GENAPP.DDSLIN44.DATA
//DDSLOT44 DD DISP=SHR,DSN=GENAPP.DDSLOT44.DATA
//DDSLRP44 DD DISP=SHR,DSN=GENAPP.DDSLRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO021M7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN45 DD DISP=SHR,DSN=GENAPP.DDHOIN45.DATA
//DDHOOT45 DD DISP=SHR,DSN=GENAPP.DDHOOT45.DATA
//DDHORP45 DD DISP=SHR,DSN=GENAPP.DDHORP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
