//VJOB4009 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE024EK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN58 DD DISP=SHR,DSN=GENAPP.DDSEIN58.DATA
//DDSEOT58 DD DISP=SHR,DSN=GENAPP.DDSEOT58.DATA
//DDSERP58 DD DISP=SHR,DSN=GENAPP.DDSERP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI024EL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN59 DD DISP=SHR,DSN=GENAPP.DDBIIN59.DATA
//DDBIOT59 DD DISP=SHR,DSN=GENAPP.DDBIOT59.DATA
//DDBIRP59 DD DISP=SHR,DSN=GENAPP.DDBIRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU024EM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN60 DD DISP=SHR,DSN=GENAPP.DDCUIN60.DATA
//DDCUOT60 DD DISP=SHR,DSN=GENAPP.DDCUOT60.DATA
//DDCURP60 DD DISP=SHR,DSN=GENAPP.DDCURP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
