//VJOB0897 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZGW01X78
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN82 DD DISP=SHR,DSN=GENAPP.DDGWIN82.DATA
//DDGWOT82 DD DISP=SHR,DSN=GENAPP.DDGWOT82.DATA
//DDGWRP82 DD DISP=SHR,DSN=GENAPP.DDGWRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01X79
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN83 DD DISP=SHR,DSN=GENAPP.DDCUIN83.DATA
//DDCUOT83 DD DISP=SHR,DSN=GENAPP.DDCUOT83.DATA
//DDCURP83 DD DISP=SHR,DSN=GENAPP.DDCURP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA01X7A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN84 DD DISP=SHR,DSN=GENAPP.DDPAIN84.DATA
//DDPAOT84 DD DISP=SHR,DSN=GENAPP.DDPAOT84.DATA
//DDPARP84 DD DISP=SHR,DSN=GENAPP.DDPARP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
