//VJOB4261 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRC024ZK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN04 DD DISP=SHR,DSN=GENAPP.DDRCIN04.DATA
//DDRCOT04 DD DISP=SHR,DSN=GENAPP.DDRCOT04.DATA
//DDRCRP04 DD DISP=SHR,DSN=GENAPP.DDRCRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN024ZL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN05 DD DISP=SHR,DSN=GENAPP.DDENIN05.DATA
//DDENOT05 DD DISP=SHR,DSN=GENAPP.DDENOT05.DATA
//DDENRP05 DD DISP=SHR,DSN=GENAPP.DDENRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL024ZM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN06 DD DISP=SHR,DSN=GENAPP.DDCLIN06.DATA
//DDCLOT06 DD DISP=SHR,DSN=GENAPP.DDCLOT06.DATA
//DDCLRP06 DD DISP=SHR,DSN=GENAPP.DDCLRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
