//VJOB1652 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN01YY5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN07 DD DISP=SHR,DSN=GENAPP.DDANIN07.DATA
//DDANOT07 DD DISP=SHR,DSN=GENAPP.DDANOT07.DATA
//DDANRP07 DD DISP=SHR,DSN=GENAPP.DDANRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01YY6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN08 DD DISP=SHR,DSN=GENAPP.DDCLIN08.DATA
//DDCLOT08 DD DISP=SHR,DSN=GENAPP.DDCLOT08.DATA
//DDCLRP08 DD DISP=SHR,DSN=GENAPP.DDCLRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01YY7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN09 DD DISP=SHR,DSN=GENAPP.DDPEIN09.DATA
//DDPEOT09 DD DISP=SHR,DSN=GENAPP.DDPEOT09.DATA
//DDPERP09 DD DISP=SHR,DSN=GENAPP.DDPERP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
