//VJOB3721 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDI023QK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN04 DD DISP=SHR,DSN=GENAPP.DDDIIN04.DATA
//DDDIOT04 DD DISP=SHR,DSN=GENAPP.DDDIOT04.DATA
//DDDIRP04 DD DISP=SHR,DSN=GENAPP.DDDIRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR023QL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN05 DD DISP=SHR,DSN=GENAPP.DDCRIN05.DATA
//DDCROT05 DD DISP=SHR,DSN=GENAPP.DDCROT05.DATA
//DDCRRP05 DD DISP=SHR,DSN=GENAPP.DDCRRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO023QM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN06 DD DISP=SHR,DSN=GENAPP.DDCOIN06.DATA
//DDCOOT06 DD DISP=SHR,DSN=GENAPP.DDCOOT06.DATA
//DDCORP06 DD DISP=SHR,DSN=GENAPP.DDCORP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
