//VJOB2292 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL020FH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN37 DD DISP=SHR,DSN=GENAPP.DDCLIN37.DATA
//DDCLOT37 DD DISP=SHR,DSN=GENAPP.DDCLOT37.DATA
//DDCLRP37 DD DISP=SHR,DSN=GENAPP.DDCLRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG020FI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN38 DD DISP=SHR,DSN=GENAPP.DDAGIN38.DATA
//DDAGOT38 DD DISP=SHR,DSN=GENAPP.DDAGOT38.DATA
//DDAGRP38 DD DISP=SHR,DSN=GENAPP.DDAGRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE020FJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN39 DD DISP=SHR,DSN=GENAPP.DDPEIN39.DATA
//DDPEOT39 DD DISP=SHR,DSN=GENAPP.DDPEOT39.DATA
//DDPERP39 DD DISP=SHR,DSN=GENAPP.DDPERP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
