//VJOB0680 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV01WP5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN61 DD DISP=SHR,DSN=GENAPP.DDIVIN61.DATA
//DDIVOT61 DD DISP=SHR,DSN=GENAPP.DDIVOT61.DATA
//DDIVRP61 DD DISP=SHR,DSN=GENAPP.DDIVRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01WP6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN62 DD DISP=SHR,DSN=GENAPP.DDMTIN62.DATA
//DDMTOT62 DD DISP=SHR,DSN=GENAPP.DDMTOT62.DATA
//DDMTRP62 DD DISP=SHR,DSN=GENAPP.DDMTRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG01WP7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN63 DD DISP=SHR,DSN=GENAPP.DDAGIN63.DATA
//DDAGOT63 DD DISP=SHR,DSN=GENAPP.DDAGOT63.DATA
//DDAGRP63 DD DISP=SHR,DSN=GENAPP.DDAGRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
