//VJOB1689 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAZ01Z18
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN28 DD DISP=SHR,DSN=GENAPP.DDAZIN28.DATA
//DDAZOT28 DD DISP=SHR,DSN=GENAPP.DDAZOT28.DATA
//DDAZRP28 DD DISP=SHR,DSN=GENAPP.DDAZRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR01Z19
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN29 DD DISP=SHR,DSN=GENAPP.DDPRIN29.DATA
//DDPROT29 DD DISP=SHR,DSN=GENAPP.DDPROT29.DATA
//DDPRRP29 DD DISP=SHR,DSN=GENAPP.DDPRRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01Z1A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN30 DD DISP=SHR,DSN=GENAPP.DDCUIN30.DATA
//DDCUOT30 DD DISP=SHR,DSN=GENAPP.DDCUOT30.DATA
//DDCURP30 DD DISP=SHR,DSN=GENAPP.DDCURP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
