//VJOB2814 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE021MZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN73 DD DISP=SHR,DSN=GENAPP.DDSEIN73.DATA
//DDSEOT73 DD DISP=SHR,DSN=GENAPP.DDSEOT73.DATA
//DDSERP73 DD DISP=SHR,DSN=GENAPP.DDSERP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ021N0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN74 DD DISP=SHR,DSN=GENAPP.DDAZIN74.DATA
//DDAZOT74 DD DISP=SHR,DSN=GENAPP.DDAZOT74.DATA
//DDAZRP74 DD DISP=SHR,DSN=GENAPP.DDAZRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT021N1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN75 DD DISP=SHR,DSN=GENAPP.DDMTIN75.DATA
//DDMTOT75 DD DISP=SHR,DSN=GENAPP.DDMTOT75.DATA
//DDMTRP75 DD DISP=SHR,DSN=GENAPP.DDMTRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
