//VJOB0231 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCN01VNQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN64 DD DISP=SHR,DSN=GENAPP.DDCNIN64.DATA
//DDCNOT64 DD DISP=SHR,DSN=GENAPP.DDCNOT64.DATA
//DDCNRP64 DD DISP=SHR,DSN=GENAPP.DDCNRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01VNR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN65 DD DISP=SHR,DSN=GENAPP.DDCUIN65.DATA
//DDCUOT65 DD DISP=SHR,DSN=GENAPP.DDCUOT65.DATA
//DDCURP65 DD DISP=SHR,DSN=GENAPP.DDCURP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCP01VNS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN66 DD DISP=SHR,DSN=GENAPP.DDCPIN66.DATA
//DDCPOT66 DD DISP=SHR,DSN=GENAPP.DDCPOT66.DATA
//DDCPRP66 DD DISP=SHR,DSN=GENAPP.DDCPRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
