//VJOB2572 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI0212T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN67 DD DISP=SHR,DSN=GENAPP.DDLIIN67.DATA
//DDLIOT67 DD DISP=SHR,DSN=GENAPP.DDLIOT67.DATA
//DDLIRP67 DD DISP=SHR,DSN=GENAPP.DDLIRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN0212U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN68 DD DISP=SHR,DSN=GENAPP.DDRNIN68.DATA
//DDRNOT68 DD DISP=SHR,DSN=GENAPP.DDRNOT68.DATA
//DDRNRP68 DD DISP=SHR,DSN=GENAPP.DDRNRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR0212V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN69 DD DISP=SHR,DSN=GENAPP.DDARIN69.DATA
//DDAROT69 DD DISP=SHR,DSN=GENAPP.DDAROT69.DATA
//DDARRP69 DD DISP=SHR,DSN=GENAPP.DDARRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
