//VJOB0026 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01V6N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN79 DD DISP=SHR,DSN=GENAPP.DDCLIN79.DATA
//DDCLOT79 DD DISP=SHR,DSN=GENAPP.DDCLOT79.DATA
//DDCLRP79 DD DISP=SHR,DSN=GENAPP.DDCLRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR01V6O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN80 DD DISP=SHR,DSN=GENAPP.DDBRIN80.DATA
//DDBROT80 DD DISP=SHR,DSN=GENAPP.DDBROT80.DATA
//DDBRRP80 DD DISP=SHR,DSN=GENAPP.DDBRRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG01V6P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN81 DD DISP=SHR,DSN=GENAPP.DDAGIN81.DATA
//DDAGOT81 DD DISP=SHR,DSN=GENAPP.DDAGOT81.DATA
//DDAGRP81 DD DISP=SHR,DSN=GENAPP.DDAGRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
