//VJOB3182 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI022HN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN07 DD DISP=SHR,DSN=GENAPP.DDBIIN07.DATA
//DDBIOT07 DD DISP=SHR,DSN=GENAPP.DDBIOT07.DATA
//DDBIRP07 DD DISP=SHR,DSN=GENAPP.DDBIRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ022HO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN08 DD DISP=SHR,DSN=GENAPP.DDAZIN08.DATA
//DDAZOT08 DD DISP=SHR,DSN=GENAPP.DDAZOT08.DATA
//DDAZRP08 DD DISP=SHR,DSN=GENAPP.DDAZRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRC022HP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN09 DD DISP=SHR,DSN=GENAPP.DDRCIN09.DATA
//DDRCOT09 DD DISP=SHR,DSN=GENAPP.DDRCOT09.DATA
//DDRCRP09 DD DISP=SHR,DSN=GENAPP.DDRCRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
