//VJOB0807 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01WZQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN82 DD DISP=SHR,DSN=GENAPP.DDBIIN82.DATA
//DDBIOT82 DD DISP=SHR,DSN=GENAPP.DDBIOT82.DATA
//DDBIRP82 DD DISP=SHR,DSN=GENAPP.DDBIRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI01WZR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN83 DD DISP=SHR,DSN=GENAPP.DDLIIN83.DATA
//DDLIOT83 DD DISP=SHR,DSN=GENAPP.DDLIOT83.DATA
//DDLIRP83 DD DISP=SHR,DSN=GENAPP.DDLIRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01WZS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN84 DD DISP=SHR,DSN=GENAPP.DDPRIN84.DATA
//DDPROT84 DD DISP=SHR,DSN=GENAPP.DDPROT84.DATA
//DDPRRP84 DD DISP=SHR,DSN=GENAPP.DDPRRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
