//VJOB1557 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT01YQ8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN82 DD DISP=SHR,DSN=GENAPP.DDPTIN82.DATA
//DDPTOT82 DD DISP=SHR,DSN=GENAPP.DDPTOT82.DATA
//DDPTRP82 DD DISP=SHR,DSN=GENAPP.DDPTRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01YQ9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN83 DD DISP=SHR,DSN=GENAPP.DDBIIN83.DATA
//DDBIOT83 DD DISP=SHR,DSN=GENAPP.DDBIOT83.DATA
//DDBIRP83 DD DISP=SHR,DSN=GENAPP.DDBIRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV01YQA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN84 DD DISP=SHR,DSN=GENAPP.DDAVIN84.DATA
//DDAVOT84 DD DISP=SHR,DSN=GENAPP.DDAVOT84.DATA
//DDAVRP84 DD DISP=SHR,DSN=GENAPP.DDAVRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
