//VJOB2806 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX021MB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN49 DD DISP=SHR,DSN=GENAPP.DDTXIN49.DATA
//DDTXOT49 DD DISP=SHR,DSN=GENAPP.DDTXOT49.DATA
//DDTXRP49 DD DISP=SHR,DSN=GENAPP.DDTXRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZVA021MC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN50 DD DISP=SHR,DSN=GENAPP.DDVAIN50.DATA
//DDVAOT50 DD DISP=SHR,DSN=GENAPP.DDVAOT50.DATA
//DDVARP50 DD DISP=SHR,DSN=GENAPP.DDVARP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI021MD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN51 DD DISP=SHR,DSN=GENAPP.DDLIIN51.DATA
//DDLIOT51 DD DISP=SHR,DSN=GENAPP.DDLIOT51.DATA
//DDLIRP51 DD DISP=SHR,DSN=GENAPP.DDLIRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
