//VJOB3342 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAN022UZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN37 DD DISP=SHR,DSN=GENAPP.DDANIN37.DATA
//DDANOT37 DD DISP=SHR,DSN=GENAPP.DDANOT37.DATA
//DDANRP37 DD DISP=SHR,DSN=GENAPP.DDANRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRS022V0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN38 DD DISP=SHR,DSN=GENAPP.DDRSIN38.DATA
//DDRSOT38 DD DISP=SHR,DSN=GENAPP.DDRSOT38.DATA
//DDRSRP38 DD DISP=SHR,DSN=GENAPP.DDRSRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV022V1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN39 DD DISP=SHR,DSN=GENAPP.DDIVIN39.DATA
//DDIVOT39 DD DISP=SHR,DSN=GENAPP.DDIVOT39.DATA
//DDIVRP39 DD DISP=SHR,DSN=GENAPP.DDIVRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
