//VJOB3236 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZVA022M5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDVAIN79 DD DISP=SHR,DSN=GENAPP.DDVAIN79.DATA
//DDVAOT79 DD DISP=SHR,DSN=GENAPP.DDVAOT79.DATA
//DDVARP79 DD DISP=SHR,DSN=GENAPP.DDVARP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN022M6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN80 DD DISP=SHR,DSN=GENAPP.DDRNIN80.DATA
//DDRNOT80 DD DISP=SHR,DSN=GENAPP.DDRNOT80.DATA
//DDRNRP80 DD DISP=SHR,DSN=GENAPP.DDRNRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL022M7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN81 DD DISP=SHR,DSN=GENAPP.DDCLIN81.DATA
//DDCLOT81 DD DISP=SHR,DSN=GENAPP.DDCLOT81.DATA
//DDCLRP81 DD DISP=SHR,DSN=GENAPP.DDCLRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
