//VJOB1371 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01YAQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN64 DD DISP=SHR,DSN=GENAPP.DDCUIN64.DATA
//DDCUOT64 DD DISP=SHR,DSN=GENAPP.DDCUOT64.DATA
//DDCURP64 DD DISP=SHR,DSN=GENAPP.DDCURP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZQU01YAR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN65 DD DISP=SHR,DSN=GENAPP.DDQUIN65.DATA
//DDQUOT65 DD DISP=SHR,DSN=GENAPP.DDQUOT65.DATA
//DDQURP65 DD DISP=SHR,DSN=GENAPP.DDQURP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01YAS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN66 DD DISP=SHR,DSN=GENAPP.DDMTIN66.DATA
//DDMTOT66 DD DISP=SHR,DSN=GENAPP.DDMTOT66.DATA
//DDMTRP66 DD DISP=SHR,DSN=GENAPP.DDMTRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
