//VJOB0588 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY01WHH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN55 DD DISP=SHR,DSN=GENAPP.DDTYIN55.DATA
//DDTYOT55 DD DISP=SHR,DSN=GENAPP.DDTYOT55.DATA
//DDTYRP55 DD DISP=SHR,DSN=GENAPP.DDTYRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY01WHI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN56 DD DISP=SHR,DSN=GENAPP.DDTYIN56.DATA
//DDTYOT56 DD DISP=SHR,DSN=GENAPP.DDTYOT56.DATA
//DDTYRP56 DD DISP=SHR,DSN=GENAPP.DDTYRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01WHJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN57 DD DISP=SHR,DSN=GENAPP.DDPEIN57.DATA
//DDPEOT57 DD DISP=SHR,DSN=GENAPP.DDPEOT57.DATA
//DDPERP57 DD DISP=SHR,DSN=GENAPP.DDPERP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
