//VJOB1429 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01YFK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN58 DD DISP=SHR,DSN=GENAPP.DDHOIN58.DATA
//DDHOOT58 DD DISP=SHR,DSN=GENAPP.DDHOOT58.DATA
//DDHORP58 DD DISP=SHR,DSN=GENAPP.DDHORP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRS01YFL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN59 DD DISP=SHR,DSN=GENAPP.DDRSIN59.DATA
//DDRSOT59 DD DISP=SHR,DSN=GENAPP.DDRSOT59.DATA
//DDRSRP59 DD DISP=SHR,DSN=GENAPP.DDRSRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR01YFM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN60 DD DISP=SHR,DSN=GENAPP.DDARIN60.DATA
//DDAROT60 DD DISP=SHR,DSN=GENAPP.DDAROT60.DATA
//DDARRP60 DD DISP=SHR,DSN=GENAPP.DDARRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
