//VJOB3617 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSB023HW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSBIN52 DD DISP=SHR,DSN=GENAPP.DDSBIN52.DATA
//DDSBOT52 DD DISP=SHR,DSN=GENAPP.DDSBOT52.DATA
//DDSBRP52 DD DISP=SHR,DSN=GENAPP.DDSBRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE023HX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN53 DD DISP=SHR,DSN=GENAPP.DDPEIN53.DATA
//DDPEOT53 DD DISP=SHR,DSN=GENAPP.DDPEOT53.DATA
//DDPERP53 DD DISP=SHR,DSN=GENAPP.DDPERP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO023HY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN54 DD DISP=SHR,DSN=GENAPP.DDCOIN54.DATA
//DDCOOT54 DD DISP=SHR,DSN=GENAPP.DDCOOT54.DATA
//DDCORP54 DD DISP=SHR,DSN=GENAPP.DDCORP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
