//VJOB3457 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT0234K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN22 DD DISP=SHR,DSN=GENAPP.DDNTIN22.DATA
//DDNTOT22 DD DISP=SHR,DSN=GENAPP.DDNTOT22.DATA
//DDNTRP22 DD DISP=SHR,DSN=GENAPP.DDNTRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI0234L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN23 DD DISP=SHR,DSN=GENAPP.DDLIIN23.DATA
//DDLIOT23 DD DISP=SHR,DSN=GENAPP.DDLIOT23.DATA
//DDLIRP23 DD DISP=SHR,DSN=GENAPP.DDLIRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN0234M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN24 DD DISP=SHR,DSN=GENAPP.DDENIN24.DATA
//DDENOT24 DD DISP=SHR,DSN=GENAPP.DDENOT24.DATA
//DDENRP24 DD DISP=SHR,DSN=GENAPP.DDENRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
