//VJOB1752 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01Z6H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN37 DD DISP=SHR,DSN=GENAPP.DDMTIN37.DATA
//DDMTOT37 DD DISP=SHR,DSN=GENAPP.DDMTOT37.DATA
//DDMTRP37 DD DISP=SHR,DSN=GENAPP.DDMTRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPL01Z6I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN38 DD DISP=SHR,DSN=GENAPP.DDPLIN38.DATA
//DDPLOT38 DD DISP=SHR,DSN=GENAPP.DDPLOT38.DATA
//DDPLRP38 DD DISP=SHR,DSN=GENAPP.DDPLRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI01Z6J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN39 DD DISP=SHR,DSN=GENAPP.DDLIIN39.DATA
//DDLIOT39 DD DISP=SHR,DSN=GENAPP.DDLIOT39.DATA
//DDLIRP39 DD DISP=SHR,DSN=GENAPP.DDLIRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
