//VJOB1127 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRS01XQE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRSIN52 DD DISP=SHR,DSN=GENAPP.DDRSIN52.DATA
//DDRSOT52 DD DISP=SHR,DSN=GENAPP.DDRSOT52.DATA
//DDRSRP52 DD DISP=SHR,DSN=GENAPP.DDRSRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCP01XQF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN53 DD DISP=SHR,DSN=GENAPP.DDCPIN53.DATA
//DDCPOT53 DD DISP=SHR,DSN=GENAPP.DDCPOT53.DATA
//DDCPRP53 DD DISP=SHR,DSN=GENAPP.DDCPRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN01XQG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN54 DD DISP=SHR,DSN=GENAPP.DDPNIN54.DATA
//DDPNOT54 DD DISP=SHR,DSN=GENAPP.DDPNOT54.DATA
//DDPNRP54 DD DISP=SHR,DSN=GENAPP.DDPNRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
