//VJOB1335 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB01Y7Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN46 DD DISP=SHR,DSN=GENAPP.DDLBIN46.DATA
//DDLBOT46 DD DISP=SHR,DSN=GENAPP.DDLBOT46.DATA
//DDLBRP46 DD DISP=SHR,DSN=GENAPP.DDLBRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01Y7R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN47 DD DISP=SHR,DSN=GENAPP.DDCUIN47.DATA
//DDCUOT47 DD DISP=SHR,DSN=GENAPP.DDCUOT47.DATA
//DDCURP47 DD DISP=SHR,DSN=GENAPP.DDCURP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01Y7S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN48 DD DISP=SHR,DSN=GENAPP.DDREIN48.DATA
//DDREOT48 DD DISP=SHR,DSN=GENAPP.DDREOT48.DATA
//DDRERP48 DD DISP=SHR,DSN=GENAPP.DDRERP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
