//VJOB2839 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDI021P2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN58 DD DISP=SHR,DSN=GENAPP.DDDIIN58.DATA
//DDDIOT58 DD DISP=SHR,DSN=GENAPP.DDDIOT58.DATA
//DDDIRP58 DD DISP=SHR,DSN=GENAPP.DDDIRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC021P3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN59 DD DISP=SHR,DSN=GENAPP.DDSCIN59.DATA
//DDSCOT59 DD DISP=SHR,DSN=GENAPP.DDSCOT59.DATA
//DDSCRP59 DD DISP=SHR,DSN=GENAPP.DDSCRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW021P4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN60 DD DISP=SHR,DSN=GENAPP.DDUWIN60.DATA
//DDUWOT60 DD DISP=SHR,DSN=GENAPP.DDUWOT60.DATA
//DDUWRP60 DD DISP=SHR,DSN=GENAPP.DDUWRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
