//VJOB2321 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA020HW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN34 DD DISP=SHR,DSN=GENAPP.DDPAIN34.DATA
//DDPAOT34 DD DISP=SHR,DSN=GENAPP.DDPAOT34.DATA
//DDPARP34 DD DISP=SHR,DSN=GENAPP.DDPARP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO020HX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN35 DD DISP=SHR,DSN=GENAPP.DDCOIN35.DATA
//DDCOOT35 DD DISP=SHR,DSN=GENAPP.DDCOOT35.DATA
//DDCORP35 DD DISP=SHR,DSN=GENAPP.DDCORP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI020HY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN36 DD DISP=SHR,DSN=GENAPP.DDBIIN36.DATA
//DDBIOT36 DD DISP=SHR,DSN=GENAPP.DDBIOT36.DATA
//DDBIRP36 DD DISP=SHR,DSN=GENAPP.DDBIRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
