//VJOB2010 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR01ZRZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN01 DD DISP=SHR,DSN=GENAPP.DDTRIN01.DATA
//DDTROT01 DD DISP=SHR,DSN=GENAPP.DDTROT01.DATA
//DDTRRP01 DD DISP=SHR,DSN=GENAPP.DDTRRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG01ZS0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN02 DD DISP=SHR,DSN=GENAPP.DDAGIN02.DATA
//DDAGOT02 DD DISP=SHR,DSN=GENAPP.DDAGOT02.DATA
//DDAGRP02 DD DISP=SHR,DSN=GENAPP.DDAGRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMB01ZS1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN03 DD DISP=SHR,DSN=GENAPP.DDMBIN03.DATA
//DDMBOT03 DD DISP=SHR,DSN=GENAPP.DDMBOT03.DATA
//DDMBRP03 DD DISP=SHR,DSN=GENAPP.DDMBRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
