//VJOB4278 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLT0250Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN55 DD DISP=SHR,DSN=GENAPP.DDLTIN55.DATA
//DDLTOT55 DD DISP=SHR,DSN=GENAPP.DDLTOT55.DATA
//DDLTRP55 DD DISP=SHR,DSN=GENAPP.DDLTRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI02510
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN56 DD DISP=SHR,DSN=GENAPP.DDBIIN56.DATA
//DDBIOT56 DD DISP=SHR,DSN=GENAPP.DDBIOT56.DATA
//DDBIRP56 DD DISP=SHR,DSN=GENAPP.DDBIRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA02511
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN57 DD DISP=SHR,DSN=GENAPP.DDMAIN57.DATA
//DDMAOT57 DD DISP=SHR,DSN=GENAPP.DDMAOT57.DATA
//DDMARP57 DD DISP=SHR,DSN=GENAPP.DDMARP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
