//VJOB3622 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBR023IB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN67 DD DISP=SHR,DSN=GENAPP.DDBRIN67.DATA
//DDBROT67 DD DISP=SHR,DSN=GENAPP.DDBROT67.DATA
//DDBRRP67 DD DISP=SHR,DSN=GENAPP.DDBRRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU023IC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN68 DD DISP=SHR,DSN=GENAPP.DDCUIN68.DATA
//DDCUOT68 DD DISP=SHR,DSN=GENAPP.DDCUOT68.DATA
//DDCURP68 DD DISP=SHR,DSN=GENAPP.DDCURP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEX023ID
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN69 DD DISP=SHR,DSN=GENAPP.DDEXIN69.DATA
//DDEXOT69 DD DISP=SHR,DSN=GENAPP.DDEXOT69.DATA
//DDEXRP69 DD DISP=SHR,DSN=GENAPP.DDEXRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
