//VJOB3151 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI022F2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN04 DD DISP=SHR,DSN=GENAPP.DDBIIN04.DATA
//DDBIOT04 DD DISP=SHR,DSN=GENAPP.DDBIOT04.DATA
//DDBIRP04 DD DISP=SHR,DSN=GENAPP.DDBIRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU022F3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN05 DD DISP=SHR,DSN=GENAPP.DDCUIN05.DATA
//DDCUOT05 DD DISP=SHR,DSN=GENAPP.DDCUOT05.DATA
//DDCURP05 DD DISP=SHR,DSN=GENAPP.DDCURP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN022F4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN06 DD DISP=SHR,DSN=GENAPP.DDENIN06.DATA
//DDENOT06 DD DISP=SHR,DSN=GENAPP.DDENOT06.DATA
//DDENRP06 DD DISP=SHR,DSN=GENAPP.DDENRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
