//VJOB1133 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZNT01XQW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN70 DD DISP=SHR,DSN=GENAPP.DDNTIN70.DATA
//DDNTOT70 DD DISP=SHR,DSN=GENAPP.DDNTOT70.DATA
//DDNTRP70 DD DISP=SHR,DSN=GENAPP.DDNTRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01XQX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN71 DD DISP=SHR,DSN=GENAPP.DDPAIN71.DATA
//DDPAOT71 DD DISP=SHR,DSN=GENAPP.DDPAOT71.DATA
//DDPARP71 DD DISP=SHR,DSN=GENAPP.DDPARP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCP01XQY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN72 DD DISP=SHR,DSN=GENAPP.DDCPIN72.DATA
//DDCPOT72 DD DISP=SHR,DSN=GENAPP.DDCPOT72.DATA
//DDCPRP72 DD DISP=SHR,DSN=GENAPP.DDCPRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
