//VJOB3990 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR024CZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN01 DD DISP=SHR,DSN=GENAPP.DDTRIN01.DATA
//DDTROT01 DD DISP=SHR,DSN=GENAPP.DDTROT01.DATA
//DDTRRP01 DD DISP=SHR,DSN=GENAPP.DDTRRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA024D0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN02 DD DISP=SHR,DSN=GENAPP.DDMAIN02.DATA
//DDMAOT02 DD DISP=SHR,DSN=GENAPP.DDMAOT02.DATA
//DDMARP02 DD DISP=SHR,DSN=GENAPP.DDMARP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAC024D1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN03 DD DISP=SHR,DSN=GENAPP.DDACIN03.DATA
//DDACOT03 DD DISP=SHR,DSN=GENAPP.DDACOT03.DATA
//DDACRP03 DD DISP=SHR,DSN=GENAPP.DDACRP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
