//VJOB2055 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZGW01ZVQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDGWIN46 DD DISP=SHR,DSN=GENAPP.DDGWIN46.DATA
//DDGWOT46 DD DISP=SHR,DSN=GENAPP.DDGWOT46.DATA
//DDGWRP46 DD DISP=SHR,DSN=GENAPP.DDGWRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT01ZVR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN47 DD DISP=SHR,DSN=GENAPP.DDLTIN47.DATA
//DDLTOT47 DD DISP=SHR,DSN=GENAPP.DDLTOT47.DATA
//DDLTRP47 DD DISP=SHR,DSN=GENAPP.DDLTRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR01ZVS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN48 DD DISP=SHR,DSN=GENAPP.DDARIN48.DATA
//DDAROT48 DD DISP=SHR,DSN=GENAPP.DDAROT48.DATA
//DDARRP48 DD DISP=SHR,DSN=GENAPP.DDARRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
