//VJOB3193 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP022IK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN40 DD DISP=SHR,DSN=GENAPP.DDCPIN40.DATA
//DDCPOT40 DD DISP=SHR,DSN=GENAPP.DDCPOT40.DATA
//DDCPRP40 DD DISP=SHR,DSN=GENAPP.DDCPRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR022IL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN41 DD DISP=SHR,DSN=GENAPP.DDTRIN41.DATA
//DDTROT41 DD DISP=SHR,DSN=GENAPP.DDTROT41.DATA
//DDTRRP41 DD DISP=SHR,DSN=GENAPP.DDTRRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT022IM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN42 DD DISP=SHR,DSN=GENAPP.DDMTIN42.DATA
//DDMTOT42 DD DISP=SHR,DSN=GENAPP.DDMTOT42.DATA
//DDMTRP42 DD DISP=SHR,DSN=GENAPP.DDMTRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
