//VJOB2222 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO0209N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN07 DD DISP=SHR,DSN=GENAPP.DDHOIN07.DATA
//DDHOOT07 DD DISP=SHR,DSN=GENAPP.DDHOOT07.DATA
//DDHORP07 DD DISP=SHR,DSN=GENAPP.DDHORP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLB0209O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN08 DD DISP=SHR,DSN=GENAPP.DDLBIN08.DATA
//DDLBOT08 DD DISP=SHR,DSN=GENAPP.DDLBOT08.DATA
//DDLBRP08 DD DISP=SHR,DSN=GENAPP.DDLBRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO0209P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN09 DD DISP=SHR,DSN=GENAPP.DDHOIN09.DATA
//DDHOOT09 DD DISP=SHR,DSN=GENAPP.DDHOOT09.DATA
//DDHORP09 DD DISP=SHR,DSN=GENAPP.DDHORP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
