//VJOB3165 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG022G8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN46 DD DISP=SHR,DSN=GENAPP.DDAGIN46.DATA
//DDAGOT46 DD DISP=SHR,DSN=GENAPP.DDAGOT46.DATA
//DDAGRP46 DD DISP=SHR,DSN=GENAPP.DDAGRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN022G9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN47 DD DISP=SHR,DSN=GENAPP.DDPNIN47.DATA
//DDPNOT47 DD DISP=SHR,DSN=GENAPP.DDPNOT47.DATA
//DDPNRP47 DD DISP=SHR,DSN=GENAPP.DDPNRP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU022GA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN48 DD DISP=SHR,DSN=GENAPP.DDCUIN48.DATA
//DDCUOT48 DD DISP=SHR,DSN=GENAPP.DDCUOT48.DATA
//DDCURP48 DD DISP=SHR,DSN=GENAPP.DDCURP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
