//VJOB0498 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01W9Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN55 DD DISP=SHR,DSN=GENAPP.DDAVIN55.DATA
//DDAVOT55 DD DISP=SHR,DSN=GENAPP.DDAVOT55.DATA
//DDAVRP55 DD DISP=SHR,DSN=GENAPP.DDAVRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV01WA0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN56 DD DISP=SHR,DSN=GENAPP.DDAVIN56.DATA
//DDAVOT56 DD DISP=SHR,DSN=GENAPP.DDAVOT56.DATA
//DDAVRP56 DD DISP=SHR,DSN=GENAPP.DDAVRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG01WA1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN57 DD DISP=SHR,DSN=GENAPP.DDAGIN57.DATA
//DDAGOT57 DD DISP=SHR,DSN=GENAPP.DDAGOT57.DATA
//DDAGRP57 DD DISP=SHR,DSN=GENAPP.DDAGRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
