//VJOB2492 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN020W5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN07 DD DISP=SHR,DSN=GENAPP.DDENIN07.DATA
//DDENOT07 DD DISP=SHR,DSN=GENAPP.DDENOT07.DATA
//DDENRP07 DD DISP=SHR,DSN=GENAPP.DDENRP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT020W6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN08 DD DISP=SHR,DSN=GENAPP.DDMTIN08.DATA
//DDMTOT08 DD DISP=SHR,DSN=GENAPP.DDMTOT08.DATA
//DDMTRP08 DD DISP=SHR,DSN=GENAPP.DDMTRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR020W7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN09 DD DISP=SHR,DSN=GENAPP.DDTRIN09.DATA
//DDTROT09 DD DISP=SHR,DSN=GENAPP.DDTROT09.DATA
//DDTRRP09 DD DISP=SHR,DSN=GENAPP.DDTRRP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
