//VJOB1007 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01XGE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN52 DD DISP=SHR,DSN=GENAPP.DDMTIN52.DATA
//DDMTOT52 DD DISP=SHR,DSN=GENAPP.DDMTOT52.DATA
//DDMTRP52 DD DISP=SHR,DSN=GENAPP.DDMTRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01XGF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN53 DD DISP=SHR,DSN=GENAPP.DDMTIN53.DATA
//DDMTOT53 DD DISP=SHR,DSN=GENAPP.DDMTOT53.DATA
//DDMTRP53 DD DISP=SHR,DSN=GENAPP.DDMTRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR01XGG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN54 DD DISP=SHR,DSN=GENAPP.DDBRIN54.DATA
//DDBROT54 DD DISP=SHR,DSN=GENAPP.DDBROT54.DATA
//DDBRRP54 DD DISP=SHR,DSN=GENAPP.DDBRRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
