//VJOB0277 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP01VRK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN22 DD DISP=SHR,DSN=GENAPP.DDCPIN22.DATA
//DDCPOT22 DD DISP=SHR,DSN=GENAPP.DDCPOT22.DATA
//DDCPRP22 DD DISP=SHR,DSN=GENAPP.DDCPRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA01VRL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN23 DD DISP=SHR,DSN=GENAPP.DDPAIN23.DATA
//DDPAOT23 DD DISP=SHR,DSN=GENAPP.DDPAOT23.DATA
//DDPARP23 DD DISP=SHR,DSN=GENAPP.DDPARP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01VRM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN24 DD DISP=SHR,DSN=GENAPP.DDBIIN24.DATA
//DDBIOT24 DD DISP=SHR,DSN=GENAPP.DDBIOT24.DATA
//DDBIRP24 DD DISP=SHR,DSN=GENAPP.DDBIRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
