//VJOB1998 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPR01ZQZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN55 DD DISP=SHR,DSN=GENAPP.DDPRIN55.DATA
//DDPROT55 DD DISP=SHR,DSN=GENAPP.DDPROT55.DATA
//DDPRRP55 DD DISP=SHR,DSN=GENAPP.DDPRRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV01ZR0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN56 DD DISP=SHR,DSN=GENAPP.DDIVIN56.DATA
//DDIVOT56 DD DISP=SHR,DSN=GENAPP.DDIVOT56.DATA
//DDIVRP56 DD DISP=SHR,DSN=GENAPP.DDIVRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL01ZR1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN57 DD DISP=SHR,DSN=GENAPP.DDFLIN57.DATA
//DDFLOT57 DD DISP=SHR,DSN=GENAPP.DDFLOT57.DATA
//DDFLRP57 DD DISP=SHR,DSN=GENAPP.DDFLRP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
