//VJOB0308 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAU01VU5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN25 DD DISP=SHR,DSN=GENAPP.DDAUIN25.DATA
//DDAUOT25 DD DISP=SHR,DSN=GENAPP.DDAUOT25.DATA
//DDAURP25 DD DISP=SHR,DSN=GENAPP.DDAURP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01VU6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN26 DD DISP=SHR,DSN=GENAPP.DDCLIN26.DATA
//DDCLOT26 DD DISP=SHR,DSN=GENAPP.DDCLOT26.DATA
//DDCLRP26 DD DISP=SHR,DSN=GENAPP.DDCLRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01VU7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN27 DD DISP=SHR,DSN=GENAPP.DDCLIN27.DATA
//DDCLOT27 DD DISP=SHR,DSN=GENAPP.DDCLOT27.DATA
//DDCLRP27 DD DISP=SHR,DSN=GENAPP.DDCLRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
