//VJOB2781 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZED021K8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN64 DD DISP=SHR,DSN=GENAPP.DDEDIN64.DATA
//DDEDOT64 DD DISP=SHR,DSN=GENAPP.DDEDOT64.DATA
//DDEDRP64 DD DISP=SHR,DSN=GENAPP.DDEDRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX021K9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN65 DD DISP=SHR,DSN=GENAPP.DDTXIN65.DATA
//DDTXOT65 DD DISP=SHR,DSN=GENAPP.DDTXOT65.DATA
//DDTXRP65 DD DISP=SHR,DSN=GENAPP.DDTXRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR021KA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN66 DD DISP=SHR,DSN=GENAPP.DDPRIN66.DATA
//DDPROT66 DD DISP=SHR,DSN=GENAPP.DDPROT66.DATA
//DDPRRP66 DD DISP=SHR,DSN=GENAPP.DDPRRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
