//VJOB2665 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP021AK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN76 DD DISP=SHR,DSN=GENAPP.DDCPIN76.DATA
//DDCPOT76 DD DISP=SHR,DSN=GENAPP.DDCPOT76.DATA
//DDCPRP76 DD DISP=SHR,DSN=GENAPP.DDCPRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY021AL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN77 DD DISP=SHR,DSN=GENAPP.DDTYIN77.DATA
//DDTYOT77 DD DISP=SHR,DSN=GENAPP.DDTYOT77.DATA
//DDTYRP77 DD DISP=SHR,DSN=GENAPP.DDTYRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEX021AM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN78 DD DISP=SHR,DSN=GENAPP.DDEXIN78.DATA
//DDEXOT78 DD DISP=SHR,DSN=GENAPP.DDEXOT78.DATA
//DDEXRP78 DD DISP=SHR,DSN=GENAPP.DDEXRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
