//VJOB4107 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY024MQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN82 DD DISP=SHR,DSN=GENAPP.DDTYIN82.DATA
//DDTYOT82 DD DISP=SHR,DSN=GENAPP.DDTYOT82.DATA
//DDTYRP82 DD DISP=SHR,DSN=GENAPP.DDTYRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL024MR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN83 DD DISP=SHR,DSN=GENAPP.DDCLIN83.DATA
//DDCLOT83 DD DISP=SHR,DSN=GENAPP.DDCLOT83.DATA
//DDCLRP83 DD DISP=SHR,DSN=GENAPP.DDCLRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT024MS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN84 DD DISP=SHR,DSN=GENAPP.DDMTIN84.DATA
//DDMTOT84 DD DISP=SHR,DSN=GENAPP.DDMTOT84.DATA
//DDMTRP84 DD DISP=SHR,DSN=GENAPP.DDMTRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
