//VJOB1568 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01YR5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN25 DD DISP=SHR,DSN=GENAPP.DDAVIN25.DATA
//DDAVOT25 DD DISP=SHR,DSN=GENAPP.DDAVOT25.DATA
//DDAVRP25 DD DISP=SHR,DSN=GENAPP.DDAVRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01YR6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN26 DD DISP=SHR,DSN=GENAPP.DDCLIN26.DATA
//DDCLOT26 DD DISP=SHR,DSN=GENAPP.DDCLOT26.DATA
//DDCLRP26 DD DISP=SHR,DSN=GENAPP.DDCLRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPL01YR7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN27 DD DISP=SHR,DSN=GENAPP.DDPLIN27.DATA
//DDPLOT27 DD DISP=SHR,DSN=GENAPP.DDPLOT27.DATA
//DDPLRP27 DD DISP=SHR,DSN=GENAPP.DDPLRP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
