//VJOB1523 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDO01YNE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN70 DD DISP=SHR,DSN=GENAPP.DDDOIN70.DATA
//DDDOOT70 DD DISP=SHR,DSN=GENAPP.DDDOOT70.DATA
//DDDORP70 DD DISP=SHR,DSN=GENAPP.DDDORP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01YNF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN71 DD DISP=SHR,DSN=GENAPP.DDMTIN71.DATA
//DDMTOT71 DD DISP=SHR,DSN=GENAPP.DDMTOT71.DATA
//DDMTRP71 DD DISP=SHR,DSN=GENAPP.DDMTRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN01YNG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN72 DD DISP=SHR,DSN=GENAPP.DDANIN72.DATA
//DDANOT72 DD DISP=SHR,DSN=GENAPP.DDANOT72.DATA
//DDANRP72 DD DISP=SHR,DSN=GENAPP.DDANRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
