//VJOB3183 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG022HQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN10 DD DISP=SHR,DSN=GENAPP.DDRGIN10.DATA
//DDRGOT10 DD DISP=SHR,DSN=GENAPP.DDRGOT10.DATA
//DDRGRP10 DD DISP=SHR,DSN=GENAPP.DDRGRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT022HR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN11 DD DISP=SHR,DSN=GENAPP.DDMTIN11.DATA
//DDMTOT11 DD DISP=SHR,DSN=GENAPP.DDMTOT11.DATA
//DDMTRP11 DD DISP=SHR,DSN=GENAPP.DDMTRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR022HS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN12 DD DISP=SHR,DSN=GENAPP.DDPRIN12.DATA
//DDPROT12 DD DISP=SHR,DSN=GENAPP.DDPROT12.DATA
//DDPRRP12 DD DISP=SHR,DSN=GENAPP.DDPRRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
