//VJOB1946 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01ZMN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN79 DD DISP=SHR,DSN=GENAPP.DDMTIN79.DATA
//DDMTOT79 DD DISP=SHR,DSN=GENAPP.DDMTOT79.DATA
//DDMTRP79 DD DISP=SHR,DSN=GENAPP.DDMTRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01ZMO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN80 DD DISP=SHR,DSN=GENAPP.DDMTIN80.DATA
//DDMTOT80 DD DISP=SHR,DSN=GENAPP.DDMTOT80.DATA
//DDMTRP80 DD DISP=SHR,DSN=GENAPP.DDMTRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZQU01ZMP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN81 DD DISP=SHR,DSN=GENAPP.DDQUIN81.DATA
//DDQUOT81 DD DISP=SHR,DSN=GENAPP.DDQUOT81.DATA
//DDQURP81 DD DISP=SHR,DSN=GENAPP.DDQURP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
