//VJOB2591 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT0214E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN34 DD DISP=SHR,DSN=GENAPP.DDPTIN34.DATA
//DDPTOT34 DD DISP=SHR,DSN=GENAPP.DDPTOT34.DATA
//DDPTRP34 DD DISP=SHR,DSN=GENAPP.DDPTRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY0214F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN35 DD DISP=SHR,DSN=GENAPP.DDTYIN35.DATA
//DDTYOT35 DD DISP=SHR,DSN=GENAPP.DDTYOT35.DATA
//DDTYRP35 DD DISP=SHR,DSN=GENAPP.DDTYRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL0214G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN36 DD DISP=SHR,DSN=GENAPP.DDFLIN36.DATA
//DDFLOT36 DD DISP=SHR,DSN=GENAPP.DDFLOT36.DATA
//DDFLRP36 DD DISP=SHR,DSN=GENAPP.DDFLRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
