//VJOB3160 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMB022FT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN31 DD DISP=SHR,DSN=GENAPP.DDMBIN31.DATA
//DDMBOT31 DD DISP=SHR,DSN=GENAPP.DDMBOT31.DATA
//DDMBRP31 DD DISP=SHR,DSN=GENAPP.DDMBRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI022FU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN32 DD DISP=SHR,DSN=GENAPP.DDBIIN32.DATA
//DDBIOT32 DD DISP=SHR,DSN=GENAPP.DDBIOT32.DATA
//DDBIRP32 DD DISP=SHR,DSN=GENAPP.DDBIRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDO022FV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN33 DD DISP=SHR,DSN=GENAPP.DDDOIN33.DATA
//DDDOOT33 DD DISP=SHR,DSN=GENAPP.DDDOOT33.DATA
//DDDORP33 DD DISP=SHR,DSN=GENAPP.DDDORP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
