//VJOB1731 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01Z4Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN64 DD DISP=SHR,DSN=GENAPP.DDMTIN64.DATA
//DDMTOT64 DD DISP=SHR,DSN=GENAPP.DDMTOT64.DATA
//DDMTRP64 DD DISP=SHR,DSN=GENAPP.DDMTRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE01Z4R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN65 DD DISP=SHR,DSN=GENAPP.DDSEIN65.DATA
//DDSEOT65 DD DISP=SHR,DSN=GENAPP.DDSEOT65.DATA
//DDSERP65 DD DISP=SHR,DSN=GENAPP.DDSERP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE01Z4S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN66 DD DISP=SHR,DSN=GENAPP.DDHEIN66.DATA
//DDHEOT66 DD DISP=SHR,DSN=GENAPP.DDHEOT66.DATA
//DDHERP66 DD DISP=SHR,DSN=GENAPP.DDHERP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
