//VJOB1241 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01XZW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN34 DD DISP=SHR,DSN=GENAPP.DDCLIN34.DATA
//DDCLOT34 DD DISP=SHR,DSN=GENAPP.DDCLOT34.DATA
//DDCLRP34 DD DISP=SHR,DSN=GENAPP.DDCLRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01XZX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN35 DD DISP=SHR,DSN=GENAPP.DDMTIN35.DATA
//DDMTOT35 DD DISP=SHR,DSN=GENAPP.DDMTOT35.DATA
//DDMTRP35 DD DISP=SHR,DSN=GENAPP.DDMTRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZED01XZY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN36 DD DISP=SHR,DSN=GENAPP.DDEDIN36.DATA
//DDEDOT36 DD DISP=SHR,DSN=GENAPP.DDEDOT36.DATA
//DDEDRP36 DD DISP=SHR,DSN=GENAPP.DDEDRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
