//VJOB2129 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIF0201W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN88 DD DISP=SHR,DSN=GENAPP.DDIFIN88.DATA
//DDIFOT88 DD DISP=SHR,DSN=GENAPP.DDIFOT88.DATA
//DDIFRP88 DD DISP=SHR,DSN=GENAPP.DDIFRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR0201X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN89 DD DISP=SHR,DSN=GENAPP.DDCRIN89.DATA
//DDCROT89 DD DISP=SHR,DSN=GENAPP.DDCROT89.DATA
//DDCRRP89 DD DISP=SHR,DSN=GENAPP.DDCRRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCO0201Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN90 DD DISP=SHR,DSN=GENAPP.DDCOIN90.DATA
//DDCOOT90 DD DISP=SHR,DSN=GENAPP.DDCOOT90.DATA
//DDCORP90 DD DISP=SHR,DSN=GENAPP.DDCORP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
