//VJOB3063 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSU0227Q
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN10 DD DISP=SHR,DSN=GENAPP.DDSUIN10.DATA
//DDSUOT10 DD DISP=SHR,DSN=GENAPP.DDSUOT10.DATA
//DDSURP10 DD DISP=SHR,DSN=GENAPP.DDSURP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE0227R
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN11 DD DISP=SHR,DSN=GENAPP.DDPEIN11.DATA
//DDPEOT11 DD DISP=SHR,DSN=GENAPP.DDPEOT11.DATA
//DDPERP11 DD DISP=SHR,DSN=GENAPP.DDPERP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSL0227S
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN12 DD DISP=SHR,DSN=GENAPP.DDSLIN12.DATA
//DDSLOT12 DD DISP=SHR,DSN=GENAPP.DDSLOT12.DATA
//DDSLRP12 DD DISP=SHR,DSN=GENAPP.DDSLRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
