//VJOB0739 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSU01WU2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN58 DD DISP=SHR,DSN=GENAPP.DDSUIN58.DATA
//DDSUOT58 DD DISP=SHR,DSN=GENAPP.DDSUOT58.DATA
//DDSURP58 DD DISP=SHR,DSN=GENAPP.DDSURP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV01WU3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN59 DD DISP=SHR,DSN=GENAPP.DDIVIN59.DATA
//DDIVOT59 DD DISP=SHR,DSN=GENAPP.DDIVOT59.DATA
//DDIVRP59 DD DISP=SHR,DSN=GENAPP.DDIVRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI01WU4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN60 DD DISP=SHR,DSN=GENAPP.DDLIIN60.DATA
//DDLIOT60 DD DISP=SHR,DSN=GENAPP.DDLIOT60.DATA
//DDLIRP60 DD DISP=SHR,DSN=GENAPP.DDLIRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
