//VJOB1839 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE01ZDQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN28 DD DISP=SHR,DSN=GENAPP.DDHEIN28.DATA
//DDHEOT28 DD DISP=SHR,DSN=GENAPP.DDHEOT28.DATA
//DDHERP28 DD DISP=SHR,DSN=GENAPP.DDHERP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01ZDR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN29 DD DISP=SHR,DSN=GENAPP.DDHOIN29.DATA
//DDHOOT29 DD DISP=SHR,DSN=GENAPP.DDHOOT29.DATA
//DDHORP29 DD DISP=SHR,DSN=GENAPP.DDHORP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01ZDS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN30 DD DISP=SHR,DSN=GENAPP.DDPRIN30.DATA
//DDPROT30 DD DISP=SHR,DSN=GENAPP.DDPROT30.DATA
//DDPRRP30 DD DISP=SHR,DSN=GENAPP.DDPRRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
