//VJOB1277 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01Y2W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN52 DD DISP=SHR,DSN=GENAPP.DDENIN52.DATA
//DDENOT52 DD DISP=SHR,DSN=GENAPP.DDENOT52.DATA
//DDENRP52 DD DISP=SHR,DSN=GENAPP.DDENRP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW01Y2X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN53 DD DISP=SHR,DSN=GENAPP.DDUWIN53.DATA
//DDUWOT53 DD DISP=SHR,DSN=GENAPP.DDUWOT53.DATA
//DDUWRP53 DD DISP=SHR,DSN=GENAPP.DDUWRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01Y2Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN54 DD DISP=SHR,DSN=GENAPP.DDMTIN54.DATA
//DDMTOT54 DD DISP=SHR,DSN=GENAPP.DDMTOT54.DATA
//DDMTRP54 DD DISP=SHR,DSN=GENAPP.DDMTRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
