//VJOB1100 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE01XO5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN61 DD DISP=SHR,DSN=GENAPP.DDPEIN61.DATA
//DDPEOT61 DD DISP=SHR,DSN=GENAPP.DDPEOT61.DATA
//DDPERP61 DD DISP=SHR,DSN=GENAPP.DDPERP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01XO6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN62 DD DISP=SHR,DSN=GENAPP.DDFLIN62.DATA
//DDFLOT62 DD DISP=SHR,DSN=GENAPP.DDFLOT62.DATA
//DDFLRP62 DD DISP=SHR,DSN=GENAPP.DDFLRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01XO7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN63 DD DISP=SHR,DSN=GENAPP.DDREIN63.DATA
//DDREOT63 DD DISP=SHR,DSN=GENAPP.DDREOT63.DATA
//DDRERP63 DD DISP=SHR,DSN=GENAPP.DDRERP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
