//VJOB1971 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01ZOQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN64 DD DISP=SHR,DSN=GENAPP.DDMTIN64.DATA
//DDMTOT64 DD DISP=SHR,DSN=GENAPP.DDMTOT64.DATA
//DDMTRP64 DD DISP=SHR,DSN=GENAPP.DDMTRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRN01ZOR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRNIN65 DD DISP=SHR,DSN=GENAPP.DDRNIN65.DATA
//DDRNOT65 DD DISP=SHR,DSN=GENAPP.DDRNOT65.DATA
//DDRNRP65 DD DISP=SHR,DSN=GENAPP.DDRNRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01ZOS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN66 DD DISP=SHR,DSN=GENAPP.DDMTIN66.DATA
//DDMTOT66 DD DISP=SHR,DSN=GENAPP.DDMTOT66.DATA
//DDMTRP66 DD DISP=SHR,DSN=GENAPP.DDMTRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
