//VJOB0436 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZSE01W4T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN49 DD DISP=SHR,DSN=GENAPP.DDSEIN49.DATA
//DDSEOT49 DD DISP=SHR,DSN=GENAPP.DDSEOT49.DATA
//DDSERP49 DD DISP=SHR,DSN=GENAPP.DDSERP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01W4U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN50 DD DISP=SHR,DSN=GENAPP.DDHOIN50.DATA
//DDHOOT50 DD DISP=SHR,DSN=GENAPP.DDHOOT50.DATA
//DDHORP50 DD DISP=SHR,DSN=GENAPP.DDHORP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCP01W4V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN51 DD DISP=SHR,DSN=GENAPP.DDCPIN51.DATA
//DDCPOT51 DD DISP=SHR,DSN=GENAPP.DDCPOT51.DATA
//DDCPRP51 DD DISP=SHR,DSN=GENAPP.DDCPRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
