//VJOB1713 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPL01Z38
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN10 DD DISP=SHR,DSN=GENAPP.DDPLIN10.DATA
//DDPLOT10 DD DISP=SHR,DSN=GENAPP.DDPLOT10.DATA
//DDPLRP10 DD DISP=SHR,DSN=GENAPP.DDPLRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO01Z39
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN11 DD DISP=SHR,DSN=GENAPP.DDCOIN11.DATA
//DDCOOT11 DD DISP=SHR,DSN=GENAPP.DDCOOT11.DATA
//DDCORP11 DD DISP=SHR,DSN=GENAPP.DDCORP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLT01Z3A
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN12 DD DISP=SHR,DSN=GENAPP.DDLTIN12.DATA
//DDLTOT12 DD DISP=SHR,DSN=GENAPP.DDLTOT12.DATA
//DDLTRP12 DD DISP=SHR,DSN=GENAPP.DDLTRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
