//VJOB1891 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO01ZI2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN04 DD DISP=SHR,DSN=GENAPP.DDHOIN04.DATA
//DDHOOT04 DD DISP=SHR,DSN=GENAPP.DDHOOT04.DATA
//DDHORP04 DD DISP=SHR,DSN=GENAPP.DDHORP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZQU01ZI3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN05 DD DISP=SHR,DSN=GENAPP.DDQUIN05.DATA
//DDQUOT05 DD DISP=SHR,DSN=GENAPP.DDQUOT05.DATA
//DDQURP05 DD DISP=SHR,DSN=GENAPP.DDQURP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU01ZI4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN06 DD DISP=SHR,DSN=GENAPP.DDCUIN06.DATA
//DDCUOT06 DD DISP=SHR,DSN=GENAPP.DDCUOT06.DATA
//DDCURP06 DD DISP=SHR,DSN=GENAPP.DDCURP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
