//VJOB2846 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE021PN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN79 DD DISP=SHR,DSN=GENAPP.DDREIN79.DATA
//DDREOT79 DD DISP=SHR,DSN=GENAPP.DDREOT79.DATA
//DDRERP79 DD DISP=SHR,DSN=GENAPP.DDRERP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLI021PO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN80 DD DISP=SHR,DSN=GENAPP.DDLIIN80.DATA
//DDLIOT80 DD DISP=SHR,DSN=GENAPP.DDLIOT80.DATA
//DDLIRP80 DD DISP=SHR,DSN=GENAPP.DDLIRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT021PP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN81 DD DISP=SHR,DSN=GENAPP.DDMTIN81.DATA
//DDMTOT81 DD DISP=SHR,DSN=GENAPP.DDMTOT81.DATA
//DDMTRP81 DD DISP=SHR,DSN=GENAPP.DDMTRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
