//VJOB4239 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZST024XQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN28 DD DISP=SHR,DSN=GENAPP.DDSTIN28.DATA
//DDSTOT28 DD DISP=SHR,DSN=GENAPP.DDSTOT28.DATA
//DDSTRP28 DD DISP=SHR,DSN=GENAPP.DDSTRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT024XR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN29 DD DISP=SHR,DSN=GENAPP.DDMTIN29.DATA
//DDMTOT29 DD DISP=SHR,DSN=GENAPP.DDMTOT29.DATA
//DDMTRP29 DD DISP=SHR,DSN=GENAPP.DDMTRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN024XS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN30 DD DISP=SHR,DSN=GENAPP.DDENIN30.DATA
//DDENOT30 DD DISP=SHR,DSN=GENAPP.DDENOT30.DATA
//DDENRP30 DD DISP=SHR,DSN=GENAPP.DDENRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
