//VJOB1692 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIV01Z1H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN37 DD DISP=SHR,DSN=GENAPP.DDIVIN37.DATA
//DDIVOT37 DD DISP=SHR,DSN=GENAPP.DDIVOT37.DATA
//DDIVRP37 DD DISP=SHR,DSN=GENAPP.DDIVRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ01Z1I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN38 DD DISP=SHR,DSN=GENAPP.DDAZIN38.DATA
//DDAZOT38 DD DISP=SHR,DSN=GENAPP.DDAZOT38.DATA
//DDAZRP38 DD DISP=SHR,DSN=GENAPP.DDAZRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01Z1J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN39 DD DISP=SHR,DSN=GENAPP.DDMTIN39.DATA
//DDMTOT39 DD DISP=SHR,DSN=GENAPP.DDMTOT39.DATA
//DDMTRP39 DD DISP=SHR,DSN=GENAPP.DDMTRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
