//VJOB0479 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE01W8E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN88 DD DISP=SHR,DSN=GENAPP.DDREIN88.DATA
//DDREOT88 DD DISP=SHR,DSN=GENAPP.DDREOT88.DATA
//DDRERP88 DD DISP=SHR,DSN=GENAPP.DDRERP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU01W8F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN89 DD DISP=SHR,DSN=GENAPP.DDCUIN89.DATA
//DDCUOT89 DD DISP=SHR,DSN=GENAPP.DDCUOT89.DATA
//DDCURP89 DD DISP=SHR,DSN=GENAPP.DDCURP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI01W8G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN90 DD DISP=SHR,DSN=GENAPP.DDBIIN90.DATA
//DDBIOT90 DD DISP=SHR,DSN=GENAPP.DDBIOT90.DATA
//DDBIRP90 DD DISP=SHR,DSN=GENAPP.DDBIRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
