//VJOB3737 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE023RW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN52 DD DISP=SHR,DSN=GENAPP.DDPEIN52.DATA
//DDPEOT52 DD DISP=SHR,DSN=GENAPP.DDPEOT52.DATA
//DDPERP52 DD DISP=SHR,DSN=GENAPP.DDPERP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL023RX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN53 DD DISP=SHR,DSN=GENAPP.DDCLIN53.DATA
//DDCLOT53 DD DISP=SHR,DSN=GENAPP.DDCLOT53.DATA
//DDCLRP53 DD DISP=SHR,DSN=GENAPP.DDCLRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBA023RY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN54 DD DISP=SHR,DSN=GENAPP.DDBAIN54.DATA
//DDBAOT54 DD DISP=SHR,DSN=GENAPP.DDBAOT54.DATA
//DDBARP54 DD DISP=SHR,DSN=GENAPP.DDBARP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
