//VJOB4176 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP024SH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN19 DD DISP=SHR,DSN=GENAPP.DDCPIN19.DATA
//DDCPOT19 DD DISP=SHR,DSN=GENAPP.DDCPOT19.DATA
//DDCPRP19 DD DISP=SHR,DSN=GENAPP.DDCPRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZNT024SI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDNTIN20 DD DISP=SHR,DSN=GENAPP.DDNTIN20.DATA
//DDNTOT20 DD DISP=SHR,DSN=GENAPP.DDNTOT20.DATA
//DDNTRP20 DD DISP=SHR,DSN=GENAPP.DDNTRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT024SJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN21 DD DISP=SHR,DSN=GENAPP.DDMTIN21.DATA
//DDMTOT21 DD DISP=SHR,DSN=GENAPP.DDMTOT21.DATA
//DDMTRP21 DD DISP=SHR,DSN=GENAPP.DDMTRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
