//VJOB0095 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01VCE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN16 DD DISP=SHR,DSN=GENAPP.DDBIIN16.DATA
//DDBIOT16 DD DISP=SHR,DSN=GENAPP.DDBIOT16.DATA
//DDBIRP16 DD DISP=SHR,DSN=GENAPP.DDBIRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC01VCF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN17 DD DISP=SHR,DSN=GENAPP.DDSCIN17.DATA
//DDSCOT17 DD DISP=SHR,DSN=GENAPP.DDSCOT17.DATA
//DDSCRP17 DD DISP=SHR,DSN=GENAPP.DDSCRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCR01VCG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN18 DD DISP=SHR,DSN=GENAPP.DDCRIN18.DATA
//DDCROT18 DD DISP=SHR,DSN=GENAPP.DDCROT18.DATA
//DDCRRP18 DD DISP=SHR,DSN=GENAPP.DDCRRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
