//VJOB2393 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE020NW
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN70 DD DISP=SHR,DSN=GENAPP.DDREIN70.DATA
//DDREOT70 DD DISP=SHR,DSN=GENAPP.DDREOT70.DATA
//DDRERP70 DD DISP=SHR,DSN=GENAPP.DDRERP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR020NX
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN71 DD DISP=SHR,DSN=GENAPP.DDTRIN71.DATA
//DDTROT71 DD DISP=SHR,DSN=GENAPP.DDTROT71.DATA
//DDTRRP71 DD DISP=SHR,DSN=GENAPP.DDTRRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG020NY
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN72 DD DISP=SHR,DSN=GENAPP.DDAGIN72.DATA
//DDAGOT72 DD DISP=SHR,DSN=GENAPP.DDAGOT72.DATA
//DDAGRP72 DD DISP=SHR,DSN=GENAPP.DDAGRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
