//VJOB0295 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01VT2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN76 DD DISP=SHR,DSN=GENAPP.DDBIIN76.DATA
//DDBIOT76 DD DISP=SHR,DSN=GENAPP.DDBIOT76.DATA
//DDBIRP76 DD DISP=SHR,DSN=GENAPP.DDBIRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSC01VT3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN77 DD DISP=SHR,DSN=GENAPP.DDSCIN77.DATA
//DDSCOT77 DD DISP=SHR,DSN=GENAPP.DDSCOT77.DATA
//DDSCRP77 DD DISP=SHR,DSN=GENAPP.DDSCRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01VT4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN78 DD DISP=SHR,DSN=GENAPP.DDTRIN78.DATA
//DDTROT78 DD DISP=SHR,DSN=GENAPP.DDTROT78.DATA
//DDTRRP78 DD DISP=SHR,DSN=GENAPP.DDTRRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
