//VJOB0443 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCN01W5E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCNIN70 DD DISP=SHR,DSN=GENAPP.DDCNIN70.DATA
//DDCNOT70 DD DISP=SHR,DSN=GENAPP.DDCNOT70.DATA
//DDCNRP70 DD DISP=SHR,DSN=GENAPP.DDCNRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMB01W5F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN71 DD DISP=SHR,DSN=GENAPP.DDMBIN71.DATA
//DDMBOT71 DD DISP=SHR,DSN=GENAPP.DDMBOT71.DATA
//DDMBRP71 DD DISP=SHR,DSN=GENAPP.DDMBRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG01W5G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN72 DD DISP=SHR,DSN=GENAPP.DDAGIN72.DATA
//DDAGOT72 DD DISP=SHR,DSN=GENAPP.DDAGOT72.DATA
//DDAGRP72 DD DISP=SHR,DSN=GENAPP.DDAGRP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
