//VJOB1887 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01ZHQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN82 DD DISP=SHR,DSN=GENAPP.DDBIIN82.DATA
//DDBIOT82 DD DISP=SHR,DSN=GENAPP.DDBIOT82.DATA
//DDBIRP82 DD DISP=SHR,DSN=GENAPP.DDBIRP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE01ZHR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN83 DD DISP=SHR,DSN=GENAPP.DDREIN83.DATA
//DDREOT83 DD DISP=SHR,DSN=GENAPP.DDREOT83.DATA
//DDRERP83 DD DISP=SHR,DSN=GENAPP.DDRERP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZED01ZHS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN84 DD DISP=SHR,DSN=GENAPP.DDEDIN84.DATA
//DDEDOT84 DD DISP=SHR,DSN=GENAPP.DDEDOT84.DATA
//DDEDRP84 DD DISP=SHR,DSN=GENAPP.DDEDRP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
