//VJOB1075 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01XM2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN76 DD DISP=SHR,DSN=GENAPP.DDENIN76.DATA
//DDENOT76 DD DISP=SHR,DSN=GENAPP.DDENOT76.DATA
//DDENRP76 DD DISP=SHR,DSN=GENAPP.DDENRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01XM3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN77 DD DISP=SHR,DSN=GENAPP.DDFLIN77.DATA
//DDFLOT77 DD DISP=SHR,DSN=GENAPP.DDFLOT77.DATA
//DDFLRP77 DD DISP=SHR,DSN=GENAPP.DDFLRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMB01XM4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMBIN78 DD DISP=SHR,DSN=GENAPP.DDMBIN78.DATA
//DDMBOT78 DD DISP=SHR,DSN=GENAPP.DDMBOT78.DATA
//DDMBRP78 DD DISP=SHR,DSN=GENAPP.DDMBRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
