//VJOB3026 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT0224N
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN79 DD DISP=SHR,DSN=GENAPP.DDPTIN79.DATA
//DDPTOT79 DD DISP=SHR,DSN=GENAPP.DDPTOT79.DATA
//DDPTRP79 DD DISP=SHR,DSN=GENAPP.DDPTRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPN0224O
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN80 DD DISP=SHR,DSN=GENAPP.DDPNIN80.DATA
//DDPNOT80 DD DISP=SHR,DSN=GENAPP.DDPNOT80.DATA
//DDPNRP80 DD DISP=SHR,DSN=GENAPP.DDPNRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEX0224P
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN81 DD DISP=SHR,DSN=GENAPP.DDEXIN81.DATA
//DDEXOT81 DD DISP=SHR,DSN=GENAPP.DDEXOT81.DATA
//DDEXRP81 DD DISP=SHR,DSN=GENAPP.DDEXRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
