//VJOB3827 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA023ZE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN52 DD DISP=SHR,DSN=GENAPP.DDPAIN52.DATA
//DDPAOT52 DD DISP=SHR,DSN=GENAPP.DDPAOT52.DATA
//DDPARP52 DD DISP=SHR,DSN=GENAPP.DDPARP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRT023ZF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN53 DD DISP=SHR,DSN=GENAPP.DDRTIN53.DATA
//DDRTOT53 DD DISP=SHR,DSN=GENAPP.DDRTOT53.DATA
//DDRTRP53 DD DISP=SHR,DSN=GENAPP.DDRTRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAN023ZG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN54 DD DISP=SHR,DSN=GENAPP.DDANIN54.DATA
//DDANOT54 DD DISP=SHR,DSN=GENAPP.DDANOT54.DATA
//DDANRP54 DD DISP=SHR,DSN=GENAPP.DDANRP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
