//VJOB2019 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA01ZSQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN28 DD DISP=SHR,DSN=GENAPP.DDPAIN28.DATA
//DDPAOT28 DD DISP=SHR,DSN=GENAPP.DDPAOT28.DATA
//DDPARP28 DD DISP=SHR,DSN=GENAPP.DDPARP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIF01ZSR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN29 DD DISP=SHR,DSN=GENAPP.DDIFIN29.DATA
//DDIFOT29 DD DISP=SHR,DSN=GENAPP.DDIFOT29.DATA
//DDIFRP29 DD DISP=SHR,DSN=GENAPP.DDIFRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTR01ZSS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN30 DD DISP=SHR,DSN=GENAPP.DDTRIN30.DATA
//DDTROT30 DD DISP=SHR,DSN=GENAPP.DDTROT30.DATA
//DDTRRP30 DD DISP=SHR,DSN=GENAPP.DDTRRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
