//VJOB4191 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE024TQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN64 DD DISP=SHR,DSN=GENAPP.DDREIN64.DATA
//DDREOT64 DD DISP=SHR,DSN=GENAPP.DDREOT64.DATA
//DDRERP64 DD DISP=SHR,DSN=GENAPP.DDRERP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG024TR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN65 DD DISP=SHR,DSN=GENAPP.DDRGIN65.DATA
//DDRGOT65 DD DISP=SHR,DSN=GENAPP.DDRGOT65.DATA
//DDRGRP65 DD DISP=SHR,DSN=GENAPP.DDRGRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAU024TS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN66 DD DISP=SHR,DSN=GENAPP.DDAUIN66.DATA
//DDAUOT66 DD DISP=SHR,DSN=GENAPP.DDAUOT66.DATA
//DDAURP66 DD DISP=SHR,DSN=GENAPP.DDAURP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
