//VJOB1546 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA01YPB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN49 DD DISP=SHR,DSN=GENAPP.DDBAIN49.DATA
//DDBAOT49 DD DISP=SHR,DSN=GENAPP.DDBAOT49.DATA
//DDBARP49 DD DISP=SHR,DSN=GENAPP.DDBARP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZDO01YPC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN50 DD DISP=SHR,DSN=GENAPP.DDDOIN50.DATA
//DDDOOT50 DD DISP=SHR,DSN=GENAPP.DDDOOT50.DATA
//DDDORP50 DD DISP=SHR,DSN=GENAPP.DDDORP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTY01YPD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN51 DD DISP=SHR,DSN=GENAPP.DDTYIN51.DATA
//DDTYOT51 DD DISP=SHR,DSN=GENAPP.DDTYOT51.DATA
//DDTYRP51 DD DISP=SHR,DSN=GENAPP.DDTYRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
