//VJOB3782 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE023VN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN07 DD DISP=SHR,DSN=GENAPP.DDHEIN07.DATA
//DDHEOT07 DD DISP=SHR,DSN=GENAPP.DDHEOT07.DATA
//DDHERP07 DD DISP=SHR,DSN=GENAPP.DDHERP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW023VO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN08 DD DISP=SHR,DSN=GENAPP.DDUWIN08.DATA
//DDUWOT08 DD DISP=SHR,DSN=GENAPP.DDUWOT08.DATA
//DDUWRP08 DD DISP=SHR,DSN=GENAPP.DDUWRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA023VP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN09 DD DISP=SHR,DSN=GENAPP.DDMAIN09.DATA
//DDMAOT09 DD DISP=SHR,DSN=GENAPP.DDMAOT09.DATA
//DDMARP09 DD DISP=SHR,DSN=GENAPP.DDMARP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
