//VJOB1132 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01XQT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN67 DD DISP=SHR,DSN=GENAPP.DDMTIN67.DATA
//DDMTOT67 DD DISP=SHR,DSN=GENAPP.DDMTOT67.DATA
//DDMTRP67 DD DISP=SHR,DSN=GENAPP.DDMTRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSU01XQU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSUIN68 DD DISP=SHR,DSN=GENAPP.DDSUIN68.DATA
//DDSUOT68 DD DISP=SHR,DSN=GENAPP.DDSUOT68.DATA
//DDSURP68 DD DISP=SHR,DSN=GENAPP.DDSURP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFR01XQV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN69 DD DISP=SHR,DSN=GENAPP.DDFRIN69.DATA
//DDFROT69 DD DISP=SHR,DSN=GENAPP.DDFROT69.DATA
//DDFRRP69 DD DISP=SHR,DSN=GENAPP.DDFRRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
