//VJOB0215 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN01VME
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN16 DD DISP=SHR,DSN=GENAPP.DDENIN16.DATA
//DDENOT16 DD DISP=SHR,DSN=GENAPP.DDENOT16.DATA
//DDENRP16 DD DISP=SHR,DSN=GENAPP.DDENRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPT01VMF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN17 DD DISP=SHR,DSN=GENAPP.DDPTIN17.DATA
//DDPTOT17 DD DISP=SHR,DSN=GENAPP.DDPTOT17.DATA
//DDPTRP17 DD DISP=SHR,DSN=GENAPP.DDPTRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAV01VMG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN18 DD DISP=SHR,DSN=GENAPP.DDAVIN18.DATA
//DDAVOT18 DD DISP=SHR,DSN=GENAPP.DDAVOT18.DATA
//DDAVRP18 DD DISP=SHR,DSN=GENAPP.DDAVRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
