//VJOB2860 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRG021QT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN31 DD DISP=SHR,DSN=GENAPP.DDRGIN31.DATA
//DDRGOT31 DD DISP=SHR,DSN=GENAPP.DDRGOT31.DATA
//DDRGRP31 DD DISP=SHR,DSN=GENAPP.DDRGRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZED021QU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN32 DD DISP=SHR,DSN=GENAPP.DDEDIN32.DATA
//DDEDOT32 DD DISP=SHR,DSN=GENAPP.DDEDOT32.DATA
//DDEDRP32 DD DISP=SHR,DSN=GENAPP.DDEDRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEX021QV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN33 DD DISP=SHR,DSN=GENAPP.DDEXIN33.DATA
//DDEXOT33 DD DISP=SHR,DSN=GENAPP.DDEXOT33.DATA
//DDEXRP33 DD DISP=SHR,DSN=GENAPP.DDEXRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
