//VJOB2195 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW0207E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN16 DD DISP=SHR,DSN=GENAPP.DDUWIN16.DATA
//DDUWOT16 DD DISP=SHR,DSN=GENAPP.DDUWOT16.DATA
//DDUWRP16 DD DISP=SHR,DSN=GENAPP.DDUWRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG0207F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN17 DD DISP=SHR,DSN=GENAPP.DDRGIN17.DATA
//DDRGOT17 DD DISP=SHR,DSN=GENAPP.DDRGOT17.DATA
//DDRGRP17 DD DISP=SHR,DSN=GENAPP.DDRGRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA0207G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN18 DD DISP=SHR,DSN=GENAPP.DDMAIN18.DATA
//DDMAOT18 DD DISP=SHR,DSN=GENAPP.DDMAOT18.DATA
//DDMARP18 DD DISP=SHR,DSN=GENAPP.DDMARP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
