//VJOB2740 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE021GT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN31 DD DISP=SHR,DSN=GENAPP.DDHEIN31.DATA
//DDHEOT31 DD DISP=SHR,DSN=GENAPP.DDHEOT31.DATA
//DDHERP31 DD DISP=SHR,DSN=GENAPP.DDHERP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZLT021GU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN32 DD DISP=SHR,DSN=GENAPP.DDLTIN32.DATA
//DDLTOT32 DD DISP=SHR,DSN=GENAPP.DDLTOT32.DATA
//DDLTRP32 DD DISP=SHR,DSN=GENAPP.DDLTRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLT021GV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLTIN33 DD DISP=SHR,DSN=GENAPP.DDLTIN33.DATA
//DDLTOT33 DD DISP=SHR,DSN=GENAPP.DDLTOT33.DATA
//DDLTRP33 DD DISP=SHR,DSN=GENAPP.DDLTRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
