//VJOB3586 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN023FB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN49 DD DISP=SHR,DSN=GENAPP.DDENIN49.DATA
//DDENOT49 DD DISP=SHR,DSN=GENAPP.DDENOT49.DATA
//DDENRP49 DD DISP=SHR,DSN=GENAPP.DDENRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU023FC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN50 DD DISP=SHR,DSN=GENAPP.DDCUIN50.DATA
//DDCUOT50 DD DISP=SHR,DSN=GENAPP.DDCUOT50.DATA
//DDCURP50 DD DISP=SHR,DSN=GENAPP.DDCURP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA023FD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN51 DD DISP=SHR,DSN=GENAPP.DDPAIN51.DATA
//DDPAOT51 DD DISP=SHR,DSN=GENAPP.DDPAOT51.DATA
//DDPARP51 DD DISP=SHR,DSN=GENAPP.DDPARP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
