//VJOB3144 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAZ022EH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN73 DD DISP=SHR,DSN=GENAPP.DDAZIN73.DATA
//DDAZOT73 DD DISP=SHR,DSN=GENAPP.DDAZOT73.DATA
//DDAZRP73 DD DISP=SHR,DSN=GENAPP.DDAZRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZST022EI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN74 DD DISP=SHR,DSN=GENAPP.DDSTIN74.DATA
//DDSTOT74 DD DISP=SHR,DSN=GENAPP.DDSTOT74.DATA
//DDSTRP74 DD DISP=SHR,DSN=GENAPP.DDSTRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZFL022EJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN75 DD DISP=SHR,DSN=GENAPP.DDFLIN75.DATA
//DDFLOT75 DD DISP=SHR,DSN=GENAPP.DDFLOT75.DATA
//DDFLRP75 DD DISP=SHR,DSN=GENAPP.DDFLRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
