//VJOB0820 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL01X0T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN31 DD DISP=SHR,DSN=GENAPP.DDCLIN31.DATA
//DDCLOT31 DD DISP=SHR,DSN=GENAPP.DDCLOT31.DATA
//DDCLRP31 DD DISP=SHR,DSN=GENAPP.DDCLRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTR01X0U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN32 DD DISP=SHR,DSN=GENAPP.DDTRIN32.DATA
//DDTROT32 DD DISP=SHR,DSN=GENAPP.DDTROT32.DATA
//DDTRRP32 DD DISP=SHR,DSN=GENAPP.DDTRRP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01X0V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN33 DD DISP=SHR,DSN=GENAPP.DDREIN33.DATA
//DDREOT33 DD DISP=SHR,DSN=GENAPP.DDREOT33.DATA
//DDRERP33 DD DISP=SHR,DSN=GENAPP.DDRERP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
