//VJOB2733 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN021G8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN10 DD DISP=SHR,DSN=GENAPP.DDENIN10.DATA
//DDENOT10 DD DISP=SHR,DSN=GENAPP.DDENOT10.DATA
//DDENRP10 DD DISP=SHR,DSN=GENAPP.DDENRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA021G9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN11 DD DISP=SHR,DSN=GENAPP.DDMAIN11.DATA
//DDMAOT11 DD DISP=SHR,DSN=GENAPP.DDMAOT11.DATA
//DDMARP11 DD DISP=SHR,DSN=GENAPP.DDMARP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPL021GA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPLIN12 DD DISP=SHR,DSN=GENAPP.DDPLIN12.DATA
//DDPLOT12 DD DISP=SHR,DSN=GENAPP.DDPLOT12.DATA
//DDPLRP12 DD DISP=SHR,DSN=GENAPP.DDPLRP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
