//VJOB3546 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR023BZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN19 DD DISP=SHR,DSN=GENAPP.DDTRIN19.DATA
//DDTROT19 DD DISP=SHR,DSN=GENAPP.DDTROT19.DATA
//DDTRRP19 DD DISP=SHR,DSN=GENAPP.DDTRRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAZ023C0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN20 DD DISP=SHR,DSN=GENAPP.DDAZIN20.DATA
//DDAZOT20 DD DISP=SHR,DSN=GENAPP.DDAZOT20.DATA
//DDAZRP20 DD DISP=SHR,DSN=GENAPP.DDAZRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTX023C1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN21 DD DISP=SHR,DSN=GENAPP.DDTXIN21.DATA
//DDTXOT21 DD DISP=SHR,DSN=GENAPP.DDTXOT21.DATA
//DDTXRP21 DD DISP=SHR,DSN=GENAPP.DDTXRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
