//VJOB3259 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN022O2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN58 DD DISP=SHR,DSN=GENAPP.DDENIN58.DATA
//DDENOT58 DD DISP=SHR,DSN=GENAPP.DDENOT58.DATA
//DDENRP58 DD DISP=SHR,DSN=GENAPP.DDENRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAC022O3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN59 DD DISP=SHR,DSN=GENAPP.DDACIN59.DATA
//DDACOT59 DD DISP=SHR,DSN=GENAPP.DDACOT59.DATA
//DDACRP59 DD DISP=SHR,DSN=GENAPP.DDACRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR022O4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN60 DD DISP=SHR,DSN=GENAPP.DDBRIN60.DATA
//DDBROT60 DD DISP=SHR,DSN=GENAPP.DDBROT60.DATA
//DDBRRP60 DD DISP=SHR,DSN=GENAPP.DDBRRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
