//VJOB1835 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTX01ZDE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN16 DD DISP=SHR,DSN=GENAPP.DDTXIN16.DATA
//DDTXOT16 DD DISP=SHR,DSN=GENAPP.DDTXOT16.DATA
//DDTXRP16 DD DISP=SHR,DSN=GENAPP.DDTXRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG01ZDF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN17 DD DISP=SHR,DSN=GENAPP.DDRGIN17.DATA
//DDRGOT17 DD DISP=SHR,DSN=GENAPP.DDRGOT17.DATA
//DDRGRP17 DD DISP=SHR,DSN=GENAPP.DDRGRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN01ZDG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN18 DD DISP=SHR,DSN=GENAPP.DDENIN18.DATA
//DDENOT18 DD DISP=SHR,DSN=GENAPP.DDENOT18.DATA
//DDENRP18 DD DISP=SHR,DSN=GENAPP.DDENRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
