//VJOB0427 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU01W42
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN22 DD DISP=SHR,DSN=GENAPP.DDCUIN22.DATA
//DDCUOT22 DD DISP=SHR,DSN=GENAPP.DDCUOT22.DATA
//DDCURP22 DD DISP=SHR,DSN=GENAPP.DDCURP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO01W43
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN23 DD DISP=SHR,DSN=GENAPP.DDHOIN23.DATA
//DDHOOT23 DD DISP=SHR,DSN=GENAPP.DDHOOT23.DATA
//DDHORP23 DD DISP=SHR,DSN=GENAPP.DDHORP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN01W44
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN24 DD DISP=SHR,DSN=GENAPP.DDPNIN24.DATA
//DDPNOT24 DD DISP=SHR,DSN=GENAPP.DDPNOT24.DATA
//DDPNRP24 DD DISP=SHR,DSN=GENAPP.DDPNRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
