//VJOB3530 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC023AN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN61 DD DISP=SHR,DSN=GENAPP.DDACIN61.DATA
//DDACOT61 DD DISP=SHR,DSN=GENAPP.DDACOT61.DATA
//DDACRP61 DD DISP=SHR,DSN=GENAPP.DDACRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMA023AO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN62 DD DISP=SHR,DSN=GENAPP.DDMAIN62.DATA
//DDMAOT62 DD DISP=SHR,DSN=GENAPP.DDMAOT62.DATA
//DDMARP62 DD DISP=SHR,DSN=GENAPP.DDMARP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT023AP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN63 DD DISP=SHR,DSN=GENAPP.DDMTIN63.DATA
//DDMTOT63 DD DISP=SHR,DSN=GENAPP.DDMTOT63.DATA
//DDMTRP63 DD DISP=SHR,DSN=GENAPP.DDMTRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
