//VJOB1411 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCO01YE2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN04 DD DISP=SHR,DSN=GENAPP.DDCOIN04.DATA
//DDCOOT04 DD DISP=SHR,DSN=GENAPP.DDCOOT04.DATA
//DDCORP04 DD DISP=SHR,DSN=GENAPP.DDCORP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZST01YE3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSTIN05 DD DISP=SHR,DSN=GENAPP.DDSTIN05.DATA
//DDSTOT05 DD DISP=SHR,DSN=GENAPP.DDSTOT05.DATA
//DDSTRP05 DD DISP=SHR,DSN=GENAPP.DDSTRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAZ01YE4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN06 DD DISP=SHR,DSN=GENAPP.DDAZIN06.DATA
//DDAZOT06 DD DISP=SHR,DSN=GENAPP.DDAZOT06.DATA
//DDAZRP06 DD DISP=SHR,DSN=GENAPP.DDAZRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
