//VJOB0409 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBA01W2K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN58 DD DISP=SHR,DSN=GENAPP.DDBAIN58.DATA
//DDBAOT58 DD DISP=SHR,DSN=GENAPP.DDBAOT58.DATA
//DDBARP58 DD DISP=SHR,DSN=GENAPP.DDBARP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01W2L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN59 DD DISP=SHR,DSN=GENAPP.DDBIIN59.DATA
//DDBIOT59 DD DISP=SHR,DSN=GENAPP.DDBIOT59.DATA
//DDBIRP59 DD DISP=SHR,DSN=GENAPP.DDBIRP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBR01W2M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN60 DD DISP=SHR,DSN=GENAPP.DDBRIN60.DATA
//DDBROT60 DD DISP=SHR,DSN=GENAPP.DDBROT60.DATA
//DDBRRP60 DD DISP=SHR,DSN=GENAPP.DDBRRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
