//VJOB3119 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMA022CE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN88 DD DISP=SHR,DSN=GENAPP.DDMAIN88.DATA
//DDMAOT88 DD DISP=SHR,DSN=GENAPP.DDMAOT88.DATA
//DDMARP88 DD DISP=SHR,DSN=GENAPP.DDMARP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRC022CF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRCIN89 DD DISP=SHR,DSN=GENAPP.DDRCIN89.DATA
//DDRCOT89 DD DISP=SHR,DSN=GENAPP.DDRCOT89.DATA
//DDRCRP89 DD DISP=SHR,DSN=GENAPP.DDRCRP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE022CG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN90 DD DISP=SHR,DSN=GENAPP.DDREIN90.DATA
//DDREOT90 DD DISP=SHR,DSN=GENAPP.DDREOT90.DATA
//DDRERP90 DD DISP=SHR,DSN=GENAPP.DDRERP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
