//VJOB2291 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO020FE
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN34 DD DISP=SHR,DSN=GENAPP.DDHOIN34.DATA
//DDHOOT34 DD DISP=SHR,DSN=GENAPP.DDHOOT34.DATA
//DDHORP34 DD DISP=SHR,DSN=GENAPP.DDHORP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZSE020FF
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN35 DD DISP=SHR,DSN=GENAPP.DDSEIN35.DATA
//DDSEOT35 DD DISP=SHR,DSN=GENAPP.DDSEOT35.DATA
//DDSERP35 DD DISP=SHR,DSN=GENAPP.DDSERP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL020FG
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN36 DD DISP=SHR,DSN=GENAPP.DDCLIN36.DATA
//DDCLOT36 DD DISP=SHR,DSN=GENAPP.DDCLOT36.DATA
//DDCLRP36 DD DISP=SHR,DSN=GENAPP.DDCLRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
