//VJOB1970 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN01ZON
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN61 DD DISP=SHR,DSN=GENAPP.DDPNIN61.DATA
//DDPNOT61 DD DISP=SHR,DSN=GENAPP.DDPNOT61.DATA
//DDPNRP61 DD DISP=SHR,DSN=GENAPP.DDPNRP61.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTX01ZOO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTXIN62 DD DISP=SHR,DSN=GENAPP.DDTXIN62.DATA
//DDTXOT62 DD DISP=SHR,DSN=GENAPP.DDTXOT62.DATA
//DDTXRP62 DD DISP=SHR,DSN=GENAPP.DDTXRP62.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01ZOP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN63 DD DISP=SHR,DSN=GENAPP.DDMTIN63.DATA
//DDMTOT63 DD DISP=SHR,DSN=GENAPP.DDMTOT63.DATA
//DDMTRP63 DD DISP=SHR,DSN=GENAPP.DDMTRP63.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
