//VJOB2713 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE021EK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN40 DD DISP=SHR,DSN=GENAPP.DDPEIN40.DATA
//DDPEOT40 DD DISP=SHR,DSN=GENAPP.DDPEOT40.DATA
//DDPERP40 DD DISP=SHR,DSN=GENAPP.DDPERP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBR021EL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN41 DD DISP=SHR,DSN=GENAPP.DDBRIN41.DATA
//DDBROT41 DD DISP=SHR,DSN=GENAPP.DDBROT41.DATA
//DDBRRP41 DD DISP=SHR,DSN=GENAPP.DDBRRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA021EM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN42 DD DISP=SHR,DSN=GENAPP.DDPAIN42.DATA
//DDPAOT42 DD DISP=SHR,DSN=GENAPP.DDPAOT42.DATA
//DDPARP42 DD DISP=SHR,DSN=GENAPP.DDPARP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
