//VJOB2448 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCR020SH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN55 DD DISP=SHR,DSN=GENAPP.DDCRIN55.DATA
//DDCROT55 DD DISP=SHR,DSN=GENAPP.DDCROT55.DATA
//DDCRRP55 DD DISP=SHR,DSN=GENAPP.DDCRRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHE020SI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN56 DD DISP=SHR,DSN=GENAPP.DDHEIN56.DATA
//DDHEOT56 DD DISP=SHR,DSN=GENAPP.DDHEOT56.DATA
//DDHERP56 DD DISP=SHR,DSN=GENAPP.DDHERP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO020SJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN57 DD DISP=SHR,DSN=GENAPP.DDHOIN57.DATA
//DDHOOT57 DD DISP=SHR,DSN=GENAPP.DDHOOT57.DATA
//DDHORP57 DD DISP=SHR,DSN=GENAPP.DDHORP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
