//VJOB3875 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZDI0243E
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDIIN16 DD DISP=SHR,DSN=GENAPP.DDDIIN16.DATA
//DDDIOT16 DD DISP=SHR,DSN=GENAPP.DDDIOT16.DATA
//DDDIRP16 DD DISP=SHR,DSN=GENAPP.DDDIRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPE0243F
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN17 DD DISP=SHR,DSN=GENAPP.DDPEIN17.DATA
//DDPEOT17 DD DISP=SHR,DSN=GENAPP.DDPEOT17.DATA
//DDPERP17 DD DISP=SHR,DSN=GENAPP.DDPERP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE0243G
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN18 DD DISP=SHR,DSN=GENAPP.DDHEIN18.DATA
//DDHEOT18 DD DISP=SHR,DSN=GENAPP.DDHEOT18.DATA
//DDHERP18 DD DISP=SHR,DSN=GENAPP.DDHERP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
