//VJOB0988 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRT01XET
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN85 DD DISP=SHR,DSN=GENAPP.DDRTIN85.DATA
//DDRTOT85 DD DISP=SHR,DSN=GENAPP.DDRTOT85.DATA
//DDRTRP85 DD DISP=SHR,DSN=GENAPP.DDRTRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI01XEU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN86 DD DISP=SHR,DSN=GENAPP.DDBIIN86.DATA
//DDBIOT86 DD DISP=SHR,DSN=GENAPP.DDBIOT86.DATA
//DDBIRP86 DD DISP=SHR,DSN=GENAPP.DDBIRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPR01XEV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN87 DD DISP=SHR,DSN=GENAPP.DDPRIN87.DATA
//DDPROT87 DD DISP=SHR,DSN=GENAPP.DDPROT87.DATA
//DDPRRP87 DD DISP=SHR,DSN=GENAPP.DDPRRP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
