//VJOB1320 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI01Y6H
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN01 DD DISP=SHR,DSN=GENAPP.DDBIIN01.DATA
//DDBIOT01 DD DISP=SHR,DSN=GENAPP.DDBIOT01.DATA
//DDBIRP01 DD DISP=SHR,DSN=GENAPP.DDBIRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW01Y6I
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN02 DD DISP=SHR,DSN=GENAPP.DDUWIN02.DATA
//DDUWOT02 DD DISP=SHR,DSN=GENAPP.DDUWOT02.DATA
//DDUWRP02 DD DISP=SHR,DSN=GENAPP.DDUWRP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01Y6J
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN03 DD DISP=SHR,DSN=GENAPP.DDHOIN03.DATA
//DDHOOT03 DD DISP=SHR,DSN=GENAPP.DDHOOT03.DATA
//DDHORP03 DD DISP=SHR,DSN=GENAPP.DDHORP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
