//VJOB0247 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTR01VP2
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTRIN22 DD DISP=SHR,DSN=GENAPP.DDTRIN22.DATA
//DDTROT22 DD DISP=SHR,DSN=GENAPP.DDTROT22.DATA
//DDTRRP22 DD DISP=SHR,DSN=GENAPP.DDTRRP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV01VP3
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN23 DD DISP=SHR,DSN=GENAPP.DDAVIN23.DATA
//DDAVOT23 DD DISP=SHR,DSN=GENAPP.DDAVOT23.DATA
//DDAVRP23 DD DISP=SHR,DSN=GENAPP.DDAVRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTY01VP4
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN24 DD DISP=SHR,DSN=GENAPP.DDTYIN24.DATA
//DDTYOT24 DD DISP=SHR,DSN=GENAPP.DDTYOT24.DATA
//DDTYRP24 DD DISP=SHR,DSN=GENAPP.DDTYRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
