//VJOB3664 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZWF023LT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDWFIN13 DD DISP=SHR,DSN=GENAPP.DDWFIN13.DATA
//DDWFOT13 DD DISP=SHR,DSN=GENAPP.DDWFOT13.DATA
//DDWFRP13 DD DISP=SHR,DSN=GENAPP.DDWFRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAV023LU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN14 DD DISP=SHR,DSN=GENAPP.DDAVIN14.DATA
//DDAVOT14 DD DISP=SHR,DSN=GENAPP.DDAVOT14.DATA
//DDAVRP14 DD DISP=SHR,DSN=GENAPP.DDAVRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHE023LV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN15 DD DISP=SHR,DSN=GENAPP.DDHEIN15.DATA
//DDHEOT15 DD DISP=SHR,DSN=GENAPP.DDHEOT15.DATA
//DDHERP15 DD DISP=SHR,DSN=GENAPP.DDHERP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
