//VJOB4301 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT0252W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN34 DD DISP=SHR,DSN=GENAPP.DDMTIN34.DATA
//DDMTOT34 DD DISP=SHR,DSN=GENAPP.DDMTOT34.DATA
//DDMTRP34 DD DISP=SHR,DSN=GENAPP.DDMTRP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT0252X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN35 DD DISP=SHR,DSN=GENAPP.DDMTIN35.DATA
//DDMTOT35 DD DISP=SHR,DSN=GENAPP.DDMTOT35.DATA
//DDMTRP35 DD DISP=SHR,DSN=GENAPP.DDMTRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW0252Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN36 DD DISP=SHR,DSN=GENAPP.DDUWIN36.DATA
//DDUWOT36 DD DISP=SHR,DSN=GENAPP.DDUWOT36.DATA
//DDUWRP36 DD DISP=SHR,DSN=GENAPP.DDUWRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
