//VJOB3968 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAZ024B5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN25 DD DISP=SHR,DSN=GENAPP.DDAZIN25.DATA
//DDAZOT25 DD DISP=SHR,DSN=GENAPP.DDAZOT25.DATA
//DDAZRP25 DD DISP=SHR,DSN=GENAPP.DDAZRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT024B6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN26 DD DISP=SHR,DSN=GENAPP.DDMTIN26.DATA
//DDMTOT26 DD DISP=SHR,DSN=GENAPP.DDMTOT26.DATA
//DDMTRP26 DD DISP=SHR,DSN=GENAPP.DDMTRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZQU024B7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDQUIN27 DD DISP=SHR,DSN=GENAPP.DDQUIN27.DATA
//DDQUOT27 DD DISP=SHR,DSN=GENAPP.DDQUOT27.DATA
//DDQURP27 DD DISP=SHR,DSN=GENAPP.DDQURP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
