//VJOB1464 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZIF01YIH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN73 DD DISP=SHR,DSN=GENAPP.DDIFIN73.DATA
//DDIFOT73 DD DISP=SHR,DSN=GENAPP.DDIFOT73.DATA
//DDIFRP73 DD DISP=SHR,DSN=GENAPP.DDIFRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZED01YII
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEDIN74 DD DISP=SHR,DSN=GENAPP.DDEDIN74.DATA
//DDEDOT74 DD DISP=SHR,DSN=GENAPP.DDEDOT74.DATA
//DDEDRP74 DD DISP=SHR,DSN=GENAPP.DDEDRP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSE01YIJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSEIN75 DD DISP=SHR,DSN=GENAPP.DDSEIN75.DATA
//DDSEOT75 DD DISP=SHR,DSN=GENAPP.DDSEOT75.DATA
//DDSERP75 DD DISP=SHR,DSN=GENAPP.DDSERP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
