//VJOB2864 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN021R5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN43 DD DISP=SHR,DSN=GENAPP.DDENIN43.DATA
//DDENOT43 DD DISP=SHR,DSN=GENAPP.DDENOT43.DATA
//DDENRP43 DD DISP=SHR,DSN=GENAPP.DDENRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN021R6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN44 DD DISP=SHR,DSN=GENAPP.DDENIN44.DATA
//DDENOT44 DD DISP=SHR,DSN=GENAPP.DDENOT44.DATA
//DDENRP44 DD DISP=SHR,DSN=GENAPP.DDENRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSC021R7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSCIN45 DD DISP=SHR,DSN=GENAPP.DDSCIN45.DATA
//DDSCOT45 DD DISP=SHR,DSN=GENAPP.DDSCOT45.DATA
//DDSCRP45 DD DISP=SHR,DSN=GENAPP.DDSCRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
