//VJOB3351 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI022VQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN64 DD DISP=SHR,DSN=GENAPP.DDLIIN64.DATA
//DDLIOT64 DD DISP=SHR,DSN=GENAPP.DDLIOT64.DATA
//DDLIRP64 DD DISP=SHR,DSN=GENAPP.DDLIRP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL022VR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN65 DD DISP=SHR,DSN=GENAPP.DDCLIN65.DATA
//DDCLOT65 DD DISP=SHR,DSN=GENAPP.DDCLOT65.DATA
//DDCLRP65 DD DISP=SHR,DSN=GENAPP.DDCLRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIV022VS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN66 DD DISP=SHR,DSN=GENAPP.DDIVIN66.DATA
//DDIVOT66 DD DISP=SHR,DSN=GENAPP.DDIVOT66.DATA
//DDIVRP66 DD DISP=SHR,DSN=GENAPP.DDIVRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
