//VJOB2341 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPN020JK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN04 DD DISP=SHR,DSN=GENAPP.DDPNIN04.DATA
//DDPNOT04 DD DISP=SHR,DSN=GENAPP.DDPNOT04.DATA
//DDPNRP04 DD DISP=SHR,DSN=GENAPP.DDPNRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR020JL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN05 DD DISP=SHR,DSN=GENAPP.DDPRIN05.DATA
//DDPROT05 DD DISP=SHR,DSN=GENAPP.DDPROT05.DATA
//DDPRRP05 DD DISP=SHR,DSN=GENAPP.DDPRRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPN020JM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPNIN06 DD DISP=SHR,DSN=GENAPP.DDPNIN06.DATA
//DDPNOT06 DD DISP=SHR,DSN=GENAPP.DDPNOT06.DATA
//DDPNRP06 DD DISP=SHR,DSN=GENAPP.DDPNRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
