//VJOB3706 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO023PB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN49 DD DISP=SHR,DSN=GENAPP.DDHOIN49.DATA
//DDHOOT49 DD DISP=SHR,DSN=GENAPP.DDHOOT49.DATA
//DDHORP49 DD DISP=SHR,DSN=GENAPP.DDHORP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU023PC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN50 DD DISP=SHR,DSN=GENAPP.DDCUIN50.DATA
//DDCUOT50 DD DISP=SHR,DSN=GENAPP.DDCUOT50.DATA
//DDCURP50 DD DISP=SHR,DSN=GENAPP.DDCURP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG023PD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN51 DD DISP=SHR,DSN=GENAPP.DDAGIN51.DATA
//DDAGOT51 DD DISP=SHR,DSN=GENAPP.DDAGOT51.DATA
//DDAGRP51 DD DISP=SHR,DSN=GENAPP.DDAGRP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
