//VJOB1357 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA01Y9K
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN22 DD DISP=SHR,DSN=GENAPP.DDPAIN22.DATA
//DDPAOT22 DD DISP=SHR,DSN=GENAPP.DDPAOT22.DATA
//DDPARP22 DD DISP=SHR,DSN=GENAPP.DDPARP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01Y9L
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN23 DD DISP=SHR,DSN=GENAPP.DDMTIN23.DATA
//DDMTOT23 DD DISP=SHR,DSN=GENAPP.DDMTOT23.DATA
//DDMTRP23 DD DISP=SHR,DSN=GENAPP.DDMTRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01Y9M
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN24 DD DISP=SHR,DSN=GENAPP.DDMTIN24.DATA
//DDMTOT24 DD DISP=SHR,DSN=GENAPP.DDMTOT24.DATA
//DDMTRP24 DD DISP=SHR,DSN=GENAPP.DDMTRP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
