//VJOB0845 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLI01X2W
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN16 DD DISP=SHR,DSN=GENAPP.DDLIIN16.DATA
//DDLIOT16 DD DISP=SHR,DSN=GENAPP.DDLIOT16.DATA
//DDLIRP16 DD DISP=SHR,DSN=GENAPP.DDLIRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01X2X
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN17 DD DISP=SHR,DSN=GENAPP.DDFLIN17.DATA
//DDFLOT17 DD DISP=SHR,DSN=GENAPP.DDFLOT17.DATA
//DDFLRP17 DD DISP=SHR,DSN=GENAPP.DDFLRP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO01X2Y
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN18 DD DISP=SHR,DSN=GENAPP.DDHOIN18.DATA
//DDHOOT18 DD DISP=SHR,DSN=GENAPP.DDHOOT18.DATA
//DDHORP18 DD DISP=SHR,DSN=GENAPP.DDHORP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
