//VJOB0265 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG01VQK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN76 DD DISP=SHR,DSN=GENAPP.DDAGIN76.DATA
//DDAGOT76 DD DISP=SHR,DSN=GENAPP.DDAGOT76.DATA
//DDAGRP76 DD DISP=SHR,DSN=GENAPP.DDAGRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCO01VQL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCOIN77 DD DISP=SHR,DSN=GENAPP.DDCOIN77.DATA
//DDCOOT77 DD DISP=SHR,DSN=GENAPP.DDCOOT77.DATA
//DDCORP77 DD DISP=SHR,DSN=GENAPP.DDCORP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01VQM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN78 DD DISP=SHR,DSN=GENAPP.DDCLIN78.DATA
//DDCLOT78 DD DISP=SHR,DSN=GENAPP.DDCLOT78.DATA
//DDCLRP78 DD DISP=SHR,DSN=GENAPP.DDCLRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
