//VJOB2944 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE021XT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN13 DD DISP=SHR,DSN=GENAPP.DDPEIN13.DATA
//DDPEOT13 DD DISP=SHR,DSN=GENAPP.DDPEOT13.DATA
//DDPERP13 DD DISP=SHR,DSN=GENAPP.DDPERP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPR021XU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPRIN14 DD DISP=SHR,DSN=GENAPP.DDPRIN14.DATA
//DDPROT14 DD DISP=SHR,DSN=GENAPP.DDPROT14.DATA
//DDPRRP14 DD DISP=SHR,DSN=GENAPP.DDPRRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRT021XV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN15 DD DISP=SHR,DSN=GENAPP.DDRTIN15.DATA
//DDRTOT15 DD DISP=SHR,DSN=GENAPP.DDRTOT15.DATA
//DDRTRP15 DD DISP=SHR,DSN=GENAPP.DDRTRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
