//VJOB0871 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRT01X52
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRTIN04 DD DISP=SHR,DSN=GENAPP.DDRTIN04.DATA
//DDRTOT04 DD DISP=SHR,DSN=GENAPP.DDRTOT04.DATA
//DDRTRP04 DD DISP=SHR,DSN=GENAPP.DDRTRP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZTY01X53
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN05 DD DISP=SHR,DSN=GENAPP.DDTYIN05.DATA
//DDTYOT05 DD DISP=SHR,DSN=GENAPP.DDTYOT05.DATA
//DDTYRP05 DD DISP=SHR,DSN=GENAPP.DDTYRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBA01X54
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBAIN06 DD DISP=SHR,DSN=GENAPP.DDBAIN06.DATA
//DDBAOT06 DD DISP=SHR,DSN=GENAPP.DDBAOT06.DATA
//DDBARP06 DD DISP=SHR,DSN=GENAPP.DDBARP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
