//VJOB0205 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01VLK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN76 DD DISP=SHR,DSN=GENAPP.DDAVIN76.DATA
//DDAVOT76 DD DISP=SHR,DSN=GENAPP.DDAVOT76.DATA
//DDAVRP76 DD DISP=SHR,DSN=GENAPP.DDAVRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01VLL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN77 DD DISP=SHR,DSN=GENAPP.DDMTIN77.DATA
//DDMTOT77 DD DISP=SHR,DSN=GENAPP.DDMTOT77.DATA
//DDMTRP77 DD DISP=SHR,DSN=GENAPP.DDMTRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT01VLM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN78 DD DISP=SHR,DSN=GENAPP.DDMTIN78.DATA
//DDMTOT78 DD DISP=SHR,DSN=GENAPP.DDMTOT78.DATA
//DDMTRP78 DD DISP=SHR,DSN=GENAPP.DDMTRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
