//VJOB3612 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHE023HH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHEIN37 DD DISP=SHR,DSN=GENAPP.DDHEIN37.DATA
//DDHEOT37 DD DISP=SHR,DSN=GENAPP.DDHEOT37.DATA
//DDHERP37 DD DISP=SHR,DSN=GENAPP.DDHERP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU023HI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN38 DD DISP=SHR,DSN=GENAPP.DDCUIN38.DATA
//DDCUOT38 DD DISP=SHR,DSN=GENAPP.DDCUOT38.DATA
//DDCURP38 DD DISP=SHR,DSN=GENAPP.DDCURP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO023HJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN39 DD DISP=SHR,DSN=GENAPP.DDHOIN39.DATA
//DDHOOT39 DD DISP=SHR,DSN=GENAPP.DDHOOT39.DATA
//DDHORP39 DD DISP=SHR,DSN=GENAPP.DDHORP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
