//VJOB0376 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR01VZT
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN49 DD DISP=SHR,DSN=GENAPP.DDFRIN49.DATA
//DDFROT49 DD DISP=SHR,DSN=GENAPP.DDFROT49.DATA
//DDFRRP49 DD DISP=SHR,DSN=GENAPP.DDFRRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT01VZU
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN50 DD DISP=SHR,DSN=GENAPP.DDMTIN50.DATA
//DDMTOT50 DD DISP=SHR,DSN=GENAPP.DDMTOT50.DATA
//DDMTRP50 DD DISP=SHR,DSN=GENAPP.DDMTRP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE01VZV
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN51 DD DISP=SHR,DSN=GENAPP.DDREIN51.DATA
//DDREOT51 DD DISP=SHR,DSN=GENAPP.DDREOT51.DATA
//DDRERP51 DD DISP=SHR,DSN=GENAPP.DDRERP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
