//VJOB1076 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBR01XM5
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBRIN79 DD DISP=SHR,DSN=GENAPP.DDBRIN79.DATA
//DDBROT79 DD DISP=SHR,DSN=GENAPP.DDBROT79.DATA
//DDBRRP79 DD DISP=SHR,DSN=GENAPP.DDBRRP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAU01XM6
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAUIN80 DD DISP=SHR,DSN=GENAPP.DDAUIN80.DATA
//DDAUOT80 DD DISP=SHR,DSN=GENAPP.DDAUOT80.DATA
//DDAURP80 DD DISP=SHR,DSN=GENAPP.DDAURP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZSL01XM7
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDSLIN81 DD DISP=SHR,DSN=GENAPP.DDSLIN81.DATA
//DDSLOT81 DD DISP=SHR,DSN=GENAPP.DDSLOT81.DATA
//DDSLRP81 DD DISP=SHR,DSN=GENAPP.DDSLRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
