//VJOB1405 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFL01YDK
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN76 DD DISP=SHR,DSN=GENAPP.DDFLIN76.DATA
//DDFLOT76 DD DISP=SHR,DSN=GENAPP.DDFLOT76.DATA
//DDFLRP76 DD DISP=SHR,DSN=GENAPP.DDFLRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZFL01YDL
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFLIN77 DD DISP=SHR,DSN=GENAPP.DDFLIN77.DATA
//DDFLOT77 DD DISP=SHR,DSN=GENAPP.DDFLOT77.DATA
//DDFLRP77 DD DISP=SHR,DSN=GENAPP.DDFLRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL01YDM
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN78 DD DISP=SHR,DSN=GENAPP.DDCLIN78.DATA
//DDCLOT78 DD DISP=SHR,DSN=GENAPP.DDCLOT78.DATA
//DDCLRP78 DD DISP=SHR,DSN=GENAPP.DDCLRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
