//VJOB2646 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZTY0218Z
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN19 DD DISP=SHR,DSN=GENAPP.DDTYIN19.DATA
//DDTYOT19 DD DISP=SHR,DSN=GENAPP.DDTYOT19.DATA
//DDTYRP19 DD DISP=SHR,DSN=GENAPP.DDTYRP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW02190
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN20 DD DISP=SHR,DSN=GENAPP.DDUWIN20.DATA
//DDUWOT20 DD DISP=SHR,DSN=GENAPP.DDUWOT20.DATA
//DDUWRP20 DD DISP=SHR,DSN=GENAPP.DDUWRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZDO02191
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDDOIN21 DD DISP=SHR,DSN=GENAPP.DDDOIN21.DATA
//DDDOOT21 DD DISP=SHR,DSN=GENAPP.DDDOOT21.DATA
//DDDORP21 DD DISP=SHR,DSN=GENAPP.DDDORP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
