//VJOB1539 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAV01YOQ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAVIN28 DD DISP=SHR,DSN=GENAPP.DDAVIN28.DATA
//DDAVOT28 DD DISP=SHR,DSN=GENAPP.DDAVOT28.DATA
//DDAVRP28 DD DISP=SHR,DSN=GENAPP.DDAVRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR01YOR
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN29 DD DISP=SHR,DSN=GENAPP.DDCRIN29.DATA
//DDCROT29 DD DISP=SHR,DSN=GENAPP.DDCROT29.DATA
//DDCRRP29 DD DISP=SHR,DSN=GENAPP.DDCRRP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA01YOS
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN30 DD DISP=SHR,DSN=GENAPP.DDMAIN30.DATA
//DDMAOT30 DD DISP=SHR,DSN=GENAPP.DDMAOT30.DATA
//DDMARP30 DD DISP=SHR,DSN=GENAPP.DDMARP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
