//VJOB3570 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT023DZ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN01 DD DISP=SHR,DSN=GENAPP.DDMTIN01.DATA
//DDMTOT01 DD DISP=SHR,DSN=GENAPP.DDMTOT01.DATA
//DDMTRP01 DD DISP=SHR,DSN=GENAPP.DDMTRP01.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO023E0
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN02 DD DISP=SHR,DSN=GENAPP.DDHOIN02.DATA
//DDHOOT02 DD DISP=SHR,DSN=GENAPP.DDHOOT02.DATA
//DDHORP02 DD DISP=SHR,DSN=GENAPP.DDHORP02.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMA023E1
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMAIN03 DD DISP=SHR,DSN=GENAPP.DDMAIN03.DATA
//DDMAOT03 DD DISP=SHR,DSN=GENAPP.DDMAOT03.DATA
//DDMARP03 DD DISP=SHR,DSN=GENAPP.DDMARP03.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
