//VJOB0463 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZLB01W72
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN40 DD DISP=SHR,DSN=GENAPP.DDLBIN40.DATA
//DDLBOT40 DD DISP=SHR,DSN=GENAPP.DDLBOT40.DATA
//DDLBRP40 DD DISP=SHR,DSN=GENAPP.DDLBRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL01W73
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN41 DD DISP=SHR,DSN=GENAPP.DDCLIN41.DATA
//DDCLOT41 DD DISP=SHR,DSN=GENAPP.DDCLOT41.DATA
//DDCLRP41 DD DISP=SHR,DSN=GENAPP.DDCLRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAZ01W74
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAZIN42 DD DISP=SHR,DSN=GENAPP.DDAZIN42.DATA
//DDAZOT42 DD DISP=SHR,DSN=GENAPP.DDAZOT42.DATA
//DDAZRP42 DD DISP=SHR,DSN=GENAPP.DDAZRP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
