//VJOB3134 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPT022DN
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN43 DD DISP=SHR,DSN=GENAPP.DDPTIN43.DATA
//DDPTOT43 DD DISP=SHR,DSN=GENAPP.DDPTOT43.DATA
//DDPTRP43 DD DISP=SHR,DSN=GENAPP.DDPTRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV022DO
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN44 DD DISP=SHR,DSN=GENAPP.DDIVIN44.DATA
//DDIVOT44 DD DISP=SHR,DSN=GENAPP.DDIVOT44.DATA
//DDIVRP44 DD DISP=SHR,DSN=GENAPP.DDIVRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZTY022DP
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDTYIN45 DD DISP=SHR,DSN=GENAPP.DDTYIN45.DATA
//DDTYOT45 DD DISP=SHR,DSN=GENAPP.DDTYOT45.DATA
//DDTYRP45 DD DISP=SHR,DSN=GENAPP.DDTYRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
