//VJOB0972 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT01XDH
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN37 DD DISP=SHR,DSN=GENAPP.DDMTIN37.DATA
//DDMTOT37 DD DISP=SHR,DSN=GENAPP.DDMTOT37.DATA
//DDMTRP37 DD DISP=SHR,DSN=GENAPP.DDMTRP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAN01XDI
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDANIN38 DD DISP=SHR,DSN=GENAPP.DDANIN38.DATA
//DDANOT38 DD DISP=SHR,DSN=GENAPP.DDANOT38.DATA
//DDANRP38 DD DISP=SHR,DSN=GENAPP.DDANRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLB01XDJ
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLBIN39 DD DISP=SHR,DSN=GENAPP.DDLBIN39.DATA
//DDLBOT39 DD DISP=SHR,DSN=GENAPP.DDLBOT39.DATA
//DDLBRP39 DD DISP=SHR,DSN=GENAPP.DDLBRP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
