//VJOB2086 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZFR01ZYB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDFRIN49 DD DISP=SHR,DSN=GENAPP.DDFRIN49.DATA
//DDFROT49 DD DISP=SHR,DSN=GENAPP.DDFROT49.DATA
//DDFRRP49 DD DISP=SHR,DSN=GENAPP.DDFRRP49.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE01ZYC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN50 DD DISP=SHR,DSN=GENAPP.DDREIN50.DATA
//DDREOT50 DD DISP=SHR,DSN=GENAPP.DDREOT50.DATA
//DDRERP50 DD DISP=SHR,DSN=GENAPP.DDRERP50.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPE01ZYD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN51 DD DISP=SHR,DSN=GENAPP.DDPEIN51.DATA
//DDPEOT51 DD DISP=SHR,DSN=GENAPP.DDPEOT51.DATA
//DDPERP51 DD DISP=SHR,DSN=GENAPP.DDPERP51.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
