//VJOB2584 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPE0213T
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPEIN13 DD DISP=SHR,DSN=GENAPP.DDPEIN13.DATA
//DDPEOT13 DD DISP=SHR,DSN=GENAPP.DDPEOT13.DATA
//DDPERP13 DD DISP=SHR,DSN=GENAPP.DDPERP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZIV0213U
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIVIN14 DD DISP=SHR,DSN=GENAPP.DDIVIN14.DATA
//DDIVOT14 DD DISP=SHR,DSN=GENAPP.DDIVOT14.DATA
//DDIVRP14 DD DISP=SHR,DSN=GENAPP.DDIVRP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAR0213V
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN15 DD DISP=SHR,DSN=GENAPP.DDARIN15.DATA
//DDAROT15 DD DISP=SHR,DSN=GENAPP.DDAROT15.DATA
//DDARRP15 DD DISP=SHR,DSN=GENAPP.DDARRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
