//VJOB0622 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAC01WKB
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDACIN67 DD DISP=SHR,DSN=GENAPP.DDACIN67.DATA
//DDACOT67 DD DISP=SHR,DSN=GENAPP.DDACOT67.DATA
//DDACRP67 DD DISP=SHR,DSN=GENAPP.DDACRP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRG01WKC
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDRGIN68 DD DISP=SHR,DSN=GENAPP.DDRGIN68.DATA
//DDRGOT68 DD DISP=SHR,DSN=GENAPP.DDRGOT68.DATA
//DDRGRP68 DD DISP=SHR,DSN=GENAPP.DDRGRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPT01WKD
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPTIN69 DD DISP=SHR,DSN=GENAPP.DDPTIN69.DATA
//DDPTOT69 DD DISP=SHR,DSN=GENAPP.DDPTOT69.DATA
//DDPTRP69 DD DISP=SHR,DSN=GENAPP.DDPTRP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
