//VJOB2215 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCP02092
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCPIN76 DD DISP=SHR,DSN=GENAPP.DDCPIN76.DATA
//DDCPOT76 DD DISP=SHR,DSN=GENAPP.DDCPOT76.DATA
//DDCPRP76 DD DISP=SHR,DSN=GENAPP.DDCPRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAR02093
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDARIN77 DD DISP=SHR,DSN=GENAPP.DDARIN77.DATA
//DDAROT77 DD DISP=SHR,DSN=GENAPP.DDAROT77.DATA
//DDARRP77 DD DISP=SHR,DSN=GENAPP.DDARRP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZLI02094
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDLIIN78 DD DISP=SHR,DSN=GENAPP.DDLIIN78.DATA
//DDLIOT78 DD DISP=SHR,DSN=GENAPP.DDLIOT78.DATA
//DDLIRP78 DD DISP=SHR,DSN=GENAPP.DDLIRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
