//VJOB2204 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT02085
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN43 DD DISP=SHR,DSN=GENAPP.DDMTIN43.DATA
//DDMTOT43 DD DISP=SHR,DSN=GENAPP.DDMTOT43.DATA
//DDMTRP43 DD DISP=SHR,DSN=GENAPP.DDMTRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEX02086
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDEXIN44 DD DISP=SHR,DSN=GENAPP.DDEXIN44.DATA
//DDEXOT44 DD DISP=SHR,DSN=GENAPP.DDEXOT44.DATA
//DDEXRP44 DD DISP=SHR,DSN=GENAPP.DDEXRP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW02087
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN45 DD DISP=SHR,DSN=GENAPP.DDUWIN45.DATA
//DDUWOT45 DD DISP=SHR,DSN=GENAPP.DDUWOT45.DATA
//DDUWRP45 DD DISP=SHR,DSN=GENAPP.DDUWRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
