//VJOB3141 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO022E8
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN64 DD DISP=SHR,DSN=GENAPP.DDHOIN64.DATA
//DDHOOT64 DD DISP=SHR,DSN=GENAPP.DDHOOT64.DATA
//DDHORP64 DD DISP=SHR,DSN=GENAPP.DDHORP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCR022E9
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCRIN65 DD DISP=SHR,DSN=GENAPP.DDCRIN65.DATA
//DDCROT65 DD DISP=SHR,DSN=GENAPP.DDCROT65.DATA
//DDCRRP65 DD DISP=SHR,DSN=GENAPP.DDCRRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZIF022EA
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDIFIN66 DD DISP=SHR,DSN=GENAPP.DDIFIN66.DATA
//DDIFOT66 DD DISP=SHR,DSN=GENAPP.DDIFOT66.DATA
//DDIFRP66 DD DISP=SHR,DSN=GENAPP.DDIFRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
